Work around TOML Python parser bug of parsing `\x`
gramineproject/gsc pull request #101
Opened 2022-10-11 13:20 UTC by dimakuv

## Description of the changes 

The currently used TOML parser in Python is buggy and doesn't allow to parse filenames like `system-systemd\x2dcryptsetup.slice`. Since the only files that we detected in real world are systemd helper files (which are not used by graminized apps anyway), the current workaround is to simply skip such files when collecting `sgx.trusted_files`.

The bug was already reported by someone else: https://github.com/uiri/toml/issues/404.

The bug was found in https://github.com/gramineproject/gsc/issues/100.

Fixes #100.

## How to test this PR? 

Try the workload in #100.

2022-10-11 14:39 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/101#-NE6RoR01KhIoztCPeJL:-NE6RoR01KhIoztCPeJM:b-m6vc7g) (no related file):*
Please create an issue about migration to `tomli` in the main repo (and maybe also here? or just mention gsc in the main repo).

___


<!-- Sent from Reviewable.io -->

2022-10-11 15:07 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/101)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/101#-NE6RoR01KhIoztCPeJL:-NE6_Tii7FEMA3VSTDTU:b-ww29g2) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please create an issue about migration to `tomli` in the main repo (and maybe also here? or just mention gsc in the main repo).
</blockquote></details>

Done: https://github.com/gramineproject/gramine/issues/968

___


<!-- Sent from Reviewable.io -->

2022-10-11 15:35 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/101)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-10-13 14:31 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/101)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-13 15:05 UTC, merged