Add `.cache` directory to the exclusion list of trusted_files
gramineproject/gsc pull request #103
Opened 2022-10-19 00:30 UTC by jkr0103

## Description of the changes 
A temporary directory `.cache` gets created inside image during GSC build process and GSC tries to add this directory to the list of trusted_files which fails with `permission denied` error. It seems reasonable to exclude this directory from trusted_files list.

## How to test this PR? 

graminize `bitnami/scikit-learn-intel` image with GSC

2022-10-19 06:40 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/103)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jkr0103)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/103#-NEixsM5BLo9m4A4mLcG):*
I would remove this commit body message. The `permission denied` error happens only in some corner cases with different users, and we still don't understand the exact conditions when this happens.

So the commit message is only partially true. But since excluding `/.cache/` sounds reasonable anyway, we don't need additional justifications.

I'll fix it during final rebase.


<!-- Sent from Reviewable.io -->

2022-10-19 10:10 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/103)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/103#-NEixsM5BLo9m4A4mLcG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this commit body message. The `permission denied` error happens only in some corner cases with different users, and we still don't understand the exact conditions when this happens.

So the commit message is only partially true. But since excluding `/.cache/` sounds reasonable anyway, we don't need additional justifications.

I'll fix it during final rebase.
</blockquote></details>

What creates that `/.cache/` directory? I've never seen it on Linux.


<!-- Sent from Reviewable.io -->

2022-10-19 10:19 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/103)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/103#-NEixsM5BLo9m4A4mLcG):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What creates that `/.cache/` directory? I've never seen it on Linux.
</blockquote></details>

Python's pip.


<!-- Sent from Reviewable.io -->

2022-10-19 21:56 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/103)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/103#-NEixsM5BLo9m4A4mLcG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Python's pip.
</blockquote></details>

In root directory?


<!-- Sent from Reviewable.io -->

2022-10-20 15:34 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/103)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/103#-NEixsM5BLo9m4A4mLcG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, because the cache dir is typically created as `$HOME/.cache/`.

In this case, we have an official Scikit Docker image:
```sh
$ docker pull bitnami/scikit-learn-intel
Using default tag: latest
latest: Pulling from bitnami/scikit-learn-intel
1d8866550bdd: Pull complete
93095ef05c8e: Pull complete
Digest: sha256:5264a1484043bb8192b661ebe5d954331db5f260e727d132cefc16804d851852
Status: Downloaded newer image for bitnami/scikit-learn-intel:latest
docker.io/bitnami/scikit-learn-intel:latest

$ docker run -it --entrypoint /bin/bash bitnami/scikit-learn-intel:latest
I have no name!@470836384bb8:/app$ echo $HOME
/
```

See https://hub.docker.com/r/bitnami/scikit-learn-intel/ and https://github.com/bitnami/containers/blob/main/bitnami/scikit-learn-intel/2021/debian-11/Dockerfile

So this creates a `/.cache/` dir. I wonder, maybe we should just exclude `.cache` dir everywhere? With this regex: `.*\.cache/.*`?
</blockquote></details>

Shouldn't we instead remove this directory? `rm -rf $HOME/.cache` somewhere?


<!-- Sent from Reviewable.io -->

2022-10-21 10:07 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/103)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @woju)

___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/103#-NEixsM5BLo9m4A4mLcG):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Shouldn't we instead remove this directory? `rm -rf $HOME/.cache` somewhere?
</blockquote></details>

Good suggestion. I created another PR that does this: https://github.com/gramineproject/gsc/pull/107

@woju Please check that PR.


<!-- Sent from Reviewable.io -->

2022-10-21 15:45 UTC, closed without merging