Gramine Attestation Inside AKS
gramineproject/gsc pull request #11
Opened 2021-09-14 06:07 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 

This PR provides a reference implementation to show how gramine attestation (DCAP) samples works inside AKS cluster. We have created two docker images for ra-tls-secret-prov server and ra-tls-secret-prov client. Both images are deployed as part of AKS confidential compute cluster and both quote generation and quote verification are successful inside AKS cluster.

For client deployment inside AKS cluster, we have gsc/examples/gramine-aks-attestation/aks-secret-prov-client-deployment.yaml and for server  deployment gsc/examples/gramine-aks-attestation/aks-secret-prov-server-deployment.yaml file.

For more details, we have created a readme file.  

This PR is an updated version of https://github.com/gramineproject/graphene/pull/2473. Once this is merged, I will delete 2473 PR.

## How to test this PR? 
Please follow gsc/examples/gramine-aks-attestation/gramine_attestation_inside_aks_readme.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/graphene/2473)

2021-09-23 12:21 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXQ8u5so2mjpXvZBs):*
This should have a better name like `Add example of AKS attestation and secret provisioning`
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZ71O0_KurepnTKnb:-MkHZ71O0_KurepnTKnc:bdy8hoi) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.dockerfile#L24)):*
> ```Dockerfile
> # Build environment of this Dockerfile should point to the root of Gramine directory
> 
> # Before copy do "make clean && make secret_prov_min_client" in CI-Examples/ra-tls-secret-prov directory
> ```

This step should be in the README, not here
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 26 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHYWdO8qDkg02kX2Lp:-MkHYWdO8qDkg02kX2Lq:bv8uwcz) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.dockerfile#L26)):*
> ```Dockerfile
> # Before copy do "make clean && make secret_prov_min_client" in CI-Examples/ra-tls-secret-prov directory
> 
> COPY CI-Examples/ra-tls-secret-prov /gramine/Examples/ra-tls-secret-prov
> ```

Why do you need this complex dir `/gramine/Examples/ra-tls-secret-prov`? All Gramine binaries/utilities/libraries (including RA-TLS, Secret Provisioning, MbedTLS) are installed correctly in your Ubuntu OS inside this Docker image. So you don't need any references to `gramine/Examples`.

Please replace `/gramine/Examples/ra-tls-secret-prov` to simply `/ra-tls-secret-prov` everywhere in this PR.
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXg96AOJffdoWJDdh:-MkHXg97A162DFmOLikf:b-19vzx1) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
> ```Dockerfile
> WORKDIR /gramine/Examples/ra-tls-secret-prov
> 
> ENV PATH = "${PATH}:/gramine/Examples/ra-tls-secret-prov"
> ```

Why is this needed? With the latest Gramine version, we have all libraries and utilities installed in the correct dir, and there is no need to adjust `PATH`
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHY5ZM3jFu0BpG2dkW:-MkHY5ZM3jFu0BpG2dkX:bpt5aqx) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.manifest#L4)):*
> ```
> 
> # Secret Provisioning library (client-side) is preloaded
> loader.env.LD_PRELOAD = "libs/libsecret_prov_attest.so"
> ```

With the latest Gramine, the directory is different... It is one of the common dirs on Ubuntu.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHYE6W17LCE45UB3yJ:-MkHYE6X9jpb_3FK13sB:b-a80gl4) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-server.dockerfile#L15)):*
> ```Dockerfile
> # Here, the version of az-dcap-client should be in sync with the
> # az-dcap-client version used for quote generation.
> # User can replace the below package with the latest package.
> ```

Why this strange char limit per line? Please re-wrap to 80 chars.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 30 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZ9qQ2xMfXvKLK2-0:-MkHZ9qQ2xMfXvKLK2-1:bdy8hoi) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-server.dockerfile#L30)):*
> ```Dockerfile
> # Build environment of this Dockerfile should point to the root of Gramine directory
> 
> # Before copy do "make clean && make dcap" in CI-Examples/ra-tls-secret-prov directory
> ```

This step should be in the README, not here
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 32 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZCRA7lDnFT_vqYdh:-MkHZCRA7lDnFT_vqYdi:b-2gao50) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-server.dockerfile#L32)):*
> ```Dockerfile
> # Before copy do "make clean && make dcap" in CI-Examples/ra-tls-secret-prov directory
> 
> COPY CI-Examples/ra-tls-secret-prov /gramine/Examples/ra-tls-secret-prov
> ```

ditto (Please replace `/gramine/Examples/ra-tls-secret-prov` to simply `/ra-tls-secret-prov` everywhere in this PR.)
___
*[examples/aks-attestation/README.md, line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZQ-rCj8_Bg-todQI:-MkHZQ-rCj8_Bg-todQJ:b5oj2sz) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L5)):*
> ```Markdown
> This guide demonstrates how Gramine DCAP attestation quote can be generated and verified from
> within an AKS cluster. Here, we provide an end-to-end example to help Cloud Solution Providers
> integrate gramine’s RA-TLS attestation and secret provisioning feature with a confidential compute
> ```

Please upper-case all `gramine` words in your README
___
*[examples/aks-attestation/README.md, line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_tz63IYyg9TDRYWy:-MkH_tz63IYyg9TDRYWz:b-xsg1ea) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L11)):*
> ```Markdown
> deployed to the AKS cluster.
> 
> ## Create client and server images for gramine attestation samples
> ```

Please remove `for gramine attestation samples` -- it's obvious from the context.

I suggest `## Preparing client and server images`
___
*[examples/aks-attestation/README.md, line 14 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZGaW5FD7WLNRf6LZ:-MkHZGaW5FD7WLNRf6L_:bolsrpu) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L14)):*
> ```Markdown
> 
> This demonstration is created for ``gramine/CI-Examples/ra-tls-secret-prov`` sample.
> In order to create the below two images, user needs to download core [gramine repository](https://github.com/gramineproject/gramine).
> ```

`gramine repository` -> `Gramine repository`
___
*[examples/aks-attestation/README.md, line 16 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_xDq9TO5S-O1y6y9:-MkH_xDq9TO5S-O1y6yA:bsm4iuc) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L16)):*
> ```Markdown
> In order to create the below two images, user needs to download core [gramine repository](https://github.com/gramineproject/gramine).
> 
> ### Steps to create ra-tls-secret-prov server image for AKS
> ```

Please remove `Steps to create ...` -- it's obvious from the context.

I suggest `### Creating server image`
___
*[examples/aks-attestation/README.md, line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_IXX7EDCMYkzLlmY:-MkH_IXX7EDCMYkzLlmZ:b-bhin) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L18)):*
> ```Markdown
> ### Steps to create ra-tls-secret-prov server image for AKS
> 
> [...]

2021-09-24 06:42 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 0 of 7 files reviewed, 32 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXQ8u5so2mjpXvZBs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should have a better name like `Add example of AKS attestation and secret provisioning`
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZ71O0_KurepnTKnb:-MkLRX1u0n-sYr-j5RYk:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.dockerfile#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This step should be in the README, not here
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 26 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHYWdO8qDkg02kX2Lp:-MkL2nyz6nIsUiOW-Bu9:b-iry7x8) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.dockerfile#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this complex dir `/gramine/Examples/ra-tls-secret-prov`? All Gramine binaries/utilities/libraries (including RA-TLS, Secret Provisioning, MbedTLS) are installed correctly in your Ubuntu OS inside this Docker image. So you don't need any references to `gramine/Examples`.

Please replace `/gramine/Examples/ra-tls-secret-prov` to simply `/ra-tls-secret-prov` everywhere in this PR.
</blockquote></details>

Done, thanks
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXg96AOJffdoWJDdh:-MkL2pg_-i_BxXZqQ1zl:b-iry7x8) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this needed? With the latest Gramine version, we have all libraries and utilities installed in the correct dir, and there is no need to adjust `PATH`
</blockquote></details>

Done, thanks
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHY5ZM3jFu0BpG2dkW:-MkL3qI66DjyXLwn0rDO:b-dtkdrq) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-client.manifest#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With the latest Gramine, the directory is different... It is one of the common dirs on Ubuntu.
</blockquote></details>

Done, thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHYE6W17LCE45UB3yJ:-MkL3I0bBycFAXWAAxnr:b-iry7x8) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-server.dockerfile#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this strange char limit per line? Please re-wrap to 80 chars.
</blockquote></details>

Done, thanks
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 30 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZ9qQ2xMfXvKLK2-0:-MkL3KFYEH9m0Mc-anPT:b-iry7x8) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-server.dockerfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This step should be in the README, not here
</blockquote></details>

Done, thanks
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 32 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZCRA7lDnFT_vqYdh:-MkL3PSTA6lWQxiU8SiE:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/aks-secret-prov-server.dockerfile#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (Please replace `/gramine/Examples/ra-tls-secret-prov` to simply `/ra-tls-secret-prov` everywhere in this PR.)
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/README.md, line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZQ-rCj8_Bg-todQI:-MkL4ytUDOgpYzzZ8sFj:b-dtkdrq) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please upper-case all `gramine` words in your README
</blockquote></details>

Done, thanks.
___
*[examples/aks-attestation/README.md, line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_tz63IYyg9TDRYWy:-MkLRZ9q-mPeYOlkIwuW:b-iry7x8) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `for gramine attestation samples` -- it's obvious from the context.

I suggest `## Preparing client and server images`
</blockquote></details>

Done, thanks
___
*[examples/aks-attestation/README.md, line 14 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZGaW5FD7WLNRf6LZ:-MkL5Fno81KEjPeBchhg:b-dtkdrq) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`gramine repository` -> `Gramine repository`
</blockquote></details>

Done, thanks.
___
*[examples/aks-attestation/README.md, line 16 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_xDq9TO5S-O1y6y9:-MkL5UcF6EAJ1FusqyAK:b-iry7x8) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `Steps to create ...` -- it's obvious from the context.

I suggest `### Creating server image`
</blockquote></details>

Done, thanks
___
*[examples/aks-attestation/README.md, line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_IXX7EDCMYkzLlmY:-MkL7RdjADHHuo6qAsdZ:b-29vizu) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add `:` at the end of each step title
</blockquote></details>

Done, thanks. 
___
*[examples/aks-attestation/README.md, line 19 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHZdGD3H3I0C3xGYQP:-MkL7qVAAzji0m_Wq1Fb:b-29vizu) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Common Name` -> `"Common Name"`
</blockquote></details>

Done, thanks. 
___
*[examples/aks-attestation/README.md, line 20 at r1](https://reviewable. [...]

2021-09-24 10:43 UTC, dimakuv requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXQ8u5so2mjpXvZBs):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

done, thanks
</blockquote></details>

Not done, but we'll change the name during the final rebase.
___
*[examples/aks-attestation/README.md, line 48 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_YJ06H03Yg1OWtkJ:-MkMNdiL7W2wW80AZnPc:b-dicw3d) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L48)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

The non-qve based verification will pass. QVE-based verification will fail, if we don't use confidential compute node for server. 
</blockquote></details>

Ah, I understand the point now. The server doesn't really need to be run on the SGX-enabled node because it can use the non-QVE (non-Quote-Verification-Enclave) flow. But to use the QVE flow, it must run on the SGX-enabled node.

Could you add a link to some Microsoft Azure doc about these two flows? I can't find any... (If you also can't find any doc, then I'll resolve this comment. Surprisingly hard to find any good documentation on QvE.)
___
*[examples/aks-attestation/README.md, line 89 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_gpTDncsIMvhLtOH:-MkMOWYv1vV-SH6niKI3:bbrcjug) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L89)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Yeah correct. But what if the user uses "in-kernel driver option" in config.yaml file and the in-kernel driver is lower than 5.11. In that case we have to explicitely set the symbolic links, right?  
</blockquote></details>

But why would the user specify wrong driver option in `config.yaml`? I am missing something here.
___
*[examples/aks-attestation/README.md, line 48 at r2](https://reviewable.io/reviews/gramineproject/gsc/11#-MkMONV89l1r4r7yOrvJ:-MkMONV89l1r4r7yOrvK:b-v7x36d) ([raw file](https://github.com/gramineproject/gsc/blob/c93d61a855ed55b493822e255b06c5fb20431286/examples/aks-attestation/README.md#L48)):*
> ```Markdown
>         `gsc/examples/aks-attestation/aks-secret-prov-server-deployment.yaml`
> 
> NOTE:  Server can be deployed at a non-confidential compute node as well. However, in that case
> ```

Please make this `NOTE` bold or italic.
___
*[examples/aks-attestation/README.md, line 69 at r2](https://reviewable.io/reviews/gramineproject/gsc/11#-MkMOkscEXccMfIUnf-b:-MkMOkscEXccMfIUnf-c:b-71tcay) ([raw file](https://github.com/gramineproject/gsc/blob/c93d61a855ed55b493822e255b06c5fb20431286/examples/aks-attestation/README.md#L69)):*
> ```Markdown
>       inside `gsc/examples/aks-attestation/aks-secret-prov-client.manifest` file.
> 
> 4. Create gsc image for ra-tls-secret-prov min client:
> ```

`gsc` -> `GSC`
___
*[examples/aks-attestation/README.md, line 91 at r2](https://reviewable.io/reviews/gramineproject/gsc/11#-MkMOf7B63P-4jf6w32J:-MkMOf7B63P-4jf6w32K:b91ipcn) ([raw file](https://github.com/gramineproject/gsc/blob/c93d61a855ed55b493822e255b06c5fb20431286/examples/aks-attestation/README.md#L91)):*
> ```Markdown
>         `gsc/examples/aks-attestation/aks-secret-prov-client-deployment.yaml`
> 
> NOTE: We recommend deploying gsc images on Ubuntu with Linux kernel version 5.11 or higher.
> ```

Please make this `NOTE` bold or italic.

Also, `gsc` -> `GSC`.


<!-- Sent from Reviewable.io -->

2021-09-24 11:40 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 6 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXQ8u5so2mjpXvZBs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done, but we'll change the name during the final rebase.
</blockquote></details>

Looks like directly updating at github does not show up. 
___
*[examples/aks-attestation/README.md, line 48 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_YJ06H03Yg1OWtkJ:-MkMa1P1CyMFOxQRpnxy:b7uzig2) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, I understand the point now. The server doesn't really need to be run on the SGX-enabled node because it can use the non-QVE (non-Quote-Verification-Enclave) flow. But to use the QVE flow, it must run on the SGX-enabled node.

Could you add a link to some Microsoft Azure doc about these two flows? I can't find any... (If you also can't find any doc, then I'll resolve this comment. Surprisingly hard to find any good documentation on QvE.)
</blockquote></details>

Sure, I will search. Thanks.
___
*[examples/aks-attestation/README.md, line 89 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_gpTDncsIMvhLtOH:-MkMUxqzAPd3O1BHuo0u:beiayru) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But why would the user specify wrong driver option in `config.yaml`? I am missing something here.
</blockquote></details>

This happened with me. I ran gsc with default (i.e. in-kernel driver) config.yaml option. That will assume, I have in-kernel driver on my host system. This in-kernel driver can be 5.11 or lower. When I ran the same gsc image as part of AKS cluster, there it failed with the symbolic link error.  I don't know which in-kernel driver is installed on Azure host system where the container is running, when I create an AKS cluster. So only for the AKS environment, I thought providing symbolic link as part of apploader.sh would be good, until they upgrade their in-kernel driver.   
___
*[examples/aks-attestation/README.md, line 48 at r2](https://reviewable.io/reviews/gramineproject/gsc/11#-MkMONV89l1r4r7yOrvJ:-MkMYoeb8nup7Z67kt5F:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/c93d61a855ed55b493822e255b06c5fb20431286/examples/aks-attestation/README.md#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make this `NOTE` bold or italic.
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/README.md, line 69 at r2](https://reviewable.io/reviews/gramineproject/gsc/11#-MkMOkscEXccMfIUnf-b:-MkMYA4fCQ5pM2qNUbaD:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/c93d61a855ed55b493822e255b06c5fb20431286/examples/aks-attestation/README.md#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`gsc` -> `GSC`
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/README.md, line 91 at r2](https://reviewable.io/reviews/gramineproject/gsc/11#-MkMOf7B63P-4jf6w32J:-MkMY5Zn1fbjIPSaHakQ:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/c93d61a855ed55b493822e255b06c5fb20431286/examples/aks-attestation/README.md#L91)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please make this `NOTE` bold or italic.

Also, `gsc` -> `GSC`.
</blockquote></details>

done, thanks


<!-- Sent from Reviewable.io -->

2021-09-24 11:50 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 6 of 7 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[examples/aks-attestation/README.md, line 48 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_YJ06H03Yg1OWtkJ:-MkMbXjR7C1qK7uwNZ-C:b-cmtm30) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L48)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Sure, I will search. Thanks.
</blockquote></details>

Just to correct my previous statement, in gramine we are doing "non-qve based" dcap verification only. As we are passing /*p_qve_report_info=*/NULL in sgx_qv_verify_quote() . So, I think, I can remove this comment. Also, in  server deployment file there should not be any need for epc reservation.  I will check again by running the server in non-confidential compute node and get back soon. Thanks.


<!-- Sent from Reviewable.io -->

2021-09-24 12:34 UTC, veenasai2 commented
___
*[examples/aks-attestation/README.md, line 48 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_YJ06H03Yg1OWtkJ:-MkMmPDL2RT_8WvzE5te:bwxny3g) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L48)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Just to correct my previous statement, in gramine we are doing "non-qve based" dcap verification only. As we are passing /*p_qve_report_info=*/NULL in sgx_qv_verify_quote() . So, I think, I can remove this comment. Also, in  server deployment file there should not be any need for epc reservation.  I will check again by running the server in non-confidential compute node and get back soon. Thanks.
</blockquote></details>

I just ran the server image as part of AKS cluster without epc reservation. The verification succeeds and the client is receiving the secret. But the server container prints error message

 "[get_driver_type /home/sgx/jenkins/linux-ubuntuServer-release-build-trunk-214/build_target/PROD/label/Builder-UbuntuSrv18/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device."    

Hence, we need to use the confidential compute node for server as well.  Thanks. 


<!-- Sent from Reviewable.io -->

2021-09-27 09:02 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MkaUNVbB2hgurXuKkty:-MkaUNVbB2hgurXuKktz:b-nh07uz) (no related file):*
I'm approving this PR (we'll fix the commit message during final rebase), but please double-check that this latest version works correctly on AKS.

---
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXQ8u5so2mjpXvZBs):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Looks like directly updating at github does not show up. 
</blockquote></details>

Yes, git and GitHub have a one-way relationship: all changes in your git repo are visible on GitHub (after you git-push), but GitHub changes do not affect your git repo.
___
*[examples/aks-attestation/README.md, line 89 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_gpTDncsIMvhLtOH:-MkaTRPz13PZ6QU8kCoI:bb19le) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L89)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

This happened with me. I ran gsc with default (i.e. in-kernel driver) config.yaml option. That will assume, I have in-kernel driver on my host system. This in-kernel driver can be 5.11 or lower. When I ran the same gsc image as part of AKS cluster, there it failed with the symbolic link error.  I don't know which in-kernel driver is installed on Azure host system where the container is running, when I create an AKS cluster. So only for the AKS environment, I thought providing symbolic link as part of apploader.sh would be good, until they upgrade their in-kernel driver.   
</blockquote></details>

I'm resolving this issue because you reverted that change in `apploader.sh`. But in general, you shouldn't re-use the same `config.yaml` file for your *local environment* and for the *AKS environment*. These are two different deployments, so you should use two different configuration files. In other words, you're not supposed to use *the same GSC image* in AKS as you would do on your local machine.


<!-- Sent from Reviewable.io -->

2021-09-27 09:07 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MkaUNVbB2hgurXuKkty:-MkaV-mv54DX8Q-t2plk:b-phsyec) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm approving this PR (we'll fix the commit message during final rebase), but please double-check that this latest version works correctly on AKS.
</blockquote></details>

Pushing couple of fixes in few hours. Thanks. 

---
___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkHXQ8u5so2mjpXvZBs):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, git and GitHub have a one-way relationship: all changes in your git repo are visible on GitHub (after you git-push), but GitHub changes do not affect your git repo.
</blockquote></details>

Ok, thanks.
___
*[examples/aks-attestation/README.md, line 89 at r1](https://reviewable.io/reviews/gramineproject/gsc/11#-MkH_gpTDncsIMvhLtOH:-MkaVP6yCiUh7_g4L9bU:b-jcyzg0) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a51037d3a4ea53f7e7f6939a0d1b8a2d7081/examples/aks-attestation/README.md#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm resolving this issue because you reverted that change in `apploader.sh`. But in general, you shouldn't re-use the same `config.yaml` file for your *local environment* and for the *AKS environment*. These are two different deployments, so you should use two different configuration files. In other words, you're not supposed to use *the same GSC image* in AKS as you would do on your local machine.
</blockquote></details>

ok, thanks. 


<!-- Sent from Reviewable.io -->

2021-09-27 09:47 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 4 of 7 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MkacFuI2meOGqyi-ubW:-MkacFuJCsJSUxMVvslz:b-d5wqde) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
> ```Dockerfile
> WORKDIR /ra-tls-secret-prov
> 
> ENV PATH = "${PATH}:/ra-tls-secret-prov"
> ```

I had to add the path of ra-tls-secret-prov to PATH ENV variable, because I was facing errors "Error during shim_init() in init_important_handles, DkProcessExit: Returning exit code 2" during docker run. This is similar to the issue reported here: https://github.com/gramineproject/graphene/issues/2632
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 34 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mkad_5c0cWByPcmX3h4:-Mkad_5c0cWByPcmX3h5:bvlj0j1) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L34)):*
> ```Dockerfile
> COPY CI-Examples/ra-tls-secret-prov /ra-tls-secret-prov
> 
> RUN mkdir -p /ra-tls-secret-prov/libs
> ```

The below steps are to avoid "error while loading shared libraries: " error.


<!-- Sent from Reviewable.io -->

2021-10-13 09:28 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-Mliilkq-P1_-k6RlELJ:-MlswBYl8-vh1mGdq36o:b-wpb374) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 Could you rebase this PR to the latest master? Now we have the final `v1.0` Gramine release, and a lot of build/install steps and workarounds are not needed anymore. In particular, all executables, utilities, libraries should be found in the Gramine install directory. No need for `ENV` and `COPY` Dockerfile commands.
</blockquote></details>

ok, thanks.

---
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MkacFuI2meOGqyi-ubW:-Mlsw4lq0L_BSO5VleVd:bk7916f) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With the latest Gramine install process, this is not needed. Please remove.
</blockquote></details>

I will check this, thanks. 
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 6 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijrIZ83JZmgyhxl4A:-MlswDVE6rr2Mbsdhnct:bad9j2h) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.manifest#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We now have the ability to propagate env vars from host: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#environment-variables

I suggest to use it here:
```
loader.env.SECRET_PROVISION_SERVERS = { passthrough = true }
```

Then in your `aks-secret-prov-client-deployment.yaml`, you can specify this `SECRET_PROVISION_SERVERS` variable in `env`. This will be much cleaner than asking users to modify the manifest file (please also change the README!).
</blockquote></details>

sure, thanks. 
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 21 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MliiTbN0WINU6-2-4nf:-Mlsm78JEGTUfxTeNXsx:bkf6n13) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.manifest#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you please sort these filenames?
</blockquote></details>

Sure, thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 34 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mkad_5c0cWByPcmX3h4:-MlsjtVQ9CyQfrgsVsvf:bix4xzx) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With the latest Gramine install process, this is not needed. Please remove.
</blockquote></details>

Yes, you are correct! With the latest Gramine install process, these libraries' location is set to the Path. But as part of dockerfile, I am not building Gramine. I just copied the contents of ra-tls-secret-prov example directory. So, the ninja installation paths are not visible inside docker environment and I am still facing the error  "/ra-tls-secret-prov/secret_prov_server_dcap: error while loading shared libraries: libsecret_prov_verify_dcap.so: cannot open shared object file: No such file or directory" with the latest Gramine too.     

Please correct me, if I am missing something here. Thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 42 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MliifGTBwpnnXTnv_pM:-MlsyExGDGTNTLmCRLg6:bi1q2rc) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With the latest Gramine install process, this is not needed. Please remove all of this.
</blockquote></details>

Same reason as above.
___
*[examples/aks-attestation/README.md, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijQOd3ROD4jo50L9Q:-MlsltFg5EPoJdAYnobe:b77i4af) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/README.md#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove `make clean` command from here? It's kinda obvious that you need to rebuild from clean state.
</blockquote></details>

sure, thanks.
___
*[examples/aks-attestation/README.md, line 31 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijXp88EA5BUDQc94o:-Mlslxmy3K3pAtktRWbM:b77i4af) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/README.md#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change to `cd ../../` (otherwise people cannot just copy-paste this command)
</blockquote></details>

sure, thanks.
___
*[examples/aks-attestation/README.md, line 56 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijWzeCm3nv3oy-GKd:-MlslzFE4RMbFZ-Hyso0:b77i4af) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/README.md#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we remove `make clean` command from here? It's kinda obvious that you need to rebuild from clean state.
</blockquote></details>

sure, thanks.
___
*[examples/aks-attestation/README.md, line 57 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mlij_ZB6I2pstU2aQ6b:-Mlsm-ft8RxyjR5SdOtr:b-54avio) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/README.md#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please change to `cd ../../` (otherwise people cannot just copy-paste this command)
</blockquote></details>

Ok, thanks.


<!-- Sent from Reviewable.io -->

2021-10-14 07:30 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MkacFuI2meOGqyi-ubW:-MlxaDiuBuF_F22mYgTD:bcsz2w1) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

I will check this, thanks. 
</blockquote></details>

if I don't update PATH, I am still facing the same error "Error during shim_init() in init_important_handles " with the latest Gramine too. Thanks. 


<!-- Sent from Reviewable.io -->

2021-10-20 13:21 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MmSqhJf8gn8wFbNK_Oc:-MmSqhJf8gn8wFbNK_Od:b-4vkxfr) (no related file):*
So I finally got the main idea/problem of this PR: we first need to have Gramine built on the user machine to generate two base Dockerfiles, and then one of them (client) is run through GSC.

I highly dislike this requirement of "have Gramine built on the user machine". Why can't we put all the logic of "download Gramine, build Gramine and build the ra-tls-secret-prov example" inside each of these two base Dockerfiles? Then the user won't need to install Gramine on her own machine just to test this example. Also, the example will be more self-contained.

Are there any obstacles to this implementation?

---
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 22 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MmSpQ8V64bt6_hYWZVj:-MmSpQ8W5VDOX52TswnZ:b-89ssc5) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L22)):*
> ```Dockerfile
>     libsgx-quote-ex
> 
> # Build environment of this Dockerfile should point to the root of Gramine directory
> ```

Please add that `Also, the ra-tls-secret-prov example must be built.`
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MkacFuI2meOGqyi-ubW:-MmSeNza4kiCWXWf0NO1:b4aw8n4) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

if I don't update PATH, I am still facing the same error "Error during shim_init() in init_important_handles " with the latest Gramine too. Thanks. 
</blockquote></details>

Ok, I finally understand why this is needed.

So, we put the symlink to the actual executable under root of the final GSC image: https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.ubuntu.build.template#L53-L55

And then GSC actually overwrites the GSC image entrypoint: https://github.com/gramineproject/gsc/blob/master/gsc.py#L65 and https://github.com/gramineproject/gsc/blob/master/gsc.py#L82

So the final GSC image has `ENTRYPOINT ["/secret_prov_min_client]"`.

To make the symlink `/secret_prov_min_client -> /ra-tls-secret-prov/secret_prov_min_client`, we execute `which secret_prov_min_client` (see my first link). So for Bash to know where to find `secret_prov_min_client` binary, we need this PATH.

@veenasai2 I don't like this hack... Can we move this `/ra-tls-secret-prov/secret_prov_min_client` under `/usr/bin` or `/usr/local/bin` (which are the default paths for executables)? Then we won't need to play this trick with changing `PATH`.
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 6 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijrIZ83JZmgyhxl4A:-MmSmcFoBzptPo6HI0hA:b-sbz8of) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.manifest#L6)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

sure, thanks. 
</blockquote></details>

I don't see any change.
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 21 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MliiTbN0WINU6-2-4nf:-MmSmkWN14lGcXaa7m9t:bfhqmln) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.manifest#L21)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Sure, thanks.
</blockquote></details>

Not done?
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 28 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MmSpbEU4UNL171u-i2T:-MmSpbEU4UNL171u-i2U:b-mhn9ft) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L28)):*
> ```Dockerfile
> RUN apt-get update && apt-get install -y libsgx-dcap-quote-verify
> 
> # Build environment of this Dockerfile should point to the root of Gramine directory
> ```

You need to add that
```
Also, Gramine must be built under the build/ directory (via `meson setup build/`).
```
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 34 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mkad_5c0cWByPcmX3h4:-MmSprH7DKCSNo_4-DXE:b-e2jrqv) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L34)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Yes, you are correct! With the latest Gramine install process, these libraries' location is set to the Path. But as part of dockerfile, I am not building Gramine. I just copied the contents of ra-tls-secret-prov example directory. So, the ninja installation paths are not visible inside docker environment and I am still facing the error  "/ra-tls-secret-prov/secret_prov_server_dcap: error while loading shared libraries: libsecret_prov_verify_dcap.so: cannot open shared object file: No such file or directory" with the latest Gramine too.     

Please correct me, if I am missing something here. Thanks.
</blockquote></details>

Ah, now I understand. This is a bit brittle (imagine we update from mbedTLS 2.26.0 to say 2.27), I wonder if we can do anything better?

Actually, why not git-clone Gramine in this Dockerfile, build it here (and also build the `ra-tls-secret-prov` server app) and install? Then we won't need to require the user to "point to the root of Gramine directory" and perform any kinds of `COPY`.
___
*[examples/aks-attestation/README.md, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijQOd3ROD4jo50L9Q:-MmSqYur0X09rG65jM3m:b-38xt15) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/README.md#L30)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Also - would it be better to put a script here that automates the gramine and ratls example build? This would make it more automated for the user. @dimakuv  - thoughts? we could enforce this for all gsc examples that leverages the examples repo. 
</blockquote></details>

Yes, I don't mind the automated Bash script.


<!-- Sent from Reviewable.io -->

2021-11-09 13:41 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 2 of 12 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MmSqhJf8gn8wFbNK_Oc:-Mo3v3oK0Zdj7qQZ6MlO:b-28u2uo) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

So I finally got the main idea/problem of this PR: we first need to have Gramine built on the user machine to generate two base Dockerfiles, and then one of them (client) is run through GSC.

I highly dislike this requirement of "have Gramine built on the user machine". Why can't we put all the logic of "download Gramine, build Gramine and build the ra-tls-secret-prov example" inside each of these two base Dockerfiles? Then the user won't need to install Gramine on her own machine just to test this example. Also, the example will be more self-contained.

Are there any obstacles to this implementation?
</blockquote></details>

Added script  gsc/examples/aks-attestation/base-image-generation-script.sh for this purpose. Thanks. 

---
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 22 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MmSpQ8V64bt6_hYWZVj:-Mo3vKVa-WLeaWqVroes:bq964qj) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add that `Also, the ra-tls-secret-prov example must be built.`
</blockquote></details>

Removed this part from this file. Thanks.
___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MkacFuI2meOGqyi-ubW:-Mo3vRYM-4KyBuLJ5tr_:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.dockerfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I finally understand why this is needed.

So, we put the symlink to the actual executable under root of the final GSC image: https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.ubuntu.build.template#L53-L55

And then GSC actually overwrites the GSC image entrypoint: https://github.com/gramineproject/gsc/blob/master/gsc.py#L65 and https://github.com/gramineproject/gsc/blob/master/gsc.py#L82

So the final GSC image has `ENTRYPOINT ["/secret_prov_min_client]"`.

To make the symlink `/secret_prov_min_client -> /ra-tls-secret-prov/secret_prov_min_client`, we execute `which secret_prov_min_client` (see my first link). So for Bash to know where to find `secret_prov_min_client` binary, we need this PATH.

@veenasai2 I don't like this hack... Can we move this `/ra-tls-secret-prov/secret_prov_min_client` under `/usr/bin` or `/usr/local/bin` (which are the default paths for executables)? Then we won't need to play this trick with changing `PATH`.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 6 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijrIZ83JZmgyhxl4A:-Mo3vU1t1ROKnux0wJEw:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.manifest#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see any change.
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 21 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MliiTbN0WINU6-2-4nf:-Mo3tusk5bSAEeWsjdic:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-client.manifest#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done?
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 28 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MmSpbEU4UNL171u-i2T:-Mo3tzDi33vavSvvvuOd:bqfriyb) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You need to add that
```
Also, Gramine must be built under the build/ directory (via `meson setup build/`).
```
</blockquote></details>

moved gramine build steps to base-image-generation-script.sh . Thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 34 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mkad_5c0cWByPcmX3h4:-Mo3uG0w-ZNMi94KmPne:b-bu2cey) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ah, now I understand. This is a bit brittle (imagine we update from mbedTLS 2.26.0 to say 2.27), I wonder if we can do anything better?

Actually, why not git-clone Gramine in this Dockerfile, build it here (and also build the `ra-tls-secret-prov` server app) and install? Then we won't need to require the user to "point to the root of Gramine directory" and perform any kinds of `COPY`.
</blockquote></details>

I thought gramine build steps may make the image heavy in size and also the image creation may take longer time. How about keeping "COPY gramine/build/subprojects/mbedtls-mbedtls-*/libmbedcrypto_gramine.so.* /ra-tls-secret-prov/libs" ? Thanks.
___
*[examples/aks-attestation/README.md, line 30 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-MlijQOd3ROD4jo50L9Q:-Mo3v1XZ7dI2sqrBDbtK:b-ciey3m) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/README.md#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I don't mind the automated Bash script.
</blockquote></details>

ok, thanks


<!-- Sent from Reviewable.io -->

2021-11-16 11:00 UTC, aneessahib commented on examples/aks-attestation/base-image-generation-script.sh
> +# Build Gramine with DCAP enabled mode
Mention that in-kernel driver is assumed. Also point to the build page if the user intends to build with other sgx driver options

2021-11-16 11:06 UTC, aneessahib commented on examples/aks-attestation/README.md
> +This demonstration is created for ``gramine/CI-Examples/ra-tls-secret-prov`` sample. The sample
This demonstration is based on the ra-tls-secret-prov example from ```path``` . Familiarity with this sample is highly recommended before proceeding.

2021-11-16 14:20 UTC, mythi commented on examples/aks-attestation/aks-secret-prov-client-deployment.yaml
> +            kubernetes.azure.com/sgx_epc_mem_in_MiB: 10
should this be `sgx.intel.com/epc: 10Mi`?

2021-11-17 06:23 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 2 of 12 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @mythi)

___
*[examples/aks-attestation/aks-secret-prov-client-deployment.yaml, line 25 at r6](https://reviewable.io/reviews/gramineproject/gsc/11#-Mk6kXV5FsZiJHbPznkZ-r6-25:-MogY00gCIAk8wjzxfoM:bhrgui6) ([raw file](https://github.com/gramineproject/gsc/blob/eb99532b4933a64cd8cc3b8b645f0675d65a8d9a/examples/aks-attestation/aks-secret-prov-client-deployment.yaml#L25)):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

should this be `sgx.intel.com/epc: 10Mi`?
</blockquote></details>

yes, both are correct. I was following Microsoft Azure document : 
   https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-addon . Thanks for reviewing this PR. 
___
*[examples/aks-attestation/base-image-generation-script.sh, line 33 at r6](https://reviewable.io/reviews/gramineproject/gsc/11#-Mo3trYVg26JPOrJjSND-r6-33:-MogZ8ht72Vo-9QR-kDt:b77i4af) ([raw file](https://github.com/gramineproject/gsc/blob/eb99532b4933a64cd8cc3b8b645f0675d65a8d9a/examples/aks-attestation/base-image-generation-script.sh#L33)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Mention that in-kernel driver is assumed. Also point to the build page if the user intends to build with other sgx driver options
</blockquote></details>

sure, thanks.
___
*[examples/aks-attestation/README.md, line 13 at r6](https://reviewable.io/reviews/gramineproject/gsc/11#-Mk6kXV5FsZiJHbPznkY-r6-13:-MogZ0hGEz9MjOZzIsq7:bad9j1v) ([raw file](https://github.com/gramineproject/gsc/blob/eb99532b4933a64cd8cc3b8b645f0675d65a8d9a/examples/aks-attestation/README.md#L13)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

This demonstration is based on the ra-tls-secret-prov example from ```path``` . Familiarity with this sample is highly recommended before proceeding.
</blockquote></details>

sure, thanks.


<!-- Sent from Reviewable.io -->

2021-11-17 06:41 UTC, aneessahib reviewed
> Reviewed 1 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 3 of 12 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/certs/README, line 2 at r6](https://reviewable.io/reviews/gramineproject/gsc/11#-Mogbfjw5B5kPKLf6_Kb:-Mogbfjw5B5kPKLf6_Kc:bxj5sh) ([raw file](https://github.com/gramineproject/gsc/blob/eb99532b4933a64cd8cc3b8b645f0675d65a8d9a/examples/aks-attestation/certs/README#L2)):*
> ```
> This directory contains pre-generated example certificates. In particular:
> ```

Mention here that these certs should not be used in production, and that the user has to generate one with the fields updated in accordance with the respective cluster settings.


<!-- Sent from Reviewable.io -->

2021-11-17 08:43 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 2 of 12 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mythi)

___
*[examples/aks-attestation/certs/README, line 2 at r6](https://reviewable.io/reviews/gramineproject/gsc/11#-Mogbfjw5B5kPKLf6_Kb:-Moh36Pt7Jps-G_psBDy:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/eb99532b4933a64cd8cc3b8b645f0675d65a8d9a/examples/aks-attestation/certs/README#L2)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Mention here that these certs should not be used in production, and that the user has to generate one with the fields updated in accordance with the respective cluster settings.
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-11-17 09:19 UTC, mythi commented on examples/aks-attestation/base-image-generation-script.sh
> +rm -r gramine/
gramine build creates write protected files so add `-f`? Otherwise the script never finishes:

```
rm: remove write-protected regular file 'gramine/build/...
```

2021-11-17 09:37 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 2 of 12 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mythi)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 64 at r7](https://reviewable.io/reviews/gramineproject/gsc/11#-Mo3trYVg26JPOrJjSND-r7-64:-MohE_BG-J6P-uNYC4o5:b3b4blh) ([raw file](https://github.com/gramineproject/gsc/blob/26665c7b4830cd0bac336847b30f5a26d28ebdc8/examples/aks-attestation/base-image-generation-script.sh#L64)):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

gramine build creates write protected files so add `-f`? Otherwise the script never finishes:

```
rm: remove write-protected regular file 'gramine/build/...
```
</blockquote></details>

Done, thanks. Though I did not face any issues while running the script, possibly because of elevated permissions. 


<!-- Sent from Reviewable.io -->

2021-11-17 09:57 UTC, mythi commented
> Done, thanks. Though I did not face any issues while running the script, possibly because of elevated permissions.

ah, right. I made some modifications locally and dropped `apt-get` from the beginning and ran it without `sudo`. I guess this triggers questions like: which parts really need sudo and are there steps that are one-time only and not really meaningful if the script is re-run (e.g. to rebuild the images)

2021-11-17 11:16 UTC, veenasai2 reviewed
That's a good suggestion. We will try to split the script into two such that gramine build part is separate from the image creation part. Thanks. 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11#-:-MohavOE0qc-lvF0nxv6:b-osma2s)* status: 2 of 12 files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mythi)



<!-- Sent from Reviewable.io -->

2021-11-17 13:09 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 2 of 12 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/aks-secret-prov-server-deployment.yaml, line 22 at r8](https://reviewable.io/reviews/gramineproject/gsc/11#-MohuvE95yUd790Xacti:-MohuvE95yUd790Xactj:baiir50) ([raw file](https://github.com/gramineproject/gsc/blob/f8ecf6f3acd0ee5f4bc9dc672ce0955b6ecefcc3/examples/aks-attestation/aks-secret-prov-server-deployment.yaml#L22)):*
> ```YAML
>         resources:
>           limits:
>             kubernetes.azure.com/sgx_epc_mem_in_MiB: 10
> ```

Why is there an SGX-related limit? The server program runs without SGX enclave, so this is not needed.


<!-- Sent from Reviewable.io -->

2021-11-18 11:39 UTC, veenasai2 reviewed
Incorporated your suggestion, thanks. 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11#-:-MompdbNCnt4ahtGgm8y:bmrnt55)* status: 2 of 13 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)



<!-- Sent from Reviewable.io -->

2021-11-24 11:43 UTC, mythi commented on examples/aks-attestation/aks-secret-prov-server.dockerfile
> +WORKDIR /ra-tls-secret-prov
`WORKDIR` creates missing directories so it's enough to refer to `/ra-tls-secret-prov` only once:
```suggestion
WORKDIR /ra-tls-secret-prov

COPY gramine/CI-Examples/ra-tls-secret-prov .
COPY gramine/CI-Examples/ra-tls-secret-prov/secret_prov_server_dcap /usr/local/bin

RUN mkdir libs
COPY gramine/build/Pal/src/host/Linux-SGX/tools/ra-tls/libsecret_prov_verify_dcap.so libs
COPY gramine/build/Pal/src/host/Linux-SGX/tools/common/libsgx_util.so libs
COPY gramine/build/subprojects/mbedtls-mbedtls-2.26.0/libmbedcrypto_gramine.so.6 libs
COPY gramine/build/subprojects/mbedtls-mbedtls-2.26.0/libmbedtls_gramine.so.13 libs
COPY gramine/build/subprojects/mbedtls-mbedtls-2.26.0/libmbedx509_gramine.so.1 libs
```

2021-11-25 09:07 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, 3 of 8 files at r6, 1 of 3 files at r7, 2 of 3 files at r9, 2 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 68 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @mythi, and @veenasai2)

___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 24 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLINQT2kftbeRygFNi:-MpLINQT2kftbeRygFNj:bpbdugs) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-client.dockerfile#L24)):*
> ```Dockerfile
> WORKDIR /ra-tls-secret-prov
> 
> COPY gramine/CI-Examples/ra-tls-secret-prov .
> ```

Do you actually need this COPY now? You copy the `secret_prov_min_client` application inside /usr/local/bin, so I guess having some files in this `.` directory is useless now?
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 1 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLHsS5CmQMrUWndv1r:-MpLHsS5CmQMrUWndv1s:bu4bsho) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-client.manifest#L1)):*
> ```
> # Manifest file for ra-tls-secret-prov min client
> ```

This line is useful. Please remove it, it's obvious.
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 10 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLHzgv-x8tIOyFYkuk:-MpLHzgv-x8tIOyFYkul:b9c46ze) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-client.manifest#L10)):*
> ```
> loader.env.SECRET_PROVISION_CA_CHAIN_PATH = "certs/test-ca-sha256.crt"
> 
> # Request remote attestation functionality from Gramine
> ```

Please remove this comment, it's obvious
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 34 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mkad_5c0cWByPcmX3h4:-MpLLCDdCNb5dLs7H7lo:b-q3dsi5) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L34)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

I thought gramine build steps may make the image heavy in size and also the image creation may take longer time. How about keeping "COPY gramine/build/subprojects/mbedtls-mbedtls-*/libmbedcrypto_gramine.so.* /ra-tls-secret-prov/libs" ? Thanks.
</blockquote></details>

Ok, you git-clone Gramine outside of Dockerfiles, this is also fine with me. I'm resolving this, no need to change here.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 15 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLIyq7Cb1PbhcF0Jqt:-MpLIyqB783JGLN7SECp:b-l8zofg) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-server.dockerfile#L15)):*
> ```Dockerfile
> # Here, the version of az-dcap-client should be in sync with the az-dcap-client
> # version used for quote generation. User can replace the below package with the
> # latest package.
> ```

I don't understand this paragraph. Quote generation happens on the client, but I don't see any `az-dcap-client` installation in the client's dockerfile. How does the client know about `az-dcap-client` then, if it is not installed?
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 30 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLJJHIAtre0eOTwWHr:-MpLJJHIAtre0eOTwWHs:b2o8z5x) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-server.dockerfile#L30)):*
> ```Dockerfile
> WORKDIR /ra-tls-secret-prov
> 
> COPY gramine/CI-Examples/ra-tls-secret-prov .
> ```

Ditto. Do you still need this copy? 
___
*[examples/aks-attestation/base-image-generation-script.sh, line 3 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLJryh4FQYWjBl8t50:-MpLJryk8583tnURPYIg:b-gu3b28) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/base-image-generation-script.sh#L3)):*
> ```Shell
> # Download and build Gramine directory
> 
> gramine_dir="gramine"
> ```

There's no point in having this variable `gramine_dir`, because your helper script `gramine_build.sh` anyhow creates a directory named "gramine" (disregarding `gramine_dir` variable). Also, you do things like `cd gramine/...`, so you're not using this variable even in this file.

So just remove this variable and hard-code "gramine" everywhere.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 25 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKHiz-yvKmdd77A3Y:-MpLKHj21KrSsx3WS8oq:b9c46ze) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/base-image-generation-script.sh#L25)):*
> ```Shell
> docker build -f aks-secret-prov-client.dockerfile -t aks-secret-prov-client-img .
> 
> # Remove Gramine directory
> ```

Please remove this comment, it's obvious
___
*[examples/aks-attestation/gramine_build.sh, line 2 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKRkm6Q9DLW8RLlZ2:-MpLKRkm6Q9DLW8RLlZ3:b49vll6) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/gramine_build.sh#L2)):*
> ```Shell
> # This script assumes that in-kernel driver is installed on the host system.
> # Please refer https://gramine.readthedocs.io/en/latest/building.html#id2 for more details.
> ```

`refer to`
___
*[examples/aks-attestation/gramine_build.sh, line 6 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKf7A8orOvD82Om-X:-MpLKf7A8orOvD82Om-Y:b-drr0de) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/gramine_build.sh#L6)):*
> ```Shell
> # install Gramine dependencies
> 
> apt-get install -y \
> ```

Add `sudo` prefix to this
___
*[examples/aks-attestation/gramine_build.sh, line 25 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKgr-5SjTpLXc4BSP:-MpLKgr-5SjTpLXc4BSQ:b-drr0de) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/gramine_build.sh#L25)):*
> ```Shell
>         wget
> 
> python3 -B -m pip install 'toml>=0.10' 'meson>=0.55'
> ```

Add `sudo` prefix to this
___
*[examples/aks-attestation/gramine_build.sh, line 34 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKttt5TDs6z3X2uOd:-MpLKttt5TDs6z3X2uOe:b-38dj1g) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/gramine_build.sh#L34)):*
> ```Shell
> 
> cd gramine/Pal/src/host/Linux-SGX/signer/
> openssl genrsa -3 -out enclave-key.pem 3072
> ```

No need to cd, simply `openssl genrsa -3 -out gramine/Pal/src/host/Linux-SGX/signer/enclave-key.pem 3072`
___
*[examples/aks-attestation/gramine_build.sh, line 38 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKy4eAcYO9F8BScdv:-MpLKy4eAcYO9F8BScdw:bb29srr) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/gramine_build.sh#L38)):*
> ```Shell
> # Build Gramine with DCAP enabled mode (assuming in-kernel driver)
> 
> cd ../../../../../
> ```

There will be no need in this, see my comment above
___
*[examples/aks-attestation/README.md, line 7 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#- [...]

2021-11-25 09:29 UTC, mythi commented
> How does the client know about `az-dcap-client` then, if it is not installed?

the client uses aesmd and aesmd ends up using `az-dcap-client` but this is transparent to the application.

2021-11-29 08:30 UTC, veenasai2 reviewed
Sorry, I did not understand question. Can you please explain further. 

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11#-:-MpRABVMCKNDo0pa1S3d:b-wkhtjj)* status: 4 of 13 files reviewed, 68 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/aks-secret-prov-client.dockerfile, line 24 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLINQT2kftbeRygFNi:-MpQZ4za3ZTq9NXwJlP4:bt56c1s) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-client.dockerfile#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do you actually need this COPY now? You copy the `secret_prov_min_client` application inside /usr/local/bin, so I guess having some files in this `.` directory is useless now?
</blockquote></details>

Actually we need ra-tls-secret-prov/certs. 
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 1 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLHsS5CmQMrUWndv1r:-MpQdlbP86l5EZNnAxP8:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-client.manifest#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This line is useful. Please remove it, it's obvious.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/aks-secret-prov-client.manifest, line 10 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLHzgv-x8tIOyFYkuk:-MpQeXQDA-JkeoWlEnxx:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-client.manifest#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this comment, it's obvious
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 34 at r4](https://reviewable.io/reviews/gramineproject/gsc/11#-Mkad_5c0cWByPcmX3h4:-MpQy2aR1VGQjaLz1R9U:b-ucfkn4) ([raw file](https://github.com/gramineproject/gsc/blob/1eae0ee5cab0ab6e611e0bdc7bc308e217e1d6ba/examples/aks-attestation/aks-secret-prov-server.dockerfile#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, you git-clone Gramine outside of Dockerfiles, this is also fine with me. I'm resolving this, no need to change here.
</blockquote></details>

Thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 44 at r10](https://reviewable.io/reviews/gramineproject/gsc/11#-Mk6kXV6EAIjH-RGPxq6-r10-44:-MpRAHQ-5jG6lbA7qssT:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/11a24b6b7a3a7bb05ad752f7d3d05dccb31701f4/examples/aks-attestation/aks-secret-prov-server.dockerfile#L44)):*
<details><summary><i>Previously, mythi (Mikko Ylinen) wrote…</i></summary><blockquote>

`WORKDIR` creates missing directories so it's enough to refer to `/ra-tls-secret-prov` only once:
```suggestion
WORKDIR /ra-tls-secret-prov

COPY gramine/CI-Examples/ra-tls-secret-prov .
COPY gramine/CI-Examples/ra-tls-secret-prov/secret_prov_server_dcap /usr/local/bin

RUN mkdir libs
COPY gramine/build/Pal/src/host/Linux-SGX/tools/ra-tls/libsecret_prov_verify_dcap.so libs
COPY gramine/build/Pal/src/host/Linux-SGX/tools/common/libsgx_util.so libs
COPY gramine/build/subprojects/mbedtls-mbedtls-2.26.0/libmbedcrypto_gramine.so.6 libs
COPY gramine/build/subprojects/mbedtls-mbedtls-2.26.0/libmbedtls_gramine.so.13 libs
COPY gramine/build/subprojects/mbedtls-mbedtls-2.26.0/libmbedx509_gramine.so.1 libs
```
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 15 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLIyq7Cb1PbhcF0Jqt:-MpQelJ20PzYLu1hi_79:b-4tt2sm) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-server.dockerfile#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand this paragraph. Quote generation happens on the client, but I don't see any `az-dcap-client` installation in the client's dockerfile. How does the client know about `az-dcap-client` then, if it is not installed?
</blockquote></details>

Yes, at client side we are not installing az-dcap-client. Client will rely on Azure provided aesmd service and that aesmd service will internally call az-dcap-client which is installed on the host machine (or VM on which the cluster is running) .  

To make it further clear

1. Inside server image, i installed az-dcap-client 1.8 ( that can verify v2 format sgx dcap collateral)
 
2. At client side, Azure administrator installed az-dcap-client 1.10 (that generates sgx quote based on v3 format collateral) on the host system , and the aesmd service which is running on the host system will interact with az-dcap-client 1.10.


Now the generated quote is in v3 format in the client container while the server during the verification expects v2 format sgx quote. This may lead to quote verification failure.

Therefore we mentioned both the az-dcap-client should be in sync. Or in other words, user should use the same version of az-dcap-client in the server dockerfile,  for which the basic dcap attestation flow is successful.  

 
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 30 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLJJHIAtre0eOTwWHr:-MpQxkRz3dLpvjSg1M5z:b-tvlcm3) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-server.dockerfile#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ditto. Do you still need this copy? 
</blockquote></details>

replaced entire directory copy to specific directories. Thanks.
___
*[examples/aks-attestation/aks-secret-prov-server-deployment.yaml, line 22 at r8](https://reviewable.io/reviews/gramineproject/gsc/11#-MohuvE95yUd790Xacti:-MpQy4unEdDsnu8bkMG-:b-15l0hj) ([raw file](https://github.com/gramineproject/gsc/blob/f8ecf6f3acd0ee5f4bc9dc672ce0955b6ecefcc3/examples/aks-attestation/aks-secret-prov-server-deployment.yaml#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is there an SGX-related limit? The server program runs without SGX enclave, so this is not needed.
</blockquote></details>

I put a Todo (as discussed) to remove epc memory request once the sgx driver issue is resolved. Thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 3 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLJryh4FQYWjBl8t50:-MpQyeDj8CzeHbas4y2V:b-dtkdrq) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/base-image-generation-script.sh#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There's no point in having this variable `gramine_dir`, because your helper script `gramine_build.sh` anyhow creates a directory named "gramine" (disregarding `gramine_dir` variable). Also, you do things like `cd gramine/...`, so you're not using this variable even in this file.

So just remove this variable and hard-code "gramine" everywhere.
</blockquote></details>

Done, thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 25 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLKHiz-yvKmdd77A3Y:-MpQzKWq8LJhPuECQqdJ:b-r18wie)  [...]

2021-11-29 11:29 UTC, dimakuv requested changes
@mythi Could you expand on your comment? Also, please use Reviewable to comment on the PRs.

> the client uses aesmd and aesmd ends up using `az-dcap-client` but this is transparent to the application.

@veenasai2 I think Mikko didn't have a question but rather explained to me that `az-dcap-client` is not used directly by the client application (during SGX quote generation) but instead via `aesmd`. You explained the same in one of your comments. I think we are clear here.

@veenasai2 In the future, please add the at-username keyword like `@mythi` to your messages so that non-reviewers (like Mikko) get a notification about your questions. Otherwise Mikko will not even know you asked him to elaborate.

> Reviewed 9 of 9 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11#-:-MpfKlb_3WSaZQjjhmy2:b13kmys)* status: all files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @mythi, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQCyr3BJSq1M_h404:-MpfQCyr3BJSq1M_h405:bhf0svx) (no related file):*
We will need to rename `examples` to `Examples` (must start with a capital letter). This is our Gramine convention that we must start enforcing (the convention is basically: if it is not a part of the project itself but rather examples/tests/documentation, it should start with a capital letter).

We'll do it during final rebase.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfS9Vm9SZD9Kv-TvYw:-MpfS9Vm9SZD9Kv-TvYx:bcbyd9q) (no related file):*
Please add a `.gitignore` file here and put at least one line there: `/gramine` (because you could have downloaded `gramine` and put in this directory during the build process -- this should not be reflected in git diff).

---
___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 15 at r11](https://reviewable.io/reviews/gramineproject/gsc/11#-MpLIyq7Cb1PbhcF0Jqt:-MpfMX71BFyUmy9nK0hA:b-cg2oxh) ([raw file](https://github.com/gramineproject/gsc/blob/b264d1367cd088b0650d2b5cf72d1b1f3654e4f1/examples/aks-attestation/aks-secret-prov-server.dockerfile#L15)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Yes, at client side we are not installing az-dcap-client. Client will rely on Azure provided aesmd service and that aesmd service will internally call az-dcap-client which is installed on the host machine (or VM on which the cluster is running) .  

To make it further clear

1. Inside server image, i installed az-dcap-client 1.8 ( that can verify v2 format sgx dcap collateral)
 
2. At client side, Azure administrator installed az-dcap-client 1.10 (that generates sgx quote based on v3 format collateral) on the host system , and the aesmd service which is running on the host system will interact with az-dcap-client 1.10.


Now the generated quote is in v3 format in the client container while the server during the verification expects v2 format sgx quote. This may lead to quote verification failure.

Therefore we mentioned both the az-dcap-client should be in sync. Or in other words, user should use the same version of az-dcap-client in the server dockerfile,  for which the basic dcap attestation flow is successful.  

 





</blockquote></details>

OK, thanks for the detailed answer. I get it now.

SGX software infrastructure is so complicated :( I hope it will finally start to standardize in the upcoming year and be more version-compatible.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 6 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfRtB37iBeSO9UaDgm:-MpfRtB37iBeSO9UaDgn:bo9z4ac) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/base-image-generation-script.sh#L6)):*
> ```Shell
>     echo "\n\n ***** gramine directory exists, proceeding to image generation ***** \n\n"
> else
>     chmod u+x gramine_build.sh
> ```

Why do you need `chmod`? Please simply use `bash ./gramine_build.sh` below and remove this line.
___
*[examples/aks-attestation/gramine_build.sh, line 33 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfN7040eXegxu8vAgl:-MpfN7040eXegxu8vAgm:bk1asrd) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/gramine_build.sh#L33)):*
> ```Shell
> # Generate Signing Key
> 
> cd gramine
> ```

Could you move this `cd gramine` to right-after `git clone ...`? It logically belongs there.
___
*[examples/aks-attestation/README.md, line 13 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfNcjX0TyYZ2c6cOwG:-MpfNcjX0TyYZ2c6cOwH:brgt2kd) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L13)):*
> ```Markdown
> ## Preparing client and server images
> 
> This demonstration is based on the ra-tls-secret-prov example from
> ```

Please put `ra-tls-secret-prov` in single-backticks.
___
*[examples/aks-attestation/README.md, line 25 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfNzsdAz3b3LCpdfov:-MpfNzsdAz3b3LCpdfow:bd7uk2t) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L25)):*
> ```Markdown
> requests to this DNS name. Therefore, for demonstration we updated the example certificates from
> https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/certs by
> replacing "Common Name" field in the server certificate (i.e., `server2-sha256.crt`) from
> ```

`replacing "Common Name"` -> `replacing the "Common Name"`
___
*[examples/aks-attestation/README.md, line 29 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQjAxDcSe7GHBRtGJ:-MpfQjAxDcSe7GHBRtGK:b-f0iz00) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L29)):*
> ```Markdown
> 
> In order to create base client and server images for the AKS environment, user can execute
> `base-image-generation-script.sh` script (with sudo). Since both client and server applications will
> ```

```
the `base-image-generation-script.sh` script
```
___
*[examples/aks-attestation/README.md, line 40 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQrrX-a2eScyHVuPC:-MpfQrrX-a2eScyHVuPD:b-hb4ht4) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L40)):*
> ```Markdown
>    name `aks-secret-prov-server-img:latest`.
> 
> 2. Push server image to Docker Hub or your preferred registry:
> ```

`the server image`
___
*[examples/aks-attestation/README.md, line 48 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQypV7QeDORCLYg9Z:-MpfQypV7QeDORCLYg9_:b9yz8ns) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L48)):*
> ```Markdown
>     ```
> 
> 3. Deploy `aks-secret-prov-server-img:latest` in AKS confidential compute cluster:
> ```

`in the AKS ...`
___
*[examples/aks-attestation/README.md, line 50 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfR4_F-uZBhVg2x6nW:-MpfR4_F-uZBhVg2x6nX:bs2zzqk) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L50)):*
> ```Markdown
> 3. Deploy `aks-secret-prov-server-img:latest` in AKS confidential compute cluster:
>     - Reference deployment file:
>         `gsc/examples/aks-attestation/aks-secret-prov-server-deployment.yaml`
> ```

When the user reads this README, he is already in this directory. So please remove `gsc/examples/aks-attestation/` and leave [...]

2021-11-30 07:39 UTC, veenasai2 reviewed
@dimakuv thanks, got it.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11#-:-MpjOdjxErp47pjHTy0X:b-omq9na)* status: 9 of 14 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfS9Vm9SZD9Kv-TvYw:-MpjP4f68ZyRIOjqNEte:b-wpb374) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a `.gitignore` file here and put at least one line there: `/gramine` (because you could have downloaded `gramine` and put in this directory during the build process -- this should not be reflected in git diff).
</blockquote></details>

ok, thanks.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQCyr3BJSq1M_h404:-MpjRUgt16EeBhPUNphN:b73u6wq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We will need to rename `examples` to `Examples` (must start with a capital letter). This is our Gramine convention that we must start enforcing (the convention is basically: if it is not a part of the project itself but rather examples/tests/documentation, it should start with a capital letter).

We'll do it during final rebase.
</blockquote></details>

ok,thanks.

---
___
*[examples/aks-attestation/base-image-generation-script.sh, line 6 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfRtB37iBeSO9UaDgm:-MpjS8qA2p41aJ-cZ2WK:bh0k8ve) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/base-image-generation-script.sh#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need `chmod`? Please simply use `bash ./gramine_build.sh` below and remove this line.
</blockquote></details>

done, thanks.  
___
*[examples/aks-attestation/gramine_build.sh, line 33 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfN7040eXegxu8vAgl:-MpjShQY9CJDAFKDQPki:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/gramine_build.sh#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move this `cd gramine` to right-after `git clone ...`? It logically belongs there.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 13 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfNcjX0TyYZ2c6cOwG:-MpjSpm9ADxyX7SpS3kZ:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put `ra-tls-secret-prov` in single-backticks.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 25 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfNzsdAz3b3LCpdfov:-MpjT-q07cVKkTY7o4no:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`replacing "Common Name"` -> `replacing the "Common Name"`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 29 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQjAxDcSe7GHBRtGJ:-MpjTEI6CyAr0qw9kKUc:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
the `base-image-generation-script.sh` script
```
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 40 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQrrX-a2eScyHVuPC:-MpjTM869bKhr7iu88Il:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the server image`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 48 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfQypV7QeDORCLYg9Z:-MpjTVDE6cjLJ9GD-3mT:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`in the AKS ...`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 50 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfR4_F-uZBhVg2x6nW:-MpjTcmdEWml2hh0i-ua:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When the user reads this README, he is already in this directory. So please remove `gsc/examples/aks-attestation/` and leave only the actual filename.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 78 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfRBVT2MdTEq5Z0qCU:-MpjUR_00KdjKwOMcImc:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L78)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When the user reads this README, he is already in this directory. So please remove `gsc/examples/aks-attestation/` and leave only the actual filename.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 84 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfOkQVBt1DDc2LbpgR:-MpjUUYfC18dwu0dgcDh:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L84)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`using following` -> `using the following`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 89 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfOpPfDYd0L57OopdK:-MpjUiek5UM9MjZzEpMu:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L89)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the sgxquotehelper daemonset`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 94 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfOyDC-2R1iBftu7vU:-MpjUr326yuFVD_EtsAS:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L94)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the sgxquotehelper plugin`
</blockquote></details>

done, thanks
___
*[examples/aks-attestation/README.md, line 96 at r12](https://reviewable.io/reviews/gramineproject/gsc/11#-MpfP6h507cXQPRrj0-W:-MpjUzqXB10hFFIu_B0d:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/2c4905bbb76028fdec73d14737a94934cf977b38/examples/aks-attestation/README.md#L96)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote [...]

2021-11-30 10:21 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/gramine_build.sh, line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkKq4q6muj3KQwt40B:-MpkKq4q6muj3KQwt40C:beagz77) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/gramine_build.sh#L40)):*
> ```Shell
> meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled -Ddcap=enabled
> ninja -C build/
> sudo ninja -C build/ install
> ```

Wait, this is bad. You install this just-cloned Gramine system-wide. This will silently overwrite any other Gramine version that was previously installed.

You actually need to do the same as you do in GSC with Gramine: install Gramine in some specific directory. For this, you'll need to add `--prefix=...` to `meson setup`.

Then you won't need `sudo` prefix during ninja install. But you'll need to add `PYTHON_PATH`, `PATH`, etc in your Bash scripts.
___
*[examples/aks-attestation/README.md, line 9 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkLYLFArKMb8gNeP7D:-MpkLYLFArKMb8gNeP7E:b-6fn16c) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/README.md#L9)):*
> ```Markdown
> enable Gramine to use AKS components such as AESMD and DCAP quote provider libraries. This guide
> also describes a microservice deployment for the RA-TLS verifier (server) that can be readily
> deployed to the AKS cluster.
> ```

Please add somewhere that this example is Ubuntu-specific (and preferably add a version on which you tested). Because you use Ubuntu-specific commands like `apt-get install` in your scripts.
___
*[examples/aks-attestation/README.md, line 29 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkLkXG8Mc_CfNSK9gz:-MpkLkXG8Mc_CfNSK9h-:b3ih3cj) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/README.md#L29)):*
> ```Markdown
> 
> In order to create base client and server images for the AKS environment, user can execute the
> `base-image-generation-script.sh` script (with sudo). Since both client and server applications will
> ```

Please remove `(with sudo)` -- your scripts already have `sudo` prefix where needed.

Please check this README file for other `sudo` mentions -- I think you had a couple more.


<!-- Sent from Reviewable.io -->

2021-12-01 13:13 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 10 of 14 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 39 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpq6nsA6thfGume6T9l:-Mpq6nsB4ago_JTr4qnZ:b9ujgj6) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/aks-secret-prov-server.dockerfile#L39)):*
> ```Dockerfile
> COPY gramine/meson_build_output/lib/x86_64-linux-gnu/libsecret_prov_verify_dcap.so libs
> COPY gramine/meson_build_output/lib/x86_64-linux-gnu/libsgx_util.so libs
> COPY gramine/meson_build_output/lib/x86_64-linux-gnu/libmbedcrypto_gramine.so.* libs
> ```

@dimakuv , I put a * here, considering if the lib version changes in future. 
___
*[examples/aks-attestation/gramine_build.sh, line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkKq4q6muj3KQwt40B:-MpoXelD57-lPaN7u6Ly:bioq9n8) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/gramine_build.sh#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Wait, this is bad. You install this just-cloned Gramine system-wide. This will silently overwrite any other Gramine version that was previously installed.

You actually need to do the same as you do in GSC with Gramine: install Gramine in some specific directory. For this, you'll need to add `--prefix=...` to `meson setup`.

Then you won't need `sudo` prefix during ninja install. But you'll need to add `PYTHON_PATH`, `PATH`, etc in your Bash scripts.
</blockquote></details>

done, thanks. Base images does not require updating the PATH, as gramine specific executables are being used during gsc build.
___
*[examples/aks-attestation/README.md, line 9 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkLYLFArKMb8gNeP7D:-MpoYuwy8taBDpVbzg62:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add somewhere that this example is Ubuntu-specific (and preferably add a version on which you tested). Because you use Ubuntu-specific commands like `apt-get install` in your scripts.
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/README.md, line 29 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkLkXG8Mc_CfNSK9gz:-MpoZK1W7AXywBG2eHxM:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/README.md#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `(with sudo)` -- your scripts already have `sudo` prefix where needed.

Please check this README file for other `sudo` mentions -- I think you had a couple more.
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-12-01 16:04 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 39 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpq6nsA6thfGume6T9l:-MpqiIcJ7eXSe88hEEyT:brxp9sq) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/aks-secret-prov-server.dockerfile#L39)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

@dimakuv , I put a * here, considering if the lib version changes in future. 
</blockquote></details>

Sounds good.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 1 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqiYvk3a1o4QfzoS6f:-MpqiYvk3a1o4QfzoS6g:b-uvtncy) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L1)):*
> ```Shell
> # Download and build Gramine directory
> ```

Please append smth like: `: we need it to copy ra-tls-secret-prov files and relevant libraries into the server and client Dockerfiles`

Also add a line like `This script also expects Gramine to be installed on the system.`
___
*[examples/aks-attestation/base-image-generation-script.sh, line 12 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqgckJBS3ixXzOFVSl:-MpqgckJBS3ixXzOFVSm:bygtbsk) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L12)):*
> ```Shell
> 
> cd gramine/CI-Examples/ra-tls-secret-prov
> make clean && make dcap
> ```

`make dcap` actually invokes `gramine-manifest`, `gramine-sgx-sign` and so on. These tools will be taken from Gramine which is installed system-wide. (Because you're not re-defining `PATH`, `PYTHON_PATH` and `PKG_CONFIG_PATH`.)

Actually, I don't see a big problem in this, because the user should have Gramine installed on the system (system-wide) anyway, if he is looking at this AKS example.

However, I want to make sure this was your intention: do you assume that Gramine is installed system-wide on the machine? Then the only purpose of building Gramine and installing into `meson_build_output` is to copy the `libsgx*`, `libmbed*` libraries into the Dockerfile.
___
*[examples/aks-attestation/gramine_build.sh, line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkKq4q6muj3KQwt40B:-MpqgXi68Y2brYuh7Ljb:b-a8srza) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/gramine_build.sh#L40)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

done, thanks. Base images does not require updating the PATH, as gramine specific executables are being used during gsc build.
</blockquote></details>

Still not enough. See my other comment.
___
*[examples/aks-attestation/gramine_build.sh, line 31 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpqi0H02eU9jN_4cI7G:-Mpqi0H02eU9jN_4cI7H:b-f19i39) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/gramine_build.sh#L31)):*
> ```Shell
> git clone https://github.com/gramineproject/gramine.git
> cd gramine
> mkdir -p $PWD/meson_build_output
> ```

Please remove `$PWD/`, it is not needed. Simply `mkdir -p meson_build_output`


<!-- Sent from Reviewable.io -->

2021-12-02 09:18 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 12 of 14 files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/aks-secret-prov-server.dockerfile, line 39 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpq6nsA6thfGume6T9l:-Mptea2IAN52VdfbnB_Y:b-ucfkn4) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/aks-secret-prov-server.dockerfile#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

Thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 1 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqiYvk3a1o4QfzoS6f:-Mptfcg_3tV0nFz-XdZY:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please append smth like: `: we need it to copy ra-tls-secret-prov files and relevant libraries into the server and client Dockerfiles`

Also add a line like `This script also expects Gramine to be installed on the system.`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 12 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqgckJBS3ixXzOFVSl:-MpuOr0i-cSLUughn032:b-70grgf) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`make dcap` actually invokes `gramine-manifest`, `gramine-sgx-sign` and so on. These tools will be taken from Gramine which is installed system-wide. (Because you're not re-defining `PATH`, `PYTHON_PATH` and `PKG_CONFIG_PATH`.)

Actually, I don't see a big problem in this, because the user should have Gramine installed on the system (system-wide) anyway, if he is looking at this AKS example.

However, I want to make sure this was your intention: do you assume that Gramine is installed system-wide on the machine? Then the only purpose of building Gramine and installing into `meson_build_output` is to copy the `libsgx*`, `libmbed*` libraries into the Dockerfile.
</blockquote></details>

 @dimakuv  I have put all the three paths. But while building , I am getting error, only if I don't have PKG_CONFIG_PATH set.   

Reason:

LFLAGS += $(shell pkg-config --libs mbedtls_gramine)

https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/Makefile#L53

PATH and PYTHON_PATH are not required for building secret_prov_server_dcap and secret_prov_min_client. 
___
*[examples/aks-attestation/gramine_build.sh, line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/11#-MpkKq4q6muj3KQwt40B:-Mptf4zc5jxbxzh7Unh9:b-fi3dk1) ([raw file](https://github.com/gramineproject/gsc/blob/07fd80d3f26279680c0e948c29ad0deb2619090f/examples/aks-attestation/gramine_build.sh#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Still not enough. See my other comment.
</blockquote></details>

ok, got it. Thanks.
___
*[examples/aks-attestation/gramine_build.sh, line 31 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpqi0H02eU9jN_4cI7G:-Mptf0s_CqWgWjztF3fn:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/gramine_build.sh#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `$PWD/`, it is not needed. Simply `mkdir -p meson_build_output`
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-12-02 10:54 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 13 of 14 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 12 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqgckJBS3ixXzOFVSl:-Mpuj6frEbQ2TP3IND_R:b-cvds06) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L12)):*
I think you misunderstood my point.

There are two possibilities:
1. Your AKS example requires Gramine to be installed system-wide on the machine. Then you can use `gramine-manifest`, `gramine-sgx-get-token` and other Gramine utilities, without the need to download and build Gramine from GitHub. Then the only purpose of downloading and building a separate Gramine version is to copy mbedTLS files and CI-Examples files.
2. Your AKS example is self-contained and does *not* require Gramine to be installed system-wide on the machine. Then you must use `gramine-manifest`, `gramine-sgx-get-token` and other Gramine utilities from the downloaded and built Gramine version (for this, you need to specify PATH, PYTHONPATH and PKGCONFIGPATH). And you also use this downloaded and built Gramine version to copy mbedTLS files and CI-Examples files.

I was under impression that you wanted to go with option 1. And so I left my comments about this option 1.

But now you changed your PR to option 2. I'm fine with this, though I didn't expect this.

> PATH and PYTHON_PATH are not required for building secret_prov_server_dcap and secret_prov_min_client.

They are required if you don't have Gramine installed system-wide. You were only able to build ra-tls-secret-prov files because you have Gramine installed system-wide. To check it, just find a clean Ubuntu machine and try the old version of your PR -- it will fail during steps `make dcap` and `make secret_prov_min_client`.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 2 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-MpukYJv5FU4nKX3iQbe:-MpukQAx9Cxa-7DTT31V:byyhd67) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L2)):*
> ```Shell
> # Download and build Gramine directory. We need it to copy ra-tls-secret-prov files and relevant
> # libraries into the server and client Dockerfiles. This script also expects Gramine to be installed
> ```

Please expand: `We need it to copy ...` -> `we need it to build and copy ...`
___
*[examples/aks-attestation/base-image-generation-script.sh, line 3 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpuk9_U08vk2ztPhquo:-Mpuk9_U08vk2ztPhqup:b-fvcbvy) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L3)):*
> ```Shell
> # Download and build Gramine directory. We need it to copy ra-tls-secret-prov files and relevant
> # libraries into the server and client Dockerfiles. This script also expects Gramine to be installed
> # on the system.
> ```

Well now that you added PATH, PYTHONPATH, PKGCONFIGPATH, this last sentence (`This script also expects ...`) is not needed. Now your example is completely self-contained (it uses the just-built Gramine version, and doesn't use the system-wide version). So please remove this last sentence.

Or am I missing something?
___
*[examples/aks-attestation/base-image-generation-script.sh, line 15 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-MpujR4u5ChFRKCaNGAv:-MpujR4x9vQyU5gT0FK4:b-s826w0) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L15)):*
> ```Shell
> 
> # Include Meson build output Python dir in $PYTHONPATH, needed by gramine-sgx-get-token
> export PYTHONPATH="${PYTHONPATH}:$(find $PWD/gramine/meson_build_output/lib -type d -path '*/site-packages')"
> ```

You should swap these two parts:
```
export PYTHONPATH="$(find $PWD/gramine/meson_build_output/lib -type d -path '*/site-packages'):${PYTHONPATH}"
```

This forces Python to first look at the `gramine/meson_build_output/...` directory first -- exactly what we want. So even if you have Gramine installed system-wide, this script will force Python to use your just-built Gramine version.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 18 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-MpujZF90bYU_x-IEc0n:-MpujZF90bYU_x-IEc0o:b-1cq175) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L18)):*
> ```Shell
> 
> # Include Meson build output packages dir in $PKG_CONFIG_PATH, contains mbedTLS and util libs
> export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(find $PWD/gramine/meson_build_output/lib -type d -path '*/pkgconfig')"
> ```

You should swap these two parts:
```
export PKG_CONFIG_PATH="$(find $PWD/gramine/meson_build_output/lib -type d -path '*/pkgconfig'):${PKG_CONFIG_PATH}"
```


<!-- Sent from Reviewable.io -->

2021-12-02 11:23 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 13 of 14 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 12 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqgckJBS3ixXzOFVSl:-Mpupgq-0RPLMdg3Ggj_:b-58pu30) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you misunderstood my point.

There are two possibilities:
1. Your AKS example requires Gramine to be installed system-wide on the machine. Then you can use `gramine-manifest`, `gramine-sgx-get-token` and other Gramine utilities, without the need to download and build Gramine from GitHub. Then the only purpose of downloading and building a separate Gramine version is to copy mbedTLS files and CI-Examples files.
2. Your AKS example is self-contained and does *not* require Gramine to be installed system-wide on the machine. Then you must use `gramine-manifest`, `gramine-sgx-get-token` and other Gramine utilities from the downloaded and built Gramine version (for this, you need to specify PATH, PYTHONPATH and PKGCONFIGPATH). And you also use this downloaded and built Gramine version to copy mbedTLS files and CI-Examples files.

I was under impression that you wanted to go with option 1. And so I left my comments about this option 1.

But now you changed your PR to option 2. I'm fine with this, though I didn't expect this.

> PATH and PYTHON_PATH are not required for building secret_prov_server_dcap and secret_prov_min_client.

They are required if you don't have Gramine installed system-wide. You were only able to build ra-tls-secret-prov files because you have Gramine installed system-wide. To check it, just find a clean Ubuntu machine and try the old version of your PR -- it will fail during steps `make dcap` and `make secret_prov_min_client`.
</blockquote></details>

Earlier, I  just looked at the Makefile and also renamed some systemwide gramine installation paths and only error I got was for PKGCONFIGPATH. I thought since we are doing just native build (neither gramine-sgx, not gramine), so we will not require gramine-sgx-get-token and other gramine specific utilities.   

But, you are right, I will check on a clean ubuntu machine and get back. Thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 2 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-MpukYJv5FU4nKX3iQbe:-Mpunt089jdL-tIEfrIK:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please expand: `We need it to copy ...` -> `we need it to build and copy ...`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 3 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpuk9_U08vk2ztPhquo:-MpunybjDEo4qu2G5cZW:bdgc6a0) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well now that you added PATH, PYTHONPATH, PKGCONFIGPATH, this last sentence (`This script also expects ...`) is not needed. Now your example is completely self-contained (it uses the just-built Gramine version, and doesn't use the system-wide version). So please remove this last sentence.

Or am I missing something?
</blockquote></details>

@dimakuv  Yes, you are right.  Earlier I understood that "we not only download and build gramine, but we also install it". That's why I kept that statement. 
___
*[examples/aks-attestation/base-image-generation-script.sh, line 15 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-MpujR4u5ChFRKCaNGAv:-Mpuow0N08a01haFpt-2:b-433drz) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should swap these two parts:
```
export PYTHONPATH="$(find $PWD/gramine/meson_build_output/lib -type d -path '*/site-packages'):${PYTHONPATH}"
```

This forces Python to first look at the `gramine/meson_build_output/...` directory first -- exactly what we want. So even if you have Gramine installed system-wide, this script will force Python to use your just-built Gramine version.
</blockquote></details>

Understood!!  Done, thanks. 
___
*[examples/aks-attestation/base-image-generation-script.sh, line 18 at r15](https://reviewable.io/reviews/gramineproject/gsc/11#-MpujZF90bYU_x-IEc0n:-Mpuou75A9BgMAzjSfFI:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/bfb5839f0e4ffb9220a0858bf76f159912b5374f/examples/aks-attestation/base-image-generation-script.sh#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You should swap these two parts:
```
export PKG_CONFIG_PATH="$(find $PWD/gramine/meson_build_output/lib -type d -path '*/pkgconfig'):${PKG_CONFIG_PATH}"
```
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-12-03 08:16 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzMOCDA_tYSL1wXT7q:-MpzMOCDA_tYSL1wXT7r:b3nrtwm) (no related file):*
I think I'm finally happy with this PR (bar the last few comments) :)

---
___
*[examples/aks-attestation/base-image-generation-script.sh, line 12 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqgckJBS3ixXzOFVSl:-MpzL3DZDI7kZ0aOrjMR:b-o3hgtj) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L12)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Earlier, I  just looked at the Makefile and also renamed some systemwide gramine installation paths and only error I got was for PKGCONFIGPATH. I thought since we are doing just native build (neither gramine-sgx, not gramine), so we will not require gramine-sgx-get-token and other gramine specific utilities.   

But, you are right, I will check on a clean ubuntu machine and get back. Thanks.
</blockquote></details>

@veenasai2 I was wrong, you were right. I take my words back.

What you do in this bash script is `make dcap` and then `make secret_prov_min_client`. These correspond to this in the ra-tls-secret-prov Makefile:
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/Makefile#L53-L54
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/Makefile#L59-L60

These Makefile targets indeed only perform a native build (simply `gcc <output> <input>`, no Gramine involvement). I was under the impression that these Makefile targets also invoke Gramine utilities like `gramine-manifest` and `gramine-sgx-get-token`.

Thanks for explaining my error to me. You are right, we only need `PKGCONFIGPATH` and don't need the other two variables.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 1 at r16](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzLzla13OfrXzJErjU:-MpzLzlb6_BBkwBNZYED:b-k4jfiy) ([raw file](https://github.com/gramineproject/gsc/blob/395059dffaa31a0e617cc3bc443b29b031c327af/examples/aks-attestation/base-image-generation-script.sh#L1)):*
> ```Shell
> # Download and build Gramine directory. We need it to build and copy ra-tls-secret-prov files and
> ```

Please remove `directory`. One can't "build directory", it's broken English.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 11 at r16](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzLp5G8QRitwa4BDD9:-MpzLp5G8QRitwa4BDDA:b-c0l9i) ([raw file](https://github.com/gramineproject/gsc/blob/395059dffaa31a0e617cc3bc443b29b031c327af/examples/aks-attestation/base-image-generation-script.sh#L11)):*
> ```Shell
> 
> # Include Meson build output directory in $PATH
> export PATH="$PWD/gramine/meson_build_output/bin:$PATH"
> ```

Please remove these two lines, we don't need `PATH`
___
*[examples/aks-attestation/base-image-generation-script.sh, line 14 at r16](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzLsIICJUU1uFv28x4:-MpzLsIICJUU1uFv28x5:bugvhdq) ([raw file](https://github.com/gramineproject/gsc/blob/395059dffaa31a0e617cc3bc443b29b031c327af/examples/aks-attestation/base-image-generation-script.sh#L14)):*
> ```Shell
> 
> # Include Meson build output Python dir in $PYTHONPATH, needed by gramine-sgx-get-token
> export PYTHONPATH="$(find $PWD/gramine/meson_build_output/lib -type d -path '*/site-packages'):${PYTHONPATH}"
> ```

Please remove these two lines, we don't need `PYTHONPATH`


<!-- Sent from Reviewable.io -->

2021-12-03 08:39 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 12 at r14](https://reviewable.io/reviews/gramineproject/gsc/11#-MpqgckJBS3ixXzOFVSl:-MpzOQt5CJOh5asI3fZS:b-jcyzg0) ([raw file](https://github.com/gramineproject/gsc/blob/5442d9e78a5c70cafcdde54f6d57a673d2488e68/examples/aks-attestation/base-image-generation-script.sh#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@veenasai2 I was wrong, you were right. I take my words back.

What you do in this bash script is `make dcap` and then `make secret_prov_min_client`. These correspond to this in the ra-tls-secret-prov Makefile:
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/Makefile#L53-L54
- https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/Makefile#L59-L60

These Makefile targets indeed only perform a native build (simply `gcc <output> <input>`, no Gramine involvement). I was under the impression that these Makefile targets also invoke Gramine utilities like `gramine-manifest` and `gramine-sgx-get-token`.

Thanks for explaining my error to me. You are right, we only need `PKGCONFIGPATH` and don't need the other two variables.
</blockquote></details>

ok, thanks. 
___
*[examples/aks-attestation/base-image-generation-script.sh, line 1 at r16](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzLzla13OfrXzJErjU:-MpzNb4NDJeEtuNxUBh6:beaonw6) ([raw file](https://github.com/gramineproject/gsc/blob/395059dffaa31a0e617cc3bc443b29b031c327af/examples/aks-attestation/base-image-generation-script.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove `directory`. One can't "build directory", it's broken English.
</blockquote></details>

done, thanks. 
___
*[examples/aks-attestation/base-image-generation-script.sh, line 11 at r16](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzLp5G8QRitwa4BDD9:-MpzO1ET2Zmu7Re1Rgv1:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/395059dffaa31a0e617cc3bc443b29b031c327af/examples/aks-attestation/base-image-generation-script.sh#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove these two lines, we don't need `PATH`
</blockquote></details>

done, thanks.
___
*[examples/aks-attestation/base-image-generation-script.sh, line 14 at r16](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzLsIICJUU1uFv28x4:-MpzO9HW7dMRm1_rvjAG:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/395059dffaa31a0e617cc3bc443b29b031c327af/examples/aks-attestation/base-image-generation-script.sh#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove these two lines, we don't need `PYTHONPATH`
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-12-03 08:50 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 10 of 14 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 2 at r17](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzSOMh2U4kM-I_6oeN:-MpzSOMh2U4kM-I_6oeO:b-wwc2p5) ([raw file](https://github.com/gramineproject/gsc/blob/0ae230b75b1809fa429473f8daa13eb8b2dbcdf2/examples/aks-attestation/base-image-generation-script.sh#L2)):*
> ```Shell
> # Download and build Gramine. We need it to build and copy ra-tls-secret-prov files and
> # relevant libraries into the server and client Dockerfiles.
> ```

@dimakuv I removed spaces after comment statements to follow gsc and gramine convention for script and dockerfiles
 
https://github.com/gramineproject/gsc/blob/master/templates/apploader.template#L11

https://github.com/gramineproject/gramine/blob/master/.ci/ubuntu18.04.dockerfile#L4

Thanks.


<!-- Sent from Reviewable.io -->

2021-12-03 08:56 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 3 files at r17, 2 of 2 files at r18, all commit messages.
> Dismissed @veenasai2 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mythi, and @veenasai2)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 2 at r17](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzSOMh2U4kM-I_6oeN:-MpzUZvp9QCOnur1jdu3:b6zcc3v) ([raw file](https://github.com/gramineproject/gsc/blob/0ae230b75b1809fa429473f8daa13eb8b2dbcdf2/examples/aks-attestation/base-image-generation-script.sh#L2)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

@dimakuv I removed spaces after comment statements to follow gsc and gramine convention for script and dockerfiles
 
https://github.com/gramineproject/gsc/blob/master/templates/apploader.template#L11

https://github.com/gramineproject/gramine/blob/master/.ci/ubuntu18.04.dockerfile#L4

Thanks.
</blockquote></details>

Thanks, looks good


<!-- Sent from Reviewable.io -->

2021-12-03 10:53 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 13 of 14 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/gramine_build.sh, line 34 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpzu8e28dlcQd_KIGJJ:-Mpzu8e28dlcQd_KIGJK:b4zk5xh) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/gramine_build.sh#L34)):*
> ```Shell
> openssl genrsa -3 -out Pal/src/host/Linux-SGX/signer/enclave-key.pem 3072
> 
> # Install DCAP dependencies
> ```

@dimakuv  after running the script on a clean system with fresh ubuntu installation, I found that dcap headers (that's why libsgx-dcap-quote-verify-dev, instead of just libsgx-dcap-quote-verify)  are also required for meson setup build to proceed with -Ddcap=enabled option. Thanks. 
___
*[examples/aks-attestation/gramine_build.sh, line 39 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpzv-G5AedCj1vG7ucs:-Mpzv-G6B5L2GiUJO2OS:b-mvipyg) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/gramine_build.sh#L39)):*
> ```Shell
> wget https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key
> sudo apt-key add intel-sgx-deb.key
> sudo apt-get install -y libsgx-dcap-quote-verify-dev
> ```

@dimakuv Here, I have question that should we go with "--no-install-recommends " , because so many other sgx libraries are getting installed with this command?


<!-- Sent from Reviewable.io -->

2021-12-03 11:24 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 13 of 14 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/README.md, line 33 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mq--ChjDrNZ6b41sdW8:-Mq--ChjDrNZ6b41sdW9:b-7ceqvw) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/README.md#L33)):*
> ```Markdown
> server for verification, therefore the user needs to graminize the client application. Hence, the
> following two steps create a native Docker server image and a graminized GSC client image for the
> AKS cluster.
> ```

@dimakuv  Should we mention that "Before proceeding further user should check gsc prerequisites at "https://graphene.readthedocs.io/en/latest/manpages/gsc.html." ?


<!-- Sent from Reviewable.io -->

2021-12-03 11:28 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 13 of 14 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzMOCDA_tYSL1wXT7q:-Mq-1WzD9bUrNnFDUkcj:bxomqd0) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think I'm finally happy with this PR (bar the last few comments) :)
</blockquote></details>

@dimakuv thanks. Now I tested the PR completely on a clean system and everything is working smooth. Thanks.

---


<!-- Sent from Reviewable.io -->

2021-12-06 08:26 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/gramine_build.sh, line 34 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpzu8e28dlcQd_KIGJJ:-MqDqQO01XwZnuSwh_oc:b2nhll9) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/gramine_build.sh#L34)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

@dimakuv  after running the script on a clean system with fresh ubuntu installation, I found that dcap headers (that's why libsgx-dcap-quote-verify-dev, instead of just libsgx-dcap-quote-verify)  are also required for meson setup build to proceed with -Ddcap=enabled option. Thanks. 
</blockquote></details>

Ok.
___
*[examples/aks-attestation/gramine_build.sh, line 39 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpzv-G5AedCj1vG7ucs:-MqDpurJ5WU7Dj4ap89L:b-5s9e27) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/gramine_build.sh#L39)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

@dimakuv Here, I have question that should we go with "--no-install-recommends " , because so many other sgx libraries are getting installed with this command?
</blockquote></details>

Does it work correctly with your suggested flag `--no-install-recommends` on the clean system? If everything works correctly, then sure, add this flag. From what I've read on the internet, adding this flag may make the installed packages to behave incorrectly.
___
*[examples/aks-attestation/README.md, line 33 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mq--ChjDrNZ6b41sdW8:-MqDqFuED3QmzGLEWrWM:bmu4kaq) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/README.md#L33)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

@dimakuv  Should we mention that "Before proceeding further user should check gsc prerequisites at "https://graphene.readthedocs.io/en/latest/manpages/gsc.html." ?
</blockquote></details>

I don't think so. It's quite obvious that if the user wants to try this GSC example, the user is supposed to know how GSC works and is supposed to install all prerequisites.


<!-- Sent from Reviewable.io -->

2021-12-06 11:04 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 13 of 14 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/gramine_build.sh, line 39 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpzv-G5AedCj1vG7ucs:-MqEOJ8mCcHV4U6Icj_W:b-5vqib0) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/gramine_build.sh#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Does it work correctly with your suggested flag `--no-install-recommends` on the clean system? If everything works correctly, then sure, add this flag. From what I've read on the internet, adding this flag may make the installed packages to behave incorrectly.
</blockquote></details>

yes with --no-install-recommends everything works fine. One additional library "libsgx-urts" required due to the below dependency 

https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-secret-prov/Makefile#L54

thanks.
___
*[examples/aks-attestation/README.md, line 33 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mq--ChjDrNZ6b41sdW8:-MqEOtYNBdI3glmKMDiY:bilzyb) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/README.md#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think so. It's quite obvious that if the user wants to try this GSC example, the user is supposed to know how GSC works and is supposed to install all prerequisites.
</blockquote></details>

Ok, thanks. Actually, if someone just follows the README.md here and then at step "Create the GSC client image:" without gsc prerequisites, gsc build will fail on a clean system. Thanks. 


<!-- Sent from Reviewable.io -->

2021-12-06 14:46 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/README.md, line 33 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mq--ChjDrNZ6b41sdW8:-MqFC5Rp6dEizWwgahQ0:b4nbqb6) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/README.md#L33)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Ok, thanks. Actually, if someone just follows the README.md here and then at step "Create the GSC client image:" without gsc prerequisites, gsc build will fail on a clean system. Thanks. 
</blockquote></details>

It's ok if `gsc build` fails. If someone didn't install all pre-requisites of GSC before running this example, they will go to the GSC documentation and will quickly find that they need to install some pre-requisites. So I don't see a problem.


<!-- Sent from Reviewable.io -->

2021-12-08 11:41 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/README.md, line 82 at r20](https://reviewable.io/reviews/gramineproject/gsc/11#-MqOnZRMAA_qLdszdRdr:-MqOnZRMAA_qLdszdRds:b-eglg9t) ([raw file](https://github.com/gramineproject/gsc/blob/052f683d9cbd78c757f05b879d700d598dcfa58e/examples/aks-attestation/README.md#L82)):*
> ```Markdown
>         `aks-secret-prov-client-deployment.yaml`
> 
> Note: We tested this example with DCAP driver 1.11 specified in the GSC configuration file.
> ```

Shouldn't we be putting this note just when step 2 starts? So that the user can modify the config.yaml file accordingly. @dimakuv thoughts? 


<!-- Sent from Reviewable.io -->

2021-12-08 13:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/README.md, line 82 at r20](https://reviewable.io/reviews/gramineproject/gsc/11#-MqOnZRMAA_qLdszdRdr:-MqP8F-vClK8JwX709G_:b-1srmdd) ([raw file](https://github.com/gramineproject/gsc/blob/052f683d9cbd78c757f05b879d700d598dcfa58e/examples/aks-attestation/README.md#L82)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Shouldn't we be putting this note just when step 2 starts? So that the user can modify the config.yaml file accordingly. @dimakuv thoughts? 
</blockquote></details>

Sure, let's move this note to step 2.


<!-- Sent from Reviewable.io -->

2021-12-08 13:40 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/11)* status: 11 of 14 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, @mythi, and @veenasai2)

___
*[examples/aks-attestation/base-image-generation-script.sh, line 2 at r17](https://reviewable.io/reviews/gramineproject/gsc/11#-MpzSOMh2U4kM-I_6oeN:-MqPGXGoDtmrLZQ1-j3T:b-ucfkn4) ([raw file](https://github.com/gramineproject/gsc/blob/0ae230b75b1809fa429473f8daa13eb8b2dbcdf2/examples/aks-attestation/base-image-generation-script.sh#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, looks good
</blockquote></details>

Thanks.
___
*[examples/aks-attestation/gramine_build.sh, line 34 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mpzu8e28dlcQd_KIGJJ:-MqPGQ2P58RFtaVeurMz:b-zcjvte) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/gramine_build.sh#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

Thanks
___
*[examples/aks-attestation/README.md, line 33 at r19](https://reviewable.io/reviews/gramineproject/gsc/11#-Mq--ChjDrNZ6b41sdW8:-MqPGMI64UpcFdq_UhbL:b-wpb374) ([raw file](https://github.com/gramineproject/gsc/blob/06a63d75e5b342d8377ada413e9f596b23368223/examples/aks-attestation/README.md#L33)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's ok if `gsc build` fails. If someone didn't install all pre-requisites of GSC before running this example, they will go to the GSC documentation and will quickly find that they need to install some pre-requisites. So I don't see a problem.
</blockquote></details>

ok, thanks.
___
*[examples/aks-attestation/README.md, line 82 at r20](https://reviewable.io/reviews/gramineproject/gsc/11#-MqOnZRMAA_qLdszdRdr:-MqPGUTG8IpGDWhbAD0-:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/052f683d9cbd78c757f05b879d700d598dcfa58e/examples/aks-attestation/README.md#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sure, let's move this note to step 2.
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-12-08 17:22 UTC, veenasai2 commented
This PR is superseded by https://github.com/gramineproject/gsc/pull/38. Thanks

2021-12-08 17:22 UTC, closed without merging