Remove `gramine-sgx-get-token` invocation
gramineproject/gsc pull request #127
Opened 2023-02-14 14:26 UTC by dimakuv

## Description of the changes 

Gramine v1.4 deprecates its explicit usage. If needed, `gramine-sgx` gets the token automatically.

## How to test this PR? 

Manually run and check there is no warning about `gramine-sgx-get-token` deprecation anymore.

2023-02-14 14:28 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-02-14 14:31 UTC, woju requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`templates/centos/apploader.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/127#-NOFKNyl2Ic1iiPpc0cU:-NOFKNyn1VOuvY7rTSQj:b-ijphj2) ([raw file](https://github.com/gramineproject/gsc/blob/7d94c5857903ede2a8a9b14d6211c354f28f173b/templates/centos/apploader.template#L5)):*
> ```
> {% block path %}
> # Include Meson build output Python dir in $PYTHONPATH, needed by gramine-sgx-get-token
> export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib64 -type d -path '*/site-packages')"
> ```

If this was needed before, then it's still needed. `gramine-sgx-get-token`, if needed, is launched, but `gramine-sgx` doesn't adjust `PYTHONPATH`.
___
*[`templates/debian/apploader.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/127#-NOFK1863GLuvzQlbzLw:-NOFK1863GLuvzQlbzLx:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/7d94c5857903ede2a8a9b14d6211c354f28f173b/templates/debian/apploader.template#L5)):*
> ```
> {% block path %}
> # Include Meson build output Python dir in $PYTHONPATH, needed by gramine-sgx-get-token
> export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')"
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-02-14 14:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: 2 of 4 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`templates/centos/apploader.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/127#-NOFKNyl2Ic1iiPpc0cU:-NOFLFdk7ZPC1WOhui1C:b-c2f4ec) ([raw file](https://github.com/gramineproject/gsc/blob/7d94c5857903ede2a8a9b14d6211c354f28f173b/templates/centos/apploader.template#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

If this was needed before, then it's still needed. `gramine-sgx-get-token`, if needed, is launched, but `gramine-sgx` doesn't adjust `PYTHONPATH`.
</blockquote></details>

Done, you're right...
___
*[`templates/debian/apploader.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/127#-NOFK1863GLuvzQlbzLw:-NOFLFHI8Sg_lzslGlbb:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7d94c5857903ede2a8a9b14d6211c354f28f173b/templates/debian/apploader.template#L5)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-14 14:44 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-02-14 17:23 UTC, woju submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-02-14 19:54 UTC, woju approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-02-15 02:06 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/127)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-15 02:08 UTC, merged