Add LD_LIBRARY_PATH to debian entrypoint manifest
gramineproject/gsc pull request #136
Opened 2023-03-20 08:53 UTC by jkr0103

## Description of the changes 

This PR add Missing `LD_LIBRARY_PATH` in debian entrypoint manifest.

Fixes #135 

## How to test this PR? 

Create GSC image using curation framework for MySQL with PR https://github.com/gramineproject/contrib/pull/40 and shoule be able to run it.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gsc/136)

2023-03-20 09:05 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/136#-NQyFWHQAz7MfO8UNeWW):*
`Debian` (with capital letter)

`LD_LIBRARY_PATH` should be in backticks
___
*[`templates/debian/entrypoint.manifest.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/136#-NQyFnGr7TExzkiRy2sr:-NQyFnGr7TExzkiRy2ss:bbecr7p) ([raw file](https://github.com/gramineproject/gsc/blob/f746d8168be6c14801e40407a150bbc2eaa4c533/templates/debian/entrypoint.manifest.template#L6)):*
> ```
> loader.entrypoint = "file:/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/libsysdb.so"
> 
> # ldconfig in Ubuntu 21.04 doesn't produce "/usr/lib/x86_64-linux-gnu" so add it explicitly
> ```

It's a bit weird to see this comment in the Debian file, so I suggest to change the comment a bit:
```
# add "/usr/lib/x86_64-linux-gnu" explicitly because ldconfig in Ubuntu 21.04 doesn't
# produce it; note that this Debian template is used by Ubuntu templates as well
```


<!-- Sent from Reviewable.io -->

2023-03-20 09:16 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/136#-NQyFWHQAz7MfO8UNeWW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Debian` (with capital letter)

`LD_LIBRARY_PATH` should be in backticks
</blockquote></details>

Done.
___
*[`templates/debian/entrypoint.manifest.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/136#-NQyFnGr7TExzkiRy2sr:-NQyIcCqAZrt6vXdplOu:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f746d8168be6c14801e40407a150bbc2eaa4c533/templates/debian/entrypoint.manifest.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's a bit weird to see this comment in the Debian file, so I suggest to change the comment a bit:
```
# add "/usr/lib/x86_64-linux-gnu" explicitly because ldconfig in Ubuntu 21.04 doesn't
# produce it; note that this Debian template is used by Ubuntu templates as well
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-20 09:34 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/136#-NQyFWHQAz7MfO8UNeWW):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Forgot to capitalize `Debian`?


<!-- Sent from Reviewable.io -->

2023-03-20 09:39 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/136#-NQyFWHQAz7MfO8UNeWW):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to capitalize `Debian`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-20 09:57 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-03-20 15:58 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2023-03-21 10:49 UTC, woju approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/136)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-21 11:39 UTC, merged