Add a note on bloated auto-generated manifest file
gramineproject/gsc pull request #137
Opened 2023-03-22 09:18 UTC by dimakuv

## Description of the changes 

As discussed in the Gramine meeting (see https://github.com/gramineproject/gramine/discussions/1232), there is a concern that users may not know about the "bloated" problem of the original Docker image, assuming that GSC is so smart as to generate the minimal required manifest file for Gramine.

This is not true, GSC is pretty dumb in this regard, so a bloated and suboptimal original Docker image will result in a bloated and suboptimal manifest file (and thus e.g. performance problems when using the final GSC-generated Docker image).

This PR adds a note about this.

## How to test this PR? 

N/A.

2023-03-24 02:05 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/137)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`README.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/gsc/137#-NRGLpD6ARf_cynfY25Z:-NRGLpD71Ai1Mk6Mil-5:b-v6zhph) ([raw file](https://github.com/gramineproject/gsc/blob/c3238808b972912c60f5446f6320c7b0a257f4dd/README.rst#L31)):*
> ```reStructuredText
> **NOTE**: As part of the ``gsc build`` step, GSC generates the manifest file
> with a list of trusted files (files with integrity protection). This list
> contains *all* files present in the original Docker image. Therefore, GSC's
> ```

Just to be sure that users won't misunderstand this.



_Suggestion:_
```reStructuredText
contains hashes of *all* files present
```
___
*[`Documentation/index.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/gsc/137#-NRGLsY43jx-pILSAq6H:-NRGLsY43jx-pILSAq6I:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/c3238808b972912c60f5446f6320c7b0a257f4dd/Documentation/index.rst#L31)):*
> ```reStructuredText
> **NOTE**: As part of the :command:`gsc build` step, GSC generates the manifest
> file with a list of trusted files (files with integrity protection). This list
> contains *all* files present in the original Docker image. Therefore, GSC's
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-03-24 08:22 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/137)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`README.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/gsc/137#-NRGLpD6ARf_cynfY25Z:-NRHhAHk9CD5Vc6DlxXn:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c3238808b972912c60f5446f6320c7b0a257f4dd/README.rst#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Just to be sure that users won't misunderstand this.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 31 at r1](https://reviewable.io/reviews/gramineproject/gsc/137#-NRGLsY43jx-pILSAq6H:-NRHhYrEE9g0Esv3r7Mt:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c3238808b972912c60f5446f6320c7b0a257f4dd/Documentation/index.rst#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-27 01:13 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/137)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-03-28 17:23 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/137)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-03-28 18:03 UTC, merged