Remove Gramine dependencies that are not needed at runtime
gramineproject/gsc pull request #144
Opened 2023-04-13 12:18 UTC by amathew3

Remove Gramine packages that are not needed at runtime. These packages are needed in build time and not needed in run time.

2023-04-14 09:31 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amathew3)

___
*[`gsc.py` line 347 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz4yb77RwN6L4RxcIF:-NSz4yb77RwN6L4RxcIG:bh4swpd) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/gsc.py#L347)):*
> ```Python
>     # using the user-provided config file with info on OS distro, Gramine version and SGX driver
>     env = jinja2.Environment()
>     env.globals.update(yaml.safe_load(args.config_file))
> ```

After this line, you should add `env.globals.update(vars(args))`
___
*[`gsc.py` line 370 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz512J21cUtKv3Dwuu:-NSz512J21cUtKv3Dwuv:bpcch3e) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/gsc.py#L370)):*
> ```Python
>         build_docker_image(docker_socket.api, tmp_build_path, signed_image_name, 'Dockerfile.sign',
>                            forcerm=True, buildargs={"passphrase": args.passphrase,
>                            "remove_gramine_deps":str(args.remove_gramine_deps)})
> ```

This is wrong, please revert this. You should use Jinja-style variables, not `ARG` Dockerfile variables.
___
*[`gsc.py` line 515 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz3KepDyxoop_0J09Q:-NSz3KepDyxoop_0J09R:b-o8kgyo) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/gsc.py#L515)):*
> ```Python
> sub_sign.add_argument('-p', '--passphrase', help='Passphrase for the signing key.')
> sub_sign.add_argument('--remove-gramine-deps', action='store_true',
>     help='Remove Gramine dependencies that are not needed at runtime')
> ```

Please add a dot at the end of the sentence
___
*[`Documentation/index.rst` line 176 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz39V8E00QRZ5IJ72q:-NSz39V8E00QRZ5IJ72r:b-whd0bp) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/Documentation/index.rst#L176)):*
> ```reStructuredText
>    Remove Gramine dependencies that are not needed at runtime. This may have
>    a negative side effect of removing even those dependencies that are actually
>    needed by the original application.
> ```

Please also add a sentence at the end `Use with care!`
___
*[`templates/Dockerfile.common.sign.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz3XPk3e4RldLkSxh8:-NSz3XPk3e4RldLkSxh9:btbyyje) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/Dockerfile.common.sign.template#L21)):*
> ```
> COPY --from=unsigned_image /gramine/app_files/*.sgx /gramine/app_files/
> 
> {% block uninstall %}{% endblock %}
> ```

This will not work on non-root images, because uninstalling packages requires root privileges. Just try some non-root image for yourself, and you'll see how GSC fails here.

You'll need to surround this block with something like this:
- https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/templates/Dockerfile.common.build.template#L11-L12
- https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/templates/Dockerfile.common.build.template#L26-L27

And please test with root and non-root images, to make sure it works in all cases.
___
*[`templates/centos/Dockerfile.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5C9C6UTz6ghPk3VI:-NSz5C9C6UTz6ghPk3VJ:b-hglm6o) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L4)):*
> ```
> 
> {% block uninstall %}
> ARG remove_gramine_deps
> ```

That's wrong. You don't want Dockerfile arguments, you want to use Jinja-style variables. See my other comment.
___
*[`templates/centos/Dockerfile.sign.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz3zSi2GegHUOom4ay:-NSz3zSi2GegHUOom4az:b-93exz) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L5)):*
> ```
> {% block uninstall %}
> ARG remove_gramine_deps
> RUN if [ "$remove_gramine_deps" = "True" ];then \
> ```

The `RUN` keyword should be under the if body, like this:
```
{% if remove_gramine_deps %}
RUN \
       dnf update -y \
...
{% endif %}
```
___
*[`templates/centos/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5gXhETPRwwS2cWna:-NSz5gXhETPRwwS2cWnb:b8bn4jp) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L6)):*
> ```
> ARG remove_gramine_deps
> RUN if [ "$remove_gramine_deps" = "True" ];then \
>        dnf update -y \
> ```

Why do you need this update?
___
*[`templates/centos/Dockerfile.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5Yok529VnhBmyOLW:-NSz5Yok529VnhBmyOLX:bs53ywt) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L7)):*
> ```
> RUN if [ "$remove_gramine_deps" = "True" ];then \
>        dnf update -y \
>        && dnf install -y python3-pip \
> ```

You must install `pip` to uninstall the previously-installed Python packages (like `click`), do I understand correctly?
___
*[`templates/debian/Dockerfile.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5QeQ094ypo4F-dj8:-NSz5QeQ094ypo4F-dj9:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L4)):*
> ```
> 
> {% block uninstall %}
> ARG remove_gramine_deps
> ```

ditto
___
*[`templates/debian/Dockerfile.sign.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5RWbBQx0rUJWw8ZK:-NSz5RWc0TGVfM7PpKTc:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L5)):*
> ```
> {% block uninstall %}
> ARG remove_gramine_deps
> RUN if [ "$remove_gramine_deps" = "True" ];then \ 
> ```

ditto
___
*[`templates/debian/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5j2f0vBSK0PyOf5L:-NSz5j2f0vBSK0PyOf5M:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L6)):*
> ```
> ARG remove_gramine_deps
> RUN if [ "$remove_gramine_deps" = "True" ];then \ 
>        apt update -y \
> ```

ditto
___
*[`templates/debian/Dockerfile.sign.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5SqABpstYzhbZ5aN:-NSz5SqABpstYzhbZ5aO:bmvc5wm) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L18)):*
> ```
>           python3-pyelftools \
>        && apt autoremove -y \
>        && rm -rf /var/lib/apt/lists/*; \
> ```

Why this additional `rm`?


<!-- Sent from Reviewable.io -->

2023-04-17 05:51 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 0 of 5 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 347 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz4yb77RwN6L4RxcIF:-NTCfO6g0JhpcaSmqv4R:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/gsc.py#L347)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

After this line, you should add `env.globals.update(vars(args))`
</blockquote></details>

Done
___
*[`gsc.py` line 370 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz512J21cUtKv3Dwuu:-NTCfPa91xrICQw23MFJ:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/gsc.py#L370)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is wrong, please revert this. You should use Jinja-style variables, not `ARG` Dockerfile variables.
</blockquote></details>

Done
___
*[`gsc.py` line 515 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz3KepDyxoop_0J09Q:-NTCfXp-3bnHLVCcfmR6:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/gsc.py#L515)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end of the sentence
</blockquote></details>

Done
___
*[`Documentation/index.rst` line 176 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz39V8E00QRZ5IJ72q:-NTCfgR_Dw-F6GaTpc1C:bv3f1qu) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/Documentation/index.rst#L176)):*
> Use with care!
Done
___
*[`templates/Dockerfile.common.sign.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz3XPk3e4RldLkSxh8:-NTCfjKV88I1xp9BCens:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/Dockerfile.common.sign.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This will not work on non-root images, because uninstalling packages requires root privileges. Just try some non-root image for yourself, and you'll see how GSC fails here.

You'll need to surround this block with something like this:
- https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/templates/Dockerfile.common.build.template#L11-L12
- https://github.com/gramineproject/gsc/blob/f656037b664eb1ae55b2b8555755dbdcefefd067/templates/Dockerfile.common.build.template#L26-L27

And please test with root and non-root images, to make sure it works in all cases.
</blockquote></details>

Done
___
*[`templates/centos/Dockerfile.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5C9C6UTz6ghPk3VI:-NTCfoop9hKl6lYLSt7m:b-2oi8ru) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's wrong. You don't want Dockerfile arguments, you want to use Jinja-style variables. See my other comment.
</blockquote></details>

Modified to Jinja style variable...
___
*[`templates/centos/Dockerfile.sign.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz3zSi2GegHUOom4ay:-NTCftVVEwxciJceCCYa:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The `RUN` keyword should be under the if body, like this:
```
{% if remove_gramine_deps %}
RUN \
       dnf update -y \
...
{% endif %}
```
</blockquote></details>

Done
___
*[`templates/centos/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5gXhETPRwwS2cWna:-NTCgm1x2ebiZoxZOwRh:bg0bqwu) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this update?
</blockquote></details>

`dnf update` is not needed as the repo is already updated. Removed.
___
*[`templates/centos/Dockerfile.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5Yok529VnhBmyOLW:-NTCh29K-dubOU0c6WoA:b739wg6) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You must install `pip` to uninstall the previously-installed Python packages (like `click`), do I understand correctly?
</blockquote></details>

Yes, the understanding is correct. Since the install and removal is happening at the same layer no much space needed.
___
*[`templates/debian/Dockerfile.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5QeQ094ypo4F-dj8:-NTChMoHD0gmElGIobHb:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.sign.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5RWbBQx0rUJWw8ZK:-NTChS_2Bz3Q3aW5MN69:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5j2f0vBSK0PyOf5L:-NTChWfN-xyfIZOtU9XG:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.sign.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5SqABpstYzhbZ5aN:-NTCi4IY-kKTxKw49wuV:bc6v2f7) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this additional `rm`?
</blockquote></details>

Removing list of packages downloaded as part of apt update.  `rm -rf /var/lib/apt/lists/*` is also recommended in `https://docs.docker.com/develop/develop-images/dockerfile_best-practices/`


<!-- Sent from Reviewable.io -->

2023-04-17 10:18 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 0 of 5 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/centos/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5gXhETPRwwS2cWna:-NTDhbHN1MTeSyWBS0BU:b-v1770q) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L6)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

`dnf update` is not needed as the repo is already updated. Removed.
</blockquote></details>

Sorry, Considering PR#141, we should be doing `dnf update` before installing some package.
___
*[`templates/debian/Dockerfile.sign.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5RWbBQx0rUJWw8ZK:-NTDgWDI6PZc4mPuqwd9:b70j3gh) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L5)):*
> # Switch back to original app_image user
___
*[`templates/debian/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5j2f0vBSK0PyOf5L:-NTDhvkX8EBLsgvmA9Iu:b-qnjozl) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/debian/Dockerfile.sign.template#L6)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry, Considering PR#141, we should be doing `apt update` before installing some package.


<!-- Sent from Reviewable.io -->

2023-04-19 07:08 UTC, dimakuv requested changes
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`gsc.py` line 334 at r3](https://reviewable.io/reviews/gramineproject/gsc/144#-NTNK7_G-TUDg47T2eU_:-NTNK7_G-TUDg47T2eUa:bvuk47k) ([raw file](https://github.com/gramineproject/gsc/blob/e3f86d06159d8f1d564eeb9541ab712855adde3b/gsc.py#L334)):*
> ```Python
>     tmp_build_path = gsc_tmp_build_path(args.image)            # pathlib obj with build artifacts
> 
>     
> ```

Accidental change? Please remove this line.
___
*[`templates/centos/Dockerfile.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5C9C6UTz6ghPk3VI:-NTNKYsg1vaOY2eVBAdN:b-ky51oq) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

Modified to Jinja style variable...
</blockquote></details>

Thanks, looks much better now!
___
*[`templates/debian/Dockerfile.sign.template` line 5 at r3](https://reviewable.io/reviews/gramineproject/gsc/144#-NTNKsSh4SkQuRADVl9F:-NTNKsSi2Xi5U6u_aOpo:b-u8ybhh) ([raw file](https://github.com/gramineproject/gsc/blob/e3f86d06159d8f1d564eeb9541ab712855adde3b/templates/debian/Dockerfile.sign.template#L5)):*
> ```
> {% block uninstall %}
> {% if remove_gramine_deps %}
>    RUN \
> ```

There is no need for two spaces before `RUN`. Or am I missing something? Why this indentation?


<!-- Sent from Reviewable.io -->

2023-04-20 07:34 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 3 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 334 at r3](https://reviewable.io/reviews/gramineproject/gsc/144#-NTNK7_G-TUDg47T2eU_:-NTS_B0k4Qzo-lXYWRRn:b-eah0l1) ([raw file](https://github.com/gramineproject/gsc/blob/e3f86d06159d8f1d564eeb9541ab712855adde3b/gsc.py#L334)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Accidental change? Please remove this line.
</blockquote></details>

Sorry, It was an accidental change.. Removed.
___
*[`templates/debian/Dockerfile.sign.template` line 5 at r3](https://reviewable.io/reviews/gramineproject/gsc/144#-NTNKsSh4SkQuRADVl9F:-NTS_N0r-sjjWqVLxPtz:b-s4rx4w) ([raw file](https://github.com/gramineproject/gsc/blob/e3f86d06159d8f1d564eeb9541ab712855adde3b/templates/debian/Dockerfile.sign.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There is no need for two spaces before `RUN`. Or am I missing something? Why this indentation?
</blockquote></details>

Indentation not needed, removed.


<!-- Sent from Reviewable.io -->

2023-04-20 11:32 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`templates/Dockerfile.common.sign.template` line 23 at r4](https://reviewable.io/reviews/gramineproject/gsc/144#-NTTQhW98QpPpACdgQue:-NTTQhW98QpPpACdgQuf:bbxbnfq) ([raw file](https://github.com/gramineproject/gsc/blob/06eaa8821db50c7e5f145d23c46c837e5cafbbf9/templates/Dockerfile.common.sign.template#L23)):*
> ```
> # Temporarily switch to the root user to uninstall packages
> USER root
> ```

Please move `{% if remove_gramine_deps %}` here, before `block uninstall`
___
*[`templates/centos/Dockerfile.sign.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/144#-NTTQlb4EMlRBlwf0tjw:-NTTQlb4EMlRBlwf0tjx:bqgrhp5) ([raw file](https://github.com/gramineproject/gsc/blob/06eaa8821db50c7e5f145d23c46c837e5cafbbf9/templates/centos/Dockerfile.sign.template#L4)):*
> ```
> 
> {% block uninstall %}
> {% if remove_gramine_deps %}
> ```

Sorry, just noticed that you have this line duplicated in each OS-specific template. There seems to be no reason for this duplication, so please move it into the `common` template.
___
*[`templates/debian/Dockerfile.sign.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/144#-NTTQrLz3oTnJP3SjuH2:-NTTQrLz3oTnJP3SjuH3:b3o7414) ([raw file](https://github.com/gramineproject/gsc/blob/06eaa8821db50c7e5f145d23c46c837e5cafbbf9/templates/debian/Dockerfile.sign.template#L4)):*
> ```
> 
> {% block uninstall %}
> {% if remove_gramine_deps %}
> ```

ditto (move from here into `common` template)


<!-- Sent from Reviewable.io -->

2023-04-21 11:49 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 2 of 5 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/centos/Dockerfile.sign.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/144#-NTTQlb4EMlRBlwf0tjw:-NTYdGrB6rugIeYScQy3:bo0tu0m) ([raw file](https://github.com/gramineproject/gsc/blob/06eaa8821db50c7e5f145d23c46c837e5cafbbf9/templates/centos/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, just noticed that you have this line duplicated in each OS-specific template. There seems to be no reason for this duplication, so please move it into the `common` template.
</blockquote></details>

Done, Now it is in the common place
___
*[`templates/debian/Dockerfile.sign.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/144#-NTTQrLz3oTnJP3SjuH2:-NTYdLKaCFqGBXkAjbgP:bs7p1gu) ([raw file](https://github.com/gramineproject/gsc/blob/06eaa8821db50c7e5f145d23c46c837e5cafbbf9/templates/debian/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (move from here into `common` template)
</blockquote></details>

Done, Now it is in the common sign file


<!-- Sent from Reviewable.io -->

2023-04-24 09:58 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`templates/Dockerfile.common.sign.template` line 23 at r4](https://reviewable.io/reviews/gramineproject/gsc/144#-NTTQhW98QpPpACdgQue:-NTmgTIb93Z4yJPecIuG:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/06eaa8821db50c7e5f145d23c46c837e5cafbbf9/templates/Dockerfile.common.sign.template#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move `{% if remove_gramine_deps %}` here, before `block uninstall`
</blockquote></details>

Done
___
*[`templates/Dockerfile.common.sign.template` line 30 at r5](https://reviewable.io/reviews/gramineproject/gsc/144#-NTmgWHoEnILi_t_9GH2:-NTmgWHoEnILi_t_9GH3:b-kqm41c) ([raw file](https://github.com/gramineproject/gsc/blob/4ff2def91ebedde538d4c8def3a2b5699740f6db/templates/Dockerfile.common.sign.template#L30)):*
> ```
> USER {{app_user}}
> {% endif %}
> ```

Please remove empty line here.


<!-- Sent from Reviewable.io -->

2023-04-24 12:01 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/Dockerfile.common.sign.template` line 30 at r5](https://reviewable.io/reviews/gramineproject/gsc/144#-NTmgWHoEnILi_t_9GH2:-NTn7SdH2zy0pdRlFgPr:bog0amw) ([raw file](https://github.com/gramineproject/gsc/blob/4ff2def91ebedde538d4c8def3a2b5699740f6db/templates/Dockerfile.common.sign.template#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line here.
</blockquote></details>

Removed, thanks


<!-- Sent from Reviewable.io -->

2023-04-24 17:08 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-04-26 12:15 UTC, mkow requested changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`templates/centos/Dockerfile.sign.template` line 7 at r6](https://reviewable.io/reviews/gramineproject/gsc/144#-NTxSfytANID25JcqOMF:-NTxSfytANID25JcqOMG:bm0wn7g) ([raw file](https://github.com/gramineproject/gsc/blob/c8b5460464b8c360c8490af1f14dc09770461446/templates/centos/Dockerfile.sign.template#L7)):*
> ```
>        dnf update -y \
>        && dnf install -y python3-pip \
>        && pip3  uninstall -y click jinja2 \
> ```

double space



_Code quote:_
```
pip3  uninstall
```


<!-- Sent from Reviewable.io -->

2023-04-26 16:39 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 4 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`templates/centos/Dockerfile.sign.template` line 7 at r6](https://reviewable.io/reviews/gramineproject/gsc/144#-NTxSfytANID25JcqOMF:-NTyQhol0NohOjOTjr_F:bsj6464) ([raw file](https://github.com/gramineproject/gsc/blob/c8b5460464b8c360c8490af1f14dc09770461446/templates/centos/Dockerfile.sign.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

double space
</blockquote></details>

Corrected 


<!-- Sent from Reviewable.io -->

2023-04-27 01:16 UTC, mkow requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/144#-NU-G_4c5HUEIjp1-PRY:-NU-G_4c5HUEIjp1-PRZ:b87kksj) (no related file):*
Let's wait for @woju's review, he was the one involved in discussing this whole thing. I pinged him on priv already.

___


<!-- Sent from Reviewable.io -->

2023-04-27 13:51 UTC, woju requested changes
> Reviewed 1 of 5 files at r2, 1 of 2 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NU1nhwqEpqxQrXpndQI:b-hvwqkt) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
> ```Python
>     env = jinja2.Environment()
>     env.globals.update(yaml.safe_load(args.config_file))
>     env.globals.update(vars(args))
> ```

I don't like this solution, because you all options into the env, which might have conflicting names. Right now it doesn't, but it's not clear to anyone adding new CLI options that you need to make sure those don't collide with unrelated subsystem.

I'd prefer (in order of preference):
- add explicit `'--define', '-D'` option similar to what we have in `gramine-manifest` that would accept `key=value` pairs which are added to globals (and only those); then if you prefer, add `--remove-gramine-deps` as an alias for `-Dremove_gramine_deps=true`;
- add whole namespace as a single object (`env.globals['args'] = args`) and use those as `{% if args.flag %}`. Because that's namespace, there will be a less risk of a collision.
___
*[`gsc.py` line 516 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1j8wh4dUbSAncMfl-:-NU1j8wi8JGfVAwMFKu6:bujx1w5) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L516)):*
> ```Python
> sub_sign.add_argument('-p', '--passphrase', help='Passphrase for the signing key.')
> sub_sign.add_argument('--remove-gramine-deps', action='store_true',
>     help='Remove Gramine dependencies that are not needed at runtime.')
> ```

Plz also add `--no-remove-gramine-deps` (`action='store_false'` and proper `dest=`). In case someone is scripting this, you need to be able to revert this.
___
*[`templates/centos/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5gXhETPRwwS2cWna:-NU1kRPg4SUtSQdlIb1w:b-nkh569) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L6)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

Sorry, Considering PR#141, we should be doing `dnf update` before installing some package.
</blockquote></details>

This is wrong: `dnf update` is an alias for `dnf upgrade` and will update all packages in the system like `apt-get upgrade`. If you intended to force cache refresh, IIUC this is `dnf makecache`, but you probably don't need it at all, because dnf downloads repos whenever it likes as part of other commands, (here it will download in next line, `dnf install`).
___
*[`templates/centos/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1mlBu1l9s9HOoXLGw:-NU1mlBu1l9s9HOoXLGx:b-yhud21) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L9)):*
> ```
>        && pip3 uninstall -y click jinja2 \
>           'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>           'toml>=0.10' \
> ```

Why do you need explicit versions for pip uninstall?
___
*[`templates/centos/Dockerfile.sign.template` line 10 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1m-NMAvcplw4WrEck:-NU1m-NMAvcplw4WrEcl:b-ce6fae) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L10)):*
> ```
>           'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>           'toml>=0.10' \
>        && rpm -e --nodeps binutils \
> ```

No `rpm -e` please, see #141. Please do `dnf remove`, or comment why we `rpm -e`, _inter alia_, openssl or tcl.
___
*[`templates/debian/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nOEZ7mJURmArPvvi:-NU1nOEZ7mJURmArPvvj:b-d5m1ix) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/debian/Dockerfile.sign.template#L9)):*
> ```
>        && pip3 uninstall -y click jinja2 \
>           'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>           'toml>=0.10' \
> ```

ditto (why explicit versions)
___
*[`templates/debian/Dockerfile.sign.template` line 19 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1kBMt7hNHtCkf52f-:-NU1kBMu9QkdNk0JMhlZ:b-5ahnwr) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/debian/Dockerfile.sign.template#L19)):*
> ```
>           python3-pyelftools \
>        && apt autoremove -y \
>        && rm -rf /var/lib/apt/lists/*;
> ```

`apt-get` whole stanza please.


<!-- Sent from Reviewable.io -->

2023-05-02 09:48 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 1 of 5 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/144#-NU-G_4c5HUEIjp1-PRY:-NUQnXiGExLV5Vu5pxeO:b32wtd) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Let's wait for @woju's review, he was the one involved in discussing this whole thing. I pinged him on priv already.
</blockquote></details>

ok

___
___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NUQn_7y5sun_CgF65Q5:b-3t8usp) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't like this solution, because you all options into the env, which might have conflicting names. Right now it doesn't, but it's not clear to anyone adding new CLI options that you need to make sure those don't collide with unrelated subsystem.

I'd prefer (in order of preference):
- add explicit `'--define', '-D'` option similar to what we have in `gramine-manifest` that would accept `key=value` pairs which are added to globals (and only those); then if you prefer, add `--remove-gramine-deps` as an alias for `-Dremove_gramine_deps=true`;
- add whole namespace as a single object (`env.globals['args'] = args`) and use those as `{% if args.flag %}`. Because that's namespace, there will be a less risk of a collision.
</blockquote></details>

added --define option, also created alias --remove-gramine-deps which will be exposed to user.  
___
*[`gsc.py` line 516 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1j8wh4dUbSAncMfl-:-NUQntdP0PSO7idmOVsa:bqmjwcz) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L516)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Plz also add `--no-remove-gramine-deps` (`action='store_false'` and proper `dest=`). In case someone is scripting this, you need to be able to revert this.
</blockquote></details>

Added.
___
*[`templates/centos/Dockerfile.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/144#-NSz5gXhETPRwwS2cWna:-NUQo0C0CkseeudqIF-i:b-axev99) ([raw file](https://github.com/gramineproject/gsc/blob/c87245de156923313de9c14b32d3128d92c5af9e/templates/centos/Dockerfile.sign.template#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is wrong: `dnf update` is an alias for `dnf upgrade` and will update all packages in the system like `apt-get upgrade`. If you intended to force cache refresh, IIUC this is `dnf makecache`, but you probably don't need it at all, because dnf downloads repos whenever it likes as part of other commands, (here it will download in next line, `dnf install`).
</blockquote></details>

Yes, we don't need to do cache refresh in CentOS. removed  `dnf update`.
___
*[`templates/centos/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1mlBu1l9s9HOoXLGw:-NUQoME65FmP25CQqgvD:b-a8a7lk) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why do you need explicit versions for pip uninstall?
</blockquote></details>

As we install 2 version of toml, thought of  removing those explicit versions.
___
*[`templates/centos/Dockerfile.sign.template` line 10 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1m-NMAvcplw4WrEck:-NUQoxf86uX33RocCVcW:bhfy697) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No `rpm -e` please, see #141. Please do `dnf remove`, or comment why we `rpm -e`, _inter alia_, openssl or tcl.
</blockquote></details>

moved to `dnf remove`
___
*[`templates/debian/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nOEZ7mJURmArPvvi:-NUQq6R_BRm8F4GPJPOV:b-mz8tfu) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/debian/Dockerfile.sign.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (why explicit versions)
</blockquote></details>

pip3 uninstall toml is not removing  both versions of toml which we install as part of GSC build. So removing the with explicit versions.
___
*[`templates/debian/Dockerfile.sign.template` line 19 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1kBMt7hNHtCkf52f-:-NUQqAQi0V8Zd0yQ4ZNf:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/debian/Dockerfile.sign.template#L19)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`apt-get` whole stanza please.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-04 10:26 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @mkow, and @woju)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NUaHVyK2de2nq3piH5F:b-moteen) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

added --define option, also created alias --remove-gramine-deps which will be exposed to user.  
</blockquote></details>

@woju We have this problem in other places in GSC (for `gsc build` and `gsc build-gramine` sub-commands). Do you want to fix everywhere?

@amathew3 You applied **both** suggestions from Woju, though he wanted only one of them. I actually would prefer suggestion number 2 (export whole namespace)... Let's first decide how we want to deal with it in the whole GSC, not only `gsc sign-image` sub-command.
___
*[`gsc.py` line 202 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHNc64-7zm6qCJfu0:-NUaHNc7Acmff3VcohQv:btpdru7) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L202)):*
> ```Python
>     env.filters['shlex_quote'] = shlex.quote
>     env.globals.update(config)
>     env.globals.update(vars(args))
> ```

Here we're doing the same problematic thing (the one @woju doesn't like)
___
*[`gsc.py` line 306 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHTEs7U1s7i0qxpBY:-NUaHTEs7U1s7i0qxpBZ:btpdru7) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L306)):*
> ```Python
>     env = jinja2.Environment()
>     env.globals.update(config)
>     env.globals.update(vars(args))
> ```

Here we're doing the same problematic thing (the one @woju doesn't like)
___
*[`Documentation/index.rst` line 175 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHvsW2jYZuVTXwLhE:-NUaHvsW2jYZuVTXwLhF:bduw3fn) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/Documentation/index.rst#L175)):*
> ```reStructuredText
> 
>    Set image sign-time variables during :command:`gsc sign` (same as
>    `docker build --build-arg`).
> ```

This `docker build --build-arg` is meaningless here. I would remove it.
___
*[`templates/centos/Dockerfile.sign.template` line 5 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaI07XEgd1u39MgeW1:-NUaI07XEgd1u39MgeW2:bnjpzln) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/templates/centos/Dockerfile.sign.template#L5)):*
> ```
> {% block uninstall %}
> RUN \
>        pip3 uninstall -y click jinja2 \
> ```

But you need this `dnf install -y python3-pip`, no? Otherwise you probably don't have `pip3` installed at all, and this command will fail.


<!-- Sent from Reviewable.io -->

2023-05-08 12:23 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @mkow, and @woju)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NUvIX_989xSjtl-vyls:b-8rr7n2) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
> How are these two achieving the same purpose?

@aneessahib Sure, we could implement both, but this looks like an overkill for me. The main idea of @woju was to have a clear separation between variables-from-command-line-arguments and variables-from-other-places (like internal variables from a script or internal Jinja engine variables).

And we could achieve a clear separation just be prepending all variables-from-command-line-arguments with `signargs.` as is currently done in the PR (though only for the `gsc sign-image` sub-command).

I wouldn't mind using both options, though it will require non-trivial amount of changes to GSC, and it will be a completely orthogonal task to what this PR wanted to achieve initially.


<!-- Sent from Reviewable.io -->

2023-05-08 14:25 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @dimakuv, @mkow, and @woju)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NUviNvS0SgFCAE7xX8o:bgc58l) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> How are these two achieving the same purpose?

@aneessahib Sure, we could implement both, but this looks like an overkill for me. The main idea of @woju was to have a clear separation between variables-from-command-line-arguments and variables-from-other-places (like internal variables from a script or internal Jinja engine variables).

And we could achieve a clear separation just be prepending all variables-from-command-line-arguments with `signargs.` as is currently done in the PR (though only for the `gsc sign-image` sub-command).

I wouldn't mind using both options, though it will require non-trivial amount of changes to GSC, and it will be a completely orthogonal task to what this PR wanted to achieve initially.
</blockquote></details>

Ok i get it. Agree -  I would prefer keeping the namespace separation for another PR to cleanly implement across GSC.


<!-- Sent from Reviewable.io -->

2023-05-09 06:47 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 12 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @mkow, and @woju)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NUzFSC43Q0nDeVuxSXf:b-jve023) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Ok i get it. Agree -  I would prefer keeping the namespace separation for another PR to cleanly implement across GSC.
</blockquote></details>

I would also prefer two PRs, each doing exactly one thing:
1. This PR that does only the removal of Gramine dependencies (as originally intended).
2. One more PR that creates the namespace separation (for all GSC sub-commands).

If Woju insists, we could first merge the second PR and then the first one. But I wouldn't care much about the order of PRs. @woju Does this sound like a plan to you?


<!-- Sent from Reviewable.io -->

2023-05-12 12:03 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @mkow, and @woju)

___
*[`gsc.py` line 132 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEp8Jo6NHMp9Nsd3Ou:-NVEp8Jo6NHMp9Nsd3Ov:b4ntz24) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L132)):*
> ```Python
>                 print(f'Could not set build arg `{item}` from environment.')
>                 sys.exit(1)
>     return buildargs_dict
> ```

Please add an empty line after this line
___
*[`gsc.py` line 133 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpdGn4NDixGpbjw0K:-NVEpdGn4NDixGpbjw0L:bn8erfs) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L133)):*
> ```Python
>                 sys.exit(1)
>     return buildargs_dict
> def extract_sign_args(args):
> ```

Can you rename this to `extract_define_args(args)`? It makes more sense
___
*[`gsc.py` line 134 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpi0T2_LGXFMKaSYl:-NVEpi0T2_LGXFMKaSYm:blng79r) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L134)):*
> ```Python
>     return buildargs_dict
> def extract_sign_args(args):
>     signargs_dict = {}
> ```

Please rename to `defineargs_dict`
___
*[`gsc.py` line 140 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpWWY26-vj_ryP5fL:-NVEpWWY26-vj_ryP5fM:b-w9pkv6) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L140)):*
> ```Python
>             signargs_dict[key] = value
>         else:
>             # user specified --build-arg with key and without value, let's retrieve value from env
> ```

`--build-arg`- > `--define`
___
*[`gsc.py` line 144 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpuTSBq1GvbV7OZe0:-NVEpuTSBq1GvbV7OZe1:b-2clgiz) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L144)):*
> ```Python
>                 signargs_dict[item] = os.environ[item]
>             else:
>                 print(f'Could not set build arg `{item}` from environment.')
> ```

`build arg` -> `define arg`
___
*[`gsc.py` line 202 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHNc64-7zm6qCJfu0:-NVEq-v1-i_Ow6KYEU9s:b1fva7t) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L202)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we're doing the same problematic thing (the one @woju doesn't like)
</blockquote></details>

@amathew3 Please create a new PR or GitHub issue that fixes this, and I'll resolve my comment here.
___
*[`gsc.py` line 306 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHTEs7U1s7i0qxpBY:-NVEq6D67a_rj_NbDNOF:b1fva7t) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here we're doing the same problematic thing (the one @woju doesn't like)
</blockquote></details>

@amathew3 Please create a new PR or GitHub issue that fixes this, and I'll resolve my comment here.
___
*[`gsc.py` line 532 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEocif2KRLKg2oXTFV:-NVEocif2KRLKg2oXTFW:bhnove1) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L532)):*
> ```Python
>     help='Set image sign-time variables (same as "docker build --build-arg").')
> sub_sign.add_argument('--remove-gramine-deps', action='append_const', dest='define',
>     const='remove_gramine_deps=true',help='Remove Gramine dependencies that are not needed at runtime.')
> ```

Please wrap to 100 chars per line
___
*[`gsc.py` line 534 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEoffB3GaY0-PpZmTZ:-NVEoffB3GaY0-PpZmT_:bhnove1) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L534)):*
> ```Python
>     const='remove_gramine_deps=true',help='Remove Gramine dependencies that are not needed at runtime.')
> sub_sign.add_argument('--no-remove-gramine-deps', action='append_const', dest='define',
>     const='remove_gramine_deps=false',help='Retain Gramine dependencies that are not needed at runtime.')
> ```

Please wrap to 100 chars per line
___
*[`templates/centos/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1mlBu1l9s9HOoXLGw:-NVEomxQ7zLVq2GtkkeU:b-o5n1ki) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L9)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

As we install 2 version of toml, thought of  removing those explicit versions.
</blockquote></details>

I also don't understand why you need to specify explicit versions here?
___
*[`templates/debian/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nOEZ7mJURmArPvvi:-NVEovzmDonCBD3b6c8w:bh21uee) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/debian/Dockerfile.sign.template#L9)):*
> pip3 uninstall toml is not removing both versions of toml which we install as part of GSC build.

What do you mean by "both versions"?


<!-- Sent from Reviewable.io -->

2023-05-12 12:22 UTC, woju requested changes
> Reviewed 4 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @dimakuv, and @mkow)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NVEn4OxC8yPd3bL4bAQ:b-qa0m0r) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would also prefer two PRs, each doing exactly one thing:
1. This PR that does only the removal of Gramine dependencies (as originally intended).
2. One more PR that creates the namespace separation (for all GSC sub-commands).

If Woju insists, we could first merge the second PR and then the first one. But I wouldn't care much about the order of PRs. @woju Does this sound like a plan to you?
</blockquote></details>

I don't care either way, there's no need to merge the fix before this PR. As you prefer.
___
*[`gsc.py` line 140 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEnfVU4ouLFOX97wdr:-NVEnfVV311-L2MbfiCZ:b-hbtca6) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L140)):*
> ```Python
>             signargs_dict[key] = value
>         else:
>             # user specified --build-arg with key and without value, let's retrieve value from env
> ```

No, this is wrong. If user specified arg without value, then the value should either be `True`, or be a hard failure. Double-using this as sourcing value from env is unexpected. If you want to read value from env, then please add another option.
___
*[`gsc.py` line 363 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEoZgU7vYWE1Kckiw-:-NVEoZgU7vYWE1Kckiw0:b-osi6s3) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L363)):*
> ```Python
>     env.globals.update(yaml.safe_load(args.config_file))
>     extract_user_from_image_config(unsigned_image.attrs['Config'], env)
>     env.globals['signargs']=extract_sign_args(args)
> ```

Do you expect some other args that you needed to qualify those args as "sign" args?
___
*[`gsc.py` line 534 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqq7U3KXhXK1CIbLF:-NVEqq7U3KXhXK1CIbLG:b8mw0kc) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L534)):*
> ```Python
>     const='remove_gramine_deps=true',help='Remove Gramine dependencies that are not needed at runtime.')
> sub_sign.add_argument('--no-remove-gramine-deps', action='append_const', dest='define',
>     const='remove_gramine_deps=false',help='Retain Gramine dependencies that are not needed at runtime.')
> ```

Please set this to empty string, so it's always false-ish.
___
*[`templates/Dockerfile.common.sign.template` line 21 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqhuO4BkRyuhnsq-f:-NVEqhuO4BkRyuhnsq-g:b62iesu) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/templates/Dockerfile.common.sign.template#L21)):*
> ```
> COPY --from=unsigned_image /gramine/app_files/*.sgx /gramine/app_files/
> 
> {% if signargs.remove_gramine_deps == 'true' %}
> ```

`== 'true'` should be unnecessary: nonempty string is true.
___
*[`templates/centos/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1mlBu1l9s9HOoXLGw:-NVEr-wU3mXW0gSE8yRx:b-ymveb9) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I also don't understand why you need to specify explicit versions here?
</blockquote></details>

You can't have two versions installed together in one store, so if you did `pip install` twice, you have 1 version, probably newer one (or last one if you installed with `==`).


<!-- Sent from Reviewable.io -->

2023-05-12 12:27 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @mkow, and @woju)

___
*[`gsc.py` line 140 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEnfVU4ouLFOX97wdr:-NVEvVgLBVf3LcAvtyge:b7v8onx) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L140)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is wrong. If user specified arg without value, then the value should either be `True`, or be a hard failure. Double-using this as sourcing value from env is unexpected. If you want to read value from env, then please add another option.
</blockquote></details>

+1 to @woju. I kinda liked this trick, but I agree that this is very unexpected to unprepared user.
___
*[`gsc.py` line 363 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEoZgU7vYWE1Kckiw-:-NVEvJfsC0EQT5v655Qi:bmkfr4r) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L363)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Do you expect some other args that you needed to qualify those args as "sign" args?
</blockquote></details>

+1, I agree that just `['args']` is a good name. Please fix the corresponding template too!


<!-- Sent from Reviewable.io -->

2023-05-15 05:21 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 0 of 5 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NVSpXD95CsarAQKQjPC:b-v2shd3) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't care either way, there's no need to merge the fix before this PR. As you prefer.
</blockquote></details>

Will address in separate PR
___
*[`gsc.py` line 132 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEp8Jo6NHMp9Nsd3Ou:-NVSmu72DLO0XTzwjGq3:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L132)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line after this line
</blockquote></details>

Done
___
*[`gsc.py` line 134 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpi0T2_LGXFMKaSYl:-NVFMP_e6Ilzssuodlyd:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L134)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename to `defineargs_dict`
</blockquote></details>

Done
___
*[`gsc.py` line 140 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEnfVU4ouLFOX97wdr:-NVFMStW0TWefwIJZHXL:b-oa0eqr) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 to @woju. I kinda liked this trick, but I agree that this is very unexpected to unprepared user.
</blockquote></details>

User specified arg without value performing a force quit.
___
*[`gsc.py` line 140 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpWWY26-vj_ryP5fL:-NVFMQpu2hwc2XUILoqw:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L140)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`--build-arg`- > `--define`
</blockquote></details>

Done
___
*[`gsc.py` line 144 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpuTSBq1GvbV7OZe0:-NVFMasG-OSXQ9EismVV:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L144)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`build arg` -> `define arg`
</blockquote></details>

Done
___
*[`gsc.py` line 363 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEoZgU7vYWE1Kckiw-:-NVFMmQ8392v1hHsEqqg:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L363)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, I agree that just `['args']` is a good name. Please fix the corresponding template too!
</blockquote></details>

Done
___
*[`gsc.py` line 532 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEocif2KRLKg2oXTFV:-NVFMnTS10tVGNe_pSEJ:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L532)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap to 100 chars per line
</blockquote></details>

Done
___
*[`gsc.py` line 534 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEoffB3GaY0-PpZmTZ:-NVFMoKN3M7Iy4e7Dq1O:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L534)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please wrap to 100 chars per line
</blockquote></details>

Done
___
*[`gsc.py` line 534 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqq7U3KXhXK1CIbLF:-NVFMyJ04pOsHcvfFPhr:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L534)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please set this to empty string, so it's always false-ish.
</blockquote></details>

Done
___
*[`Documentation/index.rst` line 175 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHvsW2jYZuVTXwLhE:-NVFN-7G4iu94LlgCLZ5:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/Documentation/index.rst#L175)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `docker build --build-arg` is meaningless here. I would remove it.
</blockquote></details>

Done
___
*[`templates/Dockerfile.common.sign.template` line 21 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqhuO4BkRyuhnsq-f:-NVFN0cNBX0g0nKzkFbu:b-p4has0) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/templates/Dockerfile.common.sign.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`== 'true'` should be unnecessary: nonempty string is true.
</blockquote></details>

What if  user passes `--define remove_gramine_deps=false`?.  In this case we will have a nonempty string with value as `false`.
___
*[`templates/centos/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1mlBu1l9s9HOoXLGw:-NVSmS3j06PLBFwcBCvy:b-1gh3n3) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/centos/Dockerfile.sign.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

You can't have two versions installed together in one store, so if you did `pip install` twice, you have 1 version, probably newer one (or last one if you installed with `==`).
</blockquote></details>

Removed version numbers.
___
*[`templates/centos/Dockerfile.sign.template` line 5 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaI07XEgd1u39MgeW1:-NVSmZEZ6OiVJM61Avb-:b4m7gym) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/templates/centos/Dockerfile.sign.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But you need this `dnf install -y python3-pip`, no? Otherwise you probably don't have `pip3` installed at all, and this command will fail.
</blockquote></details>

In CentOS, we are not removing python3-pip after the build stage.
___
*[`templates/debian/Dockerfile.sign.template` line 9 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nOEZ7mJURmArPvvi:-NVFNKLJ0P_iCRiIkXis:bjvoqwz) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/templates/debian/Dockerfile.sign.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> pip3 uninstall toml is not removing both versions of toml which we install as part of GSC build.

What do you mean by "both versions"?
</blockquote></details>

I was taking about the specific versions of toml,tomli and toml-w. The only intention here is to remove the version which we install as part of build.  Its clear to that in remove it is not going to make any sense.  Cleaned up. Thanks.


<!-- Sent from Reviewable.io -->

2023-05-16 17:58 UTC, woju requested changes
> Reviewed 4 of 5 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @dimakuv, and @mkow)

___
*[`gsc.py` line 348 at r7](https://reviewable.io/reviews/gramineproject/gsc/144#-NU1nhwqEpqxQrXpndQH:-NV_gKFnEuP_33HzDWJ0:b-80tlqk) ([raw file](https://github.com/gramineproject/gsc/blob/9457241c42f31e79a2b6bd7b1adebb0e4527f4b4/gsc.py#L348)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

Will address in separate PR
</blockquote></details>

Sure.
___
*[`gsc.py` line 142 at r11](https://reviewable.io/reviews/gramineproject/gsc/144#-NV_gRet71kNHhchpyyd:-NV_gReuA5uE2Y4e3DJZ:bxhmuh3) ([raw file](https://github.com/gramineproject/gsc/blob/b982e98df25871e7534fcc17e6f6b2c3d5e5d1f9/gsc.py#L142)):*
> ```Python
>         else:
>             #user specified --define with key and without value, exiting here.
>             print(f'Could not find define arg `{item}` value.')
> ```

I would really prefer if this said message that you need to use `=` or that the syntax is `NAME=VALUE` or something else explaining how to correct the (to us obvious) user mistake. Otherwise this error is not actionable by user, who would rightly ask "yeah so why the d*mn thing >Could not find define arg? I've put it right there!").
___
*[`templates/Dockerfile.common.sign.template` line 21 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqhuO4BkRyuhnsq-f:-NV_a5aBBIeVLkmcwPyy:baxn4ba) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/templates/Dockerfile.common.sign.template#L21)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

What if  user passes `--define remove_gramine_deps=false`?.  In this case we will have a nonempty string with value as `false`.
</blockquote></details>

What if user passes `--define remove_gramine_deps=True`? or `=1`?

It's easier to explain to people that every non-empty string is true-ish than doing this "properly". By "properly" I mean introducing some more complicated function that folds the case and checks some common other variants like "on" and "yes". AFAIK there's no such standard function, everyone makes their own. For example, jinja itself has this internal helper in one of the extensions, but you can't use it directly, because it's not exported into the environment:

https://github.com/pallets/jinja/blob/953acd65b2be5428482dcb60f5b8481b66252ac9/src/jinja2/ext.py#L813-L814

The problem is, you can't do it when parsing `--define` (because there may be other things to define that are not boolean, for example path to the signing key will be one, cf. #118). You'd have to do parsing here in template (and then probably error out if the option value is invalid). You can do this by implementing jinja test (https://jinja.palletsprojects.com/en/3.1.x/api/#writing-tests), so eventually you'd be able to write something like:

```jinja2

{% if args.remove_gramine_deps is trueish %}
    {# ... #}
{% endif %}
```

Quick draft if you prefer, totally untested:

```python
def test_trueish(value):
    value = value.casefold()
    if not value or value in ('false', 'off', 'no'):
        return False
    if value in ('true', 'on', 'yes'):
        return True
    if value.isdigit():
        return bool(int(value))
    raise ValueError(f'invalid value for trueish: {value!r}')

env.tests['trueish'] = test_trueish
```


<!-- Sent from Reviewable.io -->

2023-05-18 12:14 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 3 of 5 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`gsc.py` line 133 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEpdGn4NDixGpbjw0K:-NVikdRH7Q0loZRD3wFx:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L133)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you rename this to `extract_define_args(args)`? It makes more sense
</blockquote></details>

Done.
___
*[`gsc.py` line 534 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqq7U3KXhXK1CIbLF:-NVT03mf7vswT0GU7q8N:b-q0u884) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L534)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Sorry for marking it as 'Done'. The parse logic for `--define` fails if we set it to empty string. Either we need to modify the parse logic to accommodate empty key, or specify remove_gramine_deps=false as `const` for `--no-remove-gramine-deps`. For me setting remove_gramine_deps=false as `const`  looks better.
___
*[`gsc.py` line 142 at r11](https://reviewable.io/reviews/gramineproject/gsc/144#-NV_gRet71kNHhchpyyd:-NVikub_-0LnPBxuPGBn:b-k9h06w) ([raw file](https://github.com/gramineproject/gsc/blob/b982e98df25871e7534fcc17e6f6b2c3d5e5d1f9/gsc.py#L142)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I would really prefer if this said message that you need to use `=` or that the syntax is `NAME=VALUE` or something else explaining how to correct the (to us obvious) user mistake. Otherwise this error is not actionable by user, who would rightly ask "yeah so why the d*mn thing >Could not find define arg? I've put it right there!").
</blockquote></details>

Modified the message.
___
*[`templates/Dockerfile.common.sign.template` line 21 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqhuO4BkRyuhnsq-f:-NVilVnf3Oymtre5rbXn:b-wrpafx) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/templates/Dockerfile.common.sign.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

What if user passes `--define remove_gramine_deps=True`? or `=1`?

It's easier to explain to people that every non-empty string is true-ish than doing this "properly". By "properly" I mean introducing some more complicated function that folds the case and checks some common other variants like "on" and "yes". AFAIK there's no such standard function, everyone makes their own. For example, jinja itself has this internal helper in one of the extensions, but you can't use it directly, because it's not exported into the environment:

https://github.com/pallets/jinja/blob/953acd65b2be5428482dcb60f5b8481b66252ac9/src/jinja2/ext.py#L813-L814

The problem is, you can't do it when parsing `--define` (because there may be other things to define that are not boolean, for example path to the signing key will be one, cf. #118). You'd have to do parsing here in template (and then probably error out if the option value is invalid). You can do this by implementing jinja test (https://jinja.palletsprojects.com/en/3.1.x/api/#writing-tests), so eventually you'd be able to write something like:

```jinja2

{% if args.remove_gramine_deps is trueish %}
    {# ... #}
{% endif %}
```

Quick draft if you prefer, totally untested:

```python
def test_trueish(value):
    value = value.casefold()
    if not value or value in ('false', 'off', 'no'):
        return False
    if value in ('true', 'on', 'yes'):
        return True
    if value.isdigit():
        return bool(int(value))
    raise ValueError(f'invalid value for trueish: {value!r}')

env.tests['trueish'] = test_trueish
```
</blockquote></details>

Thanks for the inputs.. The logic is modified and tested.


<!-- Sent from Reviewable.io -->

2023-05-19 12:12 UTC, dimakuv requested changes
> Reviewed 3 of 5 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @mkow, and @woju)

___
*[`gsc.py` line 141 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnspIM6KWlep608tUx:-NVnspIM6KWlep608tUy:b-6q4bkh) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L141)):*
> ```Python
>             defineargs_dict[key] = value
>         else:
>             #user specified --define with key and without value, exiting here.
> ```

Just remove this comment, it's obvious from the error message below.
___
*[`gsc.py` line 142 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnsyrv1jEcfqwfupc_:-NVnsyrv1jEcfqwfupca:b-sw3pfy) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L142)):*
> ```Python
>         else:
>             #user specified --define with key and without value, exiting here.
>             print(f'Invalid value for argument `{item}`, Expected `--define {item}=True/False`')
> ```

Why `True/False`? It can be any value (this is a generic function you have here). So just `... {item}=<value>`
___
*[`gsc.py` line 142 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntCws3z7qUu2NaoBf:-NVntCws3z7qUu2NaoBg:b-cv2t4y) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L142)):*
> ```Python
>         else:
>             #user specified --define with key and without value, exiting here.
>             print(f'Invalid value for argument `{item}`, Expected `--define {item}=True/False`')
> ```

`Expected` -> `expected` (small letter)
___
*[`gsc.py` line 532 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntRgZ9vfnZ1lmBja_:-NVntRgZ9vfnZ1lmBjaa:b-130yqv) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L532)):*
> ```Python
> sub_sign.add_argument('--remove-gramine-deps', action='append_const', dest='define',
>     const='remove_gramine_deps=true', help='Remove Gramine dependencies that are not needed'
>                                            'at runtime.')
> ```

Please add a space before `at`:
```
' at runtime.')
```

Otherwise it will render as `...not neededat runtime.`
___
*[`gsc.py` line 534 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnt_2z6X1qcw_MiwZK:-NVnt_2z6X1qcw_MiwZL:b-ebnk6f) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L534)):*
> ```Python
>                                            'at runtime.')
> sub_sign.add_argument('--no-remove-gramine-deps', action='append_const', dest='define',
>     const='remove_gramine_deps=false', help='Retain Gramine dependencies that are not needed' 
> ```

Remove trailing space
___
*[`gsc.py` line 535 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnta8l4E35getLU6WX:-NVnta8l4E35getLU6WY:b1boz3) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L535)):*
> ```Python
> sub_sign.add_argument('--no-remove-gramine-deps', action='append_const', dest='define',
>     const='remove_gramine_deps=false', help='Retain Gramine dependencies that are not needed' 
>                                             'at runtime.')
> ```

ditto (add space)
___
*[`gsc.py` line 541 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntyht4Jw7GqmWm5eT:-NVntyht4Jw7GqmWm5eU:b6ae5vu) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L541)):*
> ```Python
> sub_info.add_argument('image', help='Name of the graminized Docker image.')
> 
> def test_trueish(value):
> ```

Please move this function to the very beginning of this file (before other functions). It will be easier for future readers this way (people typically read from top to bottom, so it makes more sense to have this helper function as the very first one).
___
*[`templates/Dockerfile.common.sign.template` line 30 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntn6y4b-3vAUmqu6v:-NVntn6y4b-3vAUmqu6w:b-pb4q6m) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/templates/Dockerfile.common.sign.template#L30)):*
> ```
> USER {{app_user}}
> {% endif %}
> ```

Please remove empty line


<!-- Sent from Reviewable.io -->

2023-05-19 13:34 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 3 of 5 files reviewed, 14 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`gsc.py` line 141 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnspIM6KWlep608tUx:-NVoBeBW8MtXIR2qt1Gl:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just remove this comment, it's obvious from the error message below.
</blockquote></details>

Done
___
*[`gsc.py` line 142 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnsyrv1jEcfqwfupc_:-NVoBfbB1MM3PHb6-qEg:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L142)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `True/False`? It can be any value (this is a generic function you have here). So just `... {item}=<value>`
</blockquote></details>

Done
___
*[`gsc.py` line 532 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntRgZ9vfnZ1lmBja_:-NVoBiJs2UFL5RKd1_yA:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L532)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a space before `at`:
```
' at runtime.')
```

Otherwise it will render as `...not neededat runtime.`
</blockquote></details>

Done
___
*[`gsc.py` line 534 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnt_2z6X1qcw_MiwZK:-NVoBjBY7fxc4JLJMpdZ:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L534)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove trailing space
</blockquote></details>

Done
___
*[`gsc.py` line 535 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVnta8l4E35getLU6WX:-NVoBkswDEhIB8qFq2p-:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L535)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (add space)
</blockquote></details>

Done
___
*[`gsc.py` line 541 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntyht4Jw7GqmWm5eT:-NVoBm5z0MuPOLvqy58U:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/gsc.py#L541)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this function to the very beginning of this file (before other functions). It will be easier for future readers this way (people typically read from top to bottom, so it makes more sense to have this helper function as the very first one).
</blockquote></details>

Done
___
*[`templates/Dockerfile.common.sign.template` line 30 at r12](https://reviewable.io/reviews/gramineproject/gsc/144#-NVntn6y4b-3vAUmqu6v:-NVoBnm5-OLsnA9WBwXP:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/7ee42be3b84f7ddf49a5f775eb708a214a2fa131/templates/Dockerfile.common.sign.template#L30)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove empty line
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-05-22 07:32 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/144#-NVoK4UI1dTAPsO-cqVL:-NW1MK-_D4nqZYwkyoGK:b-z50fxo) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks good to me now. I'm blocking only on those comments where I requested a new PR that adds similar `--define` args to other GSC sub-commands. @amathew3 Either create such a PR, or create a GitHub issue that explains what will need to be done -- and then I resolve the rest of my blocking comments here.
</blockquote></details>

`https://github.com/gramineproject/gsc/issues/150`, created for tracking the similar --define args changes needed in gsc.py

___
___
*[`gsc.py` line 306 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NUaHTEs7U1s7i0qxpBY:-NW1Mitx-XdiKMcv9DIq:byaew6h) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@amathew3 Please create a new PR or GitHub issue that fixes this, and I'll resolve my comment here.
</blockquote></details>

https://github.com/gramineproject/gsc/issues/150


<!-- Sent from Reviewable.io -->

2023-05-22 09:16 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)



<!-- Sent from Reviewable.io -->

2023-05-22 18:30 UTC, woju approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`gsc.py` line 534 at r9](https://reviewable.io/reviews/gramineproject/gsc/144#-NVEqq7U3KXhXK1CIbLF:-NW3iBzT2gjW9ra_3rNY:b-ntm0i3) ([raw file](https://github.com/gramineproject/gsc/blob/ebede20f33b707fc9ea94944756a2db643df2999/gsc.py#L534)):*
> Sorry for marking it as 'Done'

No, why, this looks like it might be working. LGTM.


<!-- Sent from Reviewable.io -->

2023-05-22 21:39 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 5 files at r10, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-05-23 08:33 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/144#-NW6WuGz22ycvWLaM_qk:-NW6WuGz22ycvWLaM_ql:bn9fswm) (no related file):*
Quick check after final rebase:

- Without `--remove-gramine-deps` (default):
```bash
# cd /
# du -h -s -c
1015M   total
```

- With `--remove-gramine-deps` (this PR):
```bash
# cd /
# du -h -s -c
797M   total
```

I also tried `--no-remove-gramine-deps` and `-Dremove_gramine_deps=1` options. Everything works.

___
___
*[`gsc.py` line 25 at r13](https://reviewable.io/reviews/gramineproject/gsc/144#-NW6W2aJA5VirDjZOu_O:-NW6W2aJA5VirDjZOu_P:b-dp050e) ([raw file](https://github.com/gramineproject/gsc/blob/f10b7a1ebe94accce191a5706d65b639f2788e4b/gsc.py#L25)):*
> ```Python
> 
> def test_trueish(value):
>     value = value.casefold()
> ```

Had to fix this function, otherwise I had an error (when I don't specify `--remove-gramine-deps`) about `dict object is NULL` (smth like this).


<!-- Sent from Reviewable.io -->

2023-05-23 09:27 UTC, woju approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[`gsc.py` line 25 at r13](https://reviewable.io/reviews/gramineproject/gsc/144#-NW6W2aJA5VirDjZOu_O:-NW6vU7u16mVEIgP7pCE:bbiq5x0) ([raw file](https://github.com/gramineproject/gsc/blob/f10b7a1ebe94accce191a5706d65b639f2788e4b/gsc.py#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Had to fix this function, otherwise I had an error (when I don't specify `--remove-gramine-deps`) about `dict object is NULL` (smth like this).
</blockquote></details>

Yes, obviously. My mistake.


<!-- Sent from Reviewable.io -->

2023-05-23 10:14 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: 4 of 5 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`gsc.py` line 25 at r13](https://reviewable.io/reviews/gramineproject/gsc/144#-NW6W2aJA5VirDjZOu_O:-NW74t1x7P7b7QKs42tg:bt2vr1b) ([raw file](https://github.com/gramineproject/gsc/blob/f10b7a1ebe94accce191a5706d65b639f2788e4b/gsc.py#L25)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, obviously. My mistake.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2023-05-23 11:09 UTC, aneessahib commented
Looks like @amathew3  pushed more changes not realizing that @dimakuv had already fixed the new issue. The branch is in a mess now I think. He is working on reverting the changes.

2023-05-23 11:28 UTC, mkow reviewed
@amathew3: please **never** use `push --force`, but `push --force-with-lease`, it prevents such cases.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144#-:-NW7MDT64sEvtZATDTMH:b3b1gab)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3)



<!-- Sent from Reviewable.io -->

2023-05-23 12:12 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @amathew3 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/144#-NW7WZLv8nlXk9BqB37S:-NW7WZLv8nlXk9BqB37T:b5ek1eo) (no related file):*
@amathew3 Please don't do anything new on this PR, I took it over (again). We'll merge it soon.

___


<!-- Sent from Reviewable.io -->

2023-05-23 12:13 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`gsc.py` line 25 at r15](https://reviewable.io/reviews/gramineproject/gsc/144#-NW7IR67D2wfwhrqqcWb:-NW7WhA10duAr7NAKyOs:brvrv94) ([raw file](https://github.com/gramineproject/gsc/blob/8e4e3cdeecd2929d98e7a3a61ee4ba7728cff215/gsc.py#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

So, this function can now return `None`?
</blockquote></details>

Done (again)


<!-- Sent from Reviewable.io -->

2023-05-23 12:59 UTC, mkow requested changes
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`-- commits` line 9 at r14](https://reviewable.io/reviews/gramineproject/gsc/144#-NW7g0BzDfBJlvEtVgLF):*
The commit message got removed in the way, was this intended?


<!-- Sent from Reviewable.io -->

2023-05-23 13:24 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`-- commits` line 9 at r14](https://reviewable.io/reviews/gramineproject/gsc/144#-NW7g0BzDfBJlvEtVgLF):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The commit message got removed in the way, was this intended?
</blockquote></details>

Ok, seems to be a Reviewable bug, GitHub and git show the right commit message.


<!-- Sent from Reviewable.io -->

2023-05-25 06:58 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/144#-NWGge-o21WUKWbbMETX:-NWGge-o21WUKWbbMETY:bsm45xz) (no related file):*
Rebased again. Looks like Reviewable bug is gone now (I waited for a couple days, and in the meantime we heard nothing from Reviewable folks, and also the master branch was updated in this repo).

I hope Reviewable folks can still analyze what was the bug, by checking the previous revision which had problems (r16). For us, looks like we can proceed with final merge.

___


<!-- Sent from Reviewable.io -->

2023-05-25 10:26 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/144)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-05-25 10:35 UTC, merged