Add Java examples
gramineproject/gsc pull request #145
Opened 2023-04-14 08:49 UTC by b-garbacz

## Description of the changes 
Add Java examples.
## How to test this PR? 
Refer to README.

2023-05-04 11:57 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 16 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/dockerfile` line 4 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTN_TBP1En2X6pfFIvB:-NUabp5U8eHfX0L6g9b4:bsv6uop) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/dockerfile#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add empty lines in-between Dockerfiles commands? I mean, to visually group the commands. Otherwise it's hard to read.
</blockquote></details>

Empty lines have been added, and commands have been separated.


<!-- Sent from Reviewable.io -->

2023-05-04 13:33 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTN_l9JCIboYWbs6dV5:-NUaxiDK6fUnotLJ9oRi:bp4d6te) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/java-spring-boot.manifest#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? This is not needed (it's added by GSC build command if the user specifies `--insecure-args`). Please remove.
</blockquote></details>

These 2 lines have been deleted.


<!-- Sent from Reviewable.io -->

2023-05-04 13:36 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 4 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNa1iGCi0lsGlUuUlY:-NUayMHS9rVOJGs0V4Ee:b-nh9ejt) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/java-spring-boot.manifest#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `GSC performance`? It's the Gramine option. So you can just say `# For better performance`
</blockquote></details>

Text has been corrected to "For better performance"


<!-- Sent from Reviewable.io -->

2023-05-04 13:37 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNa8DE9RCh6qe_5Q0P:-NUayjzfBMusGUAwnRnA:btnm5fa) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/java-spring-boot.manifest#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this comment? It's obvious.
</blockquote></details>

Redundant comment has been deleted. 


<!-- Sent from Reviewable.io -->

2023-05-04 13:38 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 11 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNaDKO2GVsB9DXng2k:-NUaywNuArFyxOou397a:bckjr70) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/java-spring-boot.manifest#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Let's remove this parameter, as it was completely removed in Gramine v1.4 (we shouldn't support earlier versions of Gramine).
</blockquote></details>

Redundant parameter has been deleted. 


<!-- Sent from Reviewable.io -->

2023-05-05 10:41 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 1 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNaWLL0ll3rQjcheNi:-NUfUoX58Kd7Yw2cziuW:bsj646i) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It should be
```
# Java Spring Boot example
```
</blockquote></details>

Corrected.


<!-- Sent from Reviewable.io -->

2023-05-05 10:43 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNacc4-cJrr9bA_cYH:-NUfVKwo0iequWUjSp5o:b-w9onod) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add empty lines around sections, sub-sections, etc. It is very hard to read this file.
</blockquote></details>

I added empty lines to the indicated places. It should look now more clearly.


<!-- Sent from Reviewable.io -->

2023-05-05 10:44 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbrfX0nx_Tqm38VD3:-NUfVlcr1csiFk5r5kG0:bmu1de8) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have no explanation what this example is. What is Spring Boot? Why do we want to run it inside Grmaine-SGX? Please give some context, background, intro.
</blockquote></details>

A short description has been added.


<!-- Sent from Reviewable.io -->

2023-05-05 10:44 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNakDE5BA2ePXz2FPW:-NUfVnaC9Tq8Tb94JVOO:b-k7mx7q) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need for `br` tags. Remove everywhere.
</blockquote></details>

Deleted.


<!-- Sent from Reviewable.io -->

2023-05-05 10:53 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNan6643hmpbUPuqFD:-NUfXqdc-x9zUQY1D3fF:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add spaces between words correctly, and use correct spellings. Here for example the official name is `Azure Confidential Computing SGX Virtual Machine`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-05 10:53 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 8 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNb9f45IWHYfm0HpmO:-NUfXtR3CGYmofYUd-Yu:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`vCPU`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNb8JuChfhPb3rPwiw:-NUfXuNp7MBuzU7J0L5N:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`OpenJDK 11`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 10 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNb5sh-kcO-IRZT_jc:-NUfXufD5HX7e3pNjBL4:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Gradle v7.6`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbDl31MWL9iye6fN8:-NUfXxIm55n3Z-5f67n7:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is useless because the reader is already inside the GSC repository, so the reader should already know how to use GSC.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-05 11:04 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 14 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/README.md` line 21 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbMCz-pv33gJslkPs:-NUfYAGLCCdtaYS0df_g:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is `gramine-simple`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 41 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbSAF5ajyfaSq3zu8:-NUfYAvU3ecyyAkwqXQs:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is useless. Please remove. Please assume everywhere that the reader already knows how to use GSC.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 47 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbYfI0NBxBUm1TU7l:-NUfYBFF0nOhqpk0tpnV:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please split this line into two, for readability (using `\` as the delimeter of lines)
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 63 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbmsQ5yfSxBoOOeeH:-NUf_8ZHCgEDbSMmDjpr:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L63)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove trailing spaces.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 64 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNbhjR0sCnFmKEaqsX:-NUfZ5m0AMnUmo65xVKp:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use the following wrapping rule: 100 chars per line. Everywhere.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 73 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNboPOBacgVzvNf7rg:-NUfZ4v0-5K8xdGvg8ZP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/README.md#L73)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add newline symbol.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-05 13:08 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 11 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/java-spring-boot/spring-boot-web-service/gradlew` line 1 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNcEC68uI__Vo0_Dgr:-NUg-zFN3Bat9kg2pWSv:b2na487) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/spring-boot-web-service/gradlew#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Why is it needed here? Where did you get this file from?
</blockquote></details>

Redundant script has been deleted. It was previously used.


<!-- Sent from Reviewable.io -->

2023-05-05 13:56 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 8 of 19 files reviewed, 37 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/simple-java/README.md` line 1 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNcaIWA6N8l11WP4Gu:-NUgBKaM2yrT6b5fPKB3:b2hd1gx) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/simple-java/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```
# Simple Java application
```
</blockquote></details>

Done. I changed to "Simple java application example"
___
*[`Examples/simple-java/README.md` line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNccXP4WYzHU556G3j:-NUgBQJ0AEQuvrpwls3J:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/simple-java/README.md#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (what it is, context, intro)
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 10 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNcee11syd7BMMEcmz:-NUgBRsQEE8vyUWOEWm4:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/simple-java/README.md#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 27 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNcgn4DZ5RcCCP089t:-NUgBUyhAoGLvaof9qqW:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/simple-java/README.md#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 42 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNchZ2CSa6ZrzreLrS:-NUgBiVJ-KB0WmeKHCAm:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/simple-java/README.md#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Newline symbol.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-08 08:53 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 1 of 2 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "Merge branch '" found in commit messages' one-liners (waiting on @b-garbacz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuYwJgDIPOHy3RSz6z:-NUuYwJgDIPOHy3RSz7-:bs4t8o4) (no related file):*
I would definitely prefer to rename `simple-java/` to `java-simple/`. It is easier to read the list at https://github.com/b-garbacz/gsc/tree/b-garbacz/add-java-example/Examples this way.

___
___
*[`-- commits` line 113 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuOFok7qPhH1KmbvEe):*
What is this commit? For the future, please don't use merge commits during the review process.
___
*[`Examples/java-spring-boot/README.md` line 4 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuSdqH9KNNv68Bhb5a:-NUuSdqH9KNNv68Bhb5b:bfumnrw) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L4)):*
> ```Markdown
> 
> Spring Boot is a popular framework for building Java-based web applications. Running Spring Boot
> inside Gramine-SGX allows you to create web applications with an increased level of security.
> ```

I think this would sound better: `...inside a Gramine SGX enclave allows...`
___
*[`Examples/java-spring-boot/README.md` line 27 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuSzDi7RaYjn-DyE2z:-NUuSzDi7RaYjn-DyE3-:b-75i14f) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L27)):*
> ```Markdown
> ```
> 
> 2. Follow the installation guide at https://gradle.org/install/ to install Gradle in version 7.6.
> ```

Remove `in`. Or even simpler: `...to install Gradle v7.6.`
___
*[`Examples/java-spring-boot/README.md` line 31 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuT6FHCDzqZF9MxpHF:-NUuT6FHCDzqZF9MxpHG:b-hsgb1p) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L31)):*
> ```Markdown
> ## Build and run graminized Docker image
> 
> 1. Enter to java-spring-boot directory:
> ```

Broken English. Typically people write something like ```1. Navigate to the `java-spring-boot/` directory:```
___
*[`Examples/java-spring-boot/README.md` line 37 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuTGlF16AJ2N5obdPw:-NUuTGlF16AJ2N5obdPx:blv0s7m) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L37)):*
> ```Markdown
> ```
> 
> 2. Building a project using Gradle:
> ```

`Building` -> `Build`
___
*[`Examples/java-spring-boot/README.md` line 50 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuTLr33gS-6ckEhhoV:-NUuTLr33gS-6ckEhhoW:b-rnwt62) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L50)):*
> ```Markdown
> ```
> 
> 4. Cleaning up files that will be no longer used:
> ```

`Cleaning up` -> `Clean up`
___
*[`Examples/java-spring-boot/README.md` line 56 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuTOnYCR7ZTHfcVrb5:-NUuTOnYCR7ZTHfcVrb6:bdro995) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L56)):*
> ```Markdown
> ```
> 
> 5. Go back under the gsc/... directory:
> ```

```5. Navigate back to the `gsc/` directory:```
___
*[`Examples/java-spring-boot/README.md` line 62 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVeG57b8tdGXK7Jr5:-NUuVeG57b8tdGXK7Jr6:b89ssh4) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L62)):*
> ```Markdown
> ``` 
> 
> 6. Graminize the Docker image using gsc build (this step can take some time!):
> ```

``` using `gsc build` ```

(please add backticks around the command)
___
*[`Examples/java-spring-boot/README.md` line 64 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVjXI7jDvgC2st5-4:-NUuVjXI7jDvgC2st5-5:b-aqk3x9) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L64)):*
> ```Markdown
> 6. Graminize the Docker image using gsc build (this step can take some time!):
> 
> ```bash 
> ```

Please remove trailing space here
___
*[`Examples/java-spring-boot/README.md` line 69 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVqyaCy5STzFVBFLM:-NUuVqyaCy5STzFVBFLN:b2pmb4l) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L69)):*
> ```Markdown
> ```
> 
> 7. Sign the graminized Docker image using gsc sign-image:
> ```

``` using `gsc sign-image` ```

(please add backticks around the command)
___
*[`Examples/java-spring-boot/README.md` line 79 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuWErCC1771-jWiqL1:-NUuWErCC1771-jWiqL2:b-fqhew5) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L79)):*
> ```Markdown
> to the container, and this is the driver for SGX. The second parameter is used to bind mount
> a volume in the form of an ASEM service, which provides key provisioning and remote attestation.
> The third parameter is the port on which the application will run:
> ```

Why do you need all these explanations? It should be obvious to users what these parameters are, and if not, the user is supposed to read Docker documentation. Please remove all these.
___
*[`Examples/java-spring-boot/README.md` line 82 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuWOVR3uvb2Vttw3Iw:-NUuWOVR3uvb2Vttw3Ix:b-3ytowp) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L82)):*
> ```Markdown
> 
> * To run the image on the default port set to 8080,
> run the command (the application may take a while to load):
> ```

This doesn't render nicely. The bullet items are **not** under the `8.` list item: https://github.com/b-garbacz/gsc/tree/b-garbacz/add-java-example/Examples/java-spring-boot#build-and-run-graminized-docker-image

Please add indentation (spaces), so that this whole part is under the `8.` list item.
___
*[`Examples/java-spring-boot/spring-boot-web-service/build.gradle` line 1 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuWknh4jTl3TTsPEAx:-NUuWknh4jTl3TTsPEAy:b-mmsm43) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/spring-boot-web-service/build.gradle#L1)):*
> ```Gradle
> /* 
> ```

Please remove trailing space
___
*[`Examples/java-spring-boot/spring-boot-web-service/build.gradle` line 2 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuX4RT8CHfO5dwdBY4:-NUuX4RT8CHfO5dwdBY5:b-e2ue0y) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/spring-boot-web-service/build.gradle#L2)):*
> ```Gradle
> /* 
>     This is configuration file is used by Gradle, to define how to build and package a Java project.
> ```

`This is configuration file` -> `This configuration file`
___
*[`Examples/simple-java/gramine-simple-java.manifest` line 7 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuXepA45fDYKpBXSnf:-NUuXepA45fDYKpBXSng:bi74ob6) ([raw file](https [...]

2023-05-09 02:46 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @b-garbacz and @dimakuv)

___
*[`Examples/java-simple/README.md` line 10 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyEoD-49m9U-MRERHL:-NUyEoD-49m9U-MRERHM:b-2bqbe0) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L10)):*
> ```Markdown
> ## Disclaimer
> 
> * This generated confidential computing image is for non-production usage.
> ```

Suggest to remove this.



_Code quote:_
```Markdown
confidential computing
```
___
*[`Examples/java-simple/README.md` line 20 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyFNUy8kMwuSQ6qwDM:-NUyFNUz1pTglWVp7FeR:b-w3x6r3) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L20)):*
> ```Markdown
> ## Build and run graminized Docker image
> 
> 1. Navigate to the `java-simple/` directory:
> ```

Suggest to remove this step as we're supposed to be in this `java-simple` dir where this README actually lies in. Or I'd expand a bit the step 2 (see below).



_Code quote:_
```Markdown
Navigate to the `java-simple/` directory:
```
___
*[`Examples/java-simple/README.md` line 26 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyG9ksEtldQFV7jGjm:-NUyG9kt-AkSWGN4hZjz:b-qwow7c) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L26)):*
> ```Markdown
> ```
> 
> 2. Build a Docker image:
> ```

Pls use `the` or simply remove `a`



_Code quote:_
```Markdown
a
```
___
*[`Examples/java-simple/README.md` line 26 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyGI32E7kEzVq-lD86:-NUyGI32E7kEzVq-lD87:bgqevme) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L26)):*
> ```Markdown
> ```
> 
> 2. Build a Docker image:
> ```

Build Docker image from this `java-simple` directory



_Code quote:_
```Markdown
Build a Docker image
```
___
*[`Examples/java-simple/README.md` line 29 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyIKqn5S-grW8F8-wR:-NUyIKqn5S-grW8F8-wS:b-w45hed) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L29)):*
> ```Markdown
> 
> ```bash
> $ docker build -t java-simple .
> ```

I would add the openjdk version as a prefix of image, e.g., `openjdk-11-java-simple`



_Code quote:_
```Markdown
java-simple
```
___
*[`Examples/java-simple/README.md` line 32 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyGqvLCEx71_gVpabn:-NUyGqvLCEx71_gVpabo:b-hf86d) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L32)):*
> ```Markdown
> ```
> 
> 3. Navigate to the `gsc/` directory:
> ```

Suggest to simply combine this step with the step below of graminizing the Docker image



_Code quote:_
```Markdown
3. Navigate to the `gsc/` directory:
```
___
*[`Examples/java-simple/README.md` line 42 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyHq5I-sxqMs0iAOvO:-NUyHq5I-sxqMs0iAOvP:b-m42c21) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L42)):*
> ```Markdown
> ```bash
> $ ./gsc build java-simple Examples/java-simple/java-simple.manifest \
>         -c <PATH-TO-CONFIG-FILE>
> ```

4 space indent pls, same for below cmds
___
*[`Examples/java-simple/README.md` line 42 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyIBnI9b9wP61Mf367:-NUyIBnI9b9wP61Mf368:bgocs5k) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L42)):*
> ```Markdown
> ```bash
> $ ./gsc build java-simple Examples/java-simple/java-simple.manifest \
>         -c <PATH-TO-CONFIG-FILE>
> ```

BTW, can't this be held in one line? Same for below cmds



_Code quote:_
```Markdown
$ ./gsc build java-simple Examples/java-simple/java-simple.manifest \
        -c <PATH-TO-CONFIG-FILE>
```
___
*[`Examples/java-simple/README.md` line 45 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyHlxVAjyE-HR5UrZq:-NUyHlxVAjyE-HR5UrZr:b-sn8ci5) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L45)):*
> ```Markdown
> ```
> 
> 5. Sign graminized Docker image using gsc sign-image:
> ```

Sign the



_Code quote:_
```Markdown
Sign 
```
___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 9 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyNinsAiAMYrY0xqtX:-NUyNinsAiAMYrY0xqtY:bcbrhcl) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/java-spring-boot.manifest#L9)):*
> ```
> 
> # SERVER_PORT is an equivalent environment variable to server.port in Spring Boot
> # that specifies the port number on which the application runs.
> ```

Q: so this env variable'll actually override the one specified in `application.properties`?



_Code quote:_
```
# SERVER_PORT is an equivalent environment variable to server.port in Spring Boot
# that specifies the port number on which the application runs.
```
___
*[`Examples/java-spring-boot/README.md` line 69 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVqyaCy5STzFVBFLM:-NUyNu4o46isiMOQVHps:bsu4yxf) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

``` using `gsc sign-image` ```

(please add backticks around the command)
</blockquote></details>

I'd simply remove this since we already have the cmd right below
___
*[`Examples/java-spring-boot/README.md` line 9 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyKiE814kV0lBgjtWz:-NUyKiE814kV0lBgjtX-:b-hc5q7t) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L9)):*
> ```Markdown
> ## Disclaimer
> 
> * This generated confidential computing image is for non-production usage.
> ```

ditto, I'd remove this



_Code quote:_
```Markdown
confidential computing
```
___
*[`Examples/java-spring-boot/README.md` line 31 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLLbRCX31YnttA4AB:-NUyLLbRCX31YnttA4AC:b-hc5q7t) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L31)):*
> ```Markdown
> ## Build and run graminized Docker image
> 
> 1. Enter to java-spring-boot directory:
> ```

ditto, I'd remove this



_Code quote:_
```Markdown
Enter to java-spring-boot directory:
```
___
*[`Examples/java-spring-boot/README.md` line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLYMl5BJnZdf5gz4H:-NUyLYMl5BJnZdf5gz4I:b-s2qkas) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L40)):*
> ```Markdown
> 
> ```bash
> $ (cd spring-boot-web-service/; gradle build)
> ```

Why these parentheses -- meaning optional?



_Code quote:_
```Markdown
$ (cd spring-boot-web-service/; gradle build)
```
___
*[`Examples/java-spring-boot/README.md` line 44 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLpVwCLeC3gVW4Zl5:-NUyLpVwCLeC3gVW4Zl6:b6kj4yf) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L44 [...]

2023-05-09 13:17 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`Examples/simple-java/README.md` line 1 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuZ6sj1BywRNlOAMIk:-NUvUAIw3DZ5tl-gzCzc:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Java` (with capital letter)
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 4 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuXmUB6wvW-H4lqixk:-NUvTtAf3ClRT_j1Q_66:b-k7mx7q) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/README.md#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

"Increase the security level" of what? Please expand this sentence.
</blockquote></details>

Deleted.
___
*[`Examples/simple-java/README.md` line 5 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuXsRK85oAX1Z5Qj66:-NUvTsQu9REjdOyWvwIb:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/README.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also add a sentence that "This is a trivial example on running a Java application using GSC.'
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 19 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuY27u4lnjkl_1N5sT:-NUvTpsV7wDYnSa06ycT:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/README.md#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (please fix English and backticks everywhere in this file)
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 21 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuY9mj7ZslWIzMnUiO:-NUvTn9lErifrgaFgNtB:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/README.md#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You used `bash` in the Spring Boot example, please unify.
</blockquote></details>

Done.
___
*[`Examples/simple-java/README.md` line 53 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuYH7h3qW0m_IyID9e:-NUvTl417qdecz1Z46Nh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/README.md#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, no need for such long explanation. Simply `Run graminized image:` is enough.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-16 15:07 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuYwJgDIPOHy3RSz6z:-NV_5Nqq5Dlsca8vOX6V:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would definitely prefer to rename `simple-java/` to `java-simple/`. It is easier to read the list at https://github.com/b-garbacz/gsc/tree/b-garbacz/add-java-example/Examples this way.
</blockquote></details>

Done.

___
___
*[`Examples/simple-java/gramine-simple-java.manifest` line 7 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuXepA45fDYKpBXSnf:-NV_5QWh7aCtYzt20DU3:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/simple-java/gramine-simple-java.manifest#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove this option, it's not used in Gramine anymore.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 11:20 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 113 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuOFok7qPhH1KmbvEe):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this commit? For the future, please don't use merge commits during the review process.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 27 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuSzDi7RaYjn-DyE2z:-NVdKjuaC1NiwAmVMnGj:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove `in`. Or even simpler: `...to install Gradle v7.6.`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 31 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuT6FHCDzqZF9MxpHF:-NVdKnrWEIXqAwQ-qTkd:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Broken English. Typically people write something like ```1. Navigate to the `java-spring-boot/` directory:```
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 37 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuTGlF16AJ2N5obdPw:-NVdKof92LxGQnyEExJd:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Building` -> `Build`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 50 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuTLr33gS-6ckEhhoV:-NVdKukh6fsoQQwcq0XP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Cleaning up` -> `Clean up`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 56 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuTOnYCR7ZTHfcVrb5:-NVdKvLx2e8QBCnr12PN:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

```5. Navigate back to the `gsc/` directory:```
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 62 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVeG57b8tdGXK7Jr5:-NVdLlHxCgJwcWElI-sY:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L62)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

``` using `gsc build` ```

(please add backticks around the command)
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 64 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVjXI7jDvgC2st5-4:-NVdLsdk9Lz2xu-1VWOk:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L64)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove trailing space here
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 69 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuVqyaCy5STzFVBFLM:-NVdLUkyCGKvoaejt3Sh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L69)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'd simply remove this since we already have the cmd right below
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 79 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuWErCC1771-jWiqL1:-NVdM6Ae-H3fFHcGuosr:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need all these explanations? It should be obvious to users what these parameters are, and if not, the user is supposed to read Docker documentation. Please remove all these.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 82 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuWOVR3uvb2Vttw3Iw:-NVdM6mT2OilZqEUmxFj:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L82)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This doesn't render nicely. The bullet items are **not** under the `8.` list item: https://github.com/b-garbacz/gsc/tree/b-garbacz/add-java-example/Examples/java-spring-boot#build-and-run-graminized-docker-image

Please add indentation (spaces), so that this whole part is under the `8.` list item.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 31 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLLbRCX31YnttA4AB:-NVdKoFT9EO4FN958wKh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L31)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto, I'd remove this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 11:22 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-spring-boot/README.md` line 4 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuSdqH9KNNv68Bhb5a:-NVdRQW058ga1CKh-9Mg:bvi88mi) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/README.md#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this would sound better: `...inside a Gramine SGX enclave allows...`
</blockquote></details>

Changed to "Spring Boot is a popular framework for building Java-based web applications. By using the GSC tool,
you can deploy Spring Boot web applications inside a Gramine SGX enclave graminized containers."
___
*[`Examples/java-spring-boot/THIRDPARTYLICENSES.txt` line 2 at r2](https://reviewable.io/reviews/gramineproject/gsc/145#-NTNc0vr2srXzwerEUTF:-NVdR_Xo3wTiTfa01DCU:bhqjkva) ([raw file](https://github.com/gramineproject/gsc/blob/39cc1fe18aed4192aae04bbdfdc695dfa71189b7/Examples/java-spring-boot/THIRDPARTYLICENSES.txt#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this file necessary to add?
</blockquote></details>

As we are using in this example Spring as a dependency to run reference code I think that it would be reasonable to add in such file containing this information so there would be no legal issues


<!-- Sent from Reviewable.io -->

2023-05-17 11:27 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-spring-boot/spring-boot-web-service/build.gradle` line 1 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuWknh4jTl3TTsPEAx:-NVdSfFv2w_q-JqbCPRN:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/spring-boot-web-service/build.gradle#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove trailing space
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/spring-boot-web-service/build.gradle` line 2 at r12](https://reviewable.io/reviews/gramineproject/gsc/145#-NUuX4RT8CHfO5dwdBY4:-NVdSf814n3caavvyrzl:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/9e31a53e41b788dc32a4d9b15bee711e7b7b6e82/Examples/java-spring-boot/spring-boot-web-service/build.gradle#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This is configuration file` -> `This configuration file`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 11:35 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-simple/README.md` line 10 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyEoD-49m9U-MRERHL:-NVdUZci0wuZGw-iVa7P:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to remove this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-17 12:08 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 41 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-simple/README.md` line 20 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyFNUy8kMwuSQ6qwDM:-NVdb9D9E04-NLR3EBSa:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L20)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to remove this step as we're supposed to be in this `java-simple` dir where this README actually lies in. Or I'd expand a bit the step 2 (see below).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-18 13:24 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-simple/README.md` line 26 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyG9ksEtldQFV7jGjm:-NVdemJY6UYSo2wB1EVe:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls use `the` or simply remove `a`
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 26 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyGI32E7kEzVq-lD86:-NVdelom2HJvQr-8fofE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L26)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Build Docker image from this `java-simple` directory
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 29 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyIKqn5S-grW8F8-wR:-NViOhWx57zvsnf3NUHC:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L29)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I would add the openjdk version as a prefix of image, e.g., `openjdk-11-java-simple`
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 42 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyHq5I-sxqMs0iAOvO:-NVj0owM95hkKpCdFr1x:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L42)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

4 space indent pls, same for below cmds
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 42 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyIBnI9b9wP61Mf367:-NVj0s3d1-HYwiYaUNfz:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L42)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

BTW, can't this be held in one line? Same for below cmds
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 45 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyHlxVAjyE-HR5UrZq:-NVj12yt-8KWcERF8xYi:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L45)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Sign the
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-18 13:26 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-simple/README.md` line 32 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyGqvLCEx71_gVpabn:-NVj1Gd4Dfv57lcllgIX:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-simple/README.md#L32)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Suggest to simply combine this step with the step below of graminizing the Docker image
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 9 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyKiE814kV0lBgjtWz:-NVj1JGy7l3zs0lzvjAc:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto, I'd remove this
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 56 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyM1sJ-oUKzJU9t_VJ:-NVj1Rjn44ihybel0_Gp:b-k7mx7q) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L56)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto, I'd combine thi step w/ the step below
</blockquote></details>

Deleted.


<!-- Sent from Reviewable.io -->

2023-05-18 13:55 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-spring-boot/README.md` line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLYMl5BJnZdf5gz4H:-NVj78Yw-jXltt6xcADE:b-2jspkl) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L40)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Why these parentheses -- meaning optional?
</blockquote></details>

They are neccesary because it allows the path to remain unchanged. For example without parentheses after executing this command we will be moved to the spring-boot-web-service directory. We want to "stay" in the java-spring-boot directory.


<!-- Sent from Reviewable.io -->

2023-05-18 14:13 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 13 of 19 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-spring-boot/README.md` line 113 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyN1-JCvkGw0jYphTZ:-NVjBsZO9-qjrd6JzCuP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L113)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

I'd remove this whole step
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/THIRDPARTYLICENSES.txt` line 1 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyMdjF7XAON1ec9kJH:-NVjCFA86Zg-6hfi_w_x:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/THIRDPARTYLICENSES.txt#L1)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

SPDX-License-Identifier: Apache-2.0
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-19 01:25 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 12 of 19 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 9 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyNinsAiAMYrY0xqtX:-NVlb9iVCy2MdKhzFWPA:b-7xt2ki) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/java-spring-boot.manifest#L9)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Q: so this env variable'll actually override the one specified in `application.properties`?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2023-05-19 01:31 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 12 of 19 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-spring-boot/README.md` line 92 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyOWzz-0iFjcNCPyJN:-NVlcSqCB90nU18I7pE9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L92)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Simply "To run the image on a cutomized port, e.g., 9080:" should be fine
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-25 09:39 UTC, dimakuv requested changes
> Reviewed 2 of 4 files at r13, 1 of 1 files at r14, 1 of 2 files at r19, 1 of 1 files at r22, 5 of 5 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 31 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @b-garbacz and @kailun-qin)

___
*[`-- commits` line 225 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWGxd8C6t5LNS1tdIEL):*
For the future, you should use `git commit --fixup` flow. You can google how it works and how to apply it, and you can also browse through some example PRs in our core repo, to see how developers typically do it: https://github.com/gramineproject/gramine/pulls

Nothing needed from your side in this PR, as I'll clean up this history of commits myself anyway (at final rebase and merge).
___
*[`Examples/java-simple/java-simple.manifest` line 5 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDih-56nhL6jK1jaO:-NWHDih-56nhL6jK1jaP:b1ko3di) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/java-simple.manifest#L5)):*
> ```
> 
> sgx.enclave_size = "4G"
> sys.stack.size = "2M"
> ```

Could you move it above `sgx.enclave_size` option? Then we'll group two `sgx.` options together, which looks cleaner.
___
*[`Examples/java-simple/README.md` line 6 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWGyDUa9xgMFT-k_hub:-NWGyDUa9xgMFT-k_huc:b-d2g2vp) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L6)):*
> ```Markdown
> deploy graminized containers with Java code. This is a trivial example on running
> a Java application using GSC. For more information on Java, please visit
> https://www.oracle.com/pl/java/.
> ```

Lol, just noticed that this is the Polish version of the page :)

https://www.oracle.com/java/ -- please use this one
___
*[`Examples/java-simple/README.md` line 8 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDSC-3vgbK9rNf1d4:-NWHDSC-3vgbK9rNf1d5:bss7x2t) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L8)):*
> ```Markdown
> https://www.oracle.com/pl/java/.
> 
> ## Disclaimer
> ```

Why do you have the versions (second item) under Disclaimer? I think it would be better to rename this section to `Notes`
___
*[`Examples/java-simple/README.md` line 15 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHCqRF3hktXfV4WRj7:-NWHCqRF3hktXfV4WRj8:bfyai0h) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L15)):*
> ```Markdown
>   - Type: Azure Confidential Computing SGX Virtual Machine
>   - OS: Linux (Ubuntu 20.04)
>   - Size: Standard DC1s v3 (1 vCPU, 8 GiB memory)
> ```

It would make sense to swap `OS` and `Size` items places -- then you'll have logic in this list: first you describe hardware requirements, then software requirements.
___
*[`Examples/java-simple/README.md` line 46 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDCzK-36CDDw1_EWZ:-NWHDCzK-36CDDw1_EW_:bwtb43y) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L46)):*
> ```Markdown
> ```bash
> $ docker run --rm --device=/dev/sgx_enclave \
>         -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-openjdk-11-java-simple
> ```

I would actually split this line into two (after the `...aesm.socket`), for readability.
___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 5 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDp6J5VRQhGMkQuet:-NWHDp6J5VRQhGMkQueu:b1ko3di) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/java-spring-boot.manifest#L5)):*
> ```
> 
> sgx.enclave_size = "8G"
> sys.stack.size = "2M"
> ```

Could you move it above `sgx.enclave_size` option? Then we'll group two `sgx.` options together, which looks cleaner.
___
*[`Examples/java-spring-boot/README.md` line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLYMl5BJnZdf5gz4H:-NWHFVB28YyDZtg7944M:b39c4ek) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L40)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

They are neccesary because it allows the path to remain unchanged. For example without parentheses after executing this command we will be moved to the spring-boot-web-service directory. We want to "stay" in the java-spring-boot directory.
</blockquote></details>

Yeah, I like the parenthesis usage.
___
*[`Examples/java-spring-boot/README.md` line 113 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyN1-JCvkGw0jYphTZ:-NWHFo-XAoshMBPcU7zM:b1w499w) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L113)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, why do we remove this step? This looks important, so that users who test it don't forget to stop the Docker container. @kailun-qin Would you be fine with reverting this step? Please note that we started the Docker container using `docker run -d` which means it was started in the background (in the detached state), so it's easy to forget about this Docker container...
___
*[`Examples/java-spring-boot/README.md` line 4 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDwPb25KbsI4_Unso:-NWHDwPb25KbsI4_Unsp:b-digtu) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L4)):*
> ```Markdown
> 
> Spring Boot is a popular framework for building Java-based web applications. By using the GSC tool,
> you can deploy Spring Boot web applications inside a Gramine SGX enclave graminized containers.
> ```

`inside a Gramine SGX enclave graminized containers` -- no, sorry, this doesn't sound like proper English.

Maybe `inside a graminized Docker container, such that the app runs inside the SGX enclave.`
___
*[`Examples/java-spring-boot/README.md` line 7 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHEAN542tjDZafrSDx:-NWHEAN542tjDZafrSDy:b-jfqczg) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L7)):*
> ```Markdown
> For more information on Spring Boot, please visit https://spring.io/.
> 
> ## Disclaimer
> ```

ditto (maybe `Notes`?)
___
*[`Examples/java-spring-boot/README.md` line 14 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHEEuf56R6w5EYf_Aw:-NWHEEuf56R6w5EYf_Ax:b-mxxspe) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L14)):*
> ```Markdown
>   - Type: Azure Confidential Computing SGX Virtual Machine
>   - OS: Linux (Ubuntu 20.04)
>   - Size: Standard DC1s v3 (1 vCPU, 8 GiB memory)
> ```

ditto (move closer to Type)
___
*[`Examples/java-spring-boot/README.md` line 18 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHEqNd0QUrGD4FiXDN:-NWHEqNd0QUrGD4FiXDO:bjmcw1j) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L18)):*
> ```Markdown
>   - Gradle v7.6
> 
> ## Software requirements
> ```

I you change the above section to `Notes`, then you can remove the duplication of OpenJDK and Gradle, and just move the installation items under this section to `Notes`. What I mean is: just rem [...]

2023-05-25 11:19 UTC, kailun-qin requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @b-garbacz and @dimakuv)

___
*[`Examples/java-simple/README.md` line 4 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHV7qk2I_p4ziv0OFn:-NWHV7qk2I_p4ziv0OFo:b-cbf5dj) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L4)):*
> ```Markdown
> 
> Java is one of the most popular programming languages in the world. By using the GSC tool, you can
> deploy graminized containers with Java code. This is a trivial example on running
> ```

Strictly speaking, isn't it Java bytecode?



_Code quote:_
```Markdown
Java code
```
___
*[`Examples/java-simple/README.md` line 34 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHWUYo7XLijjCg4_O3:-NWHWUYo7XLijjCg4_O4:b-agixqd) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L34)):*
> ```Markdown
> ```
> 
> 3. Sign the graminized Docker image using:
> ```

Pls remove this `using` (it's obvious)



_Code quote:_
```Markdown
 using
```
___
*[`Examples/java-spring-boot/README.md` line 40 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyLYMl5BJnZdf5gz4H:-NWHXefP6e_DsmFsmVWA:bx40oul) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, I like the parenthesis usage.
</blockquote></details>

Got it, thanks for the explanation!
___
*[`Examples/java-spring-boot/README.md` line 102 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyMp7d8venLIbmhdlV:-NWHZDIX5w9l_ytFYfE2:b-c7sag2) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L102)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

In my opinion it's fine and we should keep in this form.
</blockquote></details>

Sure, I don't insist on this.
___
*[`Examples/java-spring-boot/README.md` line 113 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyN1-JCvkGw0jYphTZ:-NWHYQ_1575Dd3WVV7jH:bt99rwj) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L113)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do we remove this step? This looks important, so that users who test it don't forget to stop the Docker container. @kailun-qin Would you be fine with reverting this step? Please note that we started the Docker container using `docker run -d` which means it was started in the background (in the detached state), so it's easy to forget about this Docker container...
</blockquote></details>

Indeed, sorry that I did not notice the `-d` option. We do need this step. Pls kindly revert, thanks.

But this is under the section `Result`?  
___
*[`Examples/java-spring-boot/README.md` line 31 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHFRBDBD4w2XRyx6KS:-NWHXBdo8jD8prMqsD1G:b32v57) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you start with `3`? Doesn't make sense.
</blockquote></details>

+1
___
*[`Examples/java-spring-boot/README.md` line 67 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHZhnv-Pa3J2Qixscy:-NWHZhnv-Pa3J2Qixscz:b1nubi) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L67)):*
> ```Markdown
> 8. Run graminized image:
> 
>       * To run the image on the default port set to 8080 (the application may take a while to load):
> ```

I'd move this after Run graminized image like `Run graminized image (the application may take a while to load)`



_Code quote:_
```Markdown
(the application may take a while to load)
```
___
*[`Examples/java-spring-boot/README.md` line 67 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHZwup4zWSDY7-ImFV:-NWHZwup4zWSDY7-ImFW:b5zyfuc) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L67)):*
> ```Markdown
> 8. Run graminized image:
> 
>       * To run the image on the default port set to 8080 (the application may take a while to load):
> ```

I would remove this, simply `on the default port...`. It's duplicated w/ above.



_Code quote:_
```Markdown
To run the image 
```
___
*[`Examples/java-spring-boot/README.md` line 76 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWH_49XE5NZ-P3dWmC7:-NWH_49XE5NZ-P3dWmC8:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L76)):*
> ```Markdown
>         ```
> 
>       * To run the image on a customized port using an environment variable, i.e. 9080
> ```

ditto



_Code quote:_
```Markdown
To run the image 
```
___
*[`Examples/java-spring-boot/README.md` line 77 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHZrfwBkWfFRSWKRW2:-NWHZrfwBkWfFRSWKRW3:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L77)):*
> ```Markdown
> 
>       * To run the image on a customized port using an environment variable, i.e. 9080
>       (the application may take a while to load):
> ```

ditto



_Code quote:_
```Markdown
(the application may take a while to load)
```


<!-- Sent from Reviewable.io -->

2023-05-30 16:27 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 15 of 19 files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "Merge branch '" and "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`-- commits` line 225 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWGxd8C6t5LNS1tdIEL):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For the future, you should use `git commit --fixup` flow. You can google how it works and how to apply it, and you can also browse through some example PRs in our core repo, to see how developers typically do it: https://github.com/gramineproject/gramine/pulls

Nothing needed from your side in this PR, as I'll clean up this history of commits myself anyway (at final rebase and merge).
</blockquote></details>

The first time I used this command incorrectly which caused conflicts and I had to do a merge. The second time it worked. Thank yo
___
*[`Examples/java-simple/java-simple.manifest` line 5 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDih-56nhL6jK1jaO:-NWggHit-iuGhQYQRDd9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/java-simple.manifest#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move it above `sgx.enclave_size` option? Then we'll group two `sgx.` options together, which looks cleaner.
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 4 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHV7qk2I_p4ziv0OFn:-NWbntlD4gT3QNfCsGen:b-ma2bp1) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L4)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Strictly speaking, isn't it Java bytecode?
</blockquote></details>

Java bytecode is an intermediate code generated by the Java compiler(low-level binary code). As a programmer, we want GSC to consume java code.
Java code will be compilated and Java  bytecode will be created. Then to run program the Java bytecode will be used in JVM and so on...Java code is consumed at the beginning.
___
*[`Examples/java-simple/README.md` line 6 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWGyDUa9xgMFT-k_hub:-NWg1LQY8TA9Y4eaBMFs:b61e5rk) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Lol, just noticed that this is the Polish version of the page :)

https://www.oracle.com/java/ -- please use this one
</blockquote></details>

Ah yes. I just copied link and forgot that it refers to the Polish version.
___
*[`Examples/java-simple/README.md` line 8 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDSC-3vgbK9rNf1d4:-NWg1_oYArK_6vP8rzAI:b7dc7dh) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have the versions (second item) under Disclaimer? I think it would be better to rename this section to `Notes`
</blockquote></details>

Done. At the beginning this section had a different structure and it made sense at the time.
___
*[`Examples/java-simple/README.md` line 15 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHCqRF3hktXfV4WRj7:-NWg1xycAZc-CT09zvQ1:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It would make sense to swap `OS` and `Size` items places -- then you'll have logic in this list: first you describe hardware requirements, then software requirements.
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 34 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHWUYo7XLijjCg4_O3:-NWg2-NK4UmhjupNBqvj:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L34)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Pls remove this `using` (it's obvious)
</blockquote></details>

Done.
___
*[`Examples/java-simple/README.md` line 46 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDCzK-36CDDw1_EWZ:-NWg22m76OrEXAcj-itg:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L46)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would actually split this line into two (after the `...aesm.socket`), for readability.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/java-spring-boot.manifest` line 5 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDp6J5VRQhGMkQuet:-NWhTxp-2ERX5QNS41-H:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/java-spring-boot.manifest#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you move it above `sgx.enclave_size` option? Then we'll group two `sgx.` options together, which looks cleaner.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 113 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyN1-JCvkGw0jYphTZ:-NWgyEEe3IIhBmb0NorB:by1p1sy) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L113)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Indeed, sorry that I did not notice the `-d` option. We do need this step. Pls kindly revert, thanks.

But this is under the section `Result`?  
</blockquote></details>

Yes. Creating a new section for container termination seems redundant and can remain in the `Result` section. The user will most likely want to shut it down after running the image. 
___
*[`Examples/java-spring-boot/README.md` line 4 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHDwPb25KbsI4_Unso:-NWgjnBs9qMIDrmtGhS3:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`inside a Gramine SGX enclave graminized containers` -- no, sorry, this doesn't sound like proper English.

Maybe `inside a graminized Docker container, such that the app runs inside the SGX enclave.`
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 7 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHEAN542tjDZafrSDx:-NWgjoW6C2XaTU1Mi3lz:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (maybe `Notes`?)
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 14 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHEEuf56R6w5EYf_Aw:-NWgux5oCsqe6pAFhNQq:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L14)):*
 [...]

2023-06-01 07:32 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner, "Merge branch '" and "fixup! " found in commit messages' one-liners (waiting on @b-garbacz and @kailun-qin)

___
*[`Examples/java-simple/README.md` line 4 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHV7qk2I_p4ziv0OFn:-NWppoB9B9nX_Ii1KQfQ:b-cizdy9) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L4)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

Java code will be consumed at the beginning.*
</blockquote></details>

@kailun-qin I would agree with @b-garbacz here. The original Dockerfile here uses `JavaExample.java` as input (see `java-simple/dockerfile`). So technically, in this description, we have an initial state that consumes the `.java` file (the source code).

But anyway, I think nobody cares about such terminology details?
___
*[`Examples/java-simple/README.md` line 34 at r24](https://reviewable.io/reviews/gramineproject/gsc/145#-NWpqamg96-EYPgL9HEs:-NWpqamg96-EYPgL9HEt:b8pu2f4) ([raw file](https://github.com/gramineproject/gsc/blob/1c91835f87c9185522a3deef55e613009965a054/Examples/java-simple/README.md#L34)):*
> ```Markdown
> ```
> 
> 1. Sign the graminized Docker image:
> ```

What's the deal with the numbering? Why it's `1.` now?
___
*[`Examples/java-spring-boot/README.md` line 113 at r13](https://reviewable.io/reviews/gramineproject/gsc/145#-NUyN1-JCvkGw0jYphTZ:-NWprazK-PdaenIoNUUj:b-24h0w1) ([raw file](https://github.com/gramineproject/gsc/blob/cb77c6278525b958157f045e5725608e52bed549/Examples/java-spring-boot/README.md#L113)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

Yes. Creating a new section for container termination seems redundant and can remain in the `Result` section. The user will most likely want to shut it down after running the image. 
</blockquote></details>

Actually, I also don't like that this "terminate the container" step is located under `Result`.

What if remove the `Result` section and simply continue our numbering of the previous section? Technically, the steps here also pertain to `... run graminized Docker image` -- in the sense that we run the image, check how it runs, and then kill this image.
___
*[`Examples/java-spring-boot/README.md` line 18 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHEqNd0QUrGD4FiXDN:-NWpqzX63OVqRNp7qA5z:b-75fuqi) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-spring-boot/README.md#L18)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

I moved `Software requirements` to `Notes` as items. In my opinion it looks much better
</blockquote></details>

Yes, I also like it.
___
*[`Examples/java-spring-boot/README.md` line 91 at r24](https://reviewable.io/reviews/gramineproject/gsc/145#-NWprqZ43RyCDaQEtVJr:-NWprqZ43RyCDaQEtVJs:b-z4pdkk) ([raw file](https://github.com/gramineproject/gsc/blob/1c91835f87c9185522a3deef55e613009965a054/Examples/java-spring-boot/README.md#L91)):*
> ```Markdown
> $ cat index.html
> ```
> 2. To terminate the graminized container with Spring-Boot application, run the command:
> ```

You messed the numbering again :) Why is it `2.`?


<!-- Sent from Reviewable.io -->

2023-06-01 11:05 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)



<!-- Sent from Reviewable.io -->

2023-06-01 11:49 UTC, kailun-qin requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @b-garbacz)

___
*[`Examples/java-simple/README.md` line 4 at r23](https://reviewable.io/reviews/gramineproject/gsc/145#-NWHV7qk2I_p4ziv0OFn:-NWqFTpS0seu_ttv9RIn:bxva46x) ([raw file](https://github.com/gramineproject/gsc/blob/946bc04f28a0be367849eb6945a251a6ae5d9611/Examples/java-simple/README.md#L4)):*
> But anyway, I think nobody cares about such terminology details?

Yeah, I agree, that's why I opened it for discussions instead of blocking on it. And I also understand that in this sample we're consuming the source code.

My original question was only about this sentense -- `By using the GSC tool, you can deploy graminized containers with Java code.`. Since Java has some "write once, run anywhere" kind of design principle, I was just wondering whether Java is actually deployed as bytecode in Gramine w/ GSC in a real scenario. Anyway, it doesn't really that matter.
___
*[`Examples/java-simple/README.md` line 46 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqjHrY87Ijoziy8cJj:-NWqjHrY87Ijoziy8cJk:bmt8eu3) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-simple/README.md#L46)):*
> ```Markdown
> ```bash
> $ docker run --rm --device=/dev/sgx_enclave \
>         -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
> ```

4-space indent pls
___
*[`Examples/java-spring-boot/README.md` line 66 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWql1n--C207JxdqxRX:-NWql1n--C207JxdqxRY:bmt8eu3) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L66)):*
> ```Markdown
>         ```bash
>         $ docker run --rm --device=/dev/sgx_enclave \
>                 -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
> ```

4-space indent pls
___
*[`Examples/java-spring-boot/README.md` line 71 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWql7LP48WIhOmap5MN:-NWql7LP48WIhOmap5MO:b-7s6wll) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L71)):*
> ```Markdown
>         ```
> 
>       * On a customized port using an environment variable, i.e. 9080:
> ```

e.g.,



_Code quote:_
```Markdown
i.e.
```
___
*[`Examples/java-spring-boot/README.md` line 88 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqmHln4_pcZ25X6MuE:-NWqmHlo4HLKoY8eJBKF:b-5qt35h) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L88)):*
> ```Markdown
> ```bash
> $ wget -q localhost:<port>
> $ cat index.html
> ```

Can we just `curl` here instead of getting the `index.html`?



_Code quote:_
```Markdown
$ wget -q localhost:<port>
$ cat index.html
```
___
*[`Examples/java-spring-boot/README.md` line 93 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqlfEZ1JshuLVbvp0W:-NWqlfEZ1JshuLVbvp0X:b-mz6v8v) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L93)):*
> ```Markdown
> 8. To terminate the graminized container with Spring-Boot application, run the command:
> ```sh
> $ docker stop <containerID>
> ```

What about giving a name to the container and we won't need to specify the `containerID` here to stop it?



_Code quote:_
```Markdown
docker stop <containerID>
```


<!-- Sent from Reviewable.io -->

2023-06-01 14:48 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 16 of 19 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

___
*[`Examples/java-simple/JavaExample.java` line 5 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWrNYAK58YS61Yh99TE:-NWrNYAK58YS61Yh99TF:bgprnzf) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-simple/JavaExample.java#L5)):*
> ```Java
> class JavaExample {
>     public static void main(String[] args) {
>         System.out.println("Hello from Gramine!");
> ```

I will change it to  "Hello from Graminized Java application". This is something I overlooked and this is not true.



_Code quote:_
```Java
Hello from Gramine!
```
___
*[`Examples/java-simple/README.md` line 46 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqjHrY87Ijoziy8cJj:-NWrMdmECqtXQUOciNlb:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-simple/README.md#L46)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

4-space indent pls
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 66 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWql1n--C207JxdqxRX:-NWrMeCuD7Wh93L6G1Lm:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L66)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

4-space indent pls
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 71 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWql7LP48WIhOmap5MN:-NWrMeXd-_sYgprvvUof:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L71)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

e.g.,
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 88 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqmHln4_pcZ25X6MuE:-NWrECVQ7Jd9rbFjZv1c:b6eznrk) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L88)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Can we just `curl` here instead of getting the `index.html`?
</blockquote></details>

No, because curl needs to be installed. Maybe the user doesn't want to use curl. If we can verify without installing additional packages then let's do it.
___
*[`Examples/java-spring-boot/README.md` line 91 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWrOtgYCL5onS-6nlid:-NWrOtgYCL5onS-6nlie:b-sk2e52) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L91)):*
> ```Markdown
> ```
> 
> 8. To terminate the graminized container with Spring-Boot application, run the command:
> ```

I suggest to change it to "stop" by referring to https://docs.docker.com/engine/reference/commandline/stop/. The Documentation doesn't say anything about terminating, only stopping.



_Code quote:_
```Markdown
terminate
```
___
*[`Examples/java-spring-boot/README.md` line 93 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqlfEZ1JshuLVbvp0W:-NWrGaLA9QNam_5nuQR5:b8yhkab) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L93)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

What about giving a name to the container and we won't need to specify the `containerID` here to stop it?
</blockquote></details>

In my opinion it is enough because in this example we don't use --name option:
![image.png](https://files.reviewableusercontent.io/images/reviewable/45511879/d1a1mvlsMi-UUdxUTYelSJBY/image.png)
As you can see, docker will immediately display the container id and we will use it to stop it. 
If the user wants to name it, they obviously know Docker enough to stop it by name.


<!-- Sent from Reviewable.io -->

2023-06-02 00:40 UTC, kailun-qin requested changes
> Reviewed 4 of 19 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r9, 1 of 4 files at r13, 1 of 1 files at r22, 4 of 5 files at r23, 2 of 4 files at r24, 3 of 3 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @b-garbacz)

___
*[`Examples/java-spring-boot/README.md` line 88 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqmHln4_pcZ25X6MuE:-NWtXO-tA8ieCGs8AfmJ:b-sqxwuu) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L88)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

No, because curl needs to be installed. Maybe the user doesn't want to use curl. If we can verify without installing additional packages then let's do it.
</blockquote></details>

Fair enough. Then what about `wget -qO- <URL>`? Does this serve the purpose?
___
*[`Examples/java-spring-boot/README.md` line 93 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqlfEZ1JshuLVbvp0W:-NWtXgJl5pN-A_O8k1M7:b-7lishy) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L93)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

In my opinion it is enough because in this example we don't use --name option:
![image.png](https://files.reviewableusercontent.io/images/reviewable/45511879/d1a1mvlsMi-UUdxUTYelSJBY/image.png)
As you can see, docker will immediately display the container id and we will use it to stop it. 
If the user wants to name it, they obviously know Docker enough to stop it by name.

</blockquote></details>

OK, resolving.
___
*[`Examples/java-spring-boot/README.md` line 93 at r26](https://reviewable.io/reviews/gramineproject/gsc/145#-NWtY4JvDRbBxzlnBQRT:-NWtY4JvDRbBxzlnBQRU:b-svg4lu) ([raw file](https://github.com/gramineproject/gsc/blob/510ecc274654ca42900c882572ba8b939b0d6d1a/Examples/java-spring-boot/README.md#L93)):*
> ```Markdown
> 8. To stop the graminized container with Spring-Boot application, run the command:
> 
> ```sh
> ```

bash (to align w/ the others)



_Code quote:_
```Markdown
sh
```


<!-- Sent from Reviewable.io -->

2023-06-02 08:09 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 18 of 19 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin)

___
*[`Examples/java-spring-boot/README.md` line 88 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWqmHln4_pcZ25X6MuE:-NWv8nbhBLgxpnltTQoy:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L88)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Fair enough. Then what about `wget -qO- <URL>`? Does this serve the purpose?
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/README.md` line 93 at r26](https://reviewable.io/reviews/gramineproject/gsc/145#-NWtY4JvDRbBxzlnBQRT:-NWv8oea9LgyS_BzMaoB:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/510ecc274654ca42900c882572ba8b939b0d6d1a/Examples/java-spring-boot/README.md#L93)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

bash (to align w/ the others)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-02 09:09 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-06-02 09:15 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r26, 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`Examples/java-spring-boot/README.md` line 91 at r25](https://reviewable.io/reviews/gramineproject/gsc/145#-NWrOtgYCL5onS-6nlid:-NWvNrZV9KXHeUBqHvt3:b-weawdq) ([raw file](https://github.com/gramineproject/gsc/blob/4943a99dd7e5c39cbe4f61d1db5911967a1a58ab/Examples/java-spring-boot/README.md#L91)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

I suggest to change it to "stop" by referring to https://docs.docker.com/engine/reference/commandline/stop/. The Documentation doesn't say anything about terminating, only stopping.
</blockquote></details>

Sure. I guess I suggested the word `terminate`? I'm fine with `stop`.


<!-- Sent from Reviewable.io -->

2023-08-24 15:06 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 4 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @b-garbacz and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-Ncc44WN6enhmA17WnY7:-Ncc44WN6enhmA17WnY8:b-nue9q3) (no related file):*
We are moving to the BSD-3 license from LGPL. Thus all LGPL files in this PR should be re-license to BSD-3.

___


<!-- Sent from Reviewable.io -->

2023-09-04 07:31 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 4 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @kailun-qin)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-Ncc44WN6enhmA17WnY7:-NdU5bYx-_IVsVqpySSp:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We are moving to the BSD-3 license from LGPL. Thus all LGPL files in this PR should be re-license to BSD-3.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-09-18 09:18 UTC, dimakuv approved these changes
> Reviewed 11 of 15 files at r29, 4 of 4 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-09-19 00:46 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 11 of 15 files at r29, 4 of 4 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2024-02-07 18:51 UTC, mkow requested changes
> Reviewed 1 of 19 files at r2, 2 of 2 files at r3, 1 of 1 files at r9, 11 of 15 files at r29, 4 of 4 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @b-garbacz)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
This needs to be fixed.
___
*[`Examples/java-simple/dockerfile` line 1 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3JERY65L8-9Wr9Rxw:-Nq3JERY65L8-9Wr9Rxx:b-szrimn) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-simple/dockerfile#L1)):*
> ```
> FROM openjdk:11
> ```

Shouldn't it be `Dockerfile`, not `dockerfile`?
___
*[`Examples/java-simple/JavaExample.java` line 3 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3KL5564YesPhu0rau:-Nq3KL5564YesPhu0rav:bvhw5ft) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-simple/JavaExample.java#L3)):*
> ```Java
> // SPDX-License-Identifier: BSD-3-Clause
> // Copyright (C) 2023 Intel Corp.
> //                          Bartłomiej Garbacz <bartomiej.garbacz@intel.com>
> ```

Please unify with the other copyright notices in our repo (spacing and Intel name spelling). Ditto for other places.
___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-Nq3qFuIBd_m0vonmoS5:bll4lo4) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-simple/README.md#L10)):*
> ```Markdown
> ## Notes
> 
> * This generated image is for non-production usage.
> ```

Please briefly explain why and what steps / where to look to fix that (currently it's not really actionable for the user reading it).
___
*[`Examples/java-spring-boot/dockerfile` line 1 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3JLrOEYrTeM3STvoO:-Nq3JLrOEYrTeM3STvoP:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-spring-boot/dockerfile#L1)):*
> ```
> FROM openjdk:11
> ```

ditto
___
*[`Examples/java-spring-boot/README.md` line 9 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3tBwwBampqC0i2mZr:-Nq3tBwx6-M9TaoUFnYI:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-spring-boot/README.md#L9)):*
> ```Markdown
> ## Notes
> 
> * This generated image is for non-production usage.
> ```

ditto
___
*[`Examples/java-spring-boot/README.md` line 29 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3tWl4CgmiOy6XC_X0:-Nq3tWl4CgmiOy6XC_X1:bqmqorq) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-spring-boot/README.md#L29)):*
> ```Markdown
> 
> ```bash
> $ (cd spring-boot-web-service/; gradle build)
> ```

Please fix all shell snippets like this.



_Suggestion:_
```Markdown
$ (cd spring-boot-web-service/ && gradle build)
```
___
*[`Examples/java-spring-boot/spring-boot-web-service/src/main/resources/application.properties` line 1 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3u7MR35FGzYSMez5T:-Nq3u7MR35FGzYSMez5U:b-i1jhmj) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-spring-boot/spring-boot-web-service/src/main/resources/application.properties#L1)):*
> ```INI
> server.port=8080
> ```

Please add a newline


<!-- Sent from Reviewable.io -->

2024-02-08 13:34 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This needs to be fixed.
</blockquote></details>

@mkow 
Could you explain what should be fixed? This is a merge that updates gramine versions from 1.4 to 1.5. Not quite sure what is to be fixed in this commit.


<!-- Sent from Reviewable.io -->

2024-02-08 14:31 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-Nq84cOy07pN2ddFwlgC:bolc7yn) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please briefly explain why and what steps / where to look to fix that (currently it's not really actionable for the user reading it).
</blockquote></details>

@mkow   
Is redirecting to documentation enough? In both cases user have to follow prerequsites declarated in https://gramine.readthedocs.io/projects/gsc , install jdk11 and in spring boot case install gradle. Basically following the documentation and then following the steps below, the environment works. 

Did you encounter any error during graminization of any java example? Could you explain what you mean by that?


<!-- Sent from Reviewable.io -->

2024-02-09 00:33 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @b-garbacz)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

@mkow 
Could you explain what should be fixed? This is a merge that updates gramine versions from 1.4 to 1.5. Not quite sure what is to be fixed in this commit.
</blockquote></details>

There's only one commit in this PR and:
- The commit contains two new Java examples
- The commit message says "Merge pull request #1 from gramineproject/master" + "Merge gramine 1.5"

So, both don't match each other. Please see https://gramine.readthedocs.io/en/latest/devel/contributing.html and how other commits in our projects look like.
___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-NqAGnv41rdyDnLkw68b:b-l15yct) ([raw file](https://github.com/gramineproject/gsc/blob/b15f04dfa90f188171692473f62a82793436ace7/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

@mkow   
Is redirecting to documentation enough? In both cases user have to follow prerequsites declarated in https://gramine.readthedocs.io/projects/gsc , install jdk11 and in spring boot case install gradle. Basically following the documentation and then following the steps below, the environment works. 

Did you encounter any error during graminization of any java example? Could you explain what you mean by that?
</blockquote></details>

But I didn't write this comment that it's for non-production, you wrote it? I'm just asking to explain to the reader what do you mean by that or where the user can find a solution :)


<!-- Sent from Reviewable.io -->

2024-02-09 11:40 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 8 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There's only one commit in this PR and:
- The commit contains two new Java examples
- The commit message says "Merge pull request #1 from gramineproject/master" + "Merge gramine 1.5"

So, both don't match each other. Please see https://gramine.readthedocs.io/en/latest/devel/contributing.html and how other commits in our projects look like.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-09 15:22 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 8 of 19 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`Examples/java-simple/dockerfile` line 1 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3JERY65L8-9Wr9Rxw:-NqDSDuV5qWycu0HBnyI:b-2mcbst) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/dockerfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't it be `Dockerfile`, not `dockerfile`?
</blockquote></details>

You are right! Done.
___
*[`Examples/java-simple/JavaExample.java` line 3 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3KL5564YesPhu0rau:-NqDQ9rP4uoat_2enwzF:b-l5dcud) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/JavaExample.java#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please unify with the other copyright notices in our repo (spacing and Intel name spelling). Ditto for other places.
</blockquote></details>

Referring to the consistency of the license with https://github.com/gramineproject/gsc/blob/master/gsc I only corrected the spacing
___
*[`Examples/java-spring-boot/dockerfile` line 1 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3JLrOEYrTeM3STvoO:-NqDSTAb8b5XIu4jVLfo:b-7gtacv) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-spring-boot/dockerfile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Ditto done.
___
*[`Examples/java-spring-boot/README.md` line 29 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3tWl4CgmiOy6XC_X0:-NqDQd4h0U1fB6hqSp0W:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-spring-boot/README.md#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix all shell snippets like this.
</blockquote></details>

Done.
___
*[`Examples/java-spring-boot/spring-boot-web-service/src/main/resources/application.properties` line 1 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3u7MR35FGzYSMez5T:-NqDQf7D7XY2Shx0hF_d:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-spring-boot/spring-boot-web-service/src/main/resources/application.properties#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please add a newline
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-10 15:57 UTC, mkow requested changes
> Reviewed 11 of 11 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @b-garbacz)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
The one-liner is still in the wrong format ;) Again:

> Please see [https://gramine.readthedocs.io/en/latest/devel/contributing.html](https://gramine.readthedocs.io/en/latest/devel/contributing.html) and how other commits in our projects look like.
___
*[`Examples/java-simple/JavaExample.java` line 3 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3KL5564YesPhu0rau:-NqId6cW443uIySEAgvD:b-bajkk6) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/JavaExample.java#L3)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

Referring to the consistency of the license with https://github.com/gramineproject/gsc/blob/master/gsc I only corrected the spacing
</blockquote></details>

Ah, ok, someone wrote it weirdly there and seems it was copied all over the GSC. Unblocking then.


<!-- Sent from Reviewable.io -->

2024-03-07 10:14 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 17 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-NsNObwD2nX_bAZ6OH3B:bo8ehi4) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But I didn't write this comment that it's for non-production, you wrote it? I'm just asking to explain to the reader what do you mean by that or where the user can find a solution :)
</blockquote></details>

@mkow  
A decision has been made to remove this disclaimer:)
___
*[`Examples/java-spring-boot/README.md` line 9 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3tBwwBampqC0i2mZr:-NsNP2lp6vCR1Q4LcQMO:b-z1ti1b) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-spring-boot/README.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

ditto done.


<!-- Sent from Reviewable.io -->

2024-03-08 13:56 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 17 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @b-garbacz)

___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-NsTL6Ow7C4vLg8OQhm2:bpfwzij) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

@mkow  
A decision has been made to remove this disclaimer:)
</blockquote></details>

But why? This is open source, please describe the reasoning here, not in some private discussions :)

So: why did you add this disclaimer originally and why it isn't needed anymore?


<!-- Sent from Reviewable.io -->

2024-03-08 15:00 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 17 of 19 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-NsTXyoL9scpMC_sQ6BB:b2e1xfl) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But why? This is open source, please describe the reasoning here, not in some private discussions :)

So: why did you add this disclaimer originally and why it isn't needed anymore?
</blockquote></details>

I assume as the application is in examples, despite the fact that GSC is used correctly, user will put all efforts to analyze usage of that example against his scenario. This example could be a guide  on GSC part but will not cover other aspects i.e attestation, Spring Boot should not only be based on GSC security but also on correct security of configuration. @mkow  any suggestion how to communicate that wll in this example? It is not also said in main README as also not mentioned in openvino example. We only mention it [here](https://gramine.readthedocs.io/projects/gsc/en/latest/#example "https://gramine.readthedocs.io/projects/gsc/en/latest/#example") but it is refering to simple gsc run. 


<!-- Sent from Reviewable.io -->

2024-03-10 13:54 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @b-garbacz)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
> As a result, there is only one commit

There are 5 commits right now.

Also, the one-liner should be "Add two Java examples".
___
*[`Examples/java-simple/README.md` line 10 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3qFuIBd_m0vonmoS4:-NsccZHC3kJVV_S3NL5F:bira7da) ([raw file](https://github.com/gramineproject/gsc/blob/09160c2ddde7f6ecc34aeb9f805775bc2201bdb1/Examples/java-simple/README.md#L10)):*
<details><summary><i>Previously, b-garbacz wrote…</i></summary><blockquote>

I assume as the application is in examples, despite the fact that GSC is used correctly, user will put all efforts to analyze usage of that example against his scenario. This example could be a guide  on GSC part but will not cover other aspects i.e attestation, Spring Boot should not only be based on GSC security but also on correct security of configuration. @mkow  any suggestion how to communicate that wll in this example? It is not also said in main README as also not mentioned in openvino example. We only mention it [here](https://gramine.readthedocs.io/projects/gsc/en/latest/#example "https://gramine.readthedocs.io/projects/gsc/en/latest/#example") but it is refering to simple gsc run.
</blockquote></details>

But the link you mentioned is about a different case, where an example uses an insecure manifest option. Here I don't see that, so I guess it should be ok to remove the warning from here? I was just confused why it was here in the first place.


<!-- Sent from Reviewable.io -->

2024-03-11 07:45 UTC, dimakuv approved these changes
> Reviewed 9 of 11 files at r32, 2 of 2 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 1 unresolved discussion (waiting on @dimakuv)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> As a result, there is only one commit

There are 5 commits right now.

Also, the one-liner should be "Add two Java examples".
</blockquote></details>

@b-garbacz We use the git-fixup style for non-main commits. Please check other Gramine-related PRs for reference. Sorry if our documentation wasn't clear on this point, Michal submitted a PR to make it more explicit.

Anyway, now that the PR is approved, I will myself squash all these 5 commits into one and fix the commit title. Please don't do anything with this PR from this moment on. It's not our (Gramine maintainers) responsibility to finalize this PR and merge it.


<!-- Sent from Reviewable.io -->

2024-03-11 09:06 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @b-garbacz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-Nsgkill1_6Jc5RrVSzw:-Nsgkill1_6Jc5RrVSzx:b-qeznjf) (no related file):*
CI folks asked to postpone merging this PR **after** we release v1.6.2 and tag GSC with that version. So creating a blocking comment.

___


<!-- Sent from Reviewable.io -->

2024-03-11 13:41 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @b-garbacz and @dimakuv)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
> [@b-garbacz](https://github.com/b-garbacz) We use the git-fixup style for non-main commits. Please check other Gramine-related PRs for reference. Sorry if our documentation wasn't clear on this point, Michal submitted a PR to make it more explicit.

This is already explained in the document I liked to above ;)
https://gramine.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle


<!-- Sent from Reviewable.io -->

2024-03-12 01:19 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 9 of 11 files at r32, 2 of 2 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 2 unresolved discussions (waiting on @b-garbacz and @dimakuv)



<!-- Sent from Reviewable.io -->

2024-03-13 17:08 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 2 unresolved discussions (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-Nsgkill1_6Jc5RrVSzw:-NssmKWRESZQkE9Ycy3Q:b-vss4ri) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

CI folks asked to postpone merging this PR **after** we release v1.6.2 and tag GSC with that version. So creating a blocking comment.
</blockquote></details>

This was done, we can proceed now.

___


<!-- Sent from Reviewable.io -->

2024-03-14 08:44 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 2 at r30](https://reviewable.io/reviews/gramineproject/gsc/145#-Nq3IbEtAW1gdjPWEGWB):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> [@b-garbacz](https://github.com/b-garbacz) We use the git-fixup style for non-main commits. Please check other Gramine-related PRs for reference. Sorry if our documentation wasn't clear on this point, Michal submitted a PR to make it more explicit.

This is already explained in the document I liked to above ;)
https://gramine.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle
</blockquote></details>

Done, rebased and ready for merge


<!-- Sent from Reviewable.io -->

2024-03-15 01:38 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-03-18 01:10 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-18 01:14 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @b-garbacz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-NtE6n4ACxP_4wtST9lp:-NtE6n4ACxP_4wtST9lq:b55xoym) (no related file):*
Some of these files have Windows newlines instead of Linux, please fix.

___


<!-- Sent from Reviewable.io -->

2024-03-18 05:34 UTC, anjalirai-intel commented
@dimakuv We have verified the both of the java examples and they are working fine. No issues seen. You can go ahead with the PR merge.

2024-03-18 13:46 UTC, b-garbacz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: 16 of 19 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/145#-NtE6n4ACxP_4wtST9lp:-NtGo1-l316igBZ3XIXi:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Some of these files have Windows newlines instead of Linux, please fix.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-03-19 16:05 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2024-03-20 02:50 UTC, kailun-qin approved these changes
> Reviewed 3 of 3 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/145)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-03-20 11:53 UTC, merged