[GSC] Install toml python package properly
gramineproject/gsc pull request #15
Opened 2021-09-20 05:55 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Using quotes around toml python package specifier (`toml>=0.10`) in build and compile template files as the specifier is using `>`.
Please note below from this link https://pip.pypa.io/en/stable/cli/pip_install/
Use quotes around specifiers in the shell when using >, <, or when using environment markers.

If there is an existing toml package with version less than `0.10` in the base image, the current code fails to upgrade to version `0.10` or above. 

Fixes gramineproject/graphene#2684.

## How to test this PR? 
Follow the steps to reproduce mentioned in issue gramineproject/graphene#2684.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/graphene/2678)

2021-09-20 17:53 UTC, dimakuv commented
@sahason Could you resubmit this PR, because Reviewable is broken? Just close this one and re-submit as a new PR.

2021-09-20 23:19 UTC, mkow reviewed
Not needed anymore, I fixed with it a bit of @pkaminski's help, thanks!

Seems that @sahason copied the PR description from the old PR literally, including the Reviewable badge with the stale link. Then @dimakuv tried to fix it up by just changing the link, but this confused Reviewable - it had a check whether the review was already created and noticed that the PR description already has the Reviewable badge, so it didn't create the review.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/15#-:-Mk4UET38ZUUHj26WSmA:bia15g5)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2021-09-21 04:33 UTC, sahason commented
Currently, when I tried to create a PR the template in PR description was not filling as per graphene repo. Hence I used the old template but I made a mistake in the reviewable part that I understood now. Sorry for the inconvenience.
Could you please make changes such that the template is automatically filled in PR description?

2021-09-21 07:39 UTC, dimakuv requested changes
@mkow Thanks. Your description of our actions is exactly correct :) I thought it would be easier to just create a new PR, but since this could be fixed -- that's good.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/15#-:-Mk6H50367sqxPS0DNeh:bwu4xo9)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[templates/Dockerfile.ubuntu18.04.build.template, line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/15#-Mk6HdAmBPYX19TWvUxt:-Mk6HdAmBPYX19TWvUxu:bo7oja4) ([raw file](https://github.com/gramineproject/gsc/blob/a72ba3cc1bb1886602e01207e79f21695a404775/templates/Dockerfile.ubuntu18.04.build.template#L21)):*
> ```
>         python3-pip \
>         python3-protobuf \
>     && python3 -B -m pip install protobuf jinja2 "toml>=0.10"
> ```

I notice that the referenced https://pip.pypa.io/en/stable/cli/pip_install/ uses single-quotes (`'`) instead of the double-quotes (`"`). There is most probably no difference, but maybe replace your double-quotes with single-quotes in this PR?


<!-- Sent from Reviewable.io -->

2021-09-21 10:03 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/15)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[templates/Dockerfile.ubuntu18.04.build.template, line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/15#-Mk6HdAmBPYX19TWvUxt:-Mk6nsIRBpYMuoaQHjZa:b32w0x) ([raw file](https://github.com/gramineproject/gsc/blob/a72ba3cc1bb1886602e01207e79f21695a404775/templates/Dockerfile.ubuntu18.04.build.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I notice that the referenced https://pip.pypa.io/en/stable/cli/pip_install/ uses single-quotes (`'`) instead of the double-quotes (`"`). There is most probably no difference, but maybe replace your double-quotes with single-quotes in this PR?
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-09-21 10:05 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/15)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/15#-Mk6o8n07Y-jR1AT_nz5:-Mk6o8n07Y-jR1AT_nz6:blhxt95) (no related file):*
@sahason Something is wrong with your Committer git field:
```
Author: Sonali Saha, Committer: Sonali; svenkat9 is not a valid email address.
```

Looks like the email address got all wrong. Could push the new (squashed and rebased) commit with the proper committer setting?

---


<!-- Sent from Reviewable.io -->

2021-09-21 10:59 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/15)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/15#-Mk6o8n07Y-jR1AT_nz5:-Mk7-Zdx1QBOxYhvo8S1:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Something is wrong with your Committer git field:
```
Author: Sonali Saha, Committer: Sonali; svenkat9 is not a valid email address.
```

Looks like the email address got all wrong. Could push the new (squashed and rebased) commit with the proper committer setting?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-09-21 11:58 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/15)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2021-09-28 15:59 UTC, dimakuv commented
This was already fixed as part of https://github.com/gramineproject/gsc/pull/10. Closing this one.

2021-09-28 15:59 UTC, closed without merging