Adding support for debian12, ubuntu22.04 and removing the support of ubuntu18.04
gramineproject/gsc pull request #155
Opened 2023-07-10 17:46 UTC by amathew3

This PR fixes the build issues seen with newer distros ubuntu22.04, debian12 etc.  For newer distros the `apt-get install` is used to install the python packages. 
Also removes the support for ubuntu18.04.

This PR fixes #153

Take the hello-world example in the test folder and modify it to use the ubuntu22.04 base image.
Edit the `config.yaml` file to select the distro as ubuntu:22.04
Do the `gsc build` and `gsc sign` commands.
Expected result: The build build should pass with out errors.

2023-07-11 06:59 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_2g-qY3k1t95sTWoab:-N_2g-qY3k1t95sTWoac:b-mpjqre) (no related file):*
I don't like that this PR combines two independent tasks:
- Removing Ubuntu 18.04
- Adding support for Debian 12/Ubuntu 22.04

The former task is trivial, whereas the latter task is non-trivial and will need careful review from @woju.

Let me create a PR (with Abin as the author, because it will be mostly his stuff) for the first item.

Then, after the first PR is merged, we can rebase this PR on top, dropping "remove Ubuntu 18.04" part.

___


<!-- Sent from Reviewable.io -->

2023-07-11 07:43 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3)

___
*[`templates/debian/Dockerfile.build.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/155#-N_2tsID-pK9Qm64Oa3b:-N_2tsID-pK9Qm64Oa3c:bemq4md) ([raw file](https://github.com/gramineproject/gsc/blob/e620e5960099b4e5a06441e83436c595788e9bc1/templates/debian/Dockerfile.build.template#L21)):*
> ```
>         python3-pyelftools \
>         {%- if (distro[0] == "debian" and distro[1] |int  > 11) or
>               (distro[0] == "ubuntu" and distro[1] |int  > 21) -%}
> ```

But this issue is **not** seen on Ubuntu 22.04? The issue only starts from Ubuntu 23.04...


<!-- Sent from Reviewable.io -->

2023-07-11 10:19 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_2g-qY3k1t95sTWoab:-N_3R5142Yy-F-r8leun:b32wtd) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like that this PR combines two independent tasks:
- Removing Ubuntu 18.04
- Adding support for Debian 12/Ubuntu 22.04

The former task is trivial, whereas the latter task is non-trivial and will need careful review from @woju.

Let me create a PR (with Abin as the author, because it will be mostly his stuff) for the first item.

Then, after the first PR is merged, we can rebase this PR on top, dropping "remove Ubuntu 18.04" part.
</blockquote></details>

ok

___
___
*[`templates/debian/Dockerfile.build.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/155#-N_2tsID-pK9Qm64Oa3b:-N_3REB2BYWBZacoLG63:be9xofg) ([raw file](https://github.com/gramineproject/gsc/blob/e620e5960099b4e5a06441e83436c595788e9bc1/templates/debian/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But this issue is **not** seen on Ubuntu 22.04? The issue only starts from Ubuntu 23.04...
</blockquote></details>

Ubuntu 22.04 support apt installation of these python packages, In the issue #153 the suggestion was to use `apt-get install` as default  step in dockerfile,  So the  >21 check is added in dockerfile.


<!-- Sent from Reviewable.io -->

2023-07-12 08:41 UTC, jinengandhi-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3, @dimakuv, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_8EeoH-iWzqG8sTV9R:b-hex88l) (no related file):*
The current PR looks for the certain distro to decide whether to run `apt install` or `pip` install but instead should we have a solution that checks the `python3` version from which this issue starts i.e. python 3.11? This is in case if you have a workload where the distro might still be Ubuntu22.04 but the installed version of python3 could be higher, there are ways to upgrade python in old distros. GSC will fail with the same PEP668 in such cases.

___


<!-- Sent from Reviewable.io -->

2023-07-12 09:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @jinengandhi-intel and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_8LpNg7MQDx-mPrxol:b-id4m3q) (no related file):*
<details><summary><i>Previously, jinengandhi-intel wrote…</i></summary><blockquote>

The current PR looks for the certain distro to decide whether to run `apt install` or `pip` install but instead should we have a solution that checks the `python3` version from which this issue starts i.e. python 3.11? This is in case if you have a workload where the distro might still be Ubuntu22.04 but the installed version of python3 could be higher, there are ways to upgrade python in old distros. GSC will fail with the same PEP668 in such cases.
</blockquote></details>

Very good point from @jinengandhi-intel. Blocking on this too.

___


<!-- Sent from Reviewable.io -->

2023-07-12 11:20 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jinengandhi-intel, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_8gNNjDu8e9DDmZAjk:b-jue2st) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Very good point from @jinengandhi-intel. Blocking on this too.
</blockquote></details>

The problem here is even that even if users install non-distro latest Python version, this gets overwritten to the latest distro supplied version of Python when GSC templates installs it using 'apt install` . So, the clean solution  would be for GSC to check the version of the installed Python version before doing an `apt install`. However this would apply to all the packages that GSC attempts installing in the user's image (Not only Python). My recommendation would be to support images that go by the distro disciplines for now. And take others as and when someone reports a problem. What say @dimakuv 

___


<!-- Sent from Reviewable.io -->

2023-07-12 11:23 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jinengandhi-intel, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_8pcjT2HM3vEYS_1Se:b-rmt6u2) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

The problem here is even that even if users install non-distro latest Python version, this gets overwritten to the latest distro supplied version of Python when GSC templates installs it using 'apt install` . So, the clean solution  would be for GSC to check the version of the installed Python version before doing an `apt install`. However this would apply to all the packages that GSC attempts installing in the user's image (Not only Python). My recommendation would be to support images that go by the distro disciplines for now. And take others as and when someone reports a problem. What say @dimakuv 
</blockquote></details>

Sorry for the markdown goof-up. No idea how that happened.

___


<!-- Sent from Reviewable.io -->

2023-07-12 12:32 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 0 of 10 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jinengandhi-intel, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_946pB7ht2THGFgBDT:bj1bmc8) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Sorry for the markdown goof-up. No idea how that happened.
</blockquote></details>

There were other typos too. So let me rewrite - 

The problem here is that even if users install non-distro latest Python version, this gets overwritten to the latest distro supplied version of Python when GSC templates installs it using `apt install`. So, the clean solution would be for GSC to check the version of the installed Python before doing an `apt install`. However this would apply to all the packages that GSC attempts installing in the user's image (Not only Python). So implementing this widely would be a non-trivial job. My recommendation would be to support images that go by the distro disciplines for now. And take others as and when someone reports a problem. What say [@dimakuv](https://github.com/dimakuv)

___


<!-- Sent from Reviewable.io -->

2023-07-17 11:21 UTC, dimakuv requested changes
> Reviewed 1 of 10 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3, @jinengandhi-intel, and @woju)

___
*[`config.yaml.template` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZRzZ3Qz9Cr9_8gNx:-N_YZRzZ3Qz9Cr9_8gNy:b9eeltq) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/config.yaml.template#L6)):*
> ```
> #
> # Currently supported distros are:
> # - ubuntu:20.04, ubuntu:21.04, ubuntu:22.04
> ```

What about 23.04? I think it's also supported now, right?
___
*[`templates/debian/Dockerfile.build.template` line 21 at r1](https://reviewable.io/reviews/gramineproject/gsc/155#-N_2tsID-pK9Qm64Oa3b:-N_YZXoND05gk9Nlw9LU:bf25cek) ([raw file](https://github.com/gramineproject/gsc/blob/e620e5960099b4e5a06441e83436c595788e9bc1/templates/debian/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

Ubuntu 22.04 support apt installation of these python packages, In the issue #153 the suggestion was to use `apt-get install` as default  step in dockerfile,  So the  >21 check is added in dockerfile.
</blockquote></details>

Ah, I see your reasoning. Resolving.
___
*[`templates/debian/Dockerfile.build.template` line 20 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZefUCjeti_5JRM2s:-N_YZefUCjeti_5JRM2t:b-9ew29) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.build.template#L20)):*
> ```
>         python3-pyelftools \
>         {%- if (distro[0] == "debian" and distro[1] |int  > 11) or
>               (distro[0] == "ubuntu" and distro[1] |int  > 21) -%}
> ```

Could you add one more space before `(distro[0] ...`? This way the two lines will be nicely indented, and it will be more readable.
___
*[`templates/debian/Dockerfile.build.template` line 25 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_-MY6aDWA1xGdZij:-N_Y_-MY6aDWA1xGdZik:brqynot) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.build.template#L25)):*
> ```
>            python3-tomli \
>            python3-tomli-w \
>            python3-toml \
> ```

We can remove this `python3-toml`, it's completely deprecated now.
___
*[`templates/debian/Dockerfile.build.template` line 28 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZtfY1NpYYIxwaqBP:-N_YZtfY1NpYYIxwaqBQ:bs39kpd) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.build.template#L28)):*
> ```
>         {%- else -%}
>            python3-pip \
>            && /usr/bin/python3 -B -m pip install click jinja2 protobuf \
> ```

Why do we have `protobuf` here, if we already unconditionally install it above? Please remove from this list here, and check that everything still works.
___
*[`templates/debian/Dockerfile.compile.template` line 31 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_5r03ccvXSnOBqxR:-N_Y_5r03ccvXSnOBqxS:bblvwhu) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.compile.template#L31)):*
> ```
>            python3-tomli \
>            python3-tomli-w \
>            python3-toml 
> ```

ditto (remove this line)
___
*[`templates/debian/Dockerfile.sign.template` line 17 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_EPj0DK--WA1RUqA:-N_Y_EPj0DK--WA1RUqB:b-l1ifmw) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.sign.template#L17)):*
> ```
>            python3-tomli \
>            python3-tomli-w \
>            python3-toml \
> ```

ditto (remove)
___
*[`templates/debian/Dockerfile.sign.template` line 24 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_IGT9_t7tGAOzWsb:-N_Y_IGT9_t7tGAOzWsc:bgt34v9) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.sign.template#L24)):*
> ```
>            && apt-get install -y python3-pip \
>            && pip3 uninstall -y click jinja2 \
>               tomli tomli-w \
> ```

This can be merged with the previous line, like this:
```
           && pip3 uninstall -y click jinja2 tomli tomli-w \
```


<!-- Sent from Reviewable.io -->

2023-07-17 11:22 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3 and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_Y_T5UBKuydsY5bn1L:b-iykrnq) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

There were other typos too. So let me rewrite - 

The problem here is that even if users install non-distro latest Python version, this gets overwritten to the latest distro supplied version of Python when GSC templates installs it using `apt install`. So, the clean solution would be for GSC to check the version of the installed Python before doing an `apt install`. However this would apply to all the packages that GSC attempts installing in the user's image (Not only Python). So implementing this widely would be a non-trivial job. My recommendation would be to support images that go by the distro disciplines for now. And take others as and when someone reports a problem. What say [@dimakuv](https://github.com/dimakuv)
</blockquote></details>

Hm, I see Anees's point. I guess I agree.

I'd like to learn @woju's opinion.

___


<!-- Sent from Reviewable.io -->

2023-07-18 09:24 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 7 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`config.yaml.template` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZRzZ3Qz9Cr9_8gNx:-N_cHjwKB9IuxkWSIQy7:b-cexcdl) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/config.yaml.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about 23.04? I think it's also supported now, right?
</blockquote></details>

yes, we can build with 23.04. Since gramine is not officially supported Ubuntu23.04, it is not added in config.yaml 
___
*[`templates/debian/Dockerfile.build.template` line 20 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZefUCjeti_5JRM2s:-N_bck-K4uUp74kr_3c_:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.build.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you add one more space before `(distro[0] ...`? This way the two lines will be nicely indented, and it will be more readable.
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.build.template` line 25 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_-MY6aDWA1xGdZij:-N_bd7A_3kwZF1Nc5EVm:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.build.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can remove this `python3-toml`, it's completely deprecated now.
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.build.template` line 28 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZtfY1NpYYIxwaqBP:-N_bdk0T9KjWQvARyOOc:bnk6jey) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.build.template#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we have `protobuf` here, if we already unconditionally install it above? Please remove from this list here, and check that everything still works.
</blockquote></details>

protobuf is removed from pip3 install list. tested with Ubuntu and Debian versions. 
___
*[`templates/debian/Dockerfile.compile.template` line 31 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_5r03ccvXSnOBqxR:-N_bdtslCtKz6dc9SO0A:bb7f2mf) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.compile.template#L31)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (remove this line)
</blockquote></details>

done
___
*[`templates/debian/Dockerfile.sign.template` line 17 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_EPj0DK--WA1RUqA:-N_bdvAxDkYq2AzTHMdV:bb7f2mf) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.sign.template#L17)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (remove)
</blockquote></details>

done
___
*[`templates/debian/Dockerfile.sign.template` line 24 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_Y_IGT9_t7tGAOzWsb:-N_bdxNZCeqdrXCtrzhj:bb7f2mf) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/templates/debian/Dockerfile.sign.template#L24)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This can be merged with the previous line, like this:
```
           && pip3 uninstall -y click jinja2 tomli tomli-w \
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-07-18 10:57 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`config.yaml.template` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/155#-N_YZRzZ3Qz9Cr9_8gNx:-N_cchty31ij6t5Yau-9:b-8qihgt) ([raw file](https://github.com/gramineproject/gsc/blob/f150da3ea23fa7526cdcf1cd63296dc506c83f5c/config.yaml.template#L6)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

yes, we can build with 23.04. Since gramine is not officially supported Ubuntu23.04, it is not added in config.yaml 
</blockquote></details>

Ok, can be separate.


<!-- Sent from Reviewable.io -->

2023-07-19 13:40 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jinengandhi-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-N_8EeoH-iWzqG8sTV9Q:-N_iKpi48eCFnuBN-gMP:b-mvcuqk) (no related file):*
> The current PR looks for the certain distro to decide whether to run `apt install` or `pip` install but instead should we have a solution that checks the `python3` version from which this issue starts i.e. python 3.11? This is in case if you have a workload where the distro might still be Ubuntu22.04 but the installed version of python3 could be higher, there are ways to upgrade python in old distros. GSC will fail with the same PEP668 in such cases.

This is incorrect, PEP 668 trigger (presence of file `EXTERNALLY-MANAGED` in python's libdir; see PEP for details) is specific to distro and distro's version, not to the version of python. I.e. on Ubuntu 22.04, if you install `python3.11`, there's no `EXTERNALLY-MANAGED` file in `/usr/lib/python3.11` or anywhere else, so `python3.11 -m pip install` works as usual (just because Debian and/or Ubuntu people added it in "Debian 12", not in "python 3.11"). Additionally, availability of click, jinja and tomli in required version is also correlated with distro version too (e.g. there's no `python3.11-tomli-w`). Therefore the choice to change install procedure depending in distro version is correct. If there's workload on 22.04 with newer distro-provided python3.y, it will still work. (And if user has self-compiled python, s/he is on his/her own).

___


<!-- Sent from Reviewable.io -->

2023-07-21 08:43 UTC, aneessahib commented
@woju - Can you review rest of the PR pls

2023-08-15 20:16 UTC, woju requested changes
> Reviewed 2 of 10 files at r1, 6 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3, @dimakuv, and @jinengandhi-intel)

___
*[`templates/debian/Dockerfile.build.template` line 20 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-NbulHs3C8-J84TZ52s4:-NbulHs3C8-J84TZ52s5:b-nynd3m) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.build.template#L20)):*
> ```
>         python3-pyelftools \
>         {% if (distro[0] == "debian" and distro[1] |int  > 11) or
>               (distro[0] == "ubuntu" and distro[1] |int  > 21) -%}
> ```

Mutliple stylistic problems:
- spaces around `|` operator: either on both sides or none (as you prefer, it can be `distro[1]|int` or `distro[1] | int`
- single space before unequality operator
- the operator should be `>= 12`, not `> 11` (and similar for Ubuntu), because the question answered is "in which version this was changed", not "after which version this was changed" (you'll find the answer in changelog under this version, not the version before!)
- for Ubuntu: it releases twice a year, so it has release `YY.04` and `YY.10`, and this is not apparent from this comparison; if the logic is correct after all (the threshold is at `22.04` version, not `22.10`), this needs at least a comment here that we're targeting 22.04

Additionally this needs a comment explaining why we're doing this conditional (that the versions in distro are too old, and for each package what version we need). For people who don't know this and might think that they could fold this into one branch, just because there is a package "python3-click" in Ubuntu 20.04.
___
*[`templates/debian/Dockerfile.compile.template` line 26 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-Nbung3b6bu_0470wcCo:-Nbung3b6bu_0470wcCp:b-wevxmd) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.compile.template#L26)):*
> ```
>         wget \
>         {% if (distro[0] == "debian" and distro[1] |int  > 11) or
>               (distro[0] == "ubuntu" and distro[1] |int  > 21) -%}
> ```

ditto (stylistic + comment, or refer to another file, maybe `{# please see comment in file X for explanation for why we need this pip install #}` or something similar)
___
*[`templates/debian/Dockerfile.sign.template` line 13 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-NbunlN9A7XavS6tUW3M:-NbunlN9A7XavS6tUW3N:br3q04o) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.sign.template#L13)):*
> ```
>         python3-pyelftools \
>         {% if (distro[0] == "debian" and distro[1] |int  > 11) or
>               (distro[0] == "ubuntu" and distro[1] |int  > 21) -%}
> ```

ditto (stylistic + comment or reference)
___
*[`templates/debian/Dockerfile.sign.template` line 21 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-Nbuoo5v6xo5aOXDDn8h:-Nbuoo5v6xo5aOXDDn8i:b-22otuw) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.sign.template#L21)):*
> ```
>            && apt-get update -y \
>            && apt-get install -y python3-pip \
>            && pip3 uninstall -y click jinja2 tomli tomli-w \
> ```

Wait, does this uninstall jinja2 and tomli{,-w} from the container with user's application? If so, this is wrong: people might want those packages to be present, (maybe a CRUD with HTML interface rendered with jinja?). Click would also be wrong, because AFAIK it's a dependency of Flask. (I might be wrong on this point though).


<!-- Sent from Reviewable.io -->

2023-08-21 05:56 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), one-liner is not in imperative mood, "fixup! " found in commit messages' one-liners (waiting on @amathew3, @jinengandhi-intel, and @woju)

___
*[`templates/debian/Dockerfile.sign.template` line 21 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-Nbuoo5v6xo5aOXDDn8h:-NcLdy9X0L5THVdUqE6H:b-vg2nv0) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.sign.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Wait, does this uninstall jinja2 and tomli{,-w} from the container with user's application? If so, this is wrong: people might want those packages to be present, (maybe a CRUD with HTML interface rendered with jinja?). Click would also be wrong, because AFAIK it's a dependency of Flask. (I might be wrong on this point though).
</blockquote></details>

@woju This is not a new thing in this PR. This is the refactoring of this change from the older PR: https://github.com/gramineproject/gsc/commit/9d3bc471c73d540e046ce72da5fcd1bcc29f7d2e

That one is gated on the `-Dremove-gramine-deps=true` command-line option to GSC, so this uninstall doesn't happen by default. This is used for minimal non-Python original images.

Even if we go with your suggestion to keep jinja and tomli, then we need to sort all these packages into "definitely needed" and "can be removed": https://github.com/gramineproject/gsc/blob/dd5238699ae24c5c2e92e916f4cd18b17fba0d11/templates/debian/Dockerfile.sign.template#L7-L15

I would just keep the current logic of "remove everything that Gramine installed" as is.


<!-- Sent from Reviewable.io -->

2023-08-23 09:20 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 7 of 10 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jinengandhi-intel, and @woju)

___
*[`templates/debian/Dockerfile.build.template` line 20 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-NbulHs3C8-J84TZ52s4:-Nc6PGwV36Obyv3VqLd2:b-ycrjry) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.build.template#L20)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Mutliple stylistic problems:
- spaces around `|` operator: either on both sides or none (as you prefer, it can be `distro[1]|int` or `distro[1] | int`
- single space before unequality operator
- the operator should be `>= 12`, not `> 11` (and similar for Ubuntu), because the question answered is "in which version this was changed", not "after which version this was changed" (you'll find the answer in changelog under this version, not the version before!)
- for Ubuntu: it releases twice a year, so it has release `YY.04` and `YY.10`, and this is not apparent from this comparison; if the logic is correct after all (the threshold is at `22.04` version, not `22.10`), this needs at least a comment here that we're targeting 22.04

Additionally this needs a comment explaining why we're doing this conditional (that the versions in distro are too old, and for each package what version we need). For people who don't know this and might think that they could fold this into one branch, just because there is a package "python3-click" in Ubuntu 20.04.
</blockquote></details>

The style changes are done.   Also added a comment to explain why the distro package manager is used to install python packages in newer distros(debian 12 and Ubuntu 23.04).
___
*[`templates/debian/Dockerfile.compile.template` line 26 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-Nbung3b6bu_0470wcCo:-Nc7LCDR42IL9GSwsDaG:bb7f2mf) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.compile.template#L26)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (stylistic + comment, or refer to another file, maybe `{# please see comment in file X for explanation for why we need this pip install #}` or something similar)
</blockquote></details>

done
___
*[`templates/debian/Dockerfile.sign.template` line 13 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-NbunlN9A7XavS6tUW3M:-Nc7LS_NCXvQ474txaC6:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.sign.template#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (stylistic + comment or reference)
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.sign.template` line 21 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-Nbuoo5v6xo5aOXDDn8h:-Nc7LldfBuoTxsz_vA54:b7yr12n) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.sign.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Wait, does this uninstall jinja2 and tomli{,-w} from the container with user's application? If so, this is wrong: people might want those packages to be present, (maybe a CRUD with HTML interface rendered with jinja?). Click would also be wrong, because AFAIK it's a dependency of Flask. (I might be wrong on this point though).
</blockquote></details>

This uninstall is based on `--remove-gramine-deps` during the signing stage.


<!-- Sent from Reviewable.io -->

2023-08-23 16:12 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @amathew3, @jinengandhi-intel, and @woju)

___
*[`templates/debian/Dockerfile.build.template` line 20 at r4](https://reviewable.io/reviews/gramineproject/gsc/155#-NcY8LQN8gU1vOX7bMhx:-NcY8LQN8gU1vOX7bMhy:b-jhdv3q) ([raw file](https://github.com/gramineproject/gsc/blob/39e67c4af1eeb3a8bd2380ea32d40275cff4875b/templates/debian/Dockerfile.build.template#L20)):*
> ```
>         python3-pyelftools \
> # debian-12 and ubuntu-23.04 distros have adopted PEP 668, with this change `pip` will no longer
> # install package outside virtual env, hence using distro specific package manager.
> ```

My slight rewording suggestion:
```
# Debian 12 and Ubuntu 23.04 adopted PEP 668, which dictates that `pip` can no longer install
# packages managed by the distro's general-purpose package manager, hence we use `apt-get`
```
___
*[`templates/debian/Dockerfile.compile.template` line 25 at r4](https://reviewable.io/reviews/gramineproject/gsc/155#-NcY9ewLADzGCa2srUIO:-NcY9ewLADzGCa2srUIP:bfcpixj) ([raw file](https://github.com/gramineproject/gsc/blob/39e67c4af1eeb3a8bd2380ea32d40275cff4875b/templates/debian/Dockerfile.compile.template#L25)):*
> ```
>         python3-protobuf \
>         wget \
> # please refer the comment in Dockerfile.build.template to see why this condition is needed
> ```

`please refer the comment ... to see why` -> `please see the comment ... for explanation why`
___
*[`templates/debian/Dockerfile.sign.template` line 12 at r4](https://reviewable.io/reviews/gramineproject/gsc/155#-NcY9o9tAwwpwyho-kXL:-NcY9o9tAwwpwyho-kXM:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/39e67c4af1eeb3a8bd2380ea32d40275cff4875b/templates/debian/Dockerfile.sign.template#L12)):*
> ```
>         python3-cryptography \
>         python3-pyelftools \
> # please refer the comment in Dockerfile.build.template to see why this condition is needed
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-08-24 09:11 UTC, amathew3 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: 7 of 10 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jinengandhi-intel, and @woju)

___
*[`templates/debian/Dockerfile.build.template` line 20 at r4](https://reviewable.io/reviews/gramineproject/gsc/155#-NcY8LQN8gU1vOX7bMhx:-NcanpZ6B6hi0VQ2agTF:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/39e67c4af1eeb3a8bd2380ea32d40275cff4875b/templates/debian/Dockerfile.build.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

My slight rewording suggestion:
```
# Debian 12 and Ubuntu 23.04 adopted PEP 668, which dictates that `pip` can no longer install
# packages managed by the distro's general-purpose package manager, hence we use `apt-get`
```
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.compile.template` line 25 at r4](https://reviewable.io/reviews/gramineproject/gsc/155#-NcY9ewLADzGCa2srUIO:-Ncank0WEO3p8Ay-9KAB:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/39e67c4af1eeb3a8bd2380ea32d40275cff4875b/templates/debian/Dockerfile.compile.template#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`please refer the comment ... to see why` -> `please see the comment ... for explanation why`
</blockquote></details>

Done
___
*[`templates/debian/Dockerfile.sign.template` line 12 at r4](https://reviewable.io/reviews/gramineproject/gsc/155#-NcY9o9tAwwpwyho-kXL:-Ncanzk19PoAnbyiPDam:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/39e67c4af1eeb3a8bd2380ea32d40275cff4875b/templates/debian/Dockerfile.sign.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-24 15:13 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jinengandhi-intel and @woju)



<!-- Sent from Reviewable.io -->

2023-08-24 16:15 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 10 files at r1, 6 of 9 files at r2, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @amathew3, @jinengandhi-intel, and @woju)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/gramineproject/gsc/155#-NccJYLA03xIfBn0GK7S):*
Wrong format



_Code quote:_
```
Supporting new distros ubuntu22.04, debian12
```


<!-- Sent from Reviewable.io -->

2023-08-24 16:15 UTC, mkow reviewed
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @amathew3, @jinengandhi-intel, and @woju)



<!-- Sent from Reviewable.io -->

2023-08-25 03:38 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 6 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jinengandhi-intel, @mkow, and @woju)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/gramineproject/gsc/155#-NccJYLA03xIfBn0GK7S):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Wrong format
</blockquote></details>

We can fix it during final rebase (`Add support of Ubuntu 22.04 and Debian12`)


<!-- Sent from Reviewable.io -->

2023-08-25 08:01 UTC, woju approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 2 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @jinengandhi-intel and @mkow)

___
*[`templates/debian/Dockerfile.build.template` line 20 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-NbulHs3C8-J84TZ52s4:-NcfhA701QXkzDZr_1hb:b2c0zco) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.build.template#L20)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

The style changes are done.   Also added a comment to explain why the distro package manager is used to install python packages in newer distros(debian 12 and Ubuntu 23.04).
</blockquote></details>

LGTM, thanks.
___
*[`templates/debian/Dockerfile.sign.template` line 21 at r3](https://reviewable.io/reviews/gramineproject/gsc/155#-Nbuoo5v6xo5aOXDDn8h:-NcSsd5zCKvPef3v8jYW:bpdfupk) ([raw file](https://github.com/gramineproject/gsc/blob/aec2b922bb1c704b25b6e211709eeba8cb3cd527/templates/debian/Dockerfile.sign.template#L21)):*
<details><summary><i>Previously, amathew3 (Abin Mathew) wrote…</i></summary><blockquote>

This uninstall is based on `--remove-gramine-deps` during the signing stage.
</blockquote></details>

Oh, OK, if it's gated then it's perfectly fine. Sorry for the confusion.


<!-- Sent from Reviewable.io -->

2023-08-28 04:27 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @jinengandhi-intel and @mkow)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/gramineproject/gsc/155#-NccJYLA03xIfBn0GK7S):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We can fix it during final rebase (`Add support of Ubuntu 22.04 and Debian12`)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-28 04:27 UTC, dimakuv approved these changes
> Dismissed @jinengandhi-intel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-28 04:29 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @amathew3 and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/155#-NcuOfQ5D63CT8q43Sdg:-NcuOfQ5D63CT8q43Sdh:b-9wd2li) (no related file):*
After final rebase, I manually tested the Helloworld example on Ubuntu 20.04, 22.04 and 23.04. Everything works.

___


<!-- Sent from Reviewable.io -->

2023-08-28 04:29 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-08-28 04:49 UTC, mkow approved these changes
> Reviewed 1 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/155)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-08-28 05:02 UTC, merged