Add ubi8, ubi8-minimal support
gramineproject/gsc pull request #168
Opened 2023-08-11 09:44 UTC by sahason

## Description of the changes 
Add ubi8, ubi8-minimal support.

Implementation note: Due to unavailability of expect, protobuf-c-devel and nasm packages in ubi8 CentOS repository is made available under ubi8 to install these 3 packages.

## How to test this PR? 
Take the hello-world example in the test folder and modify it to use redhat/ubi8:8.8 and redhat/ubi8-minimal:8.8 as base image.
Edit the config.yaml file to select the distro as redhat/ubi8:8.8 and redhat/ubi8-minimal:8.8.
Do the gsc build and gsc sign commands.

2023-08-16 09:48 UTC, kailun-qin requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxgNq29B5TFiKwlRt4):*
-> `UBI8`



_Code quote:_
```
rhel8
```
___
*[`gsc.py` line 221 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxgVktBmEAxnvnsyCw:-NbxgVktBmEAxnvnsyCx:b-z78k6l) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/gsc.py#L221)):*
> ```Python
> 
>     distro, _ = distro.split(':')
>     distro = distro.split('/')[0]
> ```

Shouldn't the distro name be `ubi` instead of `redhat`?



_Code quote:_
```Python
distro = distro.split('/')[0]
```
___
*[`templates/redhat/Dockerfile.build.template` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxiHLq1xMXRH5XNZpY:-NbxiHLq1xMXRH5XNZpZ:bf1zxrj) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/templates/redhat/Dockerfile.build.template#L11)):*
> ```
> {% set distro = Distro.split(':') %}
> {% set pkg_manager = 'dnf' %}
> {% if distro[0] == "redhat/ubi8" %}
> ```

Shouldn't it be `ubi`? What if we support e.g., `ubi9` in the future?



_Code quote:_
```
"redhat/ubi8"
```
___
*[`templates/redhat/Dockerfile.build.template` line 19 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxiX_96tLSJjHN6k1W:-NbxiX_96tLSJjHN6k1X:bgby3ng) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/templates/redhat/Dockerfile.build.template#L19)):*
> ```
>         && dnf config-manager --add-repo http://vault.centos.org/centos/8/AppStream/x86_64/os
> {% else %}
>     {% set pkg_manager = 'microdnf' %}
> ```

I guess the current ELSE applies to `ubi-minimal` only? If so, I suggest to make it explicit since there are also `ubi-init` and `ubi-micro` images.



_Code quote:_
```
{% else %}
    {% set pkg_manager = 'microdnf' %}
```
___
*[`templates/redhat/Dockerfile.build.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxhvVa-z9wimc_WkD5:-NbxhvVa-z9wimc_WkD6:b-suw9i8) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/templates/redhat/Dockerfile.build.template#L20)):*
> ```
> {% else %}
>     {% set pkg_manager = 'microdnf' %}
>     RUN  rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
> ```

superfluous leading space



_Code quote:_
```
 rpm
```
___
*[`templates/redhat/Dockerfile.compile.template` line 18 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-Nbxi0l69MSpYOZuSTF_:-Nbxi0l69MSpYOZuSTFa:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/templates/redhat/Dockerfile.compile.template#L18)):*
> ```
> {% else %}
>     {% set pkg_manager = 'microdnf' %}
>     RUN  rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
> ```

ditto



_Code quote:_
```
 rpm
```


<!-- Sent from Reviewable.io -->

2023-08-21 16:54 UTC, dimakuv requested changes
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-p_r0APurtreq4v3:-NcO-p_r0APurtreq4v4:b-wa0lji) (no related file):*
Please also update the documentation correspondingly.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-sQV6EQVWVseFmO8:-NcO-sQV6EQVWVseFmO9:b-czmeog) (no related file):*
@woju @mkow What do we do with such PRs? Do we want to support these RedHat UBI and RedHat UBI Minimal?

___
___
*[`gsc.py` line 221 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNx_1y7gunbySwynnM:-NcNx_1y7gunbySwynnN:blcz7us) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L221)):*
> ```Python
> 
>     distro, _ = distro.split(':')
>     distro = distro.split('/')[0]
> ```

This is definitely wrong. This extracts `redhat` instead of `ubi`.

Why don't you like `redhat/ubi8`?  This is actually very convenient: you'll just create your Dockerfile templates under the two-layered directories `templates/redhat/ubi8/` and `templates/redhat/ubi8-minimal/` (the latter will just have `extends` keywords to the former).
___
*[`gsc.py` line 286 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNyIwr6gIJBeDTDq-7:-NcNyIwr6gIJBeDTDq-8:bv376o3) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L286)):*
> ```Python
>     # Available at https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
>     shutil.copyfile('keys/RPM-GPG-KEY-CentOS-Official',
>                     tmp_build_path / 'RPM-GPG-KEY-CentOS-Official')
> ```

I don't like this; we'll have to add keys for every single distro in our generic GSC scripts...

Instead, I recommend to copy the whole directory `keys/` instead of copying each key. Plus you can move these comments about keys in a new file `keys/README`.
___
*[`gsc.py` line 350 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNyZu6DpV1ZreBWkRP:-NcNyZu6DpV1ZreBWkRQ:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L350)):*
> ```Python
>     # Available at https://www.centos.org/keys/RPM-GPG-KEY-CentOS-Official
>     shutil.copyfile('keys/RPM-GPG-KEY-CentOS-Official',
>                     tmp_build_path / 'RPM-GPG-KEY-CentOS-Official')
> ```

ditto
___
*[`keys/RPM-GPG-KEY-CentOS-Official` line 1 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNyifN4f7e9t14J_6z:-NcNyifN4f7e9t14J_7-:ba4p079) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/keys/RPM-GPG-KEY-CentOS-Official#L1)):*
> ```
> -----BEGIN PGP PUBLIC KEY BLOCK-----
> ```

The key looks correct.
___
*[`templates/redhat/Dockerfile.build.template` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxiHLq1xMXRH5XNZpY:-NcNyvkN3e3P5toNEMAk:b-llr5uc) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/templates/redhat/Dockerfile.build.template#L11)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The link like https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm may change for ubi9 as this is specific to a version. As this PR is supports ubi8 the scope is limited to ubi8.
</blockquote></details>

I'm fine with currently hard-coding to `ubi8` (i.e. to the exact version). This can be easily fixed in the future if needed.
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-NcO-B4z0ierpahHbgSg:b-gy0ag2) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
> ```
>         && echo "enabled=1" >> /etc/yum.repos.d/ubi.repo \
>         && echo "gpgcheck=1" >> /etc/yum.repos.d/ubi.repo \
>         && echo "gpgkey=file:///RPM-GPG-KEY-CentOS-Official" >> /etc/yum.repos.d/ubi.repo
> ```

Please use multi-line `cat` instead of this ugliness: https://stackoverflow.com/a/10970616
___
*[`templates/redhat/Dockerfile.build.template` line 68 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-TVcBtoemPg2wWoU:-NcO-TVd00zHZyIWBR3L:b58qps) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L68)):*
> ```
>         strace
> {% endif %}
> {% endblock %}
> ```

Sorry but this is unreadable to me. Why don't you want to split into multiple files, like this:
- `templates/redhat/ubi8/Dockerfile.build.template`
- `templates/redhat/ubi8-minimal/Dockerfile.build.template`

Yes, you'll have some duplication, but it will be much easier to comprehend than this kung-fu with Jinja variables.
___
*[`templates/redhat/Dockerfile.compile.template` line 39 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-PBI7WSJuA0Ps4iT:-NcO-PBI7WSJuA0Ps4iU:b-gy0ag2) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L39)):*
> ```
>         && echo "enabled=1" >> /etc/yum.repos.d/ubi.repo \
>         && echo "gpgcheck=1" >> /etc/yum.repos.d/ubi.repo \
>         && echo "gpgkey=file:///RPM-GPG-KEY-CentOS-Official" >> /etc/yum.repos.d/ubi.repo
> ```

Please use multi-line `cat` instead of this ugliness: https://stackoverflow.com/a/10970616
___
*[`templates/redhat/Dockerfile.compile.template` line 75 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-lrnBjuESPOFgBWx:-NcO-lrnBjuESPOFgBWy:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L75)):*
> ```
>     && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'
> 
> {% endblock %}
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-08-22 02:25 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-sQV6EQVWVseFmO8:-NcQ2LWP9bWltKyjionZ:b-mi7s1m) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju @mkow What do we do with such PRs? Do we want to support these RedHat UBI and RedHat UBI Minimal?
</blockquote></details>

Partially fixes https://github.com/gramineproject/gsc/issues/162 where customer's base image is ubi8-minimal.

___


<!-- Sent from Reviewable.io -->

2023-08-22 10:21 UTC, woju requested changes
> Reviewed 5 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-sQV6EQVWVseFmO8:-NcRVg-s2hU0PROqflr7:b2gav54) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Partially fixes https://github.com/gramineproject/gsc/issues/162 where customer's base image is ubi8-minimal.
</blockquote></details>

UBI is RHEL packaged for containers (without kernel). If we already support RHEL family (centos), then I don't mind yet another flavour, but with usual reservation that if RH tries yet another trick to screw us and the community (that would impact us and/or our ability to test this), we might pull the support without warning or even just abandon it, stop accepting bugs and let it rot.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-NcRZSSI5PTy8jNslf-P:bj2ghh2) (no related file):*
To sum up all the different questions about `redhat/` vs `rhel` vs `ubi` vs `ubi8` etc., I'd like a general guideline somewhere about how we name thing and how we keep them consistent. I don't particularly care where and how (might be in `Documentation/` or in README somewhere or in yet another place), and also don't care much how we name it (e.g. we might just defer to docker.io naming convention), but I want a clear guideline and consistency.

___
___
*[`gsc.py` line 221 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNx_1y7gunbySwynnM:-NcRZAuR37xuEHIMIybL:bku7q3e) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L221)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is definitely wrong. This extracts `redhat` instead of `ubi`.

Why don't you like `redhat/ubi8`?  This is actually very convenient: you'll just create your Dockerfile templates under the two-layered directories `templates/redhat/ubi8/` and `templates/redhat/ubi8-minimal/` (the latter will just have `extends` keywords to the former).
</blockquote></details>

I guess it's really the same problem that Kailun pointed out above. I agree with both.
___
*[`gsc.py` line 286 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNyIwr6gIJBeDTDq-7:-NcRYsCd4YvuccQ7EWW5:bhhrobi) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L286)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this; we'll have to add keys for every single distro in our generic GSC scripts...

Instead, I recommend to copy the whole directory `keys/` instead of copying each key. Plus you can move these comments about keys in a new file `keys/README`.
</blockquote></details>

Generally agree, but you need to keep in mind that different distros have different keys, formats and tooling around them. I guess if you install them one by one in the template, then it's OK.
___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NcRY1Mk07ktDfUhBXm5:b-1vmuz7) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
> ```
> 
>     RUN rpm --import /RPM-GPG-KEY-CentOS-Official \
>         && dnf config-manager --add-repo http://vault.centos.org/centos/8/BaseOS/x86_64/os \
> ```

Mixing CentOS' BaseOS with UBI repos is wrong. AppStream might be correct if you need some packages from there, but definitely not BaseOS, and if it doesn't work without it, then we should find another solution.

Aren't those packages (that you've mentioned in PR description) available from EPEL?
___
*[`templates/redhat/Dockerfile.build.template` line 68 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-TVcBtoemPg2wWoU:-NcRYYc81qV92kBjjtCk:b-jaybew) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L68)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry but this is unreadable to me. Why don't you want to split into multiple files, like this:
- `templates/redhat/ubi8/Dockerfile.build.template`
- `templates/redhat/ubi8-minimal/Dockerfile.build.template`

Yes, you'll have some duplication, but it will be much easier to comprehend than this kung-fu with Jinja variables.
</blockquote></details>

Yes, and if you have some common areas, you can write `{{ super() }}` inside a block, which substitutes the entirety of the block from parrent template. Or you can start writing macros, if you need to parametrise it.


<!-- Sent from Reviewable.io -->

2023-08-29 03:02 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 2 of 14 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, @mkow, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-p_r0APurtreq4v3:-Ncz0I2vEYw9b4DH-8u9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please also update the documentation correspondingly.
</blockquote></details>

Done.

___
___
*[`gsc.py` line 221 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNx_1y7gunbySwynnM:-Ncz3Z6vC7YJfE0QMQp4:b-wlja37) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L221)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I guess it's really the same problem that Kailun pointed out above. I agree with both.
</blockquote></details>

Created two separate Dockerfile templates.
___
*[`gsc.py` line 286 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNyIwr6gIJBeDTDq-7:-Ncz3hl0-befrbqXbFO1:bhnwk12) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L286)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Generally agree, but you need to keep in mind that different distros have different keys, formats and tooling around them. I guess if you install them one by one in the template, then it's OK.
</blockquote></details>

Keeping it as it is as the key is copied in the template based on the distro.
___
*[`gsc.py` line 350 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcNyZu6DpV1ZreBWkRP:-Ncz41HtBhtjFa7BH9m0:bhnwk12) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/gsc.py#L350)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Keeping it as it is as the key is copied in the template based on the distro.
___
*[`templates/redhat/Dockerfile.build.template` line 11 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxiHLq1xMXRH5XNZpY:-Ncz4997EiD2NYCH6H3y:bheowg5) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/templates/redhat/Dockerfile.build.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm fine with currently hard-coding to `ubi8` (i.e. to the exact version). This can be easily fixed in the future if needed.
</blockquote></details>

Kept it as it is.
___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-Ncz4DmjEByznDqVZD2L:b-tgyub) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Mixing CentOS' BaseOS with UBI repos is wrong. AppStream might be correct if you need some packages from there, but definitely not BaseOS, and if it doesn't work without it, then we should find another solution.

Aren't those packages (that you've mentioned in PR description) available from EPEL?
</blockquote></details>

These packages are not available from EPEL repo. Could not found another solution to do this.
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-NczBALKEgAbkF2UUnef:b-toid7t) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use multi-line `cat` instead of this ugliness: https://stackoverflow.com/a/10970616
</blockquote></details>

Here documents with `cat` syntax work fine in `Dockerfile`. But in GSC when I added the same syntax in jinja2 template I ended up with this warning while building the image -`bin/sh: warning: here-document at line 0 delimited by end-of-file (wanted \EOF)`. I have tried different syntax but everything ended up in the same warning and the repo configuration file is not updated. Here is an alternate solution with `echo` command which works fine. 
"RUN echo -e "\n\
[CentOSBaseOS] \n\
name = CentOSBaseOS \n\
baseurl = http://vault.centos.org/centos/8/BaseOS/x86_64/os \n\
enable = 1 \n\
gpgcheck = 1 \n\
gpgkey = file:///RPM-GPG-KEY-CentOS-Official \n\
" >> /etc/yum.repos.d/ubi.repo"
Hence proposing this solution.
___
*[`templates/redhat/Dockerfile.build.template` line 68 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-TVcBtoemPg2wWoU:-Ncz7rhN4Q3cqA8Gk1Dy:bx5fjcj) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L68)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, and if you have some common areas, you can write `{{ super() }}` inside a block, which substitutes the entirety of the block from parrent template. Or you can start writing macros, if you need to parametrise it.
</blockquote></details>

Created separete files.
___
*[`templates/redhat/Dockerfile.compile.template` line 39 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-PBI7WSJuA0Ps4iT:-Ncz82nr8jvWueMazttd:b-toid7t) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use multi-line `cat` instead of this ugliness: https://stackoverflow.com/a/10970616
</blockquote></details>

Here documents with `cat` syntax work fine in `Dockerfile`. But in GSC when I added the same syntax in jinja2 template I ended up with this warning while building the image -`bin/sh: warning: here-document at line 0 delimited by end-of-file (wanted \EOF)`. I have tried different syntax but everything ended up in the same warning and the repo configuration file is not updated. Here is an alternate solution with `echo` command which works fine. 
"RUN echo -e "\n\
[CentOSBaseOS] \n\
name = CentOSBaseOS \n\
baseurl = http://vault.centos.org/centos/8/BaseOS/x86_64/os \n\
enable = 1 \n\
gpgcheck = 1 \n\
gpgkey = file:///RPM-GPG-KEY-CentOS-Official \n\
" >> /etc/yum.repos.d/ubi.repo"
Hence proposing this solution.
___
*[`templates/redhat/Dockerfile.compile.template` line 75 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-lrnBjuESPOFgBWx:-Ncz7xnh5TDgJDu_-v2f:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L75)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-09 17:07 UTC, dimakuv requested changes
> Reviewed 11 of 12 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @sahason, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-sQV6EQVWVseFmO8:-NduttWV-mJAl8mYqY7X:bhy9nx5) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

UBI is RHEL packaged for containers (without kernel). If we already support RHEL family (centos), then I don't mind yet another flavour, but with usual reservation that if RH tries yet another trick to screw us and the community (that would impact us and/or our ability to test this), we might pull the support without warning or even just abandon it, stop accepting bugs and let it rot.
</blockquote></details>

Ok, let's have it.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-Nduu9IBDi2K4Br4Cd1m:bdvbaa0) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

To sum up all the different questions about `redhat/` vs `rhel` vs `ubi` vs `ubi8` etc., I'd like a general guideline somewhere about how we name thing and how we keep them consistent. I don't particularly care where and how (might be in `Documentation/` or in README somewhere or in yet another place), and also don't care much how we name it (e.g. we might just defer to docker.io naming convention), but I want a clear guideline and consistency.
</blockquote></details>

Well, yes, we should put the guideline somewhere (I'd say mention in README).

We use the Dockerhub naming convention historically, so I guess that's what it is.

___
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 27 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdurXcJANKP0vEfcLSq:-NdurXcJANKP0vEfcLSr:b-z61q29) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L27)):*
> ```
>         python3-cryptography \
>         python3-pip \
>         python3-protobuf \
> ```

Please sort this list
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 28 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdurOLL8Cw2ysjEB6Bv:-NdurOLL8Cw2ysjEB6Bw:b61su81) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L28)):*
> ```
>         python3-pip \
>         python3-protobuf \
>     && /usr/bin/python3 -B -m pip install click jinja2 protobuf \
> ```

Why do you have `protobuf` here, even though you already have `python3-protobuf` above? Seems like duplication of the same package.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 32 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdurASh-wk16wQod_00:-NdurASh-wk16wQod_01:b6v0lf8) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L32)):*
> ```
>     && dnf repolist \
> # Install pyelftools after the installation of epel-release as it is provided by the EPEL repo
>     && dnf install -y python3-pyelftools \
> ```

Looks like you don't need this special treatment of `python3-pyelftools`, because you install epel in a completely separate step? Please remove the comment and move this package together with the other packages.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 41 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Nduremy9qibYtGKDbCY:-Nduremy9qibYtGKDbCZ:bekazy3) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L41)):*
> ```
>         libunwind \
>         python3-pytest \
>         strace
> ```

Did you also verify that your PR works with `gsc build -b debug`?
___
*[`templates/redhat/ubi8/Dockerfile.compile.template` line 21 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Ndurxd83iJpDvjY-QtR:-Ndurxd83iJpDvjY-QtS:b5ze8om) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.compile.template#L21)):*
> ```
>         curl \
>         elfutils-libelf-devel \
>         epel-release \
> ```

? Didn't you already install `epel-release` by the very first command?

Please explain why you even have the first command, if you can install epel-release in a normal way?
___
*[`templates/redhat/ubi8-minimal/Dockerfile.sign.template` line 5 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdutfF_BX42MuF0Bs0K:-NdutfF_BX42MuF0Bs0L:b-e6is13) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.sign.template#L5)):*
> ```
> {% block uninstall %}
> RUN \
>        pip3 uninstall -y click jinja2 protobuf \
> ```

ditto (why do you have two `protobuf`)
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-Ndusy0IAxQ6T-Eki2N8:b-iithku) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Here documents with `cat` syntax work fine in `Dockerfile`. But in GSC when I added the same syntax in jinja2 template I ended up with this warning while building the image -`bin/sh: warning: here-document at line 0 delimited by end-of-file (wanted \EOF)`. I have tried different syntax but everything ended up in the same warning and the repo configuration file is not updated. Here is an alternate solution with `echo` command which works fine. 
"RUN echo -e "\n\
[CentOSBaseOS] \n\
name = CentOSBaseOS \n\
baseurl = http://vault.centos.org/centos/8/BaseOS/x86_64/os \n\
enable = 1 \n\
gpgcheck = 1 \n\
gpgkey = file:///RPM-GPG-KEY-CentOS-Official \n\
" >> /etc/yum.repos.d/ubi.repo"
Hence proposing this solution.
</blockquote></details>

I like the alternate solution better, please use it then.
___
*[`templates/redhat/Dockerfile.compile.template` line 39 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-PBI7WSJuA0Ps4iT:-NdutOF_5E6LiwV0s31z:b-eg120b) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L39)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Here documents with `cat` syntax work fine in `Dockerfile`. But in GSC when I added the same syntax in jinja2 template I ended up with this warning while building the image -`bin/sh: warning: here-document at line 0 delimited by end-of-file (wanted \EOF)`. I have tried different syntax but everything ended up in the same warning and the repo configuration file is not updated. Here is an alternate solution with `echo` command which works fine. 
"RUN echo -e "\n\
[CentOSBaseOS] \n\
name = CentOSBaseOS \n\
baseurl = http://vault.centos.org/centos/8/BaseOS/x86_64/os \n\
enable = 1 \n\
gpgcheck = 1 \n\
gpgkey = file:///RPM-GPG-KEY-CentOS-Official \n\
" >> /etc/yum.repos.d/ubi.repo"
Hence proposing this solution.
</blockquote></details>

ditto (use the alternate solution)
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 6 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdusOOkB-sDgN8YAYcf:-NdusOOkB-sDgN8YAYcg:b-j249v3) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.build.template#L6)):*
> ```
> # Combine all in [...]

2023-09-11 10:37 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 9 of 14 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-Ne25qJ61F2cfIDSYm8W:b4ut9fl) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Well, yes, we should put the guideline somewhere (I'd say mention in README).

We use the Dockerhub naming convention historically, so I guess that's what it is.
</blockquote></details>

Will this be part of this PR or separate PR?

___
___
*[`gsc.py` line 221 at r1](https://reviewable.io/reviews/gramineproject/gsc/168#-NbxgVktBmEAxnvnsyCw:-Ne1idLSDcZkuYr6AGAe:bqwqkwn) ([raw file](https://github.com/gramineproject/gsc/blob/8036f4599e92fc8bef42de176ee3689a869bdf29/gsc.py#L221)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Shouldn't the distro name be `ubi` instead of `redhat`?
</blockquote></details>

Distros uesd are redhat/ubi8 and redhat/ubi8-minimal.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 27 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdurXcJANKP0vEfcLSq:-Ne1mfCP1yZAnRMgG-hX:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort this list
</blockquote></details>

Done.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 28 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdurOLL8Cw2ysjEB6Bv:-Ne1sBd3025PSUMHx5F2:bd0huin) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `protobuf` here, even though you already have `python3-protobuf` above? Seems like duplication of the same package.
</blockquote></details>

Yes, after deleting this package build is fine so removed it.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 32 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdurASh-wk16wQod_00:-Ne1t05JBneI9taydKUI:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks like you don't need this special treatment of `python3-pyelftools`, because you install epel in a completely separate step? Please remove the comment and move this package together with the other packages.
</blockquote></details>

Done
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 41 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Nduremy9qibYtGKDbCY:-Ne1t2gg1Mjq_AdtPOFR:b2nhswy) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.build.template#L41)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Did you also verify that your PR works with `gsc build -b debug`?
</blockquote></details>

Yes
___
*[`templates/redhat/ubi8/Dockerfile.compile.template` line 21 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Ndurxd83iJpDvjY-QtR:-Ne24gRb97CqbfDmLWTd:b-ebgzj2) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.compile.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

? Didn't you already install `epel-release` by the very first command?

Please explain why you even have the first command, if you can install epel-release in a normal way?
</blockquote></details>

My mistake. First command is required for installing epel-release. In absence of first commad and presense of second command it will throw `Error: Unable to find a match: epel-release`.  But in presencse of both it gives `Package epel-release-8-19.el8.noarch is already installed.`
___
*[`templates/redhat/ubi8-minimal/Dockerfile.sign.template` line 5 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdutfF_BX42MuF0Bs0K:-Ne2GSsxE32T1OjJUO1E:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.sign.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why do you have two `protobuf`)
</blockquote></details>

Done.
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-Ne1vtas9yyEItjbcP2R:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I like the alternate solution better, please use it then.
</blockquote></details>

Done.
___
*[`templates/redhat/Dockerfile.compile.template` line 39 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-PBI7WSJuA0Ps4iT:-Ne1xWlB9KyP5ukOefV8:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (use the alternate solution)
</blockquote></details>

Done.
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 6 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdusOOkB-sDgN8YAYcf:-Ne1vguFEIgCsJXQmWeM:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sentence is not finished.
</blockquote></details>

Done.
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 38 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Ndut6_o5xIGIRcTGsBY:-Ne1xFtuApWpsZlgEz1O:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.build.template#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort
</blockquote></details>

Done.
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 39 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Ndut7sN6kbi_copAv0V:-Ne1xHkP2tRGDXvrWyii:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.build.template#L39)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why `protobuf` twice)
</blockquote></details>

Done.
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 43 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-NdutEC42N_V-L_Hzi2x:-Ne1xSR1258oXmOjHwsC:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8-minimal/Dockerfile.build.template#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (you installed epel-release in a separate command)
</blockquote></details>

Don [...]

2023-09-11 11:09 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @sahason, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-Ne2uweQD1EmBJaxsr7C:b4pdw11) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Will this be part of this PR or separate PR?
</blockquote></details>

Separate PR, not this PR.

___
___
*[`templates/redhat/ubi8/Dockerfile.compile.template` line 21 at r5](https://reviewable.io/reviews/gramineproject/gsc/168#-Ndurxd83iJpDvjY-QtR:-Ne2vCCh-qbRuRoM4tJy:b-l9ljhu) ([raw file](https://github.com/gramineproject/gsc/blob/2b6881d5ca2db84f502417bfba9afc77d5e5023f/templates/redhat/ubi8/Dockerfile.compile.template#L21)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

My mistake. First command is required for installing epel-release. In absence of first commad and presense of second command it will throw `Error: Unable to find a match: epel-release`.  But in presencse of both it gives `Package epel-release-8-19.el8.noarch is already installed.`
</blockquote></details>

Ok, thanks for explanation.
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-Ne2vP4Y73TZFxTFclIb:b-m8clup) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks, more readable now.
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 6 at r6](https://reviewable.io/reviews/gramineproject/gsc/168#-Ne2vFH766STvWcACg5-:-Ne2vFH766STvWcACg50:b-up8hpl) ([raw file](https://github.com/gramineproject/gsc/blob/f63eee45f9ce19eb415ee342118a1df4cb7e5f17/templates/redhat/ubi8-minimal/Dockerfile.build.template#L6)):*
> ```
> # Combine all installation and removal steps in a single RUN command to reduce the final image size.
> # This is because each Dockerfile command creates a new layer which necessarily adds size to the
> # final image. This trick allow to decrease the image size by hundreds of MBs.
> ```

`allow` -> `allows`


<!-- Sent from Reviewable.io -->

2023-09-11 11:39 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 12 of 14 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-Ne3-f0h50Ri8NTAbPsa:b2nhll9) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Separate PR, not this PR.
</blockquote></details>

Ok.

___
___
*[`templates/redhat/ubi8-minimal/Dockerfile.sign.template` line 11 at r6](https://reviewable.io/reviews/gramineproject/gsc/168#-Ne30ZONBCx2w1W9-RC4:-Ne30ZONBCx2w1W9-RC5:b-tn8jet) ([raw file](https://github.com/gramineproject/gsc/blob/f63eee45f9ce19eb415ee342118a1df4cb7e5f17/templates/redhat/ubi8-minimal/Dockerfile.sign.template#L11)):*
> ```
>           expect \
>           openssl \
>           pkgconfig \
> ```

I updated to keep it consistent with Centos and Debian sign templates as these are already tested with many workloads.
___
*[`templates/redhat/ubi8-minimal/Dockerfile.build.template` line 6 at r6](https://reviewable.io/reviews/gramineproject/gsc/168#-Ne2vFH766STvWcACg5-:-Ne3-kL84Rf6rdPzIxMe:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f63eee45f9ce19eb415ee342118a1df4cb7e5f17/templates/redhat/ubi8-minimal/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`allow` -> `allows`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-11 11:46 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin, @sahason, and @woju)

___
*[`templates/redhat/ubi8-minimal/Dockerfile.sign.template` line 11 at r6](https://reviewable.io/reviews/gramineproject/gsc/168#-Ne30ZONBCx2w1W9-RC4:-Ne3380U8umsee4-KJJy:b7rbm2a) ([raw file](https://github.com/gramineproject/gsc/blob/f63eee45f9ce19eb415ee342118a1df4cb7e5f17/templates/redhat/ubi8-minimal/Dockerfile.sign.template#L11)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I updated to keep it consistent with Centos and Debian sign templates as these are already tested with many workloads.
</blockquote></details>

Good. Deleting lines is always good :)


<!-- Sent from Reviewable.io -->

2023-09-11 12:29 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 13 of 14 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`templates/redhat/ubi8-minimal/Dockerfile.sign.template` line 12 at r7](https://reviewable.io/reviews/gramineproject/gsc/168#-Ne3Chb51ane9ArHSoll:-Ne3Chb51ane9ArHSolm:b-zb1lis) ([raw file](https://github.com/gramineproject/gsc/blob/861c657a9246526d2468162d02474bcb8f8acb56/templates/redhat/ubi8-minimal/Dockerfile.sign.template#L12)):*
> ```
>           openssl \
>           python3-cryptography \
>           python3-pip \
> ```

Sorry, had to remove this as well as signing with  `--remove-gramine-deps`caused issue.


<!-- Sent from Reviewable.io -->

2023-09-11 12:33 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @kailun-qin and @woju)



<!-- Sent from Reviewable.io -->

2023-09-11 16:52 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 4 of 12 files at r3, 1 of 5 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)



<!-- Sent from Reviewable.io -->

2023-09-13 16:13 UTC, woju requested changes
> Reviewed 7 of 12 files at r3, 3 of 5 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 9 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-NeEJ9bf1bS7W3a8447D:bse2rmx) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

At least please describe anywhere (even here in the replying comment) what schema was guiding choices in this PR.

___
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 6 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGbvsD-28PSQaAXxN:-NeEGbvsD-28PSQaAXxO:b-v7fpt7) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L6)):*
> ```
> # Combine all installation and removal steps in a single RUN command to reduce the final image size.
> # This is because each Dockerfile command creates a new layer which necessarily adds size to the
> # final image. This trick allows to decrease the image size by hundreds of MBs.
> ```

This comment sounds misplaced. 1) Was it copied from another template (for another distro) and just left alone? 2) Shouldn't we actually follow the comment, combining all `dnf` and `rpm` commands below the `COPY`?
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-NeEGIof7O_wSo0_G6ns:b-8qeq3n) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
> ```
> COPY RPM-GPG-KEY-CentOS-Official /
> 
> RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
> ```

EPEL docs (https://docs.fedoraproject.org/en-US/epel/#_rhel_8) say you need to also enable codeready repo. Why this instruction is not followed?
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 14 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGXjQDJKKeCjt6L36:-NeEGXjQDJKKeCjt6L37:blj9nkf) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L14)):*
> ```
> RUN rpm --import /RPM-GPG-KEY-CentOS-Official \
>     && dnf config-manager --add-repo http://vault.centos.org/centos/8/BaseOS/x86_64/os \
>     && dnf config-manager --add-repo http://vault.centos.org/centos/8/AppStream/x86_64/os
> ```

Why do we add PowerTools in `Dockerfile.compile.template` and not here?

Unless there is a compelling reason to *not* have some repo available (e.g., a conflict between some packages/repos?), I wouls like to avoid such differences between containers, and I would prefer if there was a common file with a single macro to install dependencies (one per distro I guess), `{% import %}`ed or `{% extend %}`ed from.
___
*[`templates/redhat/ubi8/Dockerfile.compile.template` line 6 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEHbjv3Gsc-p226YNU:-NeEHbjw5FJcbfEs8LRC:b-pi1rbn) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.compile.template#L6)):*
> ```
> COPY RPM-GPG-KEY-CentOS-Official /
> 
> RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
> ```

ditto (question about combining `RUN` steps, if applicable, depending on the discussion in the other thread).
___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NeEHsbzBoFJsWyCIjD3:bocys77) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

These packages are not available from EPEL repo. Could not found another solution to do this.
</blockquote></details>

Do I understand correctly: it works on `ubi*` and doesn't work on `ubi*-minimal`? If so, then we don't support `ubi*-minimal`.
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-NeEIeKu2229FHrZbyPA:b-1y7zjh) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks, more readable now.
</blockquote></details>

I don't like this. I think if you can't `cat <<EOF` those, then commit them as separate files and `COPY` them like the key.
___
*[`templates/redhat/Dockerfile.compile.template` line 39 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-PBI7WSJuA0Ps4iT:-NeEIzLC4lCGpztL20Ib:b-hosp67) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L39)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto (`COPY`)


<!-- Sent from Reviewable.io -->

2023-09-20 16:39 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 9 of 15 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-NenFrKs7FTviq9ORFIC:b-s0sesq) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

At least please describe anywhere (even here in the replying comment) what schema was guiding choices in this PR.
</blockquote></details>

docker.io  naming convection [registry]/[namespace]/[repository]:[tag] is followed.
In this PR:
registry - Default registry Docker Hub
namespace - redhat
repository - ubi8 and ubi8-minimal
tag - 8.8

___
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 6 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGbvsD-28PSQaAXxN:-NenGgPH0cXRyiug-xjI:b-ubfsrc) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This comment sounds misplaced. 1) Was it copied from another template (for another distro) and just left alone? 2) Shouldn't we actually follow the comment, combining all `dnf` and `rpm` commands below the `COPY`?
</blockquote></details>

Addressed 2nd point.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-NenJ6OZ3iZxHslaGLQy:b-cgdilh) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

EPEL docs (https://docs.fedoraproject.org/en-US/epel/#_rhel_8) say you need to also enable codeready repo. Why this instruction is not followed?
</blockquote></details>

It throws error when the instruction is added as `subscription-manager is disabled when running inside a container. Please refer to your host system for subscription management.` while building GSC image. 
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 14 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGXjQDJKKeCjt6L36:-NelSR3C4SrHPqm2f3I9:bmxifmr) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L14)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why do we add PowerTools in `Dockerfile.compile.template` and not here?

Unless there is a compelling reason to *not* have some repo available (e.g., a conflict between some packages/repos?), I wouls like to avoid such differences between containers, and I would prefer if there was a common file with a single macro to install dependencies (one per distro I guess), `{% import %}`ed or `{% extend %}`ed from.
</blockquote></details>

It is required for `nasm` package.
___
*[`templates/redhat/ubi8/Dockerfile.compile.template` line 6 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEHbjv3Gsc-p226YNU:-NenK4O61PKNvzfv1PlM:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.compile.template#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (question about combining `RUN` steps, if applicable, depending on the discussion in the other thread).
</blockquote></details>

Done
___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NelSwin6mheszkqaB8U:b-3kuju1) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Do I understand correctly: it works on `ubi*` and doesn't work on `ubi*-minimal`? If so, then we don't support `ubi*-minimal`.
</blockquote></details>

It does not work on both.
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-NenK9zC8fOhomGNz5oF:bqoyg7m) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I don't like this. I think if you can't `cat <<EOF` those, then commit them as separate files and `COPY` them like the key.
</blockquote></details>

Created separate file.
___
*[`templates/redhat/Dockerfile.compile.template` line 39 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-PBI7WSJuA0Ps4iT:-NenKF6UBjYL32kqA7S-:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.compile.template#L39)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (`COPY`)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-21 07:59 UTC, dimakuv approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 14 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGXjQDJKKeCjt6L36:-NeqiDWM68FDnked6lhp:b-h36ye5) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L14)):*
Not a real comment from me, but more a history of GSC development:

> Unless there is a compelling reason to _not_ have some repo available (e.g., a conflict between some packages/repos?)

Actually, the original idea behind two separate phases of Gramine + app build (`Dockerfile.compile.template` and `Dockerfile.build.template`) was: the first phase builds/installs Gramine proper and the second phase installs the run-time tools and dependencies required for Gramine SGX enclave execution.

So the first phase was supposed to be interchangeable: one could build Gramine from sources (as is done currently in Gramine) *or* install Gramine from the packages (like our official Gramine DockerHub image: https://github.com/gramineproject/gramine/blob/master/packaging/docker/Dockerfile).

The "install Gramine from the packages" idea never materialized in GSC (well, not yet, but probably never). Now, if you imagine that this would be implemented, you'll see that `Dockerfile.compile.template` and `Dockerfile.build.template` would be drastically different and wouldn't have much shareable code.

That was the original idea and that explains why we have a lot of duplication of code between the two files/phases. I don't know if that ship has sailed, or we'll indeed allow the "install from packages" step in GSC...

> I would prefer if there was a common file with a single macro to install dependencies

If we would have `Dockerfile.compile.template` containing the "install from packages" logic, then there will be a lot of unused but installed dependencies (e.g. `meson`), which would break the principle of minimality. Again, that was the original idea :)
___
*[`templates/redhat/Dockerfile.build.template` line 34 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcO-B4z0ierpahHbgSf:-Neqjsd23i2aBvtMx6Bp:bafxnzj) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L34)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Created separate file.
</blockquote></details>

Right, this actually looks much cleaner! Thanks Woju for the idea.


<!-- Sent from Reviewable.io -->

2023-09-26 15:11 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 14 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGXjQDJKKeCjt6L36:-NfH1mbV9b_0z9dL3rCy:booiell) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not a real comment from me, but more a history of GSC development:

> Unless there is a compelling reason to _not_ have some repo available (e.g., a conflict between some packages/repos?)

Actually, the original idea behind two separate phases of Gramine + app build (`Dockerfile.compile.template` and `Dockerfile.build.template`) was: the first phase builds/installs Gramine proper and the second phase installs the run-time tools and dependencies required for Gramine SGX enclave execution.

So the first phase was supposed to be interchangeable: one could build Gramine from sources (as is done currently in Gramine) *or* install Gramine from the packages (like our official Gramine DockerHub image: https://github.com/gramineproject/gramine/blob/master/packaging/docker/Dockerfile).

The "install Gramine from the packages" idea never materialized in GSC (well, not yet, but probably never). Now, if you imagine that this would be implemented, you'll see that `Dockerfile.compile.template` and `Dockerfile.build.template` would be drastically different and wouldn't have much shareable code.

That was the original idea and that explains why we have a lot of duplication of code between the two files/phases. I don't know if that ship has sailed, or we'll indeed allow the "install from packages" step in GSC...

> I would prefer if there was a common file with a single macro to install dependencies

If we would have `Dockerfile.compile.template` containing the "install from packages" logic, then there will be a lot of unused but installed dependencies (e.g. `meson`), which would break the principle of minimality. Again, that was the original idea :)
</blockquote></details>

Just a quick note: as a workaround, we can build `nasm` manually from https://github.com/netwide-assembler/nasm, it is trivial to build and the build itself doesn't require any dependencies.


<!-- Sent from Reviewable.io -->

2023-09-26 15:19 UTC, woju requested changes
> Reviewed 1 of 2 files at r7, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRZSSI5PTy8jNslf-O:-NfFg_Mg8eFZO29qWby8:bj5e7nc) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

docker.io  naming convection [registry]/[namespace]/[repository]:[tag] is followed.
In this PR:
registry - Default registry Docker Hub
namespace - redhat
repository - ubi8 and ubi8-minimal
tag - 8.8
</blockquote></details>

Thanks, that's OK. Filenames look correct.

___
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 6 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGbvsD-28PSQaAXxN:-NfH-JlaEZSaXCpxopTI:bfod7zu) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Addressed 2nd point.
</blockquote></details>

Yep, thanks. Moving COPY on top is Good™.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-NfH2sBb-nufgumxaIie:busdrpi) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

It throws error when the instruction is added as `subscription-manager is disabled when running inside a container. Please refer to your host system for subscription management.` while building GSC image.
</blockquote></details>

I guess you need to configure those subscriptions on a host then. Isn't it actually a correct solution, and a missing point in readme/docs that to run UBI images you need to run on properly subscribed (and paid for...) RHEL?
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 14 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGXjQDJKKeCjt6L36:-NfH340R4A5SoGISQuMR:b-6kunkr) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just a quick note: as a workaround, we can build `nasm` manually from https://github.com/netwide-assembler/nasm, it is trivial to build and the build itself doesn't require any dependencies.
</blockquote></details>

OK, if those images are substantially different then I think it's OK to have them different. Thanks for explanation.
___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NfGvrCr-kqxR8cdzXE_:b-8e2lwg) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

It does not work on both.
</blockquote></details>

I strongly protest against including BaseOS repository from CentOS. This is no-go, because if you do that, you're not really running UBI anymore, it's a franken-distro that contains base packages from both CentOS and UBI, and you can't predict what packages will get pulled on e.g. `dnf install/update`. It's "ubi" in the name only, that is, `FROM redhat/ubi8` becomes a lie at this point. I guess CentOS' AppStream and PowerTools depend on BaseOS, so it might be that we can't use them either.

Are those repos really unavailable for UBI? Note that Red Hat messes regularly with names of those repos. About 20 s of ddg-ing found me this:
- https://access.redhat.com/discussions/5417621
- https://access.redhat.com/articles/4238681
(the terms were 'ubi powertools` and `ubi appstream`). It seems implausible to me that those would be unavailable.

`nasm` is available there: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/codereadylinuxbuilder-repository, but I can't find `expect` nor `protobuf-c-devel` (^F doesn't find that package on this docs page), but I guess are available from appstream and/or epel?


<!-- Sent from Reviewable.io -->

2023-09-27 07:13 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NfJxpnF84RNbNWiC38N:bsfy94k) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I strongly protest against including BaseOS repository from CentOS. This is no-go, because if you do that, you're not really running UBI anymore, it's a franken-distro that contains base packages from both CentOS and UBI, and you can't predict what packages will get pulled on e.g. `dnf install/update`. It's "ubi" in the name only, that is, `FROM redhat/ubi8` becomes a lie at this point. I guess CentOS' AppStream and PowerTools depend on BaseOS, so it might be that we can't use them either.

Are those repos really unavailable for UBI? Note that Red Hat messes regularly with names of those repos. About 20 s of ddg-ing found me this:
- https://access.redhat.com/discussions/5417621
- https://access.redhat.com/articles/4238681
(the terms were 'ubi powertools` and `ubi appstream`). It seems implausible to me that those would be unavailable.

`nasm` is available there: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/codereadylinuxbuilder-repository, but I can't find `expect` nor `protobuf-c-devel` (^F doesn't find that package on this docs page), but I guess are available from appstream and/or epel?
</blockquote></details>

`ubi-8-appstream-rpms`, `ubi-8-baseos-rpms`  and `ubi-8-codeready-builder-rpms` are already present with ubi8 and ubi8-minimal images. But the missing packages are not available in these repos. But there is no `powertools` in this link https://access.redhat.com/articles/4238681. 

To get [https://access.redhat.com/documentation/en-us/red\_hat\_enterprise\_linux/8/html/package\_manifest/codereadylinuxbuilder-repository](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/codereadylinuxbuilder-repository), package we will need redhat subscription.


<!-- Sent from Reviewable.io -->

2023-09-27 08:09 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @sahason and @woju)

___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NfKeqdW9lJCzaZhT-A1:b-ljnete) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

`ubi-8-appstream-rpms`, `ubi-8-baseos-rpms`  and `ubi-8-codeready-builder-rpms` are already present with ubi8 and ubi8-minimal images. But the missing packages are not available in these repos. But there is no `powertools` in this link https://access.redhat.com/articles/4238681. 

To get [https://access.redhat.com/documentation/en-us/red\_hat\_enterprise\_linux/8/html/package\_manifest/codereadylinuxbuilder-repository](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/codereadylinuxbuilder-repository), package we will need redhat subscription.
</blockquote></details>

Two notes from me:
1. I can see `nasm` and `protobuf-devel` (note! slight difference in name from `protobuf-c-devel`, but I think it's the same package that we need) in the CodeReady Linux Builder repository.
2. `expect` seems to be unavailable in UBI8, see https://stackoverflow.com/questions/63658868/redhat-ubi-8-install-expect-package. However, I also feel like we can get rid of the `expect` utility in GSC now.

So if we only have problems with these 3 packages, looks like we can remove `expect` and rely on CodeReady repo. Which in turn means requiring a RedHat subscription in order for GSC + UBI8 to work...


<!-- Sent from Reviewable.io -->

2023-09-27 08:52 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[`templates/redhat/Dockerfile.build.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/168#-NcRY1Mk07ktDfUhBXm4:-NfKjjyx4VxlEv5fJGft:b85u2qh) ([raw file](https://github.com/gramineproject/gsc/blob/1ebff9d77b11ae6322b52bedc4001b462ec7d3cb/templates/redhat/Dockerfile.build.template#L16)):*
> But there is no `powertools` in this link [https://access.redhat.com/articles/4238681](https://access.redhat.com/articles/4238681).

I think `powertools` and `codeready-builder` is the same repo really, only renamed between major versions. I might be slightly wrong on the details, but the package set is mostly the same.

> To get [https://access.redhat.com/documentation/en-us/red\_hat\_enterprise\_linux/8/html/package\_manifest/codereadylinuxbuilder-repository](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/package_manifest/codereadylinuxbuilder-repository), package we will need redhat subscription.

Yeah, so this is kind of expected. If UBI needs subscription, then GSC user needs subscription to use UBI in GSC, right?

So we either
- allow the paid option, merge on a "best effort" basis, warning people that UBI is not supported by Gramine project, because we don't test it as nobody contributed paid access for CI for this distro; or
- we don't merge at all and tell people to use one of the rebuilds (Rocky or AlmaLinux), and if Intel badly wants UBI support delivered, then Intel is free to maintain a fork.

> `protobuf-devel` (note! slight difference in name from `protobuf-c-devel`

@dimakuv You sure this is the same package? In debian there are two of those, `protobuf-compiler` and `protobuf-c-compiler` and those are different things.

I have no problem with removing `expect`, but if we want to do this, it would have to be done either in this PR or another PR merged before this one. And the SO answer you've linked says that it is available in paid repos? So if we merge anyway (and tell people to have subscription if they use UBI), this might not be needed at all.


<!-- Sent from Reviewable.io -->

2023-09-27 09:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-10-18 07:19 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 8 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin, @sahason, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-Nh0deOcC4DwhhzDLgsE:-Nh0deOd4vaVcmyk5NLs:b-myosvm) (no related file):*
@sahason Is this PR ready for review, or you're still working on it? I see the new commit, but you didn't leave any new messages in Reviewable.

___


<!-- Sent from Reviewable.io -->

2023-10-18 07:22 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 8 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-Nh0deOcC4DwhhzDLgsE:-Nh0e9Vn4iGqzNXLrqm5:b-obcb5x) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Is this PR ready for review, or you're still working on it? I see the new commit, but you didn't leave any new messages in Reviewable.
</blockquote></details>

I will update the PR and Reviewable by today.

___


<!-- Sent from Reviewable.io -->

2023-10-18 08:19 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 7 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-Nh0mkFy-GcrQqEuUdZN:bgzuapp) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I guess you need to configure those subscriptions on a host then. Isn't it actually a correct solution, and a missing point in readme/docs that to run UBI images you need to run on properly subscribed (and paid for...) RHEL?
</blockquote></details>

I have updated the PR such that it requires RHEL subscription. But from rhel8 onwards it uses `podman-docker` and current version of GSC does not support `podman-docker` and `podman` python library. When you use `podman-docker` your `redhat.repo` in UBI8 base image will automatically be updated with '' rhel-8-for-x86_64-baseos-rpms" and "rhel-8-for-x86_64-appstream-rpms". But this does not happen when you use `docker` instead `podman-docker`.  As an alternate solution the `redhat.repo` is copied from host RHEL path /etc/yum.repos.d to the UBI8 image. Then the `redhat.repo` file is parsed to get path of SSL CA certificate and SSL client key directory and the contents are copied to UBI8 base image.


<!-- Sent from Reviewable.io -->

2023-10-23 10:58 UTC, woju reviewed
> Reviewed 6 of 7 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)

___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-NhR9JSmEHLDlXbNc61H:bhi4x53) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

I have updated the PR such that it requires RHEL subscription. But from rhel8 onwards it uses `podman-docker` and current version of GSC does not support `podman-docker` and `podman` python library. When you use `podman-docker` your `redhat.repo` in UBI8 base image will automatically be updated with '' rhel-8-for-x86_64-baseos-rpms" and "rhel-8-for-x86_64-appstream-rpms". But this does not happen when you use `docker` instead `podman-docker`.  As an alternate solution the `redhat.repo` is copied from host RHEL path /etc/yum.repos.d to the UBI8 image. Then the `redhat.repo` file is parsed to get path of SSL CA certificate and SSL client key directory and the contents are copied to UBI8 base image.
</blockquote></details>

Looks OK to me. I guess this is what RH users get when they engage in this RH's DRM. When those regexps break, you can think about rewriting this in python's configparser (https://docs.python.org/3/library/configparser.html), but regexps are OK as long as they work.

Note that IIUC this means that you're shipping private keys to RH subscription with your container. Is this really what you want?


<!-- Sent from Reviewable.io -->

2023-10-24 09:41 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @sahason)



<!-- Sent from Reviewable.io -->

2023-10-26 07:17 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 11 of 15 files reviewed, 27 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`gsc.py` line 23 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW96sF2d7cAadejp5H:-NhdioQk8VVM5Ne7KttJ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we move this import to the first set of imports (the one that starts with `argparse`) and put it there sorted?
</blockquote></details>

Done.
___
*[`gsc.py` line 181 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW9GM-5NT4rL8-sNh8:-NhdmNQf60O5qj9g1oCY:b-896fjx) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L181)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please do the other way around, for readability of the code:
```
    if distro not in {"redhat/ubi8", "redhat/ubi8-minimal"}:
        return

    repo_name = "rhel-8-for-x86_64-baseos-rpms"
    with open('/etc/yum.repos.d/redhat.repo') as redhat_repo:
        ...
```
</blockquote></details>

Done
___
*[`gsc.py` line 186 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW9jok2XSbT1zb2tFB:-NheIROf7YThtVqaKpwy:b2z5ig0) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this search is enough? Can you show what is typically located in this file `/etc/yum.repos.d/redhat.repo` ? And explain the contents of this file?
</blockquote></details>

Whether the rhel8 system has a subscription or not the `/etc/yum.repos.d/redhat.repo` file exists so we can't have this condition based on the presence of the file. Now if the system does not have any subscription the file will have a few comments only but if the system has a subscription it will have repository configurations. So I have added the condition to check if one of the repo configurations exists in the file (preferably the one from which we are installing packages that are missing in the UBI image). A snippet of some parts of this file is attached.
![redhat\_repo.png](https://files.reviewableusercontent.io/images/reviewable/87360079/mCU3xuE3-jQ3d9IMHneLNnML/redhat_repo.png). 
___
*[`gsc.py` line 188 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAAy13ZbBwRmmP657:-NhdoeZv5w3OSaAdeBn-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L188)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend with a sentence that describes the actual problem:
```
Cannot find {repo_name} in /etc/yum.repos.d/redhat.repo. Register and subscribe ...
```
</blockquote></details>

Done.
___
*[`gsc.py` line 189 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW9epNEnA0Z00MrBA8:-Nhdog_61kYj1CSoKhB4:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L189)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `0`? It should be `1` -- to indicate an error
</blockquote></details>

Done.
___
*[`gsc.py` line 191 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAe-m4KZybsweiFJT:-Nhdop9FE68p5hgRLNeY:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L191)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Comment just duplicates what the code does. Remove this comment.
</blockquote></details>

Done.
___
*[`gsc.py` line 196 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAhcNE8FD5McAQNM5:-Nhdords2ewXnbFHJe_l:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L196)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Comment just duplicates what the code does. Remove this comment.
</blockquote></details>

Done.
___
*[`gsc.py` line 203 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAVwCBDKaccO3Roaz:-NhdpDre-JSn0zrt0n6W:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L203)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend with a sentence that describes the actual problem:
```
Cannot find SSL client key path in /etc/yum.repos.d/redhat.repo. Register and subscribe ...
```
</blockquote></details>

Done.
___
*[`gsc.py` line 204 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAV3vElW7m8PhYUZh:-NhdpEgyAgOf_9OTPUlE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L204)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`1`
</blockquote></details>

Done.
___
*[`gsc.py` line 207 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAiPWB06yC26Ru3Vv:-NhdpOud-EvYa5fuVCbY:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L207)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Comment just duplicates what the code does. Remove this comment.
</blockquote></details>

Done.
___
*[`gsc.py` line 213 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAkL00EqK1j45vpjA:-NhdpXjh4y8_VAbxhbb_:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L213)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend with a sentence that describes the actual problem:
```
Cannot find SSL CA certificate path in /etc/yum.repos.d/redhat.repo. Register and subscribe ...
```
</blockquote></details>

Done.
___
*[`gsc.py` line 214 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAqnaComMyH-YEhAS:-NhdpYhX7TPS2Qq_d1eQ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L214)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`1`
</blockquote></details>

Done.
___
*[`gsc.py` line 216 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWAs-E6O6jVefBsKmV:-Nhdpm3aCgCzXxg1AT6f:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L216)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Remove the comment
</blockquote></details>

Done.
___
*[`gsc.py` line 217 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWB1S42frAOzcBGhxc:-NheMuTb-HzHua6KU4lP:b-l4396t) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L217)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What does `uep` stand for? Please either rename to a more meaningful name, or add a comment
</blockquote></details>

Added a comment
___
*[`gsc.py` line 222 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWBDC36HV-aol9mz7V:-NheTawNB5MCWlYCAp69:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L222)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote [...]

2023-10-26 11:38 UTC, dimakuv requested changes
> Reviewed 1 of 7 files at r10, 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow, @oshogbo, and @sahason)

___
*[`gsc.py` line 186 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW9jok2XSbT1zb2tFB:-NhfkKwz7cFlY25PFIxw:b6ju6e5) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L186)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Whether the rhel8 system has a subscription or not the `/etc/yum.repos.d/redhat.repo` file exists so we can't have this condition based on the presence of the file. Now if the system does not have any subscription the file will have a few comments only but if the system has a subscription it will have repository configurations. So I have added the condition to check if one of the repo configurations exists in the file (preferably the one from which we are installing packages that are missing in the UBI image). A snippet of some parts of this file is attached.
![redhat\_repo.png](https://files.reviewableusercontent.io/images/reviewable/87360079/mCU3xuE3-jQ3d9IMHneLNnML/redhat_repo.png).
</blockquote></details>

One last question. You check for the existence of `rhel-8-for-x86_64-baseos-rpms` repo here, but in the Dockerfiles you seem to use the `codeready-builder-for-rhel-8-x86_64-rpms`. How are these two repos related? Aren't you supposed to check for `codeready-builder-...` in this Python code? Or maybe for both these repos, but not just one?
___
*[`Documentation/index.rst` line 346 at r12](https://reviewable.io/reviews/gramineproject/gsc/168#-Nhfj8qNCc-98lKhnRvL:-Nhfj8qNCc-98lKhnRvM:bt1ut16) ([raw file](https://github.com/gramineproject/gsc/blob/c568b10f98668cf8c04ca5ee92d95214402bc135/Documentation/index.rst#L346)):*
> ```reStructuredText
>    results may be unpredictable. Currently supported distros are Ubuntu 20.04,
>    Ubuntu 21.04, Debian 10, Debian 11, CentOS 8, Red Hat Universal Base Image (UBI)
>    8 and Red Hat Universal Base Image (UBI) 8 minimal. Default value is ``ubuntu:20.04``.
> ```

Our documentation has 80 chars per line limit (in contrast to our C/Python code, which has 100 chars per limit). Please fix and in the `warning` below.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-NhflRqG3DG7E0T0LIMC:b-v6stoa) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The keys are deleted now after the packages are installed.
</blockquote></details>

Yes, the keys are deleted from the final Docker image, but they are still in intermediate Docker images... Same problem as in #173... How do we proceed with this? Looks like we need a proper solution for all such cases, or just assume that the developer host is surely trusted, and don't bother with intermediate stuff.

By this logic, we also have a problem with our multi-stage build trick and removing the enclave-signing key...

@woju @oshogbo @mkow Any comments?
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 11 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhWCGLW6ntYLlEE6cMz:-Nhfj_SL8lfEA7D4_mv-:b-ucfknh) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/templates/redhat/ubi8/Dockerfile.build.template#L11)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

As the entitlements are copied to the image, it is required to use entitlements from the build container.
Few links:
https://docs.openshift.com/container-platform/4.2/builds/running-entitled-builds.html#builds-strategy-docker-entitled-subman_running-entitled-builds

https://docs.openshift.com/container-platform/4.13/cicd/builds/running-entitled-builds.html#builds-source-secrets-entitlements_running-entitled-builds

https://github.com/crc-org/crc/issues/914#issuecomment-597137034
</blockquote></details>

Thanks!
___
*[`templates/redhat/ubi8/Dockerfile.compile.template` line 41 at r12](https://reviewable.io/reviews/gramineproject/gsc/168#-Nhfkx_B3mN6ESgRYsA_:-Nhfkx_B3mN6ESgRYsAa:b-wmlaxq) ([raw file](https://github.com/gramineproject/gsc/blob/c568b10f98668cf8c04ca5ee92d95214402bc135/templates/redhat/ubi8/Dockerfile.compile.template#L41)):*
> ```
>         rpm-build \
>         wget \
>     && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'
> ```

For other reviewers: we don't need to remove stuff (like the subscription key) in this `.compile.template`, because it is anyway always succeeded by the `.build.template` step, where this key will be removed from the final image.

And we don't care about these intermediate images for now, I guess... There seems to be a larger problem of using secrets (like private keys) inside our intermediate Docker containers, see also discussions in https://github.com/gramineproject/gsc/pull/173 and https://github.com/gramineproject/gsc/pull/175


<!-- Sent from Reviewable.io -->

2023-10-26 14:11 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: 14 of 15 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @oshogbo)

___
*[`gsc.py` line 186 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW9jok2XSbT1zb2tFB:-NhgFbJ64IaIyFHSrTke:bvrdzm8) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L186)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

One last question. You check for the existence of `rhel-8-for-x86_64-baseos-rpms` repo here, but in the Dockerfiles you seem to use the `codeready-builder-for-rhel-8-x86_64-rpms`. How are these two repos related? Aren't you supposed to check for `codeready-builder-...` in this Python code? Or maybe for both these repos, but not just one?
</blockquote></details>

The modified `redhat.repo` after subscription has `codeready-builder-for-rhel-8-x86_64-rpms` disabled by default. So, it is enabled later as `nasm` package is available in this repo.

The condition in this python code is to check if the system is registered and subscribed for this any of the repo configuration availability check is sufficient.
___
*[`Documentation/index.rst` line 346 at r12](https://reviewable.io/reviews/gramineproject/gsc/168#-Nhfj8qNCc-98lKhnRvL:-NhgHR-tB9J8Gohi5Mus:bt2vr1b) ([raw file](https://github.com/gramineproject/gsc/blob/c568b10f98668cf8c04ca5ee92d95214402bc135/Documentation/index.rst#L346)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Our documentation has 80 chars per line limit (in contrast to our C/Python code, which has 100 chars per limit). Please fix and in the `warning` below.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2023-10-27 06:47 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[`gsc.py` line 186 at r11](https://reviewable.io/reviews/gramineproject/gsc/168#-NhW9jok2XSbT1zb2tFB:-NhjsT-CCQQq2NKysiBM:bsxk53x) ([raw file](https://github.com/gramineproject/gsc/blob/0fa7c826a0d271151a3593ad418893fdfee4d427/gsc.py#L186)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

The modified `redhat.repo` after subscription has `codeready-builder-for-rhel-8-x86_64-rpms` disabled by default. So, it is enabled later as `nasm` package is available in this repo.

The condition in this python code is to check if the system is registered and subscribed for this any of the repo configuration availability check is sufficient.
</blockquote></details>

Ok, thanks for the explanation.
___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-Nhjsd6657NrvX4JAYf7:bj45rsv) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, the keys are deleted from the final Docker image, but they are still in intermediate Docker images... Same problem as in #173... How do we proceed with this? Looks like we need a proper solution for all such cases, or just assume that the developer host is surely trusted, and don't bother with intermediate stuff.

By this logic, we also have a problem with our multi-stage build trick and removing the enclave-signing key...

@woju @oshogbo @mkow Any comments?
</blockquote></details>

The current consensus seems to be to keep things (and the threat model) as is for now, and later @oshogbo will suggest a proper fix with a proper Docker technique to forward secrets into the Docker image build process. I am resolving this issue.


<!-- Sent from Reviewable.io -->

2023-10-31 16:31 UTC, woju approved these changes
> Reviewed 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-31 16:38 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-Ni5_-rgCxyDI7CvnSPM:b-gwv8mr) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The current consensus seems to be to keep things (and the threat model) as is for now, and later @oshogbo will suggest a proper fix with a proper Docker technique to forward secrets into the Docker image build process. I am resolving this issue.
</blockquote></details>

For the record, leaking RHSM secrets is not wrong in our model, because leaking those keys does not weaken Gramine or SGX security in any way. It's true that we shouldn't do it, but ultimately that's another discussion than #173/#175, because it's a very different threat model. That's why I don't insist here on any particular fix here (or any at all). The thing I do care about is enclave singing key, but it's not this PR.


<!-- Sent from Reviewable.io -->

2023-11-01 02:38 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 2 of 12 files at r3, 1 of 1 files at r8, 4 of 7 files at r10, 3 of 4 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-11-02 07:09 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[`templates/redhat/ubi8/Dockerfile.build.template` line 9 at r8](https://reviewable.io/reviews/gramineproject/gsc/168#-NeEGIof7O_wSo0_G6nr:-NiDqli32gaf7GpYBIma:bddxgtx) ([raw file](https://github.com/gramineproject/gsc/blob/be7fdb7435af475b641a0769bb07f236c43b8025/templates/redhat/ubi8/Dockerfile.build.template#L9)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

For the record, leaking RHSM secrets is not wrong in our model, because leaking those keys does not weaken Gramine or SGX security in any way. It's true that we shouldn't do it, but ultimately that's another discussion than #173/#175, because it's a very different threat model. That's why I don't insist here on any particular fix here (or any at all). The thing I do care about is enclave singing key, but it's not this PR.
</blockquote></details>

Thanks @woju for correcting me. You're absolutely right.


<!-- Sent from Reviewable.io -->

2023-11-02 07:29 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NiDveFW9WjyHR5p6uCx:-NiDveFW9WjyHR5p6uCy:b-seq7xn) (no related file):*
Please note that I removed the `expect` tool because we merged this PR in the meantime (that removes the need for `expect`): https://github.com/gramineproject/gsc/pull/173

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NiDvokc-3a9iT7tx1BY:-NiDvokc-3a9iT7tx1BZ:b-4s1g8p) (no related file):*
@sahason Please test this rebased-and-ready-for-merge version of the PR on UBI8 and UBI8-minimal. The rebase was a bit non-trivial, and I can't test it myself (I don't have RHEL host and I don't have the Red Hat subscription).

___


<!-- Sent from Reviewable.io -->

2023-11-02 08:53 UTC, woju approved these changes
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2023-11-02 11:46 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NiDvokc-3a9iT7tx1BY:-NiEoX4uDXxU6qHZtlpF:b-vex0jx) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Please test this rebased-and-ready-for-merge version of the PR on UBI8 and UBI8-minimal. The rebase was a bit non-trivial, and I can't test it myself (I don't have RHEL host and I don't have the Red Hat subscription).
</blockquote></details>

Testing looks fine.

___


<!-- Sent from Reviewable.io -->

2023-11-02 12:08 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/168)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/168#-NiDvokc-3a9iT7tx1BY:-NiEvitX1odvXpioV1NN:b-yt62bw) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Testing looks fine.
</blockquote></details>

Thanks for double-checking!

___


<!-- Sent from Reviewable.io -->

2023-11-02 12:08 UTC, merged