Remove obsolete "--debug" and "--linux" options
gramineproject/gsc pull request #174
Opened 2023-10-05 13:55 UTC by jkr0103

## Description of the changes 

After the introduction of `--buildtype` option which supports `release`, `debug` and `debugoptimized` buildtype in GSC v1.5, `--debug` option became obsolote and marked for removal in V1.6- release.

Option `--linux` used to compile Gramine with Linux-PAL. But bydefault we build both Linux-PAL and Linux-SGX [here](https://github.com/gramineproject/gsc/blob/5099b641e171942f87254d751fe4bee086a869c2/templates/Dockerfile.common.compile.template#L32), hence this option doesn't have any use and can be removed.
## How to test this PR?

2023-10-09 06:48 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/174#-NgIBRWB0pz21zOyEgJW:-NgIBRWB0pz21zOyEgJX:b-2afzp6) (no related file):*
Just to be sure: did you verify that the Linux PAL (`gramine-direct`) still works after your PR?

___


<!-- Sent from Reviewable.io -->

2023-10-09 08:52 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/174#-NgIBRWB0pz21zOyEgJW:-NgIcNp28-bVKTwPfeCF:b-6aexqh) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Just to be sure: did you verify that the Linux PAL (`gramine-direct`) still works after your PR?
</blockquote></details>

yes I have tested that scenario, instruction to run in LINUX PAL (`gramine-direct`): https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-instead-of-linux-sgx-pal

I have updated the documentation now.

___


<!-- Sent from Reviewable.io -->

2023-10-09 12:22 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`Documentation/index.rst` line 105 at r2](https://reviewable.io/reviews/gramineproject/gsc/174#-NgJNeRa9juvQYm7WYQK:-NgJNeRa9juvQYm7WYQL:b-lyen08) ([raw file](https://github.com/gramineproject/gsc/blob/fe1e805e3a5d33b52d3bba522235d64636256592/Documentation/index.rst#L105)):*
> ```reStructuredText
> 
> ..
>   TODO: Drop `-d` option with GSC v1.6 release
> ```

You're supposed to remove this `-d` text too
___
*[`Documentation/index.rst` line 201 at r2](https://reviewable.io/reviews/gramineproject/gsc/174#-NgJNiWR0QdbGcGkO1bm:-NgJNiWR0QdbGcGkO1bn:b-lyen08) ([raw file](https://github.com/gramineproject/gsc/blob/fe1e805e3a5d33b52d3bba522235d64636256592/Documentation/index.rst#L201)):*
> ```reStructuredText
> 
> ..
>   TODO: Drop `-d` option with GSC v1.6 release
> ```

You're supposed to remove this `-d` text too


<!-- Sent from Reviewable.io -->

2023-10-09 16:51 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/index.rst` line 105 at r2](https://reviewable.io/reviews/gramineproject/gsc/174#-NgJNeRa9juvQYm7WYQK:-NgKLQeb2ZNMbL3FUSSf:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/fe1e805e3a5d33b52d3bba522235d64636256592/Documentation/index.rst#L105)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're supposed to remove this `-d` text too
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 201 at r2](https://reviewable.io/reviews/gramineproject/gsc/174#-NgJNiWR0QdbGcGkO1bm:-NgKLRjsAWEwQAKSJSjE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/fe1e805e3a5d33b52d3bba522235d64636256592/Documentation/index.rst#L201)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You're supposed to remove this `-d` text too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 17:11 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-17 22:33 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-18 05:13 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-10-18 06:53 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/174)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-18 06:53 UTC, merged