Delete dangling image generateed  while signing
gramineproject/gsc pull request #175
Opened 2023-10-25 14:53 UTC by jkr0103

## Description of the changes 

GSC signing have multistage build process and that generates a dangling image which can leak secrets using `docker histroy <image_id>` command, hence this image should be removed once GSC signing is done.

This PR removes the dangling image generated while signing.

## How to test this PR?

2023-10-25 15:59 UTC, oshogbo reviewed
I believe you have a race between removing the history and potential attackers viewing the history.
Password is also stored on persistent storage, so one might want to obtain it this way. (you are pruning it, but it was already stored, and docker prune doesn't remove it in a secure way, for example, by overwriting blocks).

IMHO, we should use one of the secure methods I have mentioned in the previous PR.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175#-:-NhbY9w_1w_rEQEapmJk:b-iglpp4)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: )



<!-- Sent from Reviewable.io -->

2023-10-25 16:09 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-Nhb_eLkEd6shrO-nWEp:b-2ts66a) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
> ```Python
>     finally:
>         os.remove(tmp_build_key_path)
>         docker_socket.api.prune_images(filters={"label": "build_id="+build_id})
> ```

No, this is totally wrong. Deleting secrets after they leaked doesn't mean that they did leak. @oshogbo is right (in the main thread) that it was already stored who-knows-where.

Even if you can't find any better method, this would still be wrong, because it gives false sense of security.


<!-- Sent from Reviewable.io -->

2023-10-25 16:09 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NhbaJQMAIE2ru4F73rM:b8okd3q) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is totally wrong. Deleting secrets after they leaked doesn't mean that they did leak. @oshogbo is right (in the main thread) that it was already stored who-knows-where.

Even if you can't find any better method, this would still be wrong, because it gives false sense of security.
</blockquote></details>

*did not leak


<!-- Sent from Reviewable.io -->

2023-10-26 04:50 UTC, jkr0103 reviewed
Agree, this gives false sense of security but we can consider this PR for saving disk space by removing the dangling image and merge it?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175#-:-NheIkmTCgExDqINdjdZ:baey2eg)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @oshogbo)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NheJF-zBUNRZUUySdBR:bhb2hrs) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

*did not leak
</blockquote></details>

Agree, but we can consider this PR for saving disk space by removing the dangling image and merge it?


<!-- Sent from Reviewable.io -->

2023-10-26 10:27 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @oshogbo)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-NhfU8_U0bQOQl4dmu3m):*
Please add a commit body message:
```
GSC signing has a multistage build process that generates
a dangling image which consumes disk space. Hence this image
should be removed after signing is done, to save disk space.
```

(fix my text above to 72 chars per line)
___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-NhfUT5sCtSItuoZ02Jb:-NhfUT5sCtSItuoZ02Jc:b85c2lh) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
> ```Python
>     finally:
>         os.remove(tmp_build_key_path)
>         docker_socket.api.prune_images(filters={"label": "build_id="+build_id})
> ```

Please add spaces around `+`
___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NhfUd669BwyLzh_z-2h:bur8pzo) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
First, I agree with @jkr0103 that we should remove this dangling image just for disk space considerations.

Second, I feel like the threat model @woju and @oshogbo have in mind is too weak. This signing process is executed on a trusted machine, by a trusted person, so even if we assume a security breach, I can't imagine that the attacker will go for scanning the raw hard disk sectors (@oshogbo's attack) or will look for a data race between creating-intermediate-image-layer and pruning-this-layer steps (@woju's attack). Won't the attacker just concentrate on stealing the `.pem` key?

So I still think that the current approach is sensible, for cases when the attacker gets access to the FS of this system (i.e., protecting against future leaks).

> Password is also stored on persistent storage, so one might want to obtain it this way. (you are pruning it, but it was already stored, and docker prune doesn't remove it in a secure way, for example, by overwriting blocks).

@oshogbo Do other secure methods available in Docker actually protect against such raw-bytes attacks? If they do not, don't your claim expand to "Docker security methods are useless in the proposed threat model"?
___
*[`templates/Dockerfile.common.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-NhfTeKn8zBqWFlk_iRa:-NhfTeKoDWXw0xQ0qmnn:b-bw4vhm) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/templates/Dockerfile.common.sign.template#L4)):*
> ```
> FROM {{image}} as unsigned_image
> ARG BUILD_ID
> LABEL build_id=$BUILD_ID
> ```

Please rewrite to a more prominent:
```
# Sign image in a separate stage to ensure that signing key is never part of the final image
FROM {{image}} as unsigned_image

# BUILD_ID is a random UUID provided by `gsc sign-image` command, to be able to remove
# the temporary intermediate-stage image later in `gsc sign-image`, to free disk space
ARG BUILD_ID
LABEL build_id=$BUILD_ID

```


<!-- Sent from Reviewable.io -->

2023-10-26 10:36 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @jkr0103, and @woju)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-Nhf0eS71Oqy3m7nfTQW:b-ymot1w) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
So the question is, do you feel secure doing:
```
echo "PASSWORD" > file
rm file
```
You at least have a real timing attack.

If you don't care about passwords, why do you use a protected pem file? If the machine is trusted, why not use certs without a password?

> [@oshogbo](https://github.com/oshogbo) Do other secure methods available in Docker actually protect against such raw-bytes attacks? If they do not, don't your claim expand to "Docker security methods are useless in the proposed threat model"?

Yes, they do, as they do not store anything on the disk nor are they available in any layer.
For example, the thing that I proposed:
```
docker build ...
docer run ... gramine-sign ...
docker commit
```

Won't store your password in any layer or on the disk. And you will get the same effect. The password will be only in memory. If the gramine-sign command simply asks for a password it isn't, won't show up in the `ps`. 


<!-- Sent from Reviewable.io -->

2023-10-26 11:18 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @woju)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NhfgzhT7W19E6aWtwxD:b-f7esva) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So the question is, do you feel secure doing:
```
echo "PASSWORD" > file
rm file
```
You at least have a real timing attack.

If you don't care about passwords, why do you use a protected pem file? If the machine is trusted, why not use certs without a password?

> [@oshogbo](https://github.com/oshogbo) Do other secure methods available in Docker actually protect against such raw-bytes attacks? If they do not, don't your claim expand to "Docker security methods are useless in the proposed threat model"?

Yes, they do, as they do not store anything on the disk nor are they available in any layer.
For example, the thing that I proposed:
```
docker build ...
docer run ... gramine-sign ...
docker commit
```

Won't store your password in any layer or on the disk. And you will get the same effect. The password will be only in memory. If the gramine-sign command simply asks for a password it isn't, won't show up in the `ps`.
</blockquote></details>

In that case, I agree with @oshogbo that we need a proper fix, like the one that he suggested (though I don't understand it, but I don't know Docker details and don't want to look into this now).

I still wonder if we want to keep this PR as a disk-space-saver. Looks reasonable to me.


<!-- Sent from Reviewable.io -->

2023-10-26 13:11 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @woju)

___
*[`gsc.py` line 398 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhg5p-SBI5F2n9FfRNH:-Nhg5p-SBI5F2n9FfRNI:b-cg0z28) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L398)):*
> ```Python
>         build_docker_image(docker_socket.api, tmp_build_path, signed_image_name, 'Dockerfile.sign',
>                            forcerm=True, buildargs={"passphrase": args.passphrase,
>                            "BUILD_ID": build_id})
> ```

`"` -> `'`
ditto for the whole PR


<!-- Sent from Reviewable.io -->

2023-10-26 14:25 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-NhfU8_U0bQOQl4dmu3m):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a commit body message:
```
GSC signing has a multistage build process that generates
a dangling image which consumes disk space. Hence this image
should be removed after signing is done, to save disk space.
```

(fix my text above to 72 chars per line)
</blockquote></details>

Done.
___
*[`gsc.py` line 398 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhg5p-SBI5F2n9FfRNH:-NhgMQIL6rMkW_Ss6lD0:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L398)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`"` -> `'`
ditto for the whole PR
</blockquote></details>

Done.
___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NhgMVR9-8XlqHsfKSLp:b-u3x6ao) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In that case, I agree with @oshogbo that we need a proper fix, like the one that he suggested (though I don't understand it, but I don't know Docker details and don't want to look into this now).

I still wonder if we want to keep this PR as a disk-space-saver. Looks reasonable to me.
</blockquote></details>

Agree with Dmitrii on keeping this PR as disk space saver and moving security related discussion to https://github.com/gramineproject/gsc/pull/173
___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-NhfUT5sCtSItuoZ02Jb:-NhgMvtT0me5lsOu1N1f:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add spaces around `+`
</blockquote></details>

Done.
___
*[`templates/Dockerfile.common.sign.template` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-NhfTeKn8zBqWFlk_iRa:-NhgMwtp2EYi9QC1T_cF:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/templates/Dockerfile.common.sign.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rewrite to a more prominent:
```
# Sign image in a separate stage to ensure that signing key is never part of the final image
FROM {{image}} as unsigned_image

# BUILD_ID is a random UUID provided by `gsc sign-image` command, to be able to remove
# the temporary intermediate-stage image later in `gsc sign-image`, to free disk space
ARG BUILD_ID
LABEL build_id=$BUILD_ID

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-26 22:58 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)



<!-- Sent from Reviewable.io -->

2023-10-27 06:11 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NhjkGSp3ysMPRHXMyA8:baf279l) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Agree with Dmitrii on keeping this PR as disk space saver and moving security related discussion to https://github.com/gramineproject/gsc/pull/173
</blockquote></details>

IIUC, the current consensus is to postpone @oshogbo's proper fix (which he will either submit as a separate PR later for all such problems in the GSC codebase) or to at least describe a proper fix in a GitHub issue.

I think we can proceed with this PR, as a disk-saving exercise. @woju What do you think? (You're blocking.)


<!-- Sent from Reviewable.io -->

2023-10-31 16:48 UTC, woju requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @oshogbo)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-Ni5bTdE-VPDNu08Q9eu:b-lf2mc0) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

IIUC, the current consensus is to postpone @oshogbo's proper fix (which he will either submit as a separate PR later for all such problems in the GSC codebase) or to at least describe a proper fix in a GitHub issue.

I think we can proceed with this PR, as a disk-saving exercise. @woju What do you think? (You're blocking.)
</blockquote></details>

This proposal would be more serious, if it was accompanied by 1) some measurements, how much of this disk space is saved, 2) a discussion, how deleting those intermediate layers do not worsen build times (layers are supposed to be cached in docker and reused), 3) a comment in the source code that this thing is not to be relied for security purposes.

Otherwise it looks very much like exercise in hiding things from static secret scanners or checkbox-oriented security certifications, or something like that. That the proper fix for the related security issue is being postponed without timeline does not make this PR easier to approve.


<!-- Sent from Reviewable.io -->

2023-11-02 12:46 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @woju)

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NiEzmQx5qg0Kc0sHKmw:b-9431pk) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*

>deleting those intermediate layers do not worsen build times

No, this particular image (generated in 1st stage) only run the `gramine-sgx-sign` tool and which should be run always, so cashing is not useful, hence build time impact is negligible. Also this is not an intermediate image, it's an independent and dangling image generated from mutistage build.

>a comment in the source code that this thing is not to be relied for security purposes

I have added a comment in source code file `gsc.py`.


>some measurements, how much of this disk space is saved

Space saved is equivelent to the size of image being graminized. First list below is without this PR and 2nd list with the PR which clearly show extra dangling image with size 6.85GB:

Without PR:



_Code snippet:_
```Python
REPOSITORY              TAG                             IMAGE ID       CREATED              SIZE
gsc-pytorch-encrypted   latest                          970def93a5a4   About a minute ago   6.85GB
<none>                  <none>                          36d7c9bf3f01   About a minute ago   6.85GB
<none>                  <none>                          60fc59e5b7e9   3 minutes ago        1.87GB
pytorch-encrypted       latest                          84d639d1aba3   2 hours ago          6.73GB


With PR:

REPOSITORY              TAG                             IMAGE ID       CREATED             SIZE
gsc-pytorch-encrypted   latest                          e7f927ba93f0   50 minutes ago      6.85GB
<none>                  <none>                          cd566a967cfc   53 minutes ago      1.81GB
pytorch-encrypted       latest                          84d639d1aba3   About an hour ago   6.73GB
```


<!-- Sent from Reviewable.io -->

2023-11-02 15:33 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[`gsc.py` line 401 at r1](https://reviewable.io/reviews/gramineproject/gsc/175#-Nhb_eLkEd6shrO-nWEo:-NiFeL1y0QNCXC-dqj4m:bhbn036) ([raw file](https://github.com/gramineproject/gsc/blob/b8661bcde90b59ba755452f4cb5a0e5d7cdb1404/gsc.py#L401)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

>deleting those intermediate layers do not worsen build times

No, this particular image (generated in 1st stage) only run the `gramine-sgx-sign` tool and which should be run always, so cashing is not useful, hence build time impact is negligible. Also this is not an intermediate image, it's an independent and dangling image generated from mutistage build.

>a comment in the source code that this thing is not to be relied for security purposes

I have added a comment in source code file `gsc.py`.


>some measurements, how much of this disk space is saved

Space saved is equivelent to the size of image being graminized. First list below is without this PR and 2nd list with the PR which clearly show extra dangling image with size 6.85GB:

Without PR:
</blockquote></details>

Thank you. Measurements and explanation about caching look convincing, comment is very much acceptable. I'm resolving.


<!-- Sent from Reviewable.io -->

2023-11-03 08:08 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`gsc.py` line 401 at r3](https://reviewable.io/reviews/gramineproject/gsc/175#-NiJD73B6s8_CrxD1mr0:-NiJD73B6s8_CrxD1mr1:bo3x041) ([raw file](https://github.com/gramineproject/gsc/blob/e023eb75fcd14ced0c262f80c0c15fc23d742799/gsc.py#L401)):*
> ```Python
>     finally:
>         os.remove(tmp_build_key_path)
>         # Remove the image created during multistage docker build to save disk space. Removing
> ```

`the image` -> ` a temporary image`
___
*[`gsc.py` line 402 at r3](https://reviewable.io/reviews/gramineproject/gsc/175#-NiJD9nk5B74m6Fz9fLA:-NiJD9nk5B74m6Fz9fLB:bcpbkcd) ([raw file](https://github.com/gramineproject/gsc/blob/e023eb75fcd14ced0c262f80c0c15fc23d742799/gsc.py#L402)):*
> ```Python
>         os.remove(tmp_build_key_path)
>         # Remove the image created during multistage docker build to save disk space. Removing
>         # the image doesn't assure security.
> ```

`Removing the image` -> `Please note taht removing the image`


<!-- Sent from Reviewable.io -->

2023-11-03 09:16 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`gsc.py` line 401 at r3](https://reviewable.io/reviews/gramineproject/gsc/175#-NiJD73B6s8_CrxD1mr0:-NiJT5y47NFt0x14hH9A:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/e023eb75fcd14ced0c262f80c0c15fc23d742799/gsc.py#L401)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the image` -> ` a temporary image`
</blockquote></details>

Done.
___
*[`gsc.py` line 402 at r3](https://reviewable.io/reviews/gramineproject/gsc/175#-NiJD9nk5B74m6Fz9fLA:-NiJT6ZE5vaV5JkMPb0m:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/e023eb75fcd14ced0c262f80c0c15fc23d742799/gsc.py#L402)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Removing the image` -> `Please note taht removing the image`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-03 13:47 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-11-06 11:55 UTC, woju approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-06 12:35 UTC, merged

2023-11-07 00:45 UTC, mkow reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/175)* status: all files reviewed, 2 unresolved discussions (waiting on @jkr0103)

___
*[`-- commits` line 5 at r5](https://reviewable.io/reviews/gramineproject/gsc/175#-NibDbcc7kYUqUMPKmaq):*
:magic_wand: 



_Code quote:_
```
Docker mage
```
___
*[`gsc.py` line 463 at r5](https://reviewable.io/reviews/gramineproject/gsc/175#-NibDqg1CnuoI1EtS7So:-NibDqg2-gO9tkh5yJe5:bua713r) ([raw file](https://github.com/gramineproject/gsc/blob/43a9b9c7f919809178f9a77c76afae5165a1ce6d/gsc.py#L463)):*
> ```Python
>         os.remove(tmp_build_key_path)
>         # Remove a temporary image created during multistage docker build to save disk space.
>         # Please note that removing the image doesn't assure security.
> ```

For the future: please don't use "security" word this way, it doesn't really say anything. Security is always in the context of some thread model (e.g. what you want to protect and from whom). Here it should be "doesn't guarantee removal of the key passphrase from the disk".



_Code quote:_
```Python
Please note that removing the image doesn't assure security.
```


<!-- Sent from Reviewable.io -->