[GSC] Add dockerfile and manifest for OpenVINO benchmark
gramineproject/gsc pull request #18
Opened 2021-09-23 09:38 UTC by sahason

Signed-off-by: Sonali Saha <sonali.saha@intel.com>

## Description of the changes 
Examples to run OpenVINO benchmark with GSC.

## How to test this PR? 
Please follow the steps present at Examples/openvino_benchmark/README.md

2021-10-04 02:48 UTC, aneessahib reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/18#-Ml3cgNm8ZbgcTlD49db):*
dont need [GSC] since this is already GSC repo


<!-- Sent from Reviewable.io -->

2021-10-05 05:15 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 0 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/18#-Ml3cgNm8ZbgcTlD49db):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

dont need [GSC] since this is already GSC repo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-11 11:12 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlil-555g8qsYYaYy96:-Mlil-555g8qsYYaYy97:bf34xh2) (no related file):*
@sahason Could you rebase this PR on the latest master? We now have a `v1.0` version of Gramine and GSC, with many modifications to the build and install processes. Also please verify that the rebased version still works correctly.

---
___
*[Examples/openvino_benchmark/README.md, line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlilBFQ8FZgVa5twRog:-MlilBFRC-wCQxh9hbzE:by58qwj) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L5)):*
> ```Markdown
> For additional information on supported models for GSC, how to install, run and optimize OpenVINO,
> please see
> https://github.com/sahason/examples/tree/sahason/ov_benchmark/openvino#readme.
> ```

This must be updated once OpenVINO benchmark is merged in core Gramine repo.
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlinxPz6984K18GJZDx:-MlinxQ-3USZ_9pkCC1x:b-efx9bl) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L12)):*
> ```Markdown
> ```bash
> docker build --build-arg BUILD_ID=2021.4.582 --shm-size=4g --rm -t ubuntu18.04-openvino -f \
> ubuntu18.04-openvino.dockerfile .
> ```

Could you explain why we need all these args?

- Why `BUILD_ID`?
- Why `shm-size`? Why is it 4GB?
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioEiSEHQlSan73YzD:-MlioEiSEHQlSan73YzE:bk5at16) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L12)):*
> ```Markdown
> ```bash
> docker build --build-arg BUILD_ID=2021.4.582 --shm-size=4g --rm -t ubuntu18.04-openvino -f \
> ubuntu18.04-openvino.dockerfile .
> ```

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line
___
*[Examples/openvino_benchmark/README.md, line 19 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioJNSAbKqzxftG2pn:-MlioJNSAbKqzxftG2po:bk5at16) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L19)):*
> ```Markdown
> cd ../..
> ./gsc build --insecure-args ubuntu18.04-openvino \
> Examples/openvino_benchmark/ubuntu18.04-openvino.manifest
> ```

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line
___
*[Examples/openvino_benchmark/README.md, line 38 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioxgsD_6LA7UAVcZp:-MlioxgsD_6LA7UAVcZq:b-vi1d48) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L38)):*
> ```Markdown
> gsc-ubuntu18.04-openvino -i <image files> \
> -m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
> -d CPU -b 1 -t 20 -nstreams 72 -nthreads 72 -nireq 72
> ```

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line (each line)
___
*[Examples/openvino_benchmark/README.md, line 45 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj0td3CYlcJiX1Hts6:-Mlj0td3CYlcJiX1Hts7:b-f6ojup) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L45)):*
> ```Markdown
> To run benchmark on native container (outside Graphene), remove
> `--device=/dev/sgx_enclave` and replace `gsc-ubuntu18.04-openvino` with
> `ubuntu18.04-openvino` in the above command.
> ```

You have the exact same text for Throughput runs and for Latency runs. Could you just move these `Native` subsections out of the two sections, and just have this:
```
## Running the benchmark in GSC

### Throughput runs

<no need for #### GSC section>
...

### Latency runs

<no need for #### GSC section>
...

## Running the benchmark natively

To run the benchmark ... in the above commands.
```
___
*[Examples/openvino_benchmark/README.md, line 56 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioyvmDN1IkrUgEapc:-MlioyvmDN1IkrUgEapd:b-vi1d48) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L56)):*
> ```Markdown
> gsc-ubuntu18.04-openvino -i <image files> \
> -m model/<public | intel>/<model_dir>/<INT8 | FP16 | FP32>/<model_xml_file> \
> -d CPU -b 1 -t 20 -api sync
> ```

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line (each line)
___
*[Examples/openvino_benchmark/README.md, line 65 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1MFaAjFVaGzV92mS:-Mlj1MFaAjFVaGzV92mT:bleo9o5) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L65)):*
> ```Markdown
> `ubuntu18.04-openvino` in the above command.
> 
> The above `docker run` commands are for a 36-core system. Please check
> ```

Please create a new section `## Notes` before this paragraph.
___
*[Examples/openvino_benchmark/README.md, line 66 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1SakB8opfqfFqZCy:-Mlj1SakB8opfqfFqZCz:by58qwj) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/README.md#L66)):*
> ```Markdown
> 
> The above `docker run` commands are for a 36-core system. Please check
> https://github.com/sahason/examples/tree/sahason/ov_benchmark/openvino#readme for an
> ```

This must be updated once OpenVINO benchmark is merged in core Gramine repo.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 19 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1VGA6uDMcrsQqm6K:-Mlj1VGA6uDMcrsQqm6L:b2s2ria) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L19)):*
> ```Dockerfile
> ARG PUBLIC_KEY="https://apt.repos.intel.com/openvino/2021/GPG-PUB-KEY-INTEL-OPENVINO-2021"
> ARG APT_REPOSITORY="deb https://apt.repos.intel.com/openvino/2021 all main"
> ARG BUILD_ID
> ```

What is this?
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 51 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1fkA9t6r6f5XV6Qw:-Mlj1fkA9t6r6f5XV6Qx:bld339a) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L51)):*
> ```Dockerfile
>     done
> 
> ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino_2021/deployment_tools/inference_engine/lib/intel64:/opt/intel/openvino_2021/deployment_tools/ngraph/lib
> ```

Why this order? Did you copy it from some OpenVINO documentation?

I'm asking because the classic template for this is like: `ENV LD_LIBRARY_PATH=/new/path1:/new/path2:LD_LIBRARY_PATH` (i.e., old `LD_LIBRARY_PATH` is appended not prepended).
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 53 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1y7m6L3K4NyjiQO-:-Mlj1y7m6L3K4NyjiQO0:b-bb8340) ([raw file](https://github.com/gramineproject/gsc/blob/16c07f42eca3ea87b13edda20dc2f841d5e6637a/Examples/openvino_benchmark/ubu [...]

2021-12-06 04:39 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 0 of 3 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlil-555g8qsYYaYy96:-MptsD642fFBbwZ8O29t:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason Could you rebase this PR on the latest master? We now have a `v1.0` version of Gramine and GSC, with many modifications to the build and install processes. Also please verify that the rebased version still works correctly.
</blockquote></details>

Done.

---
___
*[Examples/openvino_benchmark/README.md, line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlilBFQ8FZgVa5twRog:-MptsJs02i4vNMP4tRmT:bb775xo) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This must be updated once OpenVINO benchmark is merged in core Gramine repo.
</blockquote></details>

YES.
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlinxPz6984K18GJZDx:-MptsPUdAKgzWyCgVylE:bsiw0ov) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you explain why we need all these args?

- Why `BUILD_ID`?
- Why `shm-size`? Why is it 4GB?
</blockquote></details>

BUILD_ID is passed to keep it generic. The user can build gsc image with different versions of OpenVINO by only changing this parameter.
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioEiSEHQlSan73YzD:-MpuGoXu-tOYLWNsrfYt:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 19 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioJNSAbKqzxftG2pn:-MpuGs7BBUEmACG_u5Au:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 38 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioxgsD_6LA7UAVcZp:-MpuH-wyBy0gQjmNTGes:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line (each line)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 45 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj0td3CYlcJiX1Hts6:-MpuHvnFBmdVY3XiSgZ-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have the exact same text for Throughput runs and for Latency runs. Could you just move these `Native` subsections out of the two sections, and just have this:
```
## Running the benchmark in GSC

### Throughput runs

<no need for #### GSC section>
...

### Latency runs

<no need for #### GSC section>
...

## Running the benchmark natively

To run the benchmark ... in the above commands.
```
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 56 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlioyvmDN1IkrUgEapc:-MpuHzXS-IKui2t_ENmt:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L56)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please prepend four spaces, to make it clear that this is a continuation of the command on the previous line (each line)
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 65 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1MFaAjFVaGzV92mS:-MpuI5wS1bPWKe5K1oQv:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L65)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please create a new section `## Notes` before this paragraph.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 66 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1SakB8opfqfFqZCy:-MpuI7R1-p_JC7eRcHch:b2nhswy) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L66)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This must be updated once OpenVINO benchmark is merged in core Gramine repo.
</blockquote></details>

Yes
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 19 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1VGA6uDMcrsQqm6K:-MpuImHwE18WtG4NUwma:b-dbpouh) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this?
</blockquote></details>

To get openvino package from openvino repository and then install it in the docker image.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 51 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1fkA9t6r6f5XV6Qw:-MpuJXKp1f0m4NQBfSf9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why this order? Did you copy it from some OpenVINO documentation?

I'm asking because the classic template for this is like: `ENV LD_LIBRARY_PATH=/new/path1:/new/path2:LD_LIBRARY_PATH` (i.e., old `LD_LIBRARY_PATH` is appended not prepended).
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 53 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj1y7m6L3K4NyjiQO-:-MpuJcsJ5y19hgg4fSqU:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why `tee`? Why not simply `echo ... > /root/.bashrc`?
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.manifest, line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-Mlj2963DeNZ4GPGfH30:-MpuK8Qh-6W-BosRO9iv:b-896fix) ([raw  [...]

2021-12-06 08:51 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDs7m82mX1f7x2YOA8:-MlioU069ZDqJDrmZqxm:bzhts5o) (no related file):*
We decided to rename `openvino_benchmark` to `openvino` in this corresponding PR: https://github.com/gramineproject/examples/pull/6

Please rename here as well (all files and all mentions). As an example, the directory should be simply `Examples/openvino/`

---
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDqkx0ER1Jq6ZC_8Zv):*
Please don't use the merge flow in Git. We only use rebase flow. See https://www.atlassian.com/git/tutorials/merging-vs-rebasing

I'll fix this during final rebase for this PR, but please don't ever do `git merge` in the future.
___
*[Examples/openvino_benchmark/README.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDrUDCE27NJ6C37wnj:-MqDrUDCE27NJ6C37wnk:b-t7x7w5) ([raw file](https://github.com/gramineproject/gsc/blob/6e06c177c9262dbad0968b665acdd84c76e4710b/Examples/openvino_benchmark/README.md#L7)):*
> ```Markdown
> https://github.com/sahason/examples/tree/sahason/ov_benchmark/openvino#readme.
> 
> ## Building graphenize docker image
> ```

Please replace `docker` with `Docker` (capital letter) everywhere in this file.
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlinxPz6984K18GJZDx:-MqDrKka3HH3SAaYp2fy:b-fk5jr) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L12)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

BUILD_ID is passed to keep it generic. The user can build gsc image with different versions of OpenVINO by only changing this parameter.
</blockquote></details>

Could you please add a note about `BUILD_ID`? For example, like this:
```
1. Build Docker image (you can pass different `BUILD_ID` to build different versions of OpenVINO):
```
___
*[Examples/openvino_benchmark/README.md, line 3 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDsvJk9wA77-tGJ6_7:-MqDsvJk9wA77-tGJ6_8:bm7ls1i) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L3)):*
> ```Markdown
> # OpenVINO benchmark
> 
> For additional information on supported models for GSC, how to install, run and optimize OpenVINO,
> ```

Why do you say `supported modes for GSC`? I mean, why "for GSC"? Isn't GSC irrelevant here (and what's important is just what models *Gramine-SGX* supports)?

I would simply remove `for GSC`. Or replace with `for OpenVINO under Gramine`.
___
*[Examples/openvino_benchmark/README.md, line 7 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDsfEe4qs_R31dqeHj:-MqDsfEe4qs_R31dqeHk:b-2kd63i) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L7)):*
> ```Markdown
> https://github.com/sahason/examples/tree/sahason/ov_benchmark/openvino#readme.
> 
> ## Building graphenize docker image
> ```

Please replace all `graphene` mentions with `gramine` ones.

So, here it will be `graphenize` -> `graminize`. In other places, it will be `Graphene` -> `Gramine`. And so on.
___
*[Examples/openvino_benchmark/README.md, line 51 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDtn8VCycF2RUBGCjp:-MqDtn8VCycF2RUBGCjq:bl00gzp) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L51)):*
> ```Markdown
> ## Running the benchmark natively
> 
> To run benchmark on native container (outside Graphene), remove
> ```

`run benchmark` -> `run the benchmark`
___
*[Examples/openvino_benchmark/README.md, line 51 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDtr9s5N27YXYcNU2f:-MqDtr9s5N27YXYcNU2g:bx9e341) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L51)):*
> ```Markdown
> ## Running the benchmark natively
> 
> To run benchmark on native container (outside Graphene), remove
> ```

`on native container` -> `in a native Docker container`
___
*[Examples/openvino_benchmark/README.md, line 53 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDtzjb6J5ResWdxIIu:-MqDtzjb6J5ResWdxIIv:bh8k9cl) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L53)):*
> ```Markdown
> To run benchmark on native container (outside Graphene), remove
> `--device=/dev/sgx_enclave` and replace `gsc-ubuntu18.04-openvino` with
> `ubuntu18.04-openvino` in the above command.
> ```

This text is a bit hard to read. I suggest to make a list out of it:
```
To run the benchmark in a native Docker container (outside Gramine), run the above
commands with the following modifications:
- remove `--device=/dev/sgx_enclave`,
- replace `gsc-ubuntu18.04-openvino` with `ubuntu18.04-openvino`.
```
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 23 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDv8357UBYggS6KQyh:-MqDv8357UBYggS6KQyi:bv7guaw) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L23)):*
> ```Dockerfile
> RUN curl -o GPG-PUB-KEY-INTEL-OPENVINO-2021 ${PUBLIC_KEY} && \
>     apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2021 && \
>     echo ${APT_REPOSITORY} | tee - a /etc/apt/sources.list.d/intel-openvino-2021.list && \
> ```

This `-2021` confuses me. So you allow to specify different `BUILD_ID` but you can only use OpenVINO versions from 2021? What happens if the user wants to try OpenVINO version from 2020? Or from the upcoming 2022?

It feels very cumbersome to me. You wanted to add flexibility to possible versions, but this flexibility is too complicated... Maybe just hard-code a specific version of OpenVINO (which you verified that it works)? Otherwise angry users will come to us in 2022 and complain that it doesn't work...
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 28 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDutqY147kEUTXXNjz:-MqDutqY147kEUTXXNk-:b-vrdmsv) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L28)):*
> ```Dockerfile
> 
> # Build apps
> RUN cd /opt/intel/openvino_2021/inference_engine/samples/cpp && \
> ```

You use `openvino_${BUILD_ID}` in other places, but for example here you don't use it. Why?
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 34 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDuzLE0QVyMpSilb0d:-MqDuzLE0QVyMpSilb0e:b-8z4u2z) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L34)):*
> ```Dockerfile
> 
> # Download models benchmark app
> RUN cd /opt/intel/openvino_2021/deployment_tools/open_model_zoo/tools/downloader && \
> ```

ditto (`openvino_${BUILD_ID}`)
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 36 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDv10OCBVIh-C1Jlep:-MqDv10OCBVIh-C1Jleq:b-8z4u2z) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L36)):*
> ```Dockerfile
> RUN cd /opt/intel/op [...]

2021-12-07 09:21 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 0 of 3 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDs7m82mX1f7x2YOA8:-MqJ3J3g5lSO9xrrSmqg:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We decided to rename `openvino_benchmark` to `openvino` in this corresponding PR: https://github.com/gramineproject/examples/pull/6

Please rename here as well (all files and all mentions). As an example, the directory should be simply `Examples/openvino/`
</blockquote></details>

Done.

---
___
*[-- commits, line 7 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDqkx0ER1Jq6ZC_8Zv):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't use the merge flow in Git. We only use rebase flow. See https://www.atlassian.com/git/tutorials/merging-vs-rebasing

I'll fix this during final rebase for this PR, but please don't ever do `git merge` in the future.
</blockquote></details>

Sure, will keep it in mind.
___
*[Examples/openvino_benchmark/README.md, line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDrUDCE27NJ6C37wnj:-MqJ3sSK7Fp0tk9TgSCA:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6e06c177c9262dbad0968b665acdd84c76e4710b/Examples/openvino_benchmark/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace `docker` with `Docker` (capital letter) everywhere in this file.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlinxPz6984K18GJZDx:-MqJ45Pg7DVo7vShumgX:b-x7t13n) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you please add a note about `BUILD_ID`? For example, like this:
```
1. Build Docker image (you can pass different `BUILD_ID` to build different versions of OpenVINO):
```
</blockquote></details>

Now I am only building the version I have tested and not enabling  users to pass build arguments.
___
*[Examples/openvino_benchmark/README.md, line 3 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDsvJk9wA77-tGJ6_7:-MqJ3ok317KgVzPOZkdF:btros6u) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you say `supported modes for GSC`? I mean, why "for GSC"? Isn't GSC irrelevant here (and what's important is just what models *Gramine-SGX* supports)?

I would simply remove `for GSC`. Or replace with `for OpenVINO under Gramine`.
</blockquote></details>

Removed for GSC part.
___
*[Examples/openvino_benchmark/README.md, line 7 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDsfEe4qs_R31dqeHj:-MqJ432SAVoMKVyBcccc:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace all `graphene` mentions with `gramine` ones.

So, here it will be `graphenize` -> `graminize`. In other places, it will be `Graphene` -> `Gramine`. And so on.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 51 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDtr9s5N27YXYcNU2f:-MqJ4Jm4DRC5EMz2wBuW:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`on native container` -> `in a native Docker container`
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 51 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDtn8VCycF2RUBGCjp:-MqJ4LAZ4QjP1AoLNZ8K:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L51)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`run benchmark` -> `run the benchmark`
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/README.md, line 53 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDtzjb6J5ResWdxIIu:-MqJ4YQ4-7hcfffDcsgD:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/README.md#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This text is a bit hard to read. I suggest to make a list out of it:
```
To run the benchmark in a native Docker container (outside Gramine), run the above
commands with the following modifications:
- remove `--device=/dev/sgx_enclave`,
- replace `gsc-ubuntu18.04-openvino` with `ubuntu18.04-openvino`.
```
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 23 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDv8357UBYggS6KQyh:-MqJ4bv21L3iWjQzwddB:bz9f4bb) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This `-2021` confuses me. So you allow to specify different `BUILD_ID` but you can only use OpenVINO versions from 2021? What happens if the user wants to try OpenVINO version from 2020? Or from the upcoming 2022?

It feels very cumbersome to me. You wanted to add flexibility to possible versions, but this flexibility is too complicated... Maybe just hard-code a specific version of OpenVINO (which you verified that it works)? Otherwise angry users will come to us in 2022 and complain that it doesn't work...
</blockquote></details>

I have hard-coded the specific version which I have tested.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 28 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDutqY147kEUTXXNjz:-MqJ4luO-uMHKhrfmLNT:brnbw43) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You use `openvino_${BUILD_ID}` in other places, but for example here you don't use it. Why?
</blockquote></details>

I have hard-coded the specific version which I have tested.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 34 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDuzLE0QVyMpSilb0d:-MqJ4nUe1fBQNYNTOKBJ:bz9f4bb) ([raw file](https://github.com/gramineproject/gsc/blob/d76d959304cb3082b83d85e985a6dab2ef801f4d/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (`openvino_${BUILD_ID}`)
</blockquote></details>

I have hard-coded the specific version which I have tested.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 36 at r3](https://reviewable.io/reviews/gramineproject/gsc/18#-MqDv10OCBVIh-C1Jlep:-MqJ4ovS0pJY7lKH6T3t:bz9f4bb) ([raw file](https://github.com/g [...]

2021-12-09 13:34 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @sahason)

___
*[Examples/openvino/README.md, line 7 at r4](https://reviewable.io/reviews/gramineproject/gsc/18#-MqUNHA1APUTLu_UHuXu:-MqUNHA1APUTLu_UHuXv:bra61ly) ([raw file](https://github.com/gramineproject/gsc/blob/6b59610a59d70052b14690c2f65ee090596258ba/Examples/openvino/README.md#L7)):*
> ```Markdown
> https://github.com/sahason/examples/tree/sahason/ov_benchmark/openvino#readme.
> 
> ## Building graminize Docker image
> ```

`graminize` -> `graminized`
___
*[Examples/openvino_benchmark/README.md, line 12 at r2](https://reviewable.io/reviews/gramineproject/gsc/18#-MlinxPz6984K18GJZDx:-MqUNMAb3xxpKe4ftMgJ:b32w0x) ([raw file](https://github.com/gramineproject/gsc/blob/403c665217919cbd98d4900edcb84fbe9f392371/Examples/openvino_benchmark/README.md#L12)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Now I am only building the version I have tested and not enabling  users to pass build arguments.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-12-16 08:38 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-Mr1O-tv-aOBQTs6gKtB:-Mr1O-tv-aOBQTs6gKtC:bw1lill) (no related file):*
Looks good to me now, but depends on https://github.com/gramineproject/examples/pull/6

---


<!-- Sent from Reviewable.io -->

2022-01-20 17:28 UTC, mkow requested changes
> Reviewed 1 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @sahason)

___
*[Examples/openvino/README.md, line 18 at r5](https://reviewable.io/reviews/gramineproject/gsc/18#-MtsCcaB6WfJj71MMXXH:-MtsCcaB6WfJj71MMXXI:b6zeozj) ([raw file](https://github.com/gramineproject/gsc/blob/3f664ecc7607b71f46dd38af2b312983901ab5de/Examples/openvino/README.md#L18)):*
> ```Markdown
> cd ../..
> ./gsc build --insecure-args ubuntu18.04-openvino \
>     Examples/openvino/ubuntu18.04-openvino.manifest
> ```

Why 18.04? It will lose support soon.


<!-- Sent from Reviewable.io -->

2022-02-16 14:41 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 2 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, and @sahason)

___
*[Examples/openvino/README.md, line 18 at r5](https://reviewable.io/reviews/gramineproject/gsc/18#-MtsCcaB6WfJj71MMXXH:-Mw1w7enCfTF_zZVz3pQ:bxnufze) ([raw file](https://github.com/gramineproject/gsc/blob/3f664ecc7607b71f46dd38af2b312983901ab5de/Examples/openvino/README.md#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why 18.04? It will lose support soon.
</blockquote></details>

At the time of submitting this PR only support for ubuntu 18.04 was available from gsc. I have added support for ubuntu 20.04 in a new commit. The remaining supported distros for gsc are ubuntu 21.04 and centos 8.  Currently, these two OSes are not supported for openvino toolkit itself. Hence currently limiting the support to ubuntu 18.04 and ubuntu 20.04.


<!-- Sent from Reviewable.io -->

2022-02-16 15:43 UTC, mkow requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @sahason)

___
*[Examples/openvino/ubuntu20.04-openvino.dockerfile, line 5 at r6](https://reviewable.io/reviews/gramineproject/gsc/18#-Mw2ADiW2vID2ZaBPCIC:-Mw2ADiW2vID2ZaBPCID:b-khi6q4) ([raw file](https://github.com/gramineproject/gsc/blob/3a378e1f20a91e87c81ce70dbe7b16b3605ea9ba/Examples/openvino/ubuntu20.04-openvino.dockerfile#L5)):*
> ```Dockerfile
> # Install prerequisites
> RUN apt-get update && \
>     env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
> ```

You have it here but not in 18.04, why?



_Code quote:_
```Dockerfile
env DEBIAN_FRONTEND=noninteractive
```


<!-- Sent from Reviewable.io -->

2022-02-17 06:44 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, and @sahason)

___
*[Examples/openvino/ubuntu20.04-openvino.dockerfile, line 5 at r6](https://reviewable.io/reviews/gramineproject/gsc/18#-Mw2ADiW2vID2ZaBPCIC:-Mw5PWiC1cYmzumcJjtA:bb4zi2a) ([raw file](https://github.com/gramineproject/gsc/blob/3a378e1f20a91e87c81ce70dbe7b16b3605ea9ba/Examples/openvino/ubuntu20.04-openvino.dockerfile#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

You have it here but not in 18.04, why?
</blockquote></details>

Unlike 18.04 in 20.04 this command installs an additional package `tzdata` which requires user interaction to prevent that I have added it here.


<!-- Sent from Reviewable.io -->

2022-02-17 14:27 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @sahason)

___
*[Examples/openvino/ubuntu20.04-openvino.dockerfile, line 5 at r6](https://reviewable.io/reviews/gramineproject/gsc/18#-Mw2ADiW2vID2ZaBPCIC:-Mw73pH1BTwxnzysHNz6:bx8aeh2) ([raw file](https://github.com/gramineproject/gsc/blob/3a378e1f20a91e87c81ce70dbe7b16b3605ea9ba/Examples/openvino/ubuntu20.04-openvino.dockerfile#L5)):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

Unlike 18.04 in 20.04 this command installs an additional package `tzdata` which requires user interaction to prevent that I have added it here.
</blockquote></details>

I'd add it to both then, I think this is a good practice in such places. Without it 18.04 can easily break after adding some packages to the list.


<!-- Sent from Reviewable.io -->

2022-02-18 11:03 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 3 of 5 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, and @sahason)

___
*[Examples/openvino/ubuntu20.04-openvino.dockerfile, line 5 at r6](https://reviewable.io/reviews/gramineproject/gsc/18#-Mw2ADiW2vID2ZaBPCIC:-MwBV8Qr8wcUrqhf7jXU:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/3a378e1f20a91e87c81ce70dbe7b16b3605ea9ba/Examples/openvino/ubuntu20.04-openvino.dockerfile#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd add it to both then, I think this is a good practice in such places. Without it 18.04 can easily break after adding some packages to the list.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-19 15:40 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-Mr1O-tv-aOBQTs6gKtB:-MwHcLzM1RDOp1ATu6nl:b-avl4w5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Looks good to me now, but depends on https://github.com/gramineproject/examples/pull/6
</blockquote></details>

gramineproject/examples#6 was merged recently

---


<!-- Sent from Reviewable.io -->

2022-02-22 05:13 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 4 of 5 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-MwROSQJ3TwyW_MD3dJz:-MwUqIlz88iD97zlS5-z:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`README.md` is marked as an "Executable file" (it has the `x` permission). Please remove it, it should be a normal non-execute file.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-02-22 08:35 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[Examples/openvino/ubuntu18.04-openvino.dockerfile, line 1 at r8](https://reviewable.io/reviews/gramineproject/gsc/18#-MwVYq4U7K2bpP7cBoT1:-MwVYq4V04MLylxbR40c:bm2db0y) ([raw file](https://github.com/gramineproject/gsc/blob/c1f87893ec46130826b62c2150fb277e39cb08a8/Examples/openvino/ubuntu18.04-openvino.dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:18.04
> ```

This file differs from the 20.04 file only in this first statement and the OpenVINO version in one line... I'm amazed at how Docker doesn't have a simple way to INCLUDE (copy-paste literally) one Dockerfile into another Dockerfile -- this would make this PR much cleaner. Docker is hardly a nice technology...

Unfortunately, there is no easy way to deduplicate this, and I don't want to use any templating for a simple example. So let's keep this as-is (and continue to bash Docker :)).


<!-- Sent from Reviewable.io -->

2022-02-22 12:59 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-02-22 13:26 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-MwWb5pS45JSDjsx1Apc:-MwWb5pT56vbNEFs8RSv:b-vaigkd) (no related file):*
@sahason @aneessahib We rebased this PR, and it is ready for merge. Could any of you verify that this latest version still works correctly?

---


<!-- Sent from Reviewable.io -->

2022-02-22 13:31 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib and @sahason)



<!-- Sent from Reviewable.io -->

2022-02-22 15:08 UTC, aneessahib commented
@sahason pls test the rebased version once

2022-02-23 07:32 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-MwWb5pS45JSDjsx1Apc:-Mw_MUjt5pPnILHAtk-t:b-8qcobr) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason @aneessahib We rebased this PR, and it is ready for merge. Could any of you verify that this latest version still works correctly?
</blockquote></details>

With the latest gramine changes, `./gsc sign-image` step fails with `No module named cryptography` error. So I have to update the dockerfile and install this module. I have pushed a commit on top of the latest version(rebased) to address this and after that, I have tested and it is working fine.

---


<!-- Sent from Reviewable.io -->

2022-02-23 08:00 UTC, aneessahib commented
@sahason - cryptography module installation must go into the templates. Jinen has just submitted a PR to address this. https://github.com/gramineproject/gsc/pull/48

2022-02-23 08:09 UTC, sahason commented
OK got it. I will wait for this PR to get submitted and revert the changes.

2022-02-23 08:26 UTC, dimakuv requested changes
@sahason The PR #48 was just merged. Please revert the changes.

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18#-:-Mw_fw_f-B58ujTXX2IQ:b-q6qh0d)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-MwWb5pS45JSDjsx1Apc:-Mw_g1J49-8rOXXZWfNL:b843dfl) (no related file):*
<details><summary><i>Previously, sahason wrote…</i></summary><blockquote>

With the latest gramine changes, `./gsc sign-image` step fails with `No module named cryptography` error. So I have to update the dockerfile and install this module. I have pushed a commit on top of the latest version(rebased) to address this and after that, I have tested and it is working fine.
</blockquote></details>

Thanks for testing this, PR #48 fixes this and was already merged.

---


<!-- Sent from Reviewable.io -->

2022-02-23 15:39 UTC, sahason reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18#-:-MwbE7QaErp8PO3ZxF8Q:bb6un1j)* status: 3 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)



<!-- Sent from Reviewable.io -->

2022-02-23 16:04 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @sahason)

___
*[Examples/openvino_benchmark/README.md, line 1 at r11](https://reviewable.io/reviews/gramineproject/gsc/18#-MwbJovB-5wpSmfE-Yc6:-MwbJovC7vGrtlJ8i2fm:bdumz81) ([raw file](https://github.com/gramineproject/gsc/blob/4f27ed5838d77237f5d363324a0eda010654b156/Examples/openvino_benchmark/README.md#L1)):*
> ```Markdown
> # OpenVINO benchmark
> ```

You accidentally added this file. Please remove.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 1 at r11](https://reviewable.io/reviews/gramineproject/gsc/18#-MwbJrF44auIwA2uBnCT:-MwbJrF44auIwA2uBnCU:bdumz81) ([raw file](https://github.com/gramineproject/gsc/blob/4f27ed5838d77237f5d363324a0eda010654b156/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L1)):*
> ```Dockerfile
> FROM ubuntu:18.04
> ```

You accidentally added this file. Please remove.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.manifest, line 2 at r11](https://reviewable.io/reviews/gramineproject/gsc/18#-MwbJrsQ8JDiH9mCWwLJ:-MwbJrsQ8JDiH9mCWwLK:bdumz81) ([raw file](https://github.com/gramineproject/gsc/blob/4f27ed5838d77237f5d363324a0eda010654b156/Examples/openvino_benchmark/ubuntu18.04-openvino.manifest#L2)):*
> ```
> sgx.enclave_size = "32G"
> sgx.thread_num = 196
> ```

You accidentally added this file. Please remove.


<!-- Sent from Reviewable.io -->

2022-02-23 16:47 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: 5 of 8 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[Examples/openvino_benchmark/README.md, line 1 at r11](https://reviewable.io/reviews/gramineproject/gsc/18#-MwbJovB-5wpSmfE-Yc6:-MwbTctL2vyPT66rGUI-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4f27ed5838d77237f5d363324a0eda010654b156/Examples/openvino_benchmark/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You accidentally added this file. Please remove.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile, line 1 at r11](https://reviewable.io/reviews/gramineproject/gsc/18#-MwbJrF44auIwA2uBnCT:-MwbTcFDBqdBwiAVEIHJ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4f27ed5838d77237f5d363324a0eda010654b156/Examples/openvino_benchmark/ubuntu18.04-openvino.dockerfile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You accidentally added this file. Please remove.
</blockquote></details>

Done.
___
*[Examples/openvino_benchmark/ubuntu18.04-openvino.manifest, line 2 at r11](https://reviewable.io/reviews/gramineproject/gsc/18#-MwbJrsQ8JDiH9mCWwLJ:-MwbTbK4Bpi-CK3QoSRg:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4f27ed5838d77237f5d363324a0eda010654b156/Examples/openvino_benchmark/ubuntu18.04-openvino.manifest#L2)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You accidentally added this file. Please remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-24 08:06 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-02-24 08:11 UTC, dimakuv requested changes
> Reviewed all commit messages.
> Dismissed @aneessahib from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @sahason)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-Mwem1KQ2-x2IBcLRiUX:-Mwem1KQ2-x2IBcLRiUY:b9ui3mz) (no related file):*
@sahason @aneessahib I rebased this PR again. It is ready for merge. Could you please verify again that this PR correctly builds and runs OpenVINO? I'll block the merge until you're done with this verification.

---


<!-- Sent from Reviewable.io -->

2022-02-24 13:11 UTC, mkow approved these changes
> Reviewed 2 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @sahason)



<!-- Sent from Reviewable.io -->

2022-02-24 15:07 UTC, sahason reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/18#-Mwem1KQ2-x2IBcLRiUX:-MwgGNK73NcZ_QTBvuhF:bk5mimq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@sahason @aneessahib I rebased this PR again. It is ready for merge. Could you please verify again that this PR correctly builds and runs OpenVINO? I'll block the merge until you're done with this verification.
</blockquote></details>

I have verified that PR correctly builds and runs OpenVINO.

---


<!-- Sent from Reviewable.io -->

2022-02-25 10:21 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/18)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-25 10:23 UTC, merged