Concat or ignore duplicate key values in different manifest files
gramineproject/gsc pull request #180
Opened 2023-11-24 13:34 UTC by jkr0103

## Description of the changes

Concatenate `LD_LIBRARY_PATH`, `PATH` and `LD_PRELOAD` from 
different manifests (user manifest, entrypoint manifest under `gsc/templates` and application docker image environments) as discussed in #166. We also issue a warning about the concatenation.

Also earlier, we reported `Duplicate key` error and exit the GSC build. I thought instead of exiting, we should give precedence to the key value in user manifest than to entrypoint manifest under `gsc/template` and than to the application docker image environments and issue a warning but continue GSC build.

User might want to override some of the application image environments in user manifest for performance tuning in Gramine.

Fixes #166 

## How to test this PR?

2023-12-05 03:33 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: 0 of 2 files reviewed, 16 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/180#-NkozePI9R4gn-d_hRU_:-Nks0d-O-TsYI2f_MSig:bb7f2mf) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we modify the Documentation too? We need to mention two things:
1. All envvars are overridden (if duplicates found) in the following order: first user-provided manifest, if not then GSC-internal manifest, if not then from original Docker image env.
2. The only exceptions are: `LD_LIBRARY_PATH`, `PATH`, `LD_PRELOAD`. They are concatenated instead of overridden. The order of concatenation is same as above.
</blockquote></details>

done

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkp-sci01tA8DtIJKlJ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's not `ignore`, it's `override`
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkp-x-wDuFnLbkGIXlZ):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove `in different manifest files` from here, because it's not only manifest files but also the original Docker image environment.
</blockquote></details>

Done.
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkp02JiB9lXv47KxuV8):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add the text from my top-level comment (about documentation) as the commit body message.
</blockquote></details>

Done.
___
*[`gsc.py` line 28 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkosXMVDNze61ONBVn1:-Nks0u3w6lpWEQYzfKPh:b-xlynvj) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No, sorry, this definitely should be a separate PR. Moreover, I'm sure there's a better way to log rather than using these constants. @woju should know a good module/built-in for this.
</blockquote></details>

Removed but would wait for @woju's inputs.
___
*[`gsc.py` line 132 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkozrul1SYiLa_K98Rj:-Nks16I4AgVJLPd7Tjtu:b-cje0du) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L132)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But aren't you supposed to modify this? You should remove this special case I guess.
</blockquote></details>

yes, removed now.
___
*[`gsc.py` line 169 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkoxJliC4AdfGnzhV9J:-Nks1B8x44R5yp7xcfyQ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you replace `_source` with `_src` everywhere? This shorter version is common in programming, and I think you'll be able to use one-lines instead of splitting always into two lines.
</blockquote></details>

Done.
___
*[`gsc.py` line 169 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkoxUvSDDHYiIcdQWfY:-Nks1CFN92nQUW41t2h9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L169)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can we rename to `merge_two_dicts_in_order()`, because now the order is very important (dict1 overwrites dict2 in some cases, or dict1 is prepended to dict2 in other cases).
</blockquote></details>

Done.
___
*[`gsc.py` line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkoy-k20fn2gtI_UHDQ:-Nks1Dh14C9YCuPLch1m:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This sentence should be below `else:`.

Also, you have typos, please use this:
```
# the key exists in both dicts but with different values, must concatenate/choose one
```
</blockquote></details>

Done.
___
*[`gsc.py` line 182 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkoyFKgDtUuWovLHYCD:-Nks1ElT6bFe1pceP1B1:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L182)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would remove this sentence, it's obvious that we concatenate
</blockquote></details>

Done.
___
*[`gsc.py` line 187 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkoyUCy-PtFzEN37Y94:-Nks1FdH99BZiR5nuGIP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L187)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's too long. Let's just do this:
```
Duplicate key: `{".".join(path + [str(key)])}`. Values from `{dict1_src}`
and `{dict2_src}` are concatenated.
```
</blockquote></details>

Done.
___
*[`gsc.py` line 192 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkoyq3PCrDa9a2wDivO:-Nks1GIP3ptHaOLbpYsI:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L192)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's too long. Let's just do this:
```
Duplicate key: `{".".join(path + [str(key)])}`. Value from `{dict1_src}`
overrides the value from `{dict2_src}`.
```
</blockquote></details>

Done.
___
*[`gsc.py` line 306 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkoz0de6rs1de262XnW:-Nks1HHw5p6LNEglXQmy:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L306)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

For uniformity, please rename to `entrypoint_manifest_dict_src`
</blockquote></details>

Done.
___
*[`gsc.py` line 317 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-Nkoz6SC8bF-3cUSgKTw:-Nks1HvrEEg2cl7uL2Yr:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L317)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename and better message:
```
base_image_dict_src = f'<{original_image} image env>'
```
</blockquote></details>

Done.
___
*[`gsc.py` line 324 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkozL38C-0089KwyATF:-Nks1IZh4SrFe3Dn7Hye:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L324)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`user_manifest_dict_src`
</blockquote></details>

Done.
___
*[`gsc.py` line 352 at r1](https://reviewable.io/reviews/gramineproject/gsc/180#-NkozSYoBCxgaoiqwXoY:-Nks1JSy9VL071R2yjHd:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/106d4bdc043558edc33760d10e527a58af8d1ce4/gsc.py#L352)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please rename and better message:
```
merged_manifest_dict_src = f'<merged {user_manifest}, {entrypoint_manifest} env>'
```
< [...]

2023-12-05 07:45 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksuhP4DhpgLEia6w3F):*
`With this commit, all ...`
___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-Nksub4xD9E3fdtOMwKS):*
`first` (no capital letter)
___
*[`gsc.py` line 172 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksuzhQC8OtrlOkUZIR:-NksuzhQC8OtrlOkUZIS:bhuk2m8) ([raw file](https://github.com/gramineproject/gsc/blob/dce2ccf7a6528ade3d698555ae4c461bfb7d8e48/gsc.py#L172)):*
> ```Python
>                 pass
>             else:
>             # the key exists in both dicts but with different values, must concatenate or choose one
> ```

This needs to be shifted by 4 spaces. I understand that you'll have an overflow of 100 chars, so just remove `the ` at the beginning, and then you'll end up with a single line.
___
*[`Documentation/index.rst` line 273 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksvfwgAOyz2xd3Qpi1:-NksvfwgAOyz2xd3Qpi2:baeitxc) ([raw file](https://github.com/gramineproject/gsc/blob/dce2ccf7a6528ade3d698555ae4c461bfb7d8e48/Documentation/index.rst#L273)):*
> ```reStructuredText
>    duplicates found) in the following order: first user-provided manifest, if
>    not then GSC-internal manifest, if not then from original Docker image env.
>    The only exceptions are: LD_LIBRARY_PATH, PATH, LD_PRELOAD. They are
> ```

Please put each of these envvars in double-backticks (as RST format requires). Like this:
```
The only exceptions are: ``LD_LIBRARY_PATH``, ``PATH``, ``LD_PRELOAD``.
```
___
*[`Documentation/index.rst` line 273 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-Nksvr-s57ZbpdY0VfTX:-Nksvr-s57ZbpdY0VfTY:bzfhthy) ([raw file](https://github.com/gramineproject/gsc/blob/dce2ccf7a6528ade3d698555ae4c461bfb7d8e48/Documentation/index.rst#L273)):*
> ```reStructuredText
>    duplicates found) in the following order: first user-provided manifest, if
>    not then GSC-internal manifest, if not then from original Docker image env.
>    The only exceptions are: LD_LIBRARY_PATH, PATH, LD_PRELOAD. They are
> ```

You have three sentences which belong to the same explanation, let's merge them into one sentence:
```
The only exceptions are: ``LD_LIBRARY_PATH``, ``PATH``, ``LD_PRELOAD``;
they are concatenated instead of overridden (concatenation order is same as above).
```


<!-- Sent from Reviewable.io -->

2023-12-05 08:55 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksuhP4DhpgLEia6w3F):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`With this commit, all ...`
</blockquote></details>

could you plz update while rebasing/merning?
___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-Nksub4xD9E3fdtOMwKS):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`first` (no capital letter)
</blockquote></details>

could you plz update while rebasing/merning?
___
*[`gsc.py` line 172 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksuzhQC8OtrlOkUZIR:-NktB2MO1weplGxtP9Eo:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/dce2ccf7a6528ade3d698555ae4c461bfb7d8e48/gsc.py#L172)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This needs to be shifted by 4 spaces. I understand that you'll have an overflow of 100 chars, so just remove `the ` at the beginning, and then you'll end up with a single line.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 273 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksvfwgAOyz2xd3Qpi1:-NktB3PYAmuBHOIHkLtt:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/dce2ccf7a6528ade3d698555ae4c461bfb7d8e48/Documentation/index.rst#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please put each of these envvars in double-backticks (as RST format requires). Like this:
```
The only exceptions are: ``LD_LIBRARY_PATH``, ``PATH``, ``LD_PRELOAD``.
```
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 273 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-Nksvr-s57ZbpdY0VfTX:-NktB3ufBbeZN8c5mMFh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/dce2ccf7a6528ade3d698555ae4c461bfb7d8e48/Documentation/index.rst#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have three sentences which belong to the same explanation, let's merge them into one sentence:
```
The only exceptions are: ``LD_LIBRARY_PATH``, ``PATH``, ``LD_PRELOAD``;
they are concatenated instead of overridden (concatenation order is same as above).
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-06 07:45 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/180#-Nky4_Bu1_ub4TXZRQFv:-Nky4_Bu1_ub4TXZRQFw:bq7ketj) (no related file):*
I'm ok with this PR, but I'll need to test it after all reviews are done and before final merge.

___
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksuhP4DhpgLEia6w3F):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

could you plz update while rebasing/merning?
</blockquote></details>

Yes, I will
___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-Nksub4xD9E3fdtOMwKS):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

could you plz update while rebasing/merning?
</blockquote></details>

Yes, I will


<!-- Sent from Reviewable.io -->

2023-12-07 01:47 UTC, kailun-qin requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`gsc.py` line 173 at r3](https://reviewable.io/reviews/gramineproject/gsc/180#-Nl0w4aZ2TGEFRLx6Lr8:-Nl0w4aZ2TGEFRLx6Lr9:bhld28g) ([raw file](https://github.com/gramineproject/gsc/blob/8689a26d950faa3305600b21c4d30632ed86e2a1/gsc.py#L173)):*
> ```Python
>             else:
>                 # key exists in both dicts but with different values, must concatenate or choose one
>                 if key in ['LD_LIBRARY_PATH', 'PATH', 'LD_PRELOAD']:
> ```

maybe we can turn this into an ELIF (`elif dict1[key] != dict2[key]`) and simply remove the check of the same key above?



_Code quote:_
```Python
            else:
                # key exists in both dicts but with different values, must concatenate or choose one
                if key in ['LD_LIBRARY_PATH', 'PATH', 'LD_PRELOAD']:
```


<!-- Sent from Reviewable.io -->

2023-12-07 07:59 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @kailun-qin)

___
*[`gsc.py` line 173 at r3](https://reviewable.io/reviews/gramineproject/gsc/180#-Nl0w4aZ2TGEFRLx6Lr8:-Nl2G_w016ubGoGpt45p:b36byxb) ([raw file](https://github.com/gramineproject/gsc/blob/8689a26d950faa3305600b21c4d30632ed86e2a1/gsc.py#L173)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

maybe we can turn this into an ELIF (`elif dict1[key] != dict2[key]`) and simply remove the check of the same key above?
</blockquote></details>

@kailun-qin I like the current version, as it easily follows plain speech: "First check if we have a nested case, if not then check if the two values are lists and concat them, if not then check if two values are exactly the same and do nothing, if not then check whether to concatenate or choose one, if not then error out"


<!-- Sent from Reviewable.io -->

2023-12-07 08:39 UTC, kailun-qin submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`gsc.py` line 173 at r3](https://reviewable.io/reviews/gramineproject/gsc/180#-Nl0w4aZ2TGEFRLx6Lr8:-Nl2QZfo88-iPu_oi-I4:bupr7mq) ([raw file](https://github.com/gramineproject/gsc/blob/8689a26d950faa3305600b21c4d30632ed86e2a1/gsc.py#L173)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@kailun-qin I like the current version, as it easily follows plain speech: "First check if we have a nested case, if not then check if the two values are lists and concat them, if not then check if two values are exactly the same and do nothing, if not then check whether to concatenate or choose one, if not then error out"
</blockquote></details>

Ok, I don't really insist. I'm resolving then.


<!-- Sent from Reviewable.io -->

2023-12-11 18:28 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/180#-Nky4_Bu1_ub4TXZRQFv:-NlP52aHC67t7rNS-SDc:b-6ycfw6) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm ok with this PR, but I'll need to test it after all reviews are done and before final merge.
</blockquote></details>

Ok, playing with it looks fine (except one bad naming, see other comments). Snippet from one GSC build:
```
$ ./gsc build --insecure-args python:bullseye test/generic.manifest

Building unsigned graminized Docker image `gsc-python:bullseye-unsigned` from original application image `python:bullseye`...
Duplicate key: `loader.env.LD_LIBRARY_PATH`. Values from `test/generic.manifest` and `ubuntu/entrypoint.manifest.template` are concatenated.
Duplicate key: `loader.env.PATH`. Values from `test/generic.manifest` and `ubuntu/entrypoint.manifest.template` are concatenated.
Duplicate key: `loader.env.PATH`. Values from `<merged test/generic.manifest, ubuntu/entrypoint.manifest.template env>` and `<<Image: 'python:bullseye'> image env>` are concatenated.
Duplicate key: `loader.env.LANG`. Value from `<merged test/generic.manifest, ubuntu/entrypoint.manifest.template env>` overrides the value from `<<Image: 'python:bullseye'> image env>`.
```

___
___
*[`gsc.py` line 304 at r3](https://reviewable.io/reviews/gramineproject/gsc/180#-NlP5Nk70qaLCN9Klw0I:-NlP5Nk70qaLCN9Klw0J:b-o3if3h) ([raw file](https://github.com/gramineproject/gsc/blob/8689a26d950faa3305600b21c4d30632ed86e2a1/gsc.py#L304)):*
> ```Python
>     base_image_environment = extract_environment_from_image_config(original_image.attrs['Config'])
>     base_image_dict = tomli.loads(base_image_environment)
>     base_image_dict_src = f'<{original_image} image env>'
> ```

Shouldn't this be `original_image_name` instead of `original_image`?

See my top-level comment with a snippet from one run, where I get
```
`<<Image: 'python:bullseye'> image env>`
```


<!-- Sent from Reviewable.io -->

2023-12-12 04:13 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`gsc.py` line 304 at r3](https://reviewable.io/reviews/gramineproject/gsc/180#-NlP5Nk70qaLCN9Klw0I:-NlRDYcT0phqRqX3Bwol:b-fblqkq) ([raw file](https://github.com/gramineproject/gsc/blob/8689a26d950faa3305600b21c4d30632ed86e2a1/gsc.py#L304)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this be `original_image_name` instead of `original_image`?

See my top-level comment with a snippet from one run, where I get
```
`<<Image: 'python:bullseye'> image env>`
```
</blockquote></details>

right, fixed it now.


<!-- Sent from Reviewable.io -->

2023-12-12 05:41 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-12-12 06:43 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-14 17:37 UTC, mkow requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`gsc.py` line 161 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldMnfS5qWs9LXLnfc0:-NldMnfT3zIlZyH_dluB:b-ekoo9y) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/gsc.py#L161)):*
> ```Python
>     env.globals.update({'app_user': user})
> 
> def merge_two_dicts_in_order(dict1, dict1_src, dict2, dict2_src, path=[]):
> ```

This function is not a generic dictionary concatenation anymore, please rename to e.g. `merge_envvars`.
___
*[`gsc.py` line 161 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldOHR153TLx5gRdnHf:-NldOHR153TLx5gRdnHg:bqrfcbv) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/gsc.py#L161)):*
> ```Python
>     env.globals.update({'app_user': user})
> 
> def merge_two_dicts_in_order(dict1, dict1_src, dict2, dict2_src, path=[]):
> ```

What are these arguments? I wasn't able to guess their meaning even after briefly reading the code... Why "merge two dicts" takes 4 dicts as arguments?
___
*[`Documentation/index.rst` line 269 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldLCV18Y6DJSHDfKPo:-NldLCV18Y6DJSHDfKPp:b-yd26vq) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/Documentation/index.rst#L269)):*
> It then prepares image-specific variables such as the executable path, the library path and envvars

By "image-specific variables" you mean envvars? Why are they also listed then? And why do you list "library path and envvars", when the latter contains the former?


<!-- Sent from Reviewable.io -->

2023-12-14 18:10 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: 0 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`gsc.py` line 161 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldMnfS5qWs9LXLnfc0:-NldVFWlAGija4kXft7v:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/gsc.py#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This function is not a generic dictionary concatenation anymore, please rename to e.g. `merge_envvars`.
</blockquote></details>

Done.
___
*[`gsc.py` line 161 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldOHR153TLx5gRdnHf:-NldVNzaCRKxRmvG_1lI:bje0kj3) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/gsc.py#L161)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What are these arguments? I wasn't able to guess their meaning even after briefly reading the code... Why "merge two dicts" takes 4 dicts as arguments?
</blockquote></details>

Arg `dict1_src` is source file of `dict1 and `dict2_src` is the source file of `dict2`. This is to issue a warning to user with source file in case of key conflicts.
___
*[`Documentation/index.rst` line 269 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldLCV18Y6DJSHDfKPo:-NldW8ZL1aDzNemVqytm:bigc3tr) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/Documentation/index.rst#L269)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> It then prepares image-specific variables such as the executable path, the library path and envvars

By "image-specific variables" you mean envvars? Why are they also listed then? And why do you list "library path and envvars", when the latter contains the former?
</blockquote></details>

"image-specific variables" means envvars and binary path etc., changed it now.


<!-- Sent from Reviewable.io -->

2023-12-14 18:41 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/gramineproject/gsc/180#-NldcE9vDwKGPuCX9v7U):*
`manifest-shaped environment of the original Docker image`
___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/gramineproject/gsc/180#-NldcNtwADMw9D4FzOUm):*
`...are PATH, LD_LIBRARY_PATH, LD_PRELOAD environment variables`
___
*[`-- commits` line 10 at r5](https://reviewable.io/reviews/gramineproject/gsc/180#-NldcUG42XNjcN8WS0HH):*
`the same`
___
*[`gsc.py` line 161 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldOHR153TLx5gRdnHf:-Nld_nkn8wB9Nl5NWnvD:b-5gg623) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/gsc.py#L161)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Arg `dict1_src` is source file of `dict1 and `dict2_src` is the source file of `dict2`. This is to issue a warning to user with source file in case of key conflicts.
</blockquote></details>

Done. Changed the names and order.
___
*[`gsc.py` line 161 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldMnfS5qWs9LXLnfc0:-Nld_rKs3DR_iGUwcPM-:b-34r3u4) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/gsc.py#L161)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done. `merge_envvars` is wrong, because we also merge things like `sgx.trusted_files` etc. Basically anything inside the manifest that is a dict/list (+ special case of envvars).


<!-- Sent from Reviewable.io -->

2023-12-14 19:10 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/180#-NldiK-bE5RaRXS0AEkg:-NldiK-c8567b85okdVQ:b-b46snp) (no related file):*
I tested the latest version (with my fixups) again, and it looks fine. Here's the snippets:
```
$ cat test/generic.manifest
loader.env.PATH = "dummy1:dummy2"
loader.env.LD_LIBRARY_PATH = "from_user_manifest"
loader.env.LANG = "en_US.UTF-8"

$ ./gsc build --insecure-args python:bullseye test/generic.manifest
Warning: Duplicate key `loader.env.LD_LIBRARY_PATH`. Values from `test/generic.manifest` and `ubuntu/entrypoint.manifest.templ
ate` are concatenated.
Warning: Duplicate key `loader.env.PATH`. Values from `test/generic.manifest` and `ubuntu/entrypoint.manifest.template` are co
ncatenated.
Warning: Duplicate key `loader.env.PATH`. Values from `<merged test/generic.manifest, ubuntu/entrypoint.manifest.template env>
` and `<python:bullseye image env>` are concatenated.
Warning: Duplicate key `loader.env.LANG`. Value from `<merged test/generic.manifest, ubuntu/entrypoint.manifest.template env>`
 overrides the value from `<python:bullseye image env>`.

# go inside the Docker image, look at the generated manifest file
$ root@4eddc5f097e3:/gramine/app_files# tail -n 50 entrypoint.manifest
...
[loader.env]
PATH = "dummy1:dummy2:/gramine/meson_build_output/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
LD_LIBRARY_PATH = "from_user_manifest:/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:"
LANG = "en_US.UTF-8"
```

___
___
*[`-- commits` line 5 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-NksuhP4DhpgLEia6w3F):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I will
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r2](https://reviewable.io/reviews/gramineproject/gsc/180#-Nksub4xD9E3fdtOMwKS):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I will
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r5](https://reviewable.io/reviews/gramineproject/gsc/180#-NldcE9vDwKGPuCX9v7U):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`manifest-shaped environment of the original Docker image`
</blockquote></details>

Done
___
*[`-- commits` line 9 at r5](https://reviewable.io/reviews/gramineproject/gsc/180#-NldcNtwADMw9D4FzOUm):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`...are PATH, LD_LIBRARY_PATH, LD_PRELOAD environment variables`
</blockquote></details>

Done
___
*[`-- commits` line 10 at r5](https://reviewable.io/reviews/gramineproject/gsc/180#-NldcUG42XNjcN8WS0HH):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`the same`
</blockquote></details>

Done
___
*[`-- commits` line 37 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NldigFW9Riv4XCL1-HG):*
TODO(myself): don't forget to use this commit image
___
*[`Documentation/index.rst` line 269 at r4](https://reviewable.io/reviews/gramineproject/gsc/180#-NldLCV18Y6DJSHDfKPo:-Nldiv_B-UwIBiRnv8IL:b-2xj4u2) ([raw file](https://github.com/gramineproject/gsc/blob/d38484da6994e8037e64be167d8280ddf391dbdd/Documentation/index.rst#L269)):*
> By "image-specific variables" you mean envvars?

Yes. I actually removed the "as the executable path and the library path" and just replaced with a generic "environment variables".


<!-- Sent from Reviewable.io -->

2023-12-14 21:21 UTC, mkow requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`gsc.py` line 179 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleAvbUCiP8nglj3q39:-NleAtF006iW3Ol6Z0lO:b-7khnx9) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L179)):*
> ```Python
>                     manifest1[key] = f'{manifest1[key]}:{manifest2[key]}'
>                     print(f'Warning: Duplicate key `{".".join(path + [str(key)])}`. Values from'
>                           f' `{manifest1_name}` and `{manifest2_name}` are concatenated.')
> ```

`are concatenated` -> `Concatenating values from [...]`
___
*[`gsc.py` line 182 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleB6TNCsXdg9uFAe38:-NleB6TNCsXdg9uFAe39:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L182)):*
> ```Python
>                 else:
>                     print(f'Warning: Duplicate key `{".".join(path + [str(key)])}`. Value from'
>                           f' `{manifest1_name}` overrides the value from `{manifest2_name}`.')
> ```

ditto
___
*[`gsc.py` line 342 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleC002342RirKZjPTe:-NleC002342RirKZjPTf:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L342)):*
> ```Python
>     merged_manifest_dict = merge_manifests_in_order(user_manifest_dict, entrypoint_manifest_dict,
>                                                     user_manifest_name, entrypoint_manifest_name)
>     merged_manifest_name = (f'<merged {user_manifest_name}, {entrypoint_manifest_name} env>')
> ```





_Suggestion:_
```Python
(f'<merged {user_manifest_name}, {entrypoint_manifest_name}, env>')
```


<!-- Sent from Reviewable.io -->

2023-12-14 22:25 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`-- commits` line 37 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NldigFW9Riv4XCL1-HG):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

TODO(myself): don't forget to use this commit image
</blockquote></details>

Done.
___
*[`gsc.py` line 179 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleAvbUCiP8nglj3q39:-NleNkZ1A1gHs9fZVZYq:bhvqkpn) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L179)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`are concatenated` -> `Concatenating values from [...]`
</blockquote></details>

Done.

With Michal's latest comments, the messages look like this:
```
Warning: Duplicate key `loader.env.LD_LIBRARY_PATH`. Concatenating values from `test/generic.manifest` and `ubuntu/entrypoint.manifest.template`.
Warning: Duplicate key `loader.env.PATH`. Concatenating values from `test/generic.manifest` and `ubuntu/entrypoint.manifest.template`.
Warning: Duplicate key `loader.env.PATH`. Concatenating values from `<merged test/generic.manifest and ubuntu/entrypoint.manifest.template>` and `<python:bullseye image env>`.
Warning: Duplicate key `loader.env.LANG`. Overriding value from `<python:bullseye image env>` by the one in `<merged test/generic.manifest and ubuntu/entrypoint.manifest.template>`.
```
___
*[`gsc.py` line 182 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleB6TNCsXdg9uFAe38:-NleNr3R01gmBvUDTmwe:b-evzjj2) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L182)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done, though I'm a bit unsure about `overriding from ... by ...`
___
*[`gsc.py` line 342 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleC002342RirKZjPTe:-NleNukaDDGlHuFcb53p:bxeff4a) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L342)):*
> ```Python
>     merged_manifest_dict = merge_manifests_in_order(user_manifest_dict, entrypoint_manifest_dict,
>                                                     user_manifest_name, entrypoint_manifest_name)
>     merged_manifest_name = (f'<merged {user_manifest_name}, {entrypoint_manifest_name} env>')
> ```

Done. There is no point in the comma -- we don't have three sources. We have only two sources -- the user manifest and the entrypoint generic manifest. But I guess this `env` (short for "environment") is confusing here, so I just removed this word and used an `and`.


<!-- Sent from Reviewable.io -->

2023-12-15 02:12 UTC, kailun-qin approved these changes
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-12-15 09:56 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`gsc.py` line 342 at r6](https://reviewable.io/reviews/gramineproject/gsc/180#-NleC002342RirKZjPTe:-NlgtYSo1ubDBVUOj793:b-wcsgxh) ([raw file](https://github.com/gramineproject/gsc/blob/c18cfb6f85f97bd85367ec95a6da72c349c34f73/gsc.py#L342)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. There is no point in the comma -- we don't have three sources. We have only two sources -- the user manifest and the entrypoint generic manifest. But I guess this `env` (short for "environment") is confusing here, so I just removed this word and used an `and`.
</blockquote></details>

Ah, then I got confused by that `env`, I thought it says there are three sources. Now it's good.


<!-- Sent from Reviewable.io -->

2023-12-15 10:13 UTC, merged