[Docs]State explicitly that Linux PAL is `gramine-direct`
gramineproject/gsc pull request #182
Opened 2023-11-30 12:17 UTC by jkr0103

## Description of the changes 

Sometimes users have difficulty in finding the command to run the workload in `gramine-direct` in GSC. This change will make it easy to understand the command used for running workload in `gramine-direct`.

## How to test this PR? 

NA

2023-11-30 13:02 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/182)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

___
*[`Documentation/index.rst` line 391 at r1](https://reviewable.io/reviews/gramineproject/gsc/182#-NkVJYyEDHxPdfjP09mR:-NkVJYyFD25P2tRm8dGo:btk8dsz) ([raw file](https://github.com/gramineproject/gsc/blob/511d24f2aa48421f7a612e492efdb1ff7dff74bb/Documentation/index.rst#L391)):*
> ```reStructuredText
> 
> 
> Execute with Linux PAL (gramine-direct) instead of Linux-SGX PAL (gramine-sgx)
> ```

Please replace to
```
Execute with Linux PAL (:program:`gramine-direct`)
```

Also, I think that `... instead of ...` is useless information. So let's just remove that part.
___
*[`Documentation/index.rst` line 394 at r1](https://reviewable.io/reviews/gramineproject/gsc/182#-NkVJTmKCtd26wqHCKVe:-NkVJTmKCtd26wqHCKVf:bn77u4d) ([raw file](https://github.com/gramineproject/gsc/blob/511d24f2aa48421f7a612e492efdb1ff7dff74bb/Documentation/index.rst#L394)):*
> ```reStructuredText
> ------------------------------------------------------------------------------
> 
> You may select the Linux PAL (gramine-direct) at Docker run time instead of
> ```

Please replace to
```
:program:`gramine-direct`
```
___
*[`Documentation/index.rst` line 395 at r1](https://reviewable.io/reviews/gramineproject/gsc/182#-NkVJY9o1hZH_LCSWPdU:-NkVJY9o1hZH_LCSWPdV:b9hstvm) ([raw file](https://github.com/gramineproject/gsc/blob/511d24f2aa48421f7a612e492efdb1ff7dff74bb/Documentation/index.rst#L395)):*
> ```reStructuredText
> 
> You may select the Linux PAL (gramine-direct) at Docker run time instead of
> the Linux-SGX PAL (gramine-sgx) by specifying the environment variable
> ```

Please replace to
```
:program:`gramine-sgx`
```


<!-- Sent from Reviewable.io -->

2023-11-30 15:41 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/182)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`Documentation/index.rst` line 391 at r1](https://reviewable.io/reviews/gramineproject/gsc/182#-NkVJYyEDHxPdfjP09mR:-NkVsxAI9nj6tY2QOn1S:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/511d24f2aa48421f7a612e492efdb1ff7dff74bb/Documentation/index.rst#L391)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace to
```
Execute with Linux PAL (:program:`gramine-direct`)
```

Also, I think that `... instead of ...` is useless information. So let's just remove that part.
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 394 at r1](https://reviewable.io/reviews/gramineproject/gsc/182#-NkVJTmKCtd26wqHCKVe:-NkVt17r4cmo3heG2zJ1:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/511d24f2aa48421f7a612e492efdb1ff7dff74bb/Documentation/index.rst#L394)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace to
```
:program:`gramine-direct`
```
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 395 at r1](https://reviewable.io/reviews/gramineproject/gsc/182#-NkVJY9o1hZH_LCSWPdU:-NkVt3vZ2nR6CBXUh6aK:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/511d24f2aa48421f7a612e492efdb1ff7dff74bb/Documentation/index.rst#L395)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please replace to
```
:program:`gramine-sgx`
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-30 15:50 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/182)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-01 05:19 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/182)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-05 11:16 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/182)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-06 07:37 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/182)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-06 07:37 UTC, merged