Fix base-Gramine Docker image name
gramineproject/gsc pull request #183
Opened 2023-11-30 17:11 UTC by jkr0103

## Description of the changes 

Please see #181 for context

Fixes #181

## How to test this PR? 

1. Create base-Gramine Docker image without this PR and use that image with `gsc build` with this PR, build should succeed with a warning.
2. Create base-Gramine Docker image with this PR and use that image with `gsc build` with this PR, build should succeed without any warnings.
3. Specify base-Gramine docker image under Gramine tag in configuration file which doesn't exists on system and do `gsc build`, build should report an error about `image doesn't exists`.

2023-12-05 04:57 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: 1 of 2 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp3eU_4hIDVqoaQOS6:-NksIAAC9MUvlTzKkop1:bi24zz5) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we do this only for the `gsc build-gramine`/"Gramine.Image" case? I thought we agreed to do this for *all cases*.
</blockquote></details>

We did not mention that we will do it for all cases. If we want to do it for all cases than user will loose his original base image with `gsc build`. This change was intended only for `build-gramine` case as this case only expect output image name [here](https://github.com/gramineproject/gsc/blob/43a9b9c7f919809178f9a77c76afae5165a1ce6d/gsc.py#L596). We don't provide any input image with `build-gramine` case.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp3akVDv4B1eZzlPKi):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This commit message doesn't explain anything...
</blockquote></details>

Added some details to commit body.
___
*[`gsc.py` line 28 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp2OwV4RpcpjXXcX68:-NksJWxBB8aR_qAGWHmW:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/gsc.py#L28)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please revert, this should be a separate PR
</blockquote></details>

Done.
___
*[`gsc.py` line 256 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp2YVMBtZx8_4S30Qd:-NksJXud71-fPmXOFj8M:bhpdwo1) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/gsc.py#L256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please fix to `v1.8`, because this change will surely not make it into GSC v1.6
</blockquote></details>

Let's see , if we cannot merge this PR to GSC v1.6 than we can change it. I am being optimistic here.
___
*[`gsc.py` line 257 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp2wcR2A229L766Imt:-NksJxTs0mWsDUr0LJcy:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/gsc.py#L257)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please use the special helper function `gsc_image_name()` instead of explicit `gsc-` string.
</blockquote></details>

Done.
___
*[`gsc.py` line 265 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp2cCEDlJKu5eCxCbC:-NksJzvK1XbKHHlo78VS:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/gsc.py#L265)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gsc.py` line 267 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp33Zl5a5cn351q3bX:-NksK-nL2Xpem0_ULuMw:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/gsc.py#L267)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove these three commented-out lines. It will be obvious how to fix it then...
</blockquote></details>

Done.
___
*[`templates/Dockerfile.common.build.template` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp3JnN9_f75-XpQ7RB:-NksK4kP6KU8Iw50bbbV:b-fag8pi) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/templates/Dockerfile.common.build.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, but now this template doesn't have a fallback?

I mean, what happens in this template if we use:
1. Old-style `image_name` value in "Gramine.Image"?
2. New-style `gsc-image_name` value in "Gramine.Image"?

Looks like the old case won't work?
</blockquote></details>

No, both cases works, we are updating `Gramine.Image` where we handle old style case at this [line](https://github.com/jkr0103/gsc/blob/fcbca374a4fef75f7fac5d819be779f791dd1a23/gsc.py#L257).


<!-- Sent from Reviewable.io -->

2023-12-05 07:38 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp3eU_4hIDVqoaQOS6:-NksseFrCPdptFxbN4s-:b-7h4b05) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We did not mention that we will do it for all cases. If we want to do it for all cases than user will loose his original base image with `gsc build`. This change was intended only for `build-gramine` case as this case only expect output image name [here](https://github.com/gramineproject/gsc/blob/43a9b9c7f919809178f9a77c76afae5165a1ce6d/gsc.py#L596). We don't provide any input image with `build-gramine` case.
</blockquote></details>

Ok, thanks, I misunderstood the original idea of the PR.

For other reviewers: This PR fixes the problem of `gsc build-gramine --image <output_base_gramine_image>`. Previously, GSC had a weird behavior, like this:
```bash
$ gsc build-gramine --image my_awesome_image
... this generates a Docker image `gsc-my_awesome_image`

$ cat config.yaml
...
Gramine:
    Image: "gsc-my_awesome_image"

$ gsc build ...
DOESN'T WORK BECAUSE GSC EXPECTS `gsc-gsc-my-awesome-image` IMAGE!
```

So this PR removes two things: (1) the addition of the prefix to the generated image during `gsc build-gramine`, (2) the addition of the prefix to the image-to-use during `gsc build`.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp3akVDv4B1eZzlPKi):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Added some details to commit body.
</blockquote></details>

Thanks, this explanation is much better now!
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nksr4N1C8P3L4ikeoqV):*
Slight rewording:
```
User must provide the output Docker image name in `build-gramine --image <name>`
command but the generated image prepends `gsc-` which leads to a confusion
about what image name should be specified in the configuration file.
```
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-NksrH6h-NGvnPnbXMNU):*
Better:
```
With this commit, the generated Docker image has the name exactly
as specified by the `--image` (without `gsc-` prepended).
```
___
*[`gsc.py` line 256 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp2YVMBtZx8_4S30Qd:-NksrfwsD31cvVB0vzUl:b-3icyed) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/gsc.py#L256)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Let's see , if we cannot merge this PR to GSC v1.6 than we can change it. I am being optimistic here.
</blockquote></details>

Ok, fair enough, but I'll keep this blocking comment.
___
*[`gsc.py` line 256 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nksruw48LuOZuxCPmC6:-Nksruw48LuOZuxCPmC7:b-iznpsi) ([raw file](https://github.com/gramineproject/gsc/blob/fcbca374a4fef75f7fac5d819be779f791dd1a23/gsc.py#L256)):*
> ```Python
>                 print(f'Cannot find `base-gramine` Docker image `{gramine_image_name}`.')
>                 sys.exit(1)
>             else:
> ```

Actually, why do we need this `else` statement? We will end up here anyway if the previous IF is false (i.e., the `gsc-...` image exists). Please remove the `else` and indent the below lines accordingly.
___
*[`gsc.py` line 259 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkss6wK1AsXVv5XABYb:-Nkss6wK1AsXVv5XABYc:b-tjt7wp) ([raw file](https://github.com/gramineproject/gsc/blob/fcbca374a4fef75f7fac5d819be779f791dd1a23/gsc.py#L259)):*
> ```Python
>                  config['Gramine']['Image'] = gsc_image_name(gramine_image_name)
>                  print('Warning: Please re-build `base-gramine` Docker image '
>                        f'`{gramine_image_name}`. It will be error in future.')
> ```

`This will become an error in future.`
___
*[`templates/Dockerfile.common.build.template` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkp3JnN9_f75-XpQ7RB:-NkssJhfBv-HZzJ0caZh:b-8tvf04) ([raw file](https://github.com/gramineproject/gsc/blob/6161ba60d0ab7069c1fd7562b4cdccd6d0c7d7a8/templates/Dockerfile.common.build.template#L3)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

No, both cases works, we are updating `Gramine.Image` where we handle old style case at this [line](https://github.com/jkr0103/gsc/blob/fcbca374a4fef75f7fac5d819be779f791dd1a23/gsc.py#L257).
</blockquote></details>

You are right, I misunderstood how the whole PR works. Now I get it, thanks for explanations.

For other reviewers: both of my cases work, because the `gsc.py` script is modified now in such a way that it parses this Dockerfile template and tries to find `Gramine.Image` first without the `gsc-` prefix (the new "sane" way) and then with the `gsc-` prefix (the old "weird" way).


<!-- Sent from Reviewable.io -->

2023-12-05 08:09 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nksr4N1C8P3L4ikeoqV):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Slight rewording:
```
User must provide the output Docker image name in `build-gramine --image <name>`
command but the generated image prepends `gsc-` which leads to a confusion
about what image name should be specified in the configuration file.
```
</blockquote></details>

Could you please do it while merging the PR?
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-NksrH6h-NGvnPnbXMNU):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Better:
```
With this commit, the generated Docker image has the name exactly
as specified by the `--image` (without `gsc-` prepended).
```
</blockquote></details>

Could you please do it while merging the PR?
___
*[`gsc.py` line 256 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nksruw48LuOZuxCPmC6:-Nkt0U1m56zWprOeUf8r:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/fcbca374a4fef75f7fac5d819be779f791dd1a23/gsc.py#L256)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, why do we need this `else` statement? We will end up here anyway if the previous IF is false (i.e., the `gsc-...` image exists). Please remove the `else` and indent the below lines accordingly.
</blockquote></details>

Done.
___
*[`gsc.py` line 259 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nkss6wK1AsXVv5XABYb:-Nkt0WHj4J6F0iidWiDh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/fcbca374a4fef75f7fac5d819be779f791dd1a23/gsc.py#L259)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`This will become an error in future.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-06 06:02 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: 1 of 2 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nksr4N1C8P3L4ikeoqV):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Could you please do it while merging the PR?
</blockquote></details>

Please remove `--image` from above commit message while merging.
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-NksrH6h-NGvnPnbXMNU):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Could you please do it while merging the PR?
</blockquote></details>

Please remove `--image` from above commit message while merging.


<!-- Sent from Reviewable.io -->

2023-12-06 07:44 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-Nky4719DG8FhnQr07zZ:-Nky4719DG8FhnQr07z_:b-36oi3) (no related file):*
For other reviewers: I rebased this PR to the latest master, so please start reviewing with r4. This was done to fix the commit message, as the commit message explains what's going on in this PR.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-Nky4HksAWGE0Jduc2cZ:-Nky4HksAWGE0Jduc2c_:bklxr8p) (no related file):*
Putting a blocking comment to test this PR when it is reviewed and ready for final merge.

___
___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-Nksr4N1C8P3L4ikeoqV):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Please remove `--image` from above commit message while merging.
</blockquote></details>

Done
___
*[`-- commits` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/183#-NksrH6h-NGvnPnbXMNU):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Please remove `--image` from above commit message while merging.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-06 09:32 UTC, kailun-qin requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @jkr0103)

___
*[`gsc.py` line 252 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkySPa83EOmsP_DZH39:-NkySPa83EOmsP_DZH3A:b-v2okkp) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L252)):*
> ```Python
>         gramine_image_name = config['Gramine']['Image']
>         if get_docker_image(docker_socket, gramine_image_name) is None:
>             # TODO: Drop below if-else block with GSC v1.7 release
> ```

But we don't have an ELSE now?



_Code quote:_
```Python
if-else
```
___
*[`gsc.py` line 254 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkySVDc71x2PWj5ymPk:-NkySVDdBPSZFlTKbl5W:b-h46poe) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L254)):*
> ```Python
>             # TODO: Drop below if-else block with GSC v1.7 release
>             if get_docker_image(docker_socket, gsc_image_name(gramine_image_name)) is None:
>                 print(f'Cannot find `base-gramine` Docker image `{gramine_image_name}`.')
> ```

why this change? we have base-Gramine elsewhere in this file.



_Code quote:_
```Python
`base-gramine`
```
___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-NkyScHEAOim6zp1_xUX:bnm7o7e) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
> ```Python
> 
>             config['Gramine']['Image'] = gsc_image_name(gramine_image_name)
>             print('Warning: Please re-build `base-gramine` Docker image '
> ```

Do users really need to re-build? Or a rename (i.e., tag+rmi) would be enough?



_Code quote:_
```Python
re-build
```
___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyT0fk7Jv9YCviFD8E:-NkyT0fk7Jv9YCviFD8F:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
> ```Python
> 
>             config['Gramine']['Image'] = gsc_image_name(gramine_image_name)
>             print('Warning: Please re-build `base-gramine` Docker image '
> ```

ditto



_Code quote:_
```Python
`base-gramine`
```


<!-- Sent from Reviewable.io -->

2023-12-07 08:17 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-Nl2JM_L79BVQTz8GD8W:b-cznzdk) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Do users really need to re-build? Or a rename (i.e., tag+rmi) would be enough?
</blockquote></details>

If we land here that means, GSC version mismatches with gramine version in `base-Gramine` Docker image and both (GSC and Gramine) might not be compatible. Hence I felt `re-build` is right thing to do if we land here. Also I feel this should be part of `build-gramine` instructions in GSC documention.

We can improve the message a bit: "Please re-build the `base-Gramine` Docker image from current workspace"




@dimakuv, your views on this?


<!-- Sent from Reviewable.io -->

2023-12-07 08:41 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: 1 of 2 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`gsc.py` line 252 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkySPa83EOmsP_DZH39:-Nl2QtQ8E6ZLJ6BAlRaO:brnwmhu) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L252)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

But we don't have an ELSE now?
</blockquote></details>

re-worded a bit.
___
*[`gsc.py` line 254 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkySVDc71x2PWj5ymPk:-Nl2Qy1d0X_tI-GrVHqu:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L254)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

why this change? we have base-Gramine elsewhere in this file.
</blockquote></details>

Done.
___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyT0fk7Jv9YCviFD8E:-Nl2R-fmADYt4azCCVT0:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-07 08:47 UTC, kailun-qin requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)

___
*[`gsc.py` line 254 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkySVDc71x2PWj5ymPk:-Nl2R54i6BhBwf_G_06W:bnwbflj) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L254)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

We also don't have those backquotes ("`") elsewhere?
___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyT0fk7Jv9YCviFD8E:-Nl2RQBOEMumfkUYU2Du:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ditto
___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-Nl2RTvP5sDx0mmsLSrP:b-r13hgh) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

If we land here that means, GSC version mismatches with gramine version in `base-Gramine` Docker image and both (GSC and Gramine) might not be compatible. Hence I felt `re-build` is right thing to do if we land here. Also I feel this should be part of `build-gramine` instructions in GSC documention.

We can improve the message a bit: "Please re-build the `base-Gramine` Docker image from current workspace"




@dimakuv, your views on this?
</blockquote></details>

Ok, rebuild is never wrong, Im unblocking. When we're here (`Image` is specified in the config), it just feels like the case that users would still want to use an old image (built using a old GSC) while using a new GSC.


<!-- Sent from Reviewable.io -->

2023-12-07 10:32 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @jkr0103)



<!-- Sent from Reviewable.io -->

2023-12-08 08:19 UTC, dimakuv requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-Nl7VTg91BKlBfWcogLf:blleexr) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

Ok, rebuild is never wrong, Im unblocking. When we're here (`Image` is specified in the config), it just feels like the case that users would still want to use an old image (built using a old GSC) while using a new GSC.
</blockquote></details>

I don't understand what `using current workspace` means. We never use the word "workspace" in GSC. Can we just remove this phrase?


<!-- Sent from Reviewable.io -->

2023-12-11 05:59 UTC, anjalirai-intel commented
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-NlMQPyo-Xcz6Kn3Zf4B:b5u3weg) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't understand what `using current workspace` means. We never use the word "workspace" in GSC. Can we just remove this phrase?
</blockquote></details>

Currently this PR supports images also build by master repo which already includes `gsc-` in image name, The initial error message was stating `Please re-build base-Gramine Docker image` which was somehow giving impression that something is wrong with the base image,  So, the error message should be more specific than just re-build gramine-base image like this feature has been updated and you should build again your base gramine image with this workspace, this was the intention behind it 


<!-- Sent from Reviewable.io -->

2023-12-11 09:59 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @jkr0103)

___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-NlNIseF8zm_lo_EMzt7:bjr9j1h) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

Currently this PR supports images also build by master repo which already includes `gsc-` in image name, The initial error message was stating `Please re-build base-Gramine Docker image` which was somehow giving impression that something is wrong with the base image,  So, the error message should be more specific than just re-build gramine-base image like this feature has been updated and you should build again your base gramine image with this workspace, this was the intention behind it
</blockquote></details>

What about this rewording:
```
Warning: The base-Gramine Docker image `{gramine_image_name}` was generated by
an older version of GSC. Please re-build this image using this GSC version. This warning
will become an error in future.
```


<!-- Sent from Reviewable.io -->

2023-12-11 10:00 UTC, anjalirai-intel commented
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-NlNJUTM07YNIxJiEjpp:b-n1to16) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What about this rewording:
```
Warning: The base-Gramine Docker image `{gramine_image_name}` was generated by
an older version of GSC. Please re-build this image using this GSC version. This warning
will become an error in future.
```
</blockquote></details>

This is good


<!-- Sent from Reviewable.io -->

2023-12-11 10:22 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: 1 of 2 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @kailun-qin)

___
*[`gsc.py` line 258 at r4](https://reviewable.io/reviews/gramineproject/gsc/183#-NkyScHEAOim6zp1_xUW:-NlNOWyuEQOjlyRLy0xd:b-l555cj) ([raw file](https://github.com/gramineproject/gsc/blob/02f0003c117f6d3d483b12ea7d3341f405c29360/gsc.py#L258)):*
<details><summary><i>Previously, anjalirai-intel wrote…</i></summary><blockquote>

This is good
</blockquote></details>

Added suggested warning message.


<!-- Sent from Reviewable.io -->

2023-12-11 10:46 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-NlNTufYDulNf1a9Pbml:-NlNTufYDulNf1a9Pbmm:b-2ombpr) (no related file):*
@jkr0103 When I have `Distro: "auto"` in config.yaml, I get the following mysterious error:
```
$ ./gsc build-gramine my-gramine-image
Building base-Gramine Docker image `my-gramine-image`...
Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "/home/dimakuv/gramineproject/gsc/./gsc.py", line 627, in main
    return args.command(args)
  File "/home/dimakuv/gramineproject/gsc/./gsc.py", line 391, in gsc_build_gramine
    distro, _ = distro.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
```

Can we please give a better error message? We need to disallow `auto` during `build-gramine`.

___


<!-- Sent from Reviewable.io -->

2023-12-11 10:56 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-NlNTufYDulNf1a9Pbml:-NlNVrb3DWLVQRDAJlaG:bjwbc4s) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@jkr0103 When I have `Distro: "auto"` in config.yaml, I get the following mysterious error:
```
$ ./gsc build-gramine my-gramine-image
Building base-Gramine Docker image `my-gramine-image`...
Traceback (most recent call last):
  File "./gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "/home/dimakuv/gramineproject/gsc/./gsc.py", line 627, in main
    return args.command(args)
  File "/home/dimakuv/gramineproject/gsc/./gsc.py", line 391, in gsc_build_gramine
    distro, _ = distro.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
```

Can we please give a better error message? We need to disallow `auto` during `build-gramine`.
</blockquote></details>

PR supporting Distro as `auto` merged recently and this PR doesn't have that support. Could you rebase with PR with master and try. We produce error message in this case [here](https://github.com/gramineproject/gsc/blob/master/gsc.py#L427).

___


<!-- Sent from Reviewable.io -->

2023-12-11 12:45 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-Nky4HksAWGE0Jduc2cZ:-NlNuA2k31C6ulc-tPCg:b-ty9581) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Putting a blocking comment to test this PR when it is reviewed and ready for final merge.
</blockquote></details>

Done, tested the PR, looks good to me.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/183#-NlNTufYDulNf1a9Pbml:-NlNfe-U5BobVdNzbq26:b5j6mxy) (no related file):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

PR supporting Distro as `auto` merged recently and this PR doesn't have that support. Could you rebase with PR with master and try. We produce error message in this case [here](https://github.com/gramineproject/gsc/blob/master/gsc.py#L427).
</blockquote></details>

Indeed. After rebasing the PR to current master (locally), it works perfectly fine.

___


<!-- Sent from Reviewable.io -->

2023-12-11 13:36 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-18 07:11 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-18 12:13 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2023-12-21 15:26 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @jkr0103)

___
*[`gsc.py` line 260 at r8](https://reviewable.io/reviews/gramineproject/gsc/183#-NmByvjX7_EjIWpQHccW:-NmByvjX7_EjIWpQHccX:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/4774ab88287c0e91064eadc393052f0ee572e876/gsc.py#L260)):*
> ```Python
>             print(f'Warning: The base-Gramine Docker image `{gramine_image_name}` was generated by'
>                   ' an older version of GSC. Please re-build this image using this GSC version.'
>                   ' This warning will become an error in future.')
> ```





_Suggestion:_
```Python
become an error in the future
```


<!-- Sent from Reviewable.io -->

2023-12-21 17:14 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @kailun-qin, and @mkow)

___
*[`gsc.py` line 260 at r8](https://reviewable.io/reviews/gramineproject/gsc/183#-NmByvjX7_EjIWpQHccW:-NmCMiIQAoTMcdQASj3I:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4774ab88287c0e91064eadc393052f0ee572e876/gsc.py#L260)):*
> ```Python
>             print(f'Warning: The base-Gramine Docker image `{gramine_image_name}` was generated by'
>                   ' an older version of GSC. Please re-build this image using this GSC version.'
>                   ' This warning will become an error in future.')
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-12-22 02:06 UTC, kailun-qin approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2023-12-22 13:20 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: all files reviewed, 1 unresolved discussion, not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-01-04 14:11 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/183)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-01-04 14:56 UTC, merged