Deprecate `GSC_PAL` and use instead `GSC_GRAMINE_BINARY`
gramineproject/gsc pull request #201
Opened 2024-05-10 12:54 UTC by dimakuv

## Description of the changes 

Previously, to run `gramine-direct`, one had to specify `docker run ... --env GSC_PAL=Linux`. This was cumbersome because (1) Gramine users don't need to know the meaning of word "PAL", (2) the value "Linux" doesn't correspond to known-to-users `gramine-direct`, (3) it requires special logic in apploader code.

This PR introduces instead `GSC_GRAMINE_BINARY` envvar with easier semantics: the value is the binary which user wants to invoke.

Extracted from #199. 

## How to test this PR? 

Manually run e.g. the HelloWorld example. After GSC build & sign, you can try:
```sh
$ docker run \
  --security-opt seccomp=unconfined \
  --env GSC_GRAMINE_BINARY=gramine-direct \
  gsc-ubuntu20.04-hello-world
"Hello World! Let's check escaped symbols: < & > "

sdp@sdp:~/tdx/gsc$ docker run \
  --device=/dev/sgx_enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
  --env GSC_GRAMINE_BINARY=gramine-sgx \
  gsc-ubuntu20.04-hello-world
Gramine is starting. Parsing TOML manifest file, this may take some time...
"Hello World! Let's check escaped symbols: < & > "

sdp@sdp:~/tdx/gsc$ docker run \
  --device=/dev/sgx_enclave \
  -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
  gsc-ubuntu20.04-hello-world
Gramine is starting. Parsing TOML manifest file, this may take some time...
"Hello World! Let's check escaped symbols: < & > "

sdp@sdp:~/tdx/gsc$ docker run \
  --env GSC_GRAMINE_BINARY=gramine-bla \
  gsc-ubuntu20.04-hello-world
/gramine/app_files/apploader.sh: line 16: exec: gramine-bla: not found
```

2024-05-13 09:19 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/index.rst` line 408 at r1](https://reviewable.io/reviews/gramineproject/gsc/201#-NxlEQvQ9_0D3AYmJgmA:-NxlEQvQ9_0D3AYmJgmB:b-dd0nfu) ([raw file](https://github.com/gramineproject/gsc/blob/cf07dbe8ff89ad1d6ff24a216ab2470e36fce5cb/Documentation/index.rst#L408)):*
> ```reStructuredText
> command-line option to :command:`docker run`.
> 
> .. envvar:: GSC_GRAMINE_BINARY
> ```

We don't have a different Gramine binary for GSC, it'll still be a gramine binary, hence I would suggest keeping `GRAMINE_BINARY` instead of `GSC_GRAMINE_BINARY` envvar.


<!-- Sent from Reviewable.io -->

2024-05-14 07:15 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: 0 of 2 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`Documentation/index.rst` line 408 at r1](https://reviewable.io/reviews/gramineproject/gsc/201#-NxlEQvQ9_0D3AYmJgmA:-NxpwsJyD01KURA4cz23:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/cf07dbe8ff89ad1d6ff24a216ab2470e36fce5cb/Documentation/index.rst#L408)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

We don't have a different Gramine binary for GSC, it'll still be a gramine binary, hence I would suggest keeping `GRAMINE_BINARY` instead of `GSC_GRAMINE_BINARY` envvar.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-05-20 15:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/201#-NyLXbnSAfLnFoLTLBap:-NyLXbnSAfLnFoLTLBaq:b-f67i3w) (no related file):*
> (1) Gramine users don't need to know the meaning of word "PAL"
> (2) the value "Linux" doesn't correspond to known-to-users `gramine-direct`
> (3) it requires special logic in apploader code.

I think I agree with these, but I'm not sure about the new name, the thing you're supposed to pass there is actually not a binary and you aren't supposed to provide a full path. Maybe `GRAMINE_BACKEND` or `GRAMINE_MODE`? And then just pass `direct` or `sgx`.

___


<!-- Sent from Reviewable.io -->

2024-06-03 11:14 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/201#-NyLXbnSAfLnFoLTLBap:-NzSnfhc6gDb6xh73jKX:b7ltvfp) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> (1) Gramine users don't need to know the meaning of word "PAL"
> (2) the value "Linux" doesn't correspond to known-to-users `gramine-direct`
> (3) it requires special logic in apploader code.

I think I agree with these, but I'm not sure about the new name, the thing you're supposed to pass there is actually not a binary and you aren't supposed to provide a full path. Maybe `GRAMINE_BACKEND` or `GRAMINE_MODE`? And then just pass `direct` or `sgx`.
</blockquote></details>

Done, changed to `GRAMINE_MODE`

___


<!-- Sent from Reviewable.io -->

2024-06-03 17:44 UTC, mkow requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`Documentation/index.rst` line 436 at r3](https://reviewable.io/reviews/gramineproject/gsc/201#-NzUATFaA9e4Qj2Bvp7m:-NzUATFaA9e4Qj2Bvp7n:b2cqo9v) ([raw file](https://github.com/gramineproject/gsc/blob/a751ba67954856433799a603b82a9ebff4dd066d/Documentation/index.rst#L436)):*
> This is deprecated in GSC v1.8

Didn't you remove it completely in this PR?
___
*[`templates/apploader.common.template` line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/201#-NzUBbgU0jEgUMF1yQ9x:-NzUBbgU0jEgUMF1yQ9y:bzevk36) ([raw file](https://github.com/gramineproject/gsc/blob/a751ba67954856433799a603b82a9ebff4dd066d/templates/apploader.common.template#L12)):*
> ```
> 
> # Note: default to SGX if Gramine mode (`direct`, `sgx`) wasn't specified
> exec gramine-${GRAMINE_MODE:-sgx} /gramine/app_files/entrypoint \
> ```

I don't like it, passing wrong value in this env will cause a weird failure (instead of a user-friendly error).



_Code quote:_
```
gramine-${GRAMINE_MODE:-sgx}
```


<!-- Sent from Reviewable.io -->

2024-06-03 21:21 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`Documentation/index.rst` line 436 at r3](https://reviewable.io/reviews/gramineproject/gsc/201#-NzUATFaA9e4Qj2Bvp7m:-NzUyOAa99pwgwJowH5v:b-k7h2a7) ([raw file](https://github.com/gramineproject/gsc/blob/a751ba67954856433799a603b82a9ebff4dd066d/Documentation/index.rst#L436)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> This is deprecated in GSC v1.8

Didn't you remove it completely in this PR?
</blockquote></details>

Oops, true :) Should I keep `GSC_PAL` logic in `apploader.common.template`? Or it's so infrequently used that I can just remove it completely?

Well, it's in the documentation, so I guess I should keep that logic but add a warning.
___
*[`templates/apploader.common.template` line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/201#-NzUBbgU0jEgUMF1yQ9x:-NzUy4VV2CXw_N5Hl-GW:bwtqn7m) ([raw file](https://github.com/gramineproject/gsc/blob/a751ba67954856433799a603b82a9ebff4dd066d/templates/apploader.common.template#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I don't like it, passing wrong value in this env will cause a weird failure (instead of a user-friendly error).
</blockquote></details>

The failure message is not that weird:
```
/gramine/app_files/apploader.sh: line 16: exec: gramine-bla: not found
```

You still don't like it and would like to have a proper if-then-else check in this bash script?


<!-- Sent from Reviewable.io -->

2024-06-04 10:09 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`Documentation/index.rst` line 436 at r3](https://reviewable.io/reviews/gramineproject/gsc/201#-NzUATFaA9e4Qj2Bvp7m:-NzXiDKt2rkcFiDnGyRV:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a751ba67954856433799a603b82a9ebff4dd066d/Documentation/index.rst#L436)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There should at least be a warning (but ideally keep it working + a warning for v1.8). Right now it will just run the SGX version and silently ignore user-provided `GSC_PAL=Linux`.
</blockquote></details>

Done.
___
*[`templates/apploader.common.template` line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/201#-NzUBbgU0jEgUMF1yQ9x:-NzXiCGhBEKYfxD2BkwP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a751ba67954856433799a603b82a9ebff4dd066d/templates/apploader.common.template#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yeah, I think I'd prefer a more explicit error pointing to the env variable which was set incorrectly. It's always nicer for the users, this mistake is rather easy to make and it's just one simple `if` in Bash to improve it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 15:53 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/apploader.common.template` line 22 at r4](https://reviewable.io/reviews/gramineproject/gsc/201#-Nzd51eo9jvccnya_i-M:-Nzd51eo9jvccnya_i-N:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/356314b65e19209ec42737a8f801b452a2faa2a2/templates/apploader.common.template#L22)):*
> ```
> if [ -n "$GSC_PAL" ]; then
>     echo "WARNING: GSC_PAL environment variable is deprecated in v1.8 and will be removed in v1.9."
>     echo "         Use instead the GRAMINE_MODE={direct|sgx} environment variable."
> ```





_Suggestion:_
```
Instead, use GRAMINE_MODE={direct|sgx}.
```


<!-- Sent from Reviewable.io -->

2024-06-05 16:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/201)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`templates/apploader.common.template` line 22 at r4](https://reviewable.io/reviews/gramineproject/gsc/201#-Nzd51eo9jvccnya_i-M:-NzdFvr_1gI3Z2TVqmBR:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/356314b65e19209ec42737a8f801b452a2faa2a2/templates/apploader.common.template#L22)):*
> ```
> if [ -n "$GSC_PAL" ]; then
>     echo "WARNING: GSC_PAL environment variable is deprecated in v1.8 and will be removed in v1.9."
>     echo "         Use instead the GRAMINE_MODE={direct|sgx} environment variable."
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-06-05 18:18 UTC, merged