Add support for CentOS Stream 9
gramineproject/gsc pull request #206
Opened 2024-07-01 05:52 UTC by adarshan-intel

## Description of the changes 
Add support for CentOS Stream 9 using the image - quay.io/centos/centos:stream9 to GSC.

## How to test this PR? 
To test this PR, set follow similar procedure as followed with Ubuntu and do gsc build and signing commands.

2024-07-01 07:50 UTC, dimakuv requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

___
*[`config.yaml.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hDXpJCHDevMgkdQKe:-O0hDXpJCHDevMgkdQKf:b-bo40ic) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/config.yaml.template#L9)):*
> ```
> # - ubuntu:20.04, ubuntu:21.04, ubuntu:22.04, ubuntu:23.04
> # - debian:10, debian:11, debian:12
> # - centos:8, quay.io/centos/centos:stream9
> ```

It looks like there is no official CentOS Stream 9 on DockerHub? Interesting. Do you know the reason for this? (All other base OS images we pull from DockerHub.)
___
*[`config.yaml.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hDkTCDGCbAmEZdoRg:-O0hDkTCDGCbAmEZdoRh:b-shfm28) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/config.yaml.template#L9)):*
> ```
> # - ubuntu:20.04, ubuntu:21.04, ubuntu:22.04, ubuntu:23.04
> # - debian:10, debian:11, debian:12
> # - centos:8, quay.io/centos/centos:stream9
> ```

I think these are sufficiently different CentOS distros, so we should split them into separate lines:
```
# - centos:8
# - centos:stream9 (pulled from quay.io/centos/centos)
```
___
*[`gsc.py` line 263 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hD1dq4DF73EuHTYqh:-O0hD1dq4DF73EuHTYqi:b-q9ykev) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/gsc.py#L263)):*
> ```Python
>             distro = 'redhat/ubi8:' + version_id
> 
>     if (os_release['ID'] == 'centos' and version_id=='9'):
> ```

`version_id == '9'` (add spaces around the equals sign)
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEVg96I026vyl6EDZ:-O0hEVg96I026vyl6ED_:bydf70t) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.build.template#L20)):*
> ```
>                                           'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>     && dnf repolist \
>     && dnf install -y \
> ```

Can you add the same comment as here: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.build.template#L24
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEpFd1PmRO69rATx7:-O0hEpFd1PmRO69rATx8:b-n2pgya) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L5)):*
> ```
> {% block install %}
> 
> RUN dnf distro-sync -y && dnf install 'dnf-command(config-manager)' -y
> ```

What is this, why is this needed? Could you share some references/links where I can read more? Also, can you add a short comment here?
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEvox72ZS6bajrU9D:-O0hEvox72ZS6bajrU9E:b-18uhiq) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L7)):*
> ```
> RUN dnf distro-sync -y && dnf install 'dnf-command(config-manager)' -y
> 
> RUN dnf config-manager --set-enabled -y crb && \
> ```

ditto, what is this?
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hGN3a17w6ov8zsEVZ:-O0hGN3a17w6ov8zsEV_:b-kmk8ok) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L7)):*
> ```
> RUN dnf distro-sync -y && dnf install 'dnf-command(config-manager)' -y
> 
> RUN dnf config-manager --set-enabled -y crb && \
> ```

Please add this comment: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L8
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hF0Ot3qgnIzcjktKl:-O0hF0Ot3qgnIzcjktKm:b29ft67) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L9)):*
> ```
> RUN dnf config-manager --set-enabled -y crb && \
>     dnf install -y yum-utils && \
>     dnf install -y epel-release && \
> ```

Why do you need to have `epel-release` installed separately from other packages? In the original CentOS Dockerfile, we installed it together with all other packages: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L15

Update: you also install `epel-release` below, in the list of packages... Please remove one of these lines.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFAHo-BLOB6RGHESL:-O0hFAHo-BLOB6RGHESM:b-nuaoh8) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
> ```
>     dnf install -y yum-utils && \
>     dnf install -y epel-release && \
>         dnf install -y \
> ```

This should be un-intended by 4 spaces
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFOBt1E1budlw9SmR:-O0hFOBt1E1budlw9SmS:buy5hup) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L12)):*
> ```
>         dnf install -y \
>         autoconf  \
>         bc \
> ```

You sure you need this package? It's not needed in CentOS 8: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L12
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFWMoEeeanuebRL_D:-O0hFWMoEeeanuebRL_E:bxdrtwp) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L14)):*
> ```
>         bc \
>         binutils \
>         bison \
> ```

Why is there no `curl` here? See https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L13

Update: probably this is replaced by `libcurl-devel`, which I see below?
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFflW3HsmFSbimW98:-O0hFflW3HsmFSbimW99:beepg15) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L20)):*
> ```
>         gawk \
>         gcc-c++ \
>         gdb \
> ```

Why do you need gdb? Please remove.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 23 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFmfG6VDm69Vls5bM:-O0hFmfG6VDm69Vls5bN:bpv804i) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L23)):*
> ```
>         git \
>         glibc-static \
>         glibc.i686 \
> ```

You sure you need these two `glibc*` package [...]

2024-07-01 08:15 UTC, adarshan-intel commented
*[`config.yaml.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hDXpJCHDevMgkdQKe:-O0hLyncBhwYRUherJZh:bci9q8i) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/config.yaml.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It looks like there is no official CentOS Stream 9 on DockerHub? Interesting. Do you know the reason for this? (All other base OS images we pull from DockerHub.)
</blockquote></details>

Yes, this is true. There is no official image for CentOS Stream 9, so I use the community-based image for CentOS Stream 9.


<!-- Sent from Reviewable.io -->

2024-07-01 11:31 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 4 of 8 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`config.yaml.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hDkTCDGCbAmEZdoRg:-O0hMPUkC54BQnfxCTIy:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/config.yaml.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think these are sufficiently different CentOS distros, so we should split them into separate lines:
```
# - centos:8
# - centos:stream9 (pulled from quay.io/centos/centos)
```
</blockquote></details>

Done.
___
*[`gsc.py` line 263 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hD1dq4DF73EuHTYqh:-O0hMZIpAbyx-SaoONK6:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/gsc.py#L263)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`version_id == '9'` (add spaces around the equals sign)
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEVg96I026vyl6EDZ:-O0hMu0uCidZTHv7E33z:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.build.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add the same comment as here: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.build.template#L24
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEpFd1PmRO69rATx7:-O0hPmU-9nAWVZTNB3oX:b6s2un3) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this, why is this needed? Could you share some references/links where I can read more? Also, can you add a short comment here?
</blockquote></details>

The `dnf-command(config-manager)` is a plugin for the DNF package manager in RPM-based Linux distributions. It provides a command-line interface for managing DNF repositories and DNF configuration options. With it, users can enable or disable repositories, add new repositories, and adjust various DNF settings without editing config files directly.

[Chapter 10. Managing custom software repositories | Red Hat Product Documentation](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool/assembly_managing-custom-software-repositories_managing-software-with-the-dnf-tool#assembly_managing-custom-software-repositories_managing-software-with-the-dnf-tool)

This is needed to install packages listed in Dockerfile. Else we get this error

`Error: Unable to find a match: glibc-static libmemcached libunwind nasm ninja-build nss-mdns protobuf-c-compiler protobuf-c-devel protobuf-compiler protobuf-devel python3-click`
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEvox72ZS6bajrU9D:-O0hQRSl3wIS90Saw9XS:b-pzh7qn) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto, what is this?
</blockquote></details>

The `dnf config-manager --set-enabled -y crb` part uses the DNF package manager to enable the CodeReady Builder (CRB) repository which is needed to install certain packages.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hGN3a17w6ov8zsEVZ:-O0hQpHr3-mZ4mz2f4xz:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add this comment: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L8
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hF0Ot3qgnIzcjktKl:-O0hR737B08mt6JhXatU:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need to have `epel-release` installed separately from other packages? In the original CentOS Dockerfile, we installed it together with all other packages: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L15

Update: you also install `epel-release` below, in the list of packages... Please remove one of these lines.
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 12 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFOBt1E1budlw9SmR:-O0hSeqA4ClWQYirM18R:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You sure you need this package? It's not needed in CentOS 8: https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L12
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFWMoEeeanuebRL_D:-O0hTWYu87QZ3mH6Faj8:b-m7q2ay) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is there no `curl` here? See https://github.com/gramineproject/gsc/blob/016b112999b893ef6d358f2f8f14231c9c8f1486/templates/centos/Dockerfile.compile.template#L13

Update: probably this is replaced by `libcurl-devel`, which I see below?
</blockquote></details>

There is already an existing installation of curl in CentOS Stream 9. Therefore, installing another curl package would lead to conflicts, so it not adding in the dockerfile.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 20 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFflW3HsmFSbimW98:-O0hU8R_4zgQOmCyyeg4:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L20)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need gdb? Please remove.
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 23 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFmfG6VDm69Vls5bM:-O0hUB-E9dByH8ftJAOd:b-896fi [...]

2024-07-01 14:39 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iiyrH8I7CXETLEcyK:-O0iiyrH8I7CXETLEcyL:by2hrg4) (no related file):*
How could I test this? It seems to require RHEL subscription.

___
___
*[`config.yaml.template` line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hDXpJCHDevMgkdQKe:-O0ihDHQ1wmmyZCOsO-G:bl91nm6) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/config.yaml.template#L9)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Yes, this is true. There is no official image for CentOS Stream 9, so I use the community-based image for CentOS Stream 9.
</blockquote></details>

Yes, this seems to be so. Let's use `quay.io` then.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEpFd1PmRO69rATx7:-O0iithA7fEFNIlf6VH2:b-a81j6n) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L5)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

The `dnf-command(config-manager)` is a plugin for the DNF package manager in RPM-based Linux distributions. It provides a command-line interface for managing DNF repositories and DNF configuration options. With it, users can enable or disable repositories, add new repositories, and adjust various DNF settings without editing config files directly.

[Chapter 10. Managing custom software repositories | Red Hat Product Documentation](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/managing_software_with_the_dnf_tool/assembly_managing-custom-software-repositories_managing-software-with-the-dnf-tool#assembly_managing-custom-software-repositories_managing-software-with-the-dnf-tool)

This is needed to install packages listed in Dockerfile. Else we get this error

`Error: Unable to find a match: glibc-static libmemcached libunwind nasm ninja-build nss-mdns protobuf-c-compiler protobuf-c-devel protobuf-compiler protobuf-devel python3-click`
</blockquote></details>

Thanks for the explanation
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEvox72ZS6bajrU9D:-O0iiN2v8VZ6LMySjntw:b-tzlfaw) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L7)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

The `dnf config-manager --set-enabled -y crb` part uses the DNF package manager to enable the CodeReady Builder (CRB) repository which is needed to install certain packages.
</blockquote></details>

Ok, I learnt about CRB: https://discussion.fedoraproject.org/t/epel-crb-it-is-the-same/44433/7

So, does this mean that in order to use this CentOS Stream 9 in GSC, the user needs to subscribe to Red Hat Enterprise Linux (RHEL)?
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 42 at r2](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iipsw41oTkVFBEtYm:-O0iipsw41oTkVFBEtYn:b-laiw3) ([raw file](https://github.com/gramineproject/gsc/blob/4125e9fb31ee65576c949e86f32379ec8bbf350f/templates/quay.io/centos/centos/Dockerfile.compile.template#L42)):*
> ```
>     && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'
> 
> {% endblock %}
> ```

Please add a newline symbol here


<!-- Sent from Reviewable.io -->

2024-07-02 05:00 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iiyrH8I7CXETLEcyK:-O0ljS512ln2MsTAMEke:b-7ibaon) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

How could I test this? It seems to require RHEL subscription.
</blockquote></details>

No any system should be able to run CentOS Stream 9, I have tested this on Ubuntu 24.04 Machine.

___
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hEvox72ZS6bajrU9D:-O0lf9O--coCCT8cY_Cd:b83wth3) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L7)):*
> So, does this mean that in order to use this CentOS Stream 9 in GSC, the user needs to subscribe to Red Hat Enterprise Linux (RHEL)?

No any system should be able to run CentOS Stream 9, I have tested this on Ubuntu 24.04 Machine
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r1](https://reviewable.io/reviews/gramineproject/gsc/206#-O0hFAHo-BLOB6RGHESL:-O0hSO0L9NcPhin-h23y:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a9ee2b19ee90a35b0cf705c0711ba44c98656223/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This should be un-intended by 4 spaces
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 42 at r2](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iipsw41oTkVFBEtYm:-O0lnh6KDKDf9TybUXYM:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4125e9fb31ee65576c949e86f32379ec8bbf350f/templates/quay.io/centos/centos/Dockerfile.compile.template#L42)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a newline symbol here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-02 08:40 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iiyrH8I7CXETLEcyK:-O0mXNcgEZDMQ88B4N-g:b92fi0t) (no related file):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

No any system should be able to run CentOS Stream 9, I have tested this on Ubuntu 24.04 Machine.
</blockquote></details>

Ok, I tested it on my local machine, using a trivial HelloWorld example. This is to reproduce my steps:

- Prepare the minimal Dockerfile and manifest:
```bash
$ cat test/centos9-hello-world.dockerfile
From quay.io/centos/centos:stream9

CMD ["echo", "\"Hello World!\""]

$ cat test/centos9-hello-world.manifest
# intentionally left empty so that GSC uses default manifest options
```

- Run GSC:
```bash
$ docker build --tag centos9-helloworld --file test/centos9-hello-world.dockerfile .
$ ./gsc build --insecure-args centos9-helloworld test/centos9-hello-world.manifest
$ ./gsc sign-image centos9-helloworld enclave-key.pem
```

- Run Docker:
```
$  docker run --device=/dev/sgx_enclave \
    -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
    gsc-centos9-helloworld

/gramine/meson_build_output/lib64/gramine/sgx/loader: error while loading shared libraries: libprotobuf-c.so.1: cannot open shared object file: No such file or directory
```

@adarshan-intel I get an error about missing file `libprotobuf-c.so.1`. Could you test yourself? Looks like some package is missing.

___


<!-- Sent from Reviewable.io -->

2024-07-08 14:22 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 6 of 8 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iiyrH8I7CXETLEcyK:-O1Hi2pp3JhH11G-SCjO:b-cvodit) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I tested it on my local machine, using a trivial HelloWorld example. This is to reproduce my steps:

- Prepare the minimal Dockerfile and manifest:
```bash
$ cat test/centos9-hello-world.dockerfile
From quay.io/centos/centos:stream9

CMD ["echo", "\"Hello World!\""]

$ cat test/centos9-hello-world.manifest
# intentionally left empty so that GSC uses default manifest options
```

- Run GSC:
```bash
$ docker build --tag centos9-helloworld --file test/centos9-hello-world.dockerfile .
$ ./gsc build --insecure-args centos9-helloworld test/centos9-hello-world.manifest
$ ./gsc sign-image centos9-helloworld enclave-key.pem
```

- Run Docker:
```
$  docker run --device=/dev/sgx_enclave \
    -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket \
    gsc-centos9-helloworld

/gramine/meson_build_output/lib64/gramine/sgx/loader: error while loading shared libraries: libprotobuf-c.so.1: cannot open shared object file: No such file or directory
```

@adarshan-intel I get an error about missing file `libprotobuf-c.so.1`. Could you test yourself? Looks like some package is missing.
</blockquote></details>

Yes, fixed the issue by installing  protobuf-c-compiler, java-11-openjdk, java-11-openjdk-devel packages

___


<!-- Sent from Reviewable.io -->

2024-07-09 06:16 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L6t6y0xWJNx_9IAxk:-O1L6t6y0xWJNx_9IAxl:b-sk34fv) ([raw file](https://github.com/gramineproject/gsc/blob/4125e9fb31ee65576c949e86f32379ec8bbf350f/templates/quay.io/centos/centos/Dockerfile.build.template#L21)):*
> ```
>     && dnf repolist \
> # Install pyelftools and voluptuous after the installation of epel-release as it is provided by the
> # EPEL repo
> ```

Why did you remove this comment?
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 26 at r2](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L6ufE9c7dALwLuH_m:-O1L6ufE9c7dALwLuH_n:bub79wg) ([raw file](https://github.com/gramineproject/gsc/blob/4125e9fb31ee65576c949e86f32379ec8bbf350f/templates/quay.io/centos/centos/Dockerfile.build.template#L26)):*
> ```
>         python3-voluptuous \
>     && dnf -y clean all
> ```

Please re-add the empty line, otherwise it's hard to read this code
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 15 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L70YM39CYH3fLlGLa:-O1L70YM39CYH3fLlGLb:b-3r4ta2) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L15)):*
> ```
>         epel-release \
>         java-11-openjdk \
>         java-11-openjdk-devel \
> ```

Why would you need Java 11 installed here?
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 23 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7PkoDnUAzJ7jo2CY:-O1L7PkoDnUAzJ7jo2CZ:bkdqbk0) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L23)):*
> ```
>         python3-protobuf \
>     && /usr/bin/python3 -B -m pip install click jinja2 protobuf \
>                                           'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*' \
> ```

I don't think you need Meson in this `.build.template` file
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7XT2DxzIOU2LCeUV:-O1L7XT2DxzIOU2LCeUW:bqb9mi3) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
> ```
> 
> RUN dnf config-manager --set-enabled -y crb && \
>     dnf install -y \
> ```

In the `.build.template` file, you have this code slightly differently:
```
RUN dnf update -y \
    && dnf distro-sync -y && dnf install 'dnf-command(config-manager)' -y \
    && dnf config-manager --set-enabled -y crb \
    && dnf install -y \
    ...
```

Can you use the same style in this `.compile.template` file?


<!-- Sent from Reviewable.io -->

2024-07-09 06:55 UTC, adarshan-intel commented
@dimakuv @jkr0103 
In this 32b4a96619964f3cd640302f13c9d317d98f0bcf commit, I have created a folder under CentOS called "stream". Now, all 5 Dockerfiles are located here, instead of quay.io/centos/centos. This eliminates the need to create extra folders for CentOS releases.

2024-07-09 06:56 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 2 of 8 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 21 at r2](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L6t6y0xWJNx_9IAxk:-O1LDoEh2mDWt3-Ro653:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4125e9fb31ee65576c949e86f32379ec8bbf350f/templates/quay.io/centos/centos/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why did you remove this comment?
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 26 at r2](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L6ufE9c7dALwLuH_m:-O1LDpmN0tC37t-X1QZx:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4125e9fb31ee65576c949e86f32379ec8bbf350f/templates/quay.io/centos/centos/Dockerfile.build.template#L26)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-add the empty line, otherwise it's hard to read this code
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 15 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L70YM39CYH3fLlGLa:-O1LEH-Z0Pil8T1T1LRG:bkmuc90) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why would you need Java 11 installed here?
</blockquote></details>

If I don't add it, it shows this error
`
[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)
`
So I have removed java-11-openjdk, and keeping java-11-openjdk-devel package
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 23 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7PkoDnUAzJ7jo2CY:-O1LDT4ACTZZFFuQVdBM:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L23)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think you need Meson in this `.build.template` file
</blockquote></details>

Done.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7XT2DxzIOU2LCeUV:-O1LE3BB0w1WAlKQdn-h:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In the `.build.template` file, you have this code slightly differently:
```
RUN dnf update -y \
    && dnf distro-sync -y && dnf install 'dnf-command(config-manager)' -y \
    && dnf config-manager --set-enabled -y crb \
    && dnf install -y \
    ...
```

Can you use the same style in this `.compile.template` file?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 07:40 UTC, dimakuv reviewed
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 196 at r5](https://reviewable.io/reviews/gramineproject/gsc/206#-O1LQYlt997wHuYgENaO:-O1LQYlu3GdVpj00h8gJ:b-7uaj1x) ([raw file](https://github.com/gramineproject/gsc/blob/32b4a96619964f3cd640302f13c9d317d98f0bcf/gsc.py#L196)):*
> ```Python
>         version_id = 8
>     elif distro in {"redhat/ubi9", "redhat/ubi9-minimal"}:
>         version_id = 9
> ```

Now this PR has unrelated changes from https://github.com/gramineproject/gsc/pull/207 (it is based on that PR).

I'm putting a blocking comment so that we first merge #207, and then we rebase this PR on top of that one. 
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 15 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L70YM39CYH3fLlGLa:-O1LQ9070hk7TEkhwYzY:bfd1fzb) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L15)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

If I don't add it, it shows this error
`
[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)
`
So I have removed java-11-openjdk, and keeping java-11-openjdk-devel package
</blockquote></details>

But that's because you run some Java workload, and you seem to not have a proper Docker image for that Java workload?

Gramine has absolutely nothing to do with Java. This should be removed, and your issue must be solved at the application Docker image level.
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7XT2DxzIOU2LCeUV:-O1LQOiM5weaIaO9kydQ:b-8mca4x) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That's not exactly what I wanted, sorry for confusing. I wanted that both files use this "one RUN command" style. Could you change?


<!-- Sent from Reviewable.io -->

2024-07-09 17:50 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 196 at r5](https://reviewable.io/reviews/gramineproject/gsc/206#-O1LQYlt997wHuYgENaO:-O1Lei-D3VFHn3I8DiW0:b-1qagb1) ([raw file](https://github.com/gramineproject/gsc/blob/32b4a96619964f3cd640302f13c9d317d98f0bcf/gsc.py#L196)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Now this PR has unrelated changes from https://github.com/gramineproject/gsc/pull/207 (it is based on that PR).

I'm putting a blocking comment so that we first merge #207, and then we rebase this PR on top of that one.
</blockquote></details>

Yes, those are unrelated changes. Are there any changes that I need to make from my side, or is the code OK?
___
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 15 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L70YM39CYH3fLlGLa:-O1Ln5Bg3eNqeZZIppKx:blpcmk3) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But that's because you run some Java workload, and you seem to not have a proper Docker image for that Java workload?

Gramine has absolutely nothing to do with Java. This should be removed, and your issue must be solved at the application Docker image level.
</blockquote></details>

Can you suggest what can I do here, since removing this package shows this error?
Not sure how to fix it
___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7XT2DxzIOU2LCeUV:-O1LfWoV9SoXp4KDD19I:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

That's not exactly what I wanted, sorry for confusing. I wanted that both files use this "one RUN command" style. Could you change?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 18:08 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 2 of 8 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 196 at r5](https://reviewable.io/reviews/gramineproject/gsc/206#-O1LQYlt997wHuYgENaO:-O1NfaXYC9Lsfx4n0G55:b2bdh9p) ([raw file](https://github.com/gramineproject/gsc/blob/32b4a96619964f3cd640302f13c9d317d98f0bcf/gsc.py#L196)):*
> Now this PR has unrelated changes from
Removed the unrelated changes and only kept changes related to centos stream 9


<!-- Sent from Reviewable.io -->

2024-07-10 06:55 UTC, adarshan-intel commented
*[`templates/quay.io/centos/centos/Dockerfile.build.template` line 15 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L70YM39CYH3fLlGLa:-O1QPkk773lGUF_WAbQ6:br4qmf1) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.build.template#L15)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Can you suggest what can I do here, since removing this package shows this error?
Not sure how to fix it
</blockquote></details>

If I install the "which" package, the build will be successful. As earlier it was not able to execute the command
```
which /bin/bash
```


<!-- Sent from Reviewable.io -->

2024-07-11 07:35 UTC, dimakuv requested changes
> Reviewed 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7XT2DxzIOU2LCeUV:-O1Vhmqd71O2iw8IVShl:b-duf918) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done? What I wanted is to have only one `RUN` command and concatenate all `dnf ...` commands under this single RUN.


<!-- Sent from Reviewable.io -->

2024-07-11 09:00 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 6 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/quay.io/centos/centos/Dockerfile.compile.template` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/206#-O1L7XT2DxzIOU2LCeUV:-O1W0MEWD0A0p7opTF8N:b-dpl7gm) ([raw file](https://github.com/gramineproject/gsc/blob/c3e6ee0f5fccd1a39bab38b3b184edc9562ad97d/templates/quay.io/centos/centos/Dockerfile.compile.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done? What I wanted is to have only one `RUN` command and concatenate all `dnf ...` commands under this single RUN.
</blockquote></details>

Done in this commit - 37e0cd4ed7e1dc5e36b550480bc38b164b028254


<!-- Sent from Reviewable.io -->

2024-07-11 10:27 UTC, dimakuv reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-12 05:01 UTC, adarshan-intel commented
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Yes, fixed the issue by installing  protobuf-c-compiler, java-11-openjdk, java-11-openjdk-devel packages
</blockquote></details>

@dimakuv Is this still blocking? I have installed the which,  protobuf-c-compiler package and removed the Java packages.




<!-- Sent from Reviewable.io -->

2024-07-17 05:59 UTC, anjalirai-intel commented
@dimakuv We did not face any such issue. The CI setup we have for running gsc workloads is stable. We have tested the helloworld, bash example with distro as "auto", "distro specified" in config.yaml and also tested "gsc build-gramine" feature. No issues seen

2024-07-17 14:25 UTC, dimakuv submitted a review, later dismissed
Thanks @anjalirai-intel 

> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206#-:-O204GHd8qkZ7g-3U4qd:b-tfzwl0)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/206#-O0iiyrH8I7CXETLEcyK:-O204IVy1lqwGMBtJMXH:b-e9m0k7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'm hitting these errors in my Docker now: https://github.com/docker/docker-py/issues/3256

I'll deal with this later. @jkr0103 @anjalirai-intel Did you test this PR?
</blockquote></details>

@anjalirai-intel tested, so I'm unblocking.

___


<!-- Sent from Reviewable.io -->

2024-07-17 15:02 UTC, jkr0103 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206#-:-O20Cl-9AqFJmRol7yn6:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-17 23:39 UTC, mkow requested changes
> Reviewed 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`config.yaml.template` line 10 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222dFsD0upI6If3lN_:-O222dFt3FbzzpEAtziG:b-cfbipc) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/config.yaml.template#L10)):*
> ```
> # - debian:10, debian:11, debian:12
> # - centos:8
> # - centos:stream9 (use complete quay.io/centos/centos:stream9)
> ```

Also: What do you mean by "complete" here?



_Suggestion:_
```
# - centos:stream9 (uses complete quay.io/centos/centos:stream9)
```
___
*[`gsc.py` line 241 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222pja-zC8vwjHLOmF:-O222pja-zC8vwjHLOmG:b-rdqd01) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L241)):*
> ```Python
>         shutil.copytree(sslclientkey_dir, tmp_build_path / 'pki/entitlement')
> 
> def template_path(distro):
> ```

Won't this conflict with #207? If so, we have to merge one of the PRs first, rebase the other and actually re-review it. Let's maybe do #207 first?
___
*[`gsc.py` line 268 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222YGPAahJnpVuvou9:-O222YGPAahJnpVuvouA:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L268)):*
> ```Python
>             distro = 'redhat/ubi8:' + version_id
> 
>     if (os_release['NAME'] == "CentOS Stream"):
> ```





_Suggestion:_
```Python
if os_release['NAME'] == 'CentOS Stream':
```


<!-- Sent from Reviewable.io -->

2024-07-18 05:49 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`config.yaml.template` line 10 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222dFsD0upI6If3lN_:-O23Li7z69kMEk9cTLlU:bsdtuc6) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/config.yaml.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Also: What do you mean by "complete" here?
</blockquote></details>

When specifying a custom distribution name in config.yaml (not auto), it's crucial to use the full path `quay.io/centos/centos:stream9`. 

Merely using `centos:stream9` as distro in the config.yaml file will not function correctly.

 I attempted to modify the code so that entering `centos:stream9` would default to pulling from `quay.io/centos/centos:stream9`, but this did not work when building the base Gramine docker image. 

Therefore, this ensures users input the complete path. Although the process works correctly when 'auto' is entered as a distro as the logic is implemented to pull from quay.io
___
*[`gsc.py` line 241 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222pja-zC8vwjHLOmF:-O23M7yZ4rc9jMiIp7Za:b5ybdkp) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L241)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Won't this conflict with #207? If so, we have to merge one of the PRs first, rebase the other and actually re-review it. Let's maybe do #207 first?
</blockquote></details>

Done. Yes once #207 is merged, I will again re-request a review for this and fix the merge conflicts 
___
*[`gsc.py` line 268 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222YGPAahJnpVuvou9:-O23MVH4AEE-Mj1S0kME:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L268)):*
> ```Python
>             distro = 'redhat/ubi8:' + version_id
> 
>     if (os_release['NAME'] == "CentOS Stream"):
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-18 11:04 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel, @dimakuv, and @jkr0103)

___
*[`gsc.py` line 241 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222pja-zC8vwjHLOmF:-O24VUHL9TiSqvDZbEZK:bdkqdhe) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L241)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done. Yes once #207 is merged, I will again re-request a review for this and fix the merge conflicts
</blockquote></details>

Why did you say "done" then? It's not done.
___
*[`gsc.py` line 268 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222YGPAahJnpVuvou9:-O24VlSc1qHLRSjXCp5c:bfhqml6) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L268)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.


<!-- Sent from Reviewable.io -->

2024-07-19 05:09 UTC, adarshan-intel commented
*[`gsc.py` line 268 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222YGPAahJnpVuvou9:-O28O7pTBkIfFr4uPbm_:b-ak64rj) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done. Sorry my bad.


<!-- Sent from Reviewable.io -->

2024-07-19 05:09 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[`gsc.py` line 241 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222pja-zC8vwjHLOmF:-O28OFiC5OgavXP9kpW-:bis536w) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L241)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why did you say "done" then? It's not done.
</blockquote></details>

Yes I mean this is the only thing pending here. 


<!-- Sent from Reviewable.io -->

2024-07-21 19:09 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 7 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel, @dimakuv, and @jkr0103)

___
*[`config.yaml.template` line 10 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222dFsD0upI6If3lN_:-O2LfosI4IE8fwwkP4tr:bih659u) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/config.yaml.template#L10)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

When specifying a custom distribution name in config.yaml (not auto), it's crucial to use the full path `quay.io/centos/centos:stream9`. 

Merely using `centos:stream9` as distro in the config.yaml file will not function correctly.

 I attempted to modify the code so that entering `centos:stream9` would default to pulling from `quay.io/centos/centos:stream9`, but this did not work when building the base Gramine docker image. 

Therefore, this ensures users input the complete path. Although the process works correctly when 'auto' is entered as a distro as the logic is implemented to pull from quay.io
</blockquote></details>

If specifying `centos:stream9` doesn't work then we should just list `quay.io/centos/centos:stream9` instead, not `centos:stream9`.


<!-- Sent from Reviewable.io -->

2024-07-22 04:33 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: 6 of 8 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @jkr0103, and @mkow)

___
*[`config.yaml.template` line 10 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222dFsD0upI6If3lN_:-O2Nhg38AU_Rv9OMU7s7:bdarrjx) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/config.yaml.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If specifying `centos:stream9` doesn't work then we should just list `quay.io/centos/centos:stream9` instead, not `centos:stream9`.
</blockquote></details>

Done. 7e2438e2d0dc91c89282d732fc9fda035e0af13b


<!-- Sent from Reviewable.io -->

2024-07-29 10:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @jkr0103 and @mkow)

___
*[`gsc.py` line 241 at r10](https://reviewable.io/reviews/gramineproject/gsc/206#-O222pja-zC8vwjHLOmF:-O2y4G2dEmzFRr35G5u0:b-qzhozk) ([raw file](https://github.com/gramineproject/gsc/blob/34bea1ef25b9eed2368ccc0f12e0005f08221c99/gsc.py#L241)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Yes I mean this is the only thing pending here.
</blockquote></details>

https://github.com/gramineproject/gsc/pull/207 -- it was merged, @adarshan-intel please rebase.


<!-- Sent from Reviewable.io -->

2024-07-29 23:58 UTC, mkow requested changes
> Reviewed 3 of 6 files at r7, 2 of 2 files at r9, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel and @jkr0103)

___
*[`gsc.py` line 248 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-sxelABKatlSAzLjU:-O3-si61Ctm3K0UJnUrN:bgrc4gu) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L248)):*
> ```Python
> 
> def template_path(distro):
>     if distro.startswith("quay.io/centos/centos"):
> ```

Why not `==`? What values are you expecting here?



_Suggestion:_
```Python
if distro.startswith("quay.io/centos/centos:"):
```
___
*[`gsc.py` line 249 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-t3Q15bECSKzmHy_B:-O3-t3Q15bECSKzmHy_C:bpf48j0) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L249)):*
> ```Python
> def template_path(distro):
>     if distro.startswith("quay.io/centos/centos"):
>         return "centos/stream"
> ```

ditto for the whole PR



_Suggestion:_
```Python
return 'centos/stream'
```


<!-- Sent from Reviewable.io -->

2024-07-30 05:07 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @mkow)

___
*[`gsc.py` line 248 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-sxelABKatlSAzLjU:-O31183XDk2Eq1ZxictB:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L248)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why not `==`? What values are you expecting here?
</blockquote></details>

Done.
___
*[`gsc.py` line 249 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-t3Q15bECSKzmHy_B:-O311A2C6h9ZxuAZZL7B:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L249)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto for the whole PR
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-30 05:22 UTC, adarshan-intel commented
*[`gsc.py` line 248 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-sxelABKatlSAzLjU:-O313XIE219sbUCDOb5D:b3xycpf) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L248)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The colon (`:`) will not be used because in the function `template_path`, we are splitting the distro based on `:` in `fetch_and_validate_distro_support`. Therefore, using colon in the `template_path` function as you suggested would result in an error as distro becomes exactly `quay.io/centos/centos`


<!-- Sent from Reviewable.io -->

2024-08-02 08:19 UTC, adarshan-intel reviewed
@dimakuv @mkow Can you review this again ?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206#-:-O3HA0gp0rDeYGqFXcMw:b-kmhbwu)* status: 7 of 8 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @jkr0103 and @mkow)



<!-- Sent from Reviewable.io -->

2024-08-04 18:49 UTC, mkow requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel and @jkr0103)

___
*[`gsc.py` line 248 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-sxelABKatlSAzLjU:-O3Ti7INC2Bm5yLN4PEH:bytht1v) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L248)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

The colon (`:`) will not be used because in the function `template_path`, we are splitting the distro based on `:` in `fetch_and_validate_distro_support`. Therefore, using colon in the `template_path` function as you suggested would result in an error as distro becomes exactly `quay.io/centos/centos`
</blockquote></details>

Ok, right, but what about the rest of my comment?


<!-- Sent from Reviewable.io -->

2024-08-05 04:09 UTC, adarshan-intel commented
*[`gsc.py` line 248 at r14](https://reviewable.io/reviews/gramineproject/gsc/206#-O3-sxelABKatlSAzLjU:-O3ViEPh4OF8lEQs9ut7:b-bokz53) ([raw file](https://github.com/gramineproject/gsc/blob/c0b7b568082a97b8a92518a3ec0709bb88c0d8e7/gsc.py#L248)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, right, but what about the rest of my comment?
</blockquote></details>

Done, made `==` comparison


<!-- Sent from Reviewable.io -->

2024-08-05 10:41 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2024-08-05 11:02 UTC, adarshan-intel commented
@dimakuv @jkr0103 can you approve this?





<!-- Sent from Reviewable.io -->

2024-08-05 13:49 UTC, kailun-qin approved these changes
> Reviewed 3 of 6 files at r7, 2 of 2 files at r9, 2 of 3 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2024-08-05 14:51 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jkr0103)



<!-- Sent from Reviewable.io -->

2024-08-05 18:12 UTC, merged

2024-08-06 05:53 UTC, jkr0103 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 6 files at r7, 2 of 2 files at r9, 2 of 3 files at r14, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/206#-:-O3aEmu86GGPRKBCdwDc:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->