Add support for ubi9, ubi9-minimal
gramineproject/gsc pull request #207
Opened 2024-07-03 12:04 UTC by adarshan-intel

## Description of the changes 
Add support for ubi9, ubi9-minimal

## How to test this PR? 

To test this PR, set follow similar procedure as followed with Ubuntu and do gsc build and signing commands.

2024-07-03 12:07 UTC, adarshan-intel commented
@jkr0103 and @anjalirai-intel Please review

2024-07-05 06:57 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 0 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 291 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fHJW2iiTc_eD2bMY:-O10fHJW2iiTc_eD2bMZ:b-i2iaop) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L291)):*
> ```Python
>     else:
>         if not os.path.exists(f'templates/{distro}'):
>             raise FileNotFoundError(f'`{distro}` distro is not supported by GSC.')
> ```

Why do you need this if-else? Your `get_formatted_redhat_repo()` function already has the `else` clause which correctly captures all non-RedHat distributions. So you can simplify to this:
```
    if not os.path.exists(f'templates/{get_formatted_redhat_repo(distro)}'):
        raise FileNotFoundError(f'`{distro}` distro is not supported by GSC.')
```
___
*[`gsc.py` line 351 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10faBPBWTc_CbfDx8h:-O10faBPBWTc_CbfDx8i:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L351)):*
> ```Python
>         compile_template = env.get_template(f'{get_formatted_redhat_repo(distro)}/Dockerfile.compile.template')
>     else:
>         compile_template = env.get_template(f'{distro}/Dockerfile.compile.template')
> ```

ditto
___
*[`gsc.py` line 360 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fbcfD3qfv5Yn71Wj:-O10fbcfD3qfv5Yn71Wk:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L360)):*
> ```Python
>         build_template = env.get_template(f'{get_formatted_redhat_repo(distro)}/Dockerfile.build.template')
>     else:
>         build_template = env.get_template(f'{distro}/Dockerfile.build.template')
> ```

ditto
___
*[`gsc.py` line 369 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fcHMDutV_GyadGxp:-O10fcHMDutV_GyadGxq:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L369)):*
> ```Python
>         apploader_template = env.get_template(f'{get_formatted_redhat_repo(distro)}/apploader.template')
>     else:
>         apploader_template = env.get_template(f'{distro}/apploader.template')
> ```

ditto
___
*[`gsc.py` line 381 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fd0J-W9M4BAGs7Ox:-O10fd0J-W9M4BAGs7Oy:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L381)):*
> ```Python
>         entrypoint_manifest_name = f'{get_formatted_redhat_repo(distro)}/entrypoint.manifest.template'
>     else:
>         entrypoint_manifest_name = f'{distro}/entrypoint.manifest.template'
> ```

ditto
___
*[`gsc.py` line 542 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fdvH24ZrtKpOIBDQ:-O10fdvH24ZrtKpOIBDR:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L542)):*
> ```Python
>         sign_template = env.get_template(f'{get_formatted_redhat_repo(distro)}/Dockerfile.sign.template')
>     else:
>         sign_template = env.get_template(f'{distro}/Dockerfile.sign.template')
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-07-05 09:10 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 0 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 291 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fHJW2iiTc_eD2bMY:-O117p36AamomHoB1BCE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L291)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you need this if-else? Your `get_formatted_redhat_repo()` function already has the `else` clause which correctly captures all non-RedHat distributions. So you can simplify to this:
```
    if not os.path.exists(f'templates/{get_formatted_redhat_repo(distro)}'):
        raise FileNotFoundError(f'`{distro}` distro is not supported by GSC.')
```
</blockquote></details>

Done.
___
*[`gsc.py` line 351 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10faBPBWTc_CbfDx8h:-O1198se-fPG7k7D40Z9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L351)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gsc.py` line 360 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fbcfD3qfv5Yn71Wj:-O1199ZP6rWASKfRQyX6:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L360)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gsc.py` line 369 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fcHMDutV_GyadGxp:-O1199tD8VHb9dBPwLtv:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L369)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gsc.py` line 381 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fd0J-W9M4BAGs7Ox:-O119ABL6gYpbeRyMRkF:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L381)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gsc.py` line 542 at r2](https://reviewable.io/reviews/gramineproject/gsc/207#-O10fdvH24ZrtKpOIBDQ:-O119Aga4KlZsc9qr6F-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0919812e04cb88614f34af5b10ab674ede33b6b2/gsc.py#L542)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 06:55 UTC, dimakuv reviewed
> Reviewed 1 of 13 files at r1, 20 of 22 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @adarshan-intel)

___
*[`gsc.py` line 246 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G4-lm5_TQBgbELKi3:-O1G4-lm5_TQBgbELKi4:b-ndp8u3) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/gsc.py#L246)):*
> ```Python
>         shutil.copytree(sslclientkey_dir, tmp_build_path / 'pki/entitlement')
> 
> def get_formatted_redhat_repo(distro):
> ```

This function name is misleading. What we want is to "return the template directory based on the OS distro name". Also, this function works on all OS distros, not only RedHat. So I suggest:
```
def template_path(distro):
```
___
*[`gsc.py` line 252 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G3p2K38pq_C7lVDNV:-O1G3p2K38pq_C7lVDNW:b-kmvew5) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/gsc.py#L252)):*
> ```Python
>         return "redhat/ubi-minimal"
>     else:
>         return distro
> ```

There's no need for an `else` here, you can simplify to:
```
    if distro in {"redhat/ubi8", "redhat/ubi9"}:
        return "redhat/ubi"
    if distro in {"redhat/ubi8-minimal", "redhat/ubi9-minimal"}:
        return "redhat/ubi-minimal"
    return distro
```
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 13 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5JJcAZ7k9pVb3eK-:-O1G5JJd5peGbcsoLp87:b5fw7ix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi/Dockerfile.build.template#L13)):*
> ```
> # final image. This trick allows to decrease the image size by hundreds of MBs.
> RUN rm -rf /etc/rhsm-host \
>     {%- if distro[0] == "redhat/ubi9" %}
> ```

Why not do something like
```
{% set ver = distro.split('ubi')[1] %}
    && subscription-manager repos --enable codeready-builder-for-rhel-{{ver}}-x86_64-rpms \
    && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ver}}.noarch.rpm \
```

This way, you won't need the `{%- if ...` clauses, and you won't have repetitive commands
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 11 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5vMd1Dpsx4T6_H3v:-O1G5vMd1Dpsx4T6_H3w:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi/Dockerfile.compile.template#L11)):*
> ```
> # NOTE: meson v1.2.* has a bug that leads to Gramine build failure because of not found `libcurl.a`
> RUN rm -rf /etc/rhsm-host \
>     {%- if distro[0] == "redhat/ubi9" %}
> ```

ditto
___
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 14 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5yCz-PQAExS09w4E:-O1G5yCz-PQAExS09w4F:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi-minimal/Dockerfile.build.template#L14)):*
> ```
> RUN rm -rf /etc/rhsm-host \
>     && microdnf install -y subscription-manager \
>     {%- if distro[0] == "redhat/ubi9-minimal" %}
> ```

ditto
___
*[`templates/redhat/ubi-minimal/Dockerfile.compile.template` line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5zUI3bglZwvz2Lti:-O1G5zUI3bglZwvz2Ltj:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi-minimal/Dockerfile.compile.template#L12)):*
> ```
> RUN rm -rf /etc/rhsm-host \
>     && microdnf install -y subscription-manager \
>     {%- if distro[0] == "redhat/ubi9-minimal" %}
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-07-08 08:18 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 17 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 246 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G4-lm5_TQBgbELKi3:-O1GC8U0B1TcmEhi9myJ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/gsc.py#L246)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This function name is misleading. What we want is to "return the template directory based on the OS distro name". Also, this function works on all OS distros, not only RedHat. So I suggest:
```
def template_path(distro):
```
</blockquote></details>

Done.
___
*[`gsc.py` line 252 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G3p2K38pq_C7lVDNV:-O1GC9-TD_B0lqYHTiAQ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/gsc.py#L252)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

There's no need for an `else` here, you can simplify to:
```
    if distro in {"redhat/ubi8", "redhat/ubi9"}:
        return "redhat/ubi"
    if distro in {"redhat/ubi8-minimal", "redhat/ubi9-minimal"}:
        return "redhat/ubi-minimal"
    return distro
```
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 13 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5JJcAZ7k9pVb3eK-:-O1GCo_7DM0WBQ1lGU58:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi/Dockerfile.build.template#L13)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not do something like
```
{% set ver = distro.split('ubi')[1] %}
    && subscription-manager repos --enable codeready-builder-for-rhel-{{ver}}-x86_64-rpms \
    && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ver}}.noarch.rpm \
```

This way, you won't need the `{%- if ...` clauses, and you won't have repetitive commands
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 11 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5vMd1Dpsx4T6_H3v:-O1GCztK5RxE_Nd1XLGH:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi/Dockerfile.compile.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 14 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5yCz-PQAExS09w4E:-O1GL-di1tKMynibbT1Q:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi-minimal/Dockerfile.build.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`templates/redhat/ubi-minimal/Dockerfile.compile.template` line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5zUI3bglZwvz2Lti:-O1GL0BgAR6dQ8GLtlS7:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/57feb64f5f4777f5e16c65a662f6e72433b8b82a/templates/redhat/ubi-minimal/Dockerfile.compile.template#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-08 10:36 UTC, adarshan-intel commented
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/207#-O1GgHhMB0VG2AV9Szyh:-O1GuWwtE4dLZoIJBkHu:b-bjdypg) ([raw file](https://github.com/gramineproject/gsc/blob/64b3438d5fda212ec6044ec87fe7a6f8f693fc4f/templates/redhat/ubi-minimal/Dockerfile.build.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Note for other reviewers: this is a smart trick for splitting UBI-minimal. Note how `-` is used as a separator instead of `:` for UBI. That's because we need to extract the major version, and the distro name for UBI-minimal is `redhat/ubi9-minimal:9.4`. Whereas for UBI it is `redhat/ubi9:9.4`.
</blockquote></details>

Thanks, this was the easier solution 


<!-- Sent from Reviewable.io -->

2024-07-08 10:37 UTC, adarshan-intel commented
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR looks good to me. Waiting for reviews from others.

TODO for myself: need to test it when all reviews are done.
</blockquote></details>

Thanks




<!-- Sent from Reviewable.io -->

2024-07-09 09:45 UTC, jkr0103 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`gsc.py` line 193 at r4](https://reviewable.io/reviews/gramineproject/gsc/207#-O1LrIaLDxjDrS4xYE4u:-O1LrIaLDxjDrS4xYE4v:b1tbnqt) ([raw file](https://github.com/gramineproject/gsc/blob/64b3438d5fda212ec6044ec87fe7a6f8f693fc4f/gsc.py#L193)):*
> ```Python
> 
> def handle_redhat_repo_configs(distro, tmp_build_path):
>     if distro in {"redhat/ubi8", "redhat/ubi8-minimal"}:
> ```

How we made same templates work for `ubi8`, `ubi9` which might work for `ubi10` also. Can we have similar approach here, this code won't work for `ubi10` if we get in near future. You could try some regex to retrieve `version_id`. WE won't need multiple `if else` clauses.
___
*[`gsc.py` line 247 at r4](https://reviewable.io/reviews/gramineproject/gsc/207#-O1Ls3RoASpLUWo3PRuq:-O1Ls3RoASpLUWo3PRur:b-txydkl) ([raw file](https://github.com/gramineproject/gsc/blob/64b3438d5fda212ec6044ec87fe7a6f8f693fc4f/gsc.py#L247)):*
> ```Python
> 
> def template_path(distro):
>     if distro in {"redhat/ubi8", "redhat/ubi9"}:
> ```

You could use regex to make this code generic to work for future versions like `ubi10`.


<!-- Sent from Reviewable.io -->

2024-07-09 16:54 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 22 of 23 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 193 at r4](https://reviewable.io/reviews/gramineproject/gsc/207#-O1LrIaLDxjDrS4xYE4u:-O1NOwLT-S_cGaFfj9Xf:bthttos) ([raw file](https://github.com/gramineproject/gsc/blob/64b3438d5fda212ec6044ec87fe7a6f8f693fc4f/gsc.py#L193)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

How we made same templates work for `ubi8`, `ubi9` which might work for `ubi10` also. Can we have similar approach here, this code won't work for `ubi10` if we get in near future. You could try some regex to retrieve `version_id`. WE won't need multiple `if else` clauses.
</blockquote></details>

Done
Single check for redhat_repos
```
if not distro.startswith("redhat/ubi"):
    return
```
Regex for version ID

```
version_id = re.search(r'\d+', distro).group()
```
___
*[`gsc.py` line 247 at r4](https://reviewable.io/reviews/gramineproject/gsc/207#-O1Ls3RoASpLUWo3PRuq:-O1NPXzs2XUX2hR_maF1:baxvxw4) ([raw file](https://github.com/gramineproject/gsc/blob/64b3438d5fda212ec6044ec87fe7a6f8f693fc4f/gsc.py#L247)):*
<details><summary><i>Previously, jkr0103 (Jitender Kumar) wrote…</i></summary><blockquote>

You could use regex to make this code generic to work for future versions like `ubi10`.
</blockquote></details>

Done, This ensures the generic functionality
```
def template_path(distro):
    if distro.startswith("redhat/ubi"):
        if "minimal" in distro:
            return "redhat/ubi-minimal"
        return "redhat/ubi"
    return distro
```


<!-- Sent from Reviewable.io -->

2024-07-10 06:36 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-11 06:19 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-15 11:06 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`templates/redhat/ubi/Dockerfile.sign.template` line 1 at r6](https://reviewable.io/reviews/gramineproject/gsc/207#-O1q3dhO1hzynTsmsYnb:-O1q3dhO1hzynTsmsYnc:b-hhs3c6) ([raw file](https://github.com/gramineproject/gsc/blob/f766e38be9eadd3793caf5fc08ccbb55455bdee0/templates/redhat/ubi/Dockerfile.sign.template#L1)):*
> ```
> {% extends "centos/Dockerfile.sign.template" %}
> ```

I think this is wrong? You should extend from the "common" sign template:
```
{% extends "Dockerfile.common.sign.template" %}
```
___
*[`templates/redhat/ubi/Dockerfile.sign.template` line 11 at r6](https://reviewable.io/reviews/gramineproject/gsc/207#-O1q36uk7TzEZwRD0NR2:-O1q36ul8TCatWCykqP_:bd1loi1) ([raw file](https://github.com/gramineproject/gsc/blob/f766e38be9eadd3793caf5fc08ccbb55455bdee0/templates/redhat/ubi/Dockerfile.sign.template#L11)):*
> ```
>           tomli tomli-w \
>        && dnf remove -y \
>           binutils \
> ```

Why do you have `binutils` removed here (in the `ubi` version) but not in the `ubi-minimal` version?
___
*[`templates/redhat/ubi-minimal/Dockerfile.sign.template` line 19 at r6](https://reviewable.io/reviews/gramineproject/gsc/207#-O1q3Ora-czK4n8hSa_L:-O1q3Ora-czK4n8hSa_M:bhi9960) ([raw file](https://github.com/gramineproject/gsc/blob/f766e38be9eadd3793caf5fc08ccbb55455bdee0/templates/redhat/ubi-minimal/Dockerfile.sign.template#L19)):*
> ```
> {% endblock %}
> 
> {% block path %}export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib64 -type d -path '*/site-packages')" &&{% endblock %}
> ```

Why do you have `export PYTHONPATH` here (in the `ubi-minimal` version) but not in the `ubi` version?


<!-- Sent from Reviewable.io -->

2024-07-15 11:16 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`templates/redhat/ubi/Dockerfile.sign.template` line 1 at r6](https://reviewable.io/reviews/gramineproject/gsc/207#-O1q3dhO1hzynTsmsYnb:-O1q4hT49MgPWuKBmjyV:b-gjaxce) ([raw file](https://github.com/gramineproject/gsc/blob/f766e38be9eadd3793caf5fc08ccbb55455bdee0/templates/redhat/ubi/Dockerfile.sign.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this is wrong? You should extend from the "common" sign template:
```
{% extends "Dockerfile.common.sign.template" %}
```
</blockquote></details>

Well actually both are correct I am just updating the uninstall block here. Ok I can change it to
 ```
{% extends "Dockerfile.common.sign.template" %}
```
___
*[`templates/redhat/ubi/Dockerfile.sign.template` line 11 at r6](https://reviewable.io/reviews/gramineproject/gsc/207#-O1q36uk7TzEZwRD0NR2:-O1q5FnS-uu2Yzfbuuod:b-5bur90) ([raw file](https://github.com/gramineproject/gsc/blob/f766e38be9eadd3793caf5fc08ccbb55455bdee0/templates/redhat/ubi/Dockerfile.sign.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `binutils` removed here (in the `ubi` version) but not in the `ubi-minimal` version?
</blockquote></details>

There is a problem with binutils package removal as it is one of the prerequisites of binutils-gold package

[binutils-gold-2.41-45.el10.x86\_64 RPM (rpmfind.net)](https://rpmfind.net/linux/RPM/centos-stream/10/baseos/x86_64/binutils-gold-2.41-45.el10.x86_64.html)

Looking at the required section, we see we need the binutil package.
___
*[`templates/redhat/ubi-minimal/Dockerfile.sign.template` line 19 at r6](https://reviewable.io/reviews/gramineproject/gsc/207#-O1q3Ora-czK4n8hSa_L:-O1q51qO84z47Z96ECN2:bvpgck7) ([raw file](https://github.com/gramineproject/gsc/blob/f766e38be9eadd3793caf5fc08ccbb55455bdee0/templates/redhat/ubi-minimal/Dockerfile.sign.template#L19)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you have `export PYTHONPATH` here (in the `ubi-minimal` version) but not in the `ubi` version?
</blockquote></details>

Because it was extended to Centos version template and `PYTHONPATH` is exported automatically . Again, changing it to common template.


<!-- Sent from Reviewable.io -->

2024-07-15 11:22 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-16 02:48 UTC, adarshan-intel commented
>  There is an option in gsc where you can just build gramine, and build workload image later, When I tried to build just gramine, it failed with error distro is not supported by GSC

>  Config.yaml
  Distro: "redhat/ubi9:9.4"

  > Steps to Reproduce
  ./gsc build-gramine bash_test
  Building base-Gramine Docker image `bash_test`...
  redhat/ubi9 distro is not supported by GSC.

The latest commits are addressing that issue. - https://github.com/gramineproject/gsc/pull/207/commits/747a51a71f2955dba74177d8c34b481c9f70c20e

2024-07-16 06:51 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-17 14:59 UTC, jkr0103 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207#-:-O20CF2V2vta8vrSUTIO:bnfp4nl)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-17 23:34 UTC, mkow requested changes
> Reviewed 1 of 13 files at r1, 14 of 22 files at r2, 5 of 6 files at r4, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 193 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21sGD_49d_Wao3rqt5:-O21sGDa9UNiCU-FUuqE:b-k26096) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L193)):*
> ```Python
> 
> def handle_redhat_repo_configs(distro, tmp_build_path):
>     if not distro.startswith("redhat/ubi"):
> ```

This should be more future-proof.



_Suggestion:_
```Python
if not distro.startswith("redhat/"):
```
___
*[`gsc.py` line 196 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21tXbL0TQQJ8fIYQol:-O21tXbL0TQQJ8fIYQom:b-6o8wzf) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L196)):*
> ```Python
>         return
> 
>     version_id = re.search(r'\d+', distro).group()
> ```

Please change it to a proper, full pattern, so we get a loud error if someone adds a redhat distro with a slightly different name format (instead of treating a random number from it as its version).



_Code quote:_
```Python
r'\d+'
```
___
*[`gsc.py` line 197 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21uC6V02cF-vDD2jCL:-O21uC6V02cF-vDD2jCM:bn0rpbm) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L197)):*
> ```Python
> 
>     version_id = re.search(r'\d+', distro).group()
>     repo_name = f"rhel-{version_id}-for-x86_64-baseos-rpms"
> ```

I know it was like that before, but please fix it while we're here.



_Suggestion:_
```Python
repo_name = f'rhel-{version_id}-for-x86_64-baseos-rpms'
```
___
*[`gsc.py` line 244 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21v0Kt0LzauxhAnKZh:-O21v0Kt0LzauxhAnKZi:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L244)):*
> ```Python
> 
> def template_path(distro):
>     if distro.startswith("redhat/ubi"):
> ```

ditto
___
*[`gsc.py` line 244 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21v8Ts9mswmca1OPLX:-O21v8Ts9mswmca1OPLY:blc0biu) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L244)):*
> ```Python
> 
> def template_path(distro):
>     if distro.startswith("redhat/ubi"):
> ```

All string should be in single quotes, please fix the whole PR.
___
*[`gsc.py` line 268 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wBAG5sMvZSFlE4al:-O21wBAG5sMvZSFlE4am:b-1i1j4a) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L268)):*
> ```Python
>         try:
>             docker_socket.containers.run(image_name, entrypoint='ls /usr/bin/microdnf', remove=True)
>             distro = f'redhat/ubi{version_id.split(".")[0]}-minimal:{version_id}'
> ```

The code joins `version_id` a few lines above, just to split it again here. Please remove that and only join inside the trailing term here.
___
*[`gsc.py` line 270 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wdZxDHUGOoJLXndz:-O21wdZxDHUGOoJLXne-:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L270)):*
> ```Python
>             distro = f'redhat/ubi{version_id.split(".")[0]}-minimal:{version_id}'
>         except docker.errors.ContainerError:
>             distro = f'redhat/ubi{version_id.split(".")[0]}:{version_id}'
> ```

ditto
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-DqX1wwG6nS3f_eh:-O22-DqX1wwG6nS3f_ei:b15d9zw) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.build.template#L5)):*
> ```
> {% block install %}
> {% set distro = Distro.split(':')[0] %}
> {% set ver = distro.split('ubi')[1] %}
> ```

Please parse this more carefully.



_Code quote:_
```
distro.split('ubi')
```
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-a9i2lvZnFyKePK-:-O22-a9i2lvZnFyKePK0:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.compile.template#L5)):*
> ```
> {% block install %}
> {% set distro = Distro.split(':')[0] %}
> {% set ver = distro.split('ubi')[1] %}
> ```

ditto
___
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O220hza2N5KWCjGV9E3:-O220hza2N5KWCjGV9E4:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi-minimal/Dockerfile.build.template#L5)):*
> ```
> {% block install %}
> {% set distro = Distro.split('-')[0] %}
> {% set ver = distro.split('ubi')[1] %}
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-07-18 05:38 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 22 of 23 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`gsc.py` line 193 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21sGD_49d_Wao3rqt5:-O230-QdAGr85srbGoCd:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L193)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This should be more future-proof.
</blockquote></details>

Done.
___
*[`gsc.py` line 196 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21tXbL0TQQJ8fIYQol:-O23JL187oOw_MaoE7wD:b-dkprma) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L196)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please change it to a proper, full pattern, so we get a loud error if someone adds a redhat distro with a slightly different name format (instead of treating a random number from it as its version).
</blockquote></details>

I'm using regular expressions to validate and parse the `distro` string in this code snippet to ensure it follows the expected Red Hat distribution format. If a match is found, I extract the version number from the `distro` string to construct the repository name in a specific format. It is a stronger match



_Code snippet:_
```Python

    version_id_match = re.search(r'^redhat/(ubi\d+|ubi\d+-minimal)$', distro)
    if version_id_match:
        version_id = re.search(r'\d+', version_id_match.group(1)).group(0)
        repo_name = f'rhel-{version_id}-for-x86_64-baseos-rpms'
    else:
        raise ValueError(f'Invalid Red Hat distro format: {distro}')
```
___
*[`gsc.py` line 197 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21uC6V02cF-vDD2jCL:-O2309CO9MQ7nVRR2lhX:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I know it was like that before, but please fix it while we're here.
</blockquote></details>

Done.
___
*[`gsc.py` line 244 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21v0Kt0LzauxhAnKZh:-O230TlY5fQ2ENrkE41K:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L244)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`gsc.py` line 244 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21v8Ts9mswmca1OPLX:-O230yT68OVjluCT3ghg:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L244)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

All string should be in single quotes, please fix the whole PR.
</blockquote></details>

Done.
___
*[`gsc.py` line 268 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wBAG5sMvZSFlE4al:-O23CyuGEn8VIi6WNRwS:b-2srqsb) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

The code joins `version_id` a few lines above, just to split it again here. Please remove that and only join inside the trailing term here.
</blockquote></details>

I need access to both version_id which is 9.4 and also need to extract 9 out of it for image name of redhat/ubi9. Final image name is 
redhat/ubi9-minimal:9.4 or redhat/ubi9:9.4. One change I can do is
Please suggest any alternatives, if any.



_Code snippet:_
```Python
if (os_release['ID'] == 'rhel'):
        ubi_version = version_id.split(".")[0]
        try:
            docker_socket.containers.run(image_name, entrypoint='ls /usr/bin/microdnf', remove=True)
            distro = f'redhat/ubi-minimal{ubi_version}:{version_id}'
        except docker.errors.ContainerError:
            distro = f'redhat/ubi{ubi_version}:{version_id}'
```
___
*[`gsc.py` line 270 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wdZxDHUGOoJLXndz:-O23DU-B9TftQ0BLKRzK:b-qhha9b) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L270)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. ditto
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-DqX1wwG6nS3f_eh:-O23DwXh6I_QmeuLlFx5:b-at1hh0) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please parse this more carefully.
</blockquote></details>

All the image names of ubi distros are in the format redhat/ubi9:9.4. Distro=redhat/ubi9:9.4.
distro=redhat/ubi9 
ver=9. 
I believe this step is correct given all the images are of the above format. 
Please suggest any alternatives, if any.
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-a9i2lvZnFyKePK-:-O23EREl39ZkrdrymA0Y:b-qhha9b) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.compile.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. ditto
___
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O220hza2N5KWCjGV9E3:-O23ESss7btLNBbjMjdq:b-qhha9b) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi-minimal/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. ditto


<!-- Sent from Reviewable.io -->

2024-07-18 11:19 UTC, mkow requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 193 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21sGD_49d_Wao3rqt5:-O24Wheb0d-2FVdCrfNr:bfhqml6) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L193)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`gsc.py` line 268 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wBAG5sMvZSFlE4al:-O24YQdNDS_eATtl9EKq:bodu4zb) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L268)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I need access to both version_id which is 9.4 and also need to extract 9 out of it for image name of redhat/ubi9. Final image name is 
redhat/ubi9-minimal:9.4 or redhat/ubi9:9.4. One change I can do is
Please suggest any alternatives, if any.
</blockquote></details>

Please read my comment carefully, I described exactly what to do.
___
*[`gsc.py` line 196 at r9](https://reviewable.io/reviews/gramineproject/gsc/207#-O24XUjU7ZwoE4ksbYYr:-O24XUjU7ZwoE4ksbYYs:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/ade258d6ef2e81082d99105f5b556bc272f5d774/gsc.py#L196)):*
> ```Python
>         return
> 
>     version_id_match = re.search(r'^redhat/(ubi\d+|ubi\d+-minimal)$', distro)
> ```





_Suggestion:_
```Python
version_id_match = re.search(r'^redhat/ubi(\d+)(-minimal)?$', distro)
```
___
*[`gsc.py` line 198 at r9](https://reviewable.io/reviews/gramineproject/gsc/207#-O24Y-W-119fnoG9KdQq:-O24Y-W-119fnoG9KdQr:b-tug02o) ([raw file](https://github.com/gramineproject/gsc/blob/ade258d6ef2e81082d99105f5b556bc272f5d774/gsc.py#L198)):*
> ```Python
>     version_id_match = re.search(r'^redhat/(ubi\d+|ubi\d+-minimal)$', distro)
>     if version_id_match:
>         version_id = re.search(r'\d+', version_id_match.group(1)).group(0)
> ```

This won't be needed if you fix the original regex.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-DqX1wwG6nS3f_eh:-O24Z1_6Awlofp4TtAp2:b-xn7pg5) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

All the image names of ubi distros are in the format redhat/ubi9:9.4. Distro=redhat/ubi9:9.4.
distro=redhat/ubi9 
ver=9. 
I believe this step is correct given all the images are of the above format. 
Please suggest any alternatives, if any.
</blockquote></details>

Please do a more careful parsing, same as in the other discussion above.


<!-- Sent from Reviewable.io -->

2024-07-19 08:05 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 22 of 23 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`gsc.py` line 193 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21sGD_49d_Wao3rqt5:-O28QN7I-UpE7-girn57:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L193)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.
___
*[`gsc.py` line 268 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wBAG5sMvZSFlE4al:-O28_whs80epvNnFPuNu:b-jyat5s) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please read my comment carefully, I described exactly what to do.
</blockquote></details>


I cannot remove the above join operation for the version id due to this comment.
```
# Some OS distros (e.g. Alpine) have very precise versions (e.g. 3.17.3), and to support these
# OS distros, we need to truncate at the 2nd dot.
version_id = '.'.join(os_release['VERSION_ID'].split(".", 2)[:2])
```

After this the version_id becomes 9.4 (for redhat/ubi9:9.4 distro)

We need to perform another split to get ubi_version to be 9. 
Please clarify since I am not understanding what is the issue here or suggest code changes.
___
*[`gsc.py` line 196 at r9](https://reviewable.io/reviews/gramineproject/gsc/207#-O24XUjU7ZwoE4ksbYYr:-O28OrXJDlFNBVtmD0ap:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/ade258d6ef2e81082d99105f5b556bc272f5d774/gsc.py#L196)):*
> ```Python
>         return
> 
>     version_id_match = re.search(r'^redhat/(ubi\d+|ubi\d+-minimal)$', distro)
> ```

Done.
___
*[`gsc.py` line 198 at r9](https://reviewable.io/reviews/gramineproject/gsc/207#-O24Y-W-119fnoG9KdQq:-O28Q_6E3WEDUgdjDvU0:b-rhhonc) ([raw file](https://github.com/gramineproject/gsc/blob/ade258d6ef2e81082d99105f5b556bc272f5d774/gsc.py#L198)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This won't be needed if you fix the original regex.
</blockquote></details>

Done. 
Yes fixing the above regex then doing this works



_Code snippet:_
```Python
version_id = version_id_match.group(1)
```
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-DqX1wwG6nS3f_eh:-O28W4YL3ayuXwvRLVgL:bqj4svu) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please do a more careful parsing, same as in the other discussion above.
</blockquote></details>

This parsing has been done according to what was suggested by @dimakuv 
Link to the discussion here - [templates/redhat/ubi/Dockerfile.build.template line 13 at r3 (reviewable.io)](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5JJcAZ7k9pVb3eK-:-O1G5JJd5peGbcsoLp87:b5fw7ix)

Please link the discussion that you are referring to.


<!-- Sent from Reviewable.io -->

2024-07-21 18:42 UTC, mkow requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`gsc.py` line 268 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wBAG5sMvZSFlE4al:-O2L_8VL89QZtWzQF-tZ:b-q3vcaz) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L268)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I cannot remove the above join operation for the version id due to this comment.
```
# Some OS distros (e.g. Alpine) have very precise versions (e.g. 3.17.3), and to support these
# OS distros, we need to truncate at the 2nd dot.
version_id = '.'.join(os_release['VERSION_ID'].split(".", 2)[:2])
```

After this the version_id becomes 9.4 (for redhat/ubi9:9.4 distro)

We need to perform another split to get ubi_version to be 9. 
Please clarify since I am not understanding what is the issue here or suggest code changes.
</blockquote></details>

Something like that:



_Suggestion:_
```Python
    if 'ID' not in os_release or 'VERSION_ID' not in os_release:
        raise DistroRetrievalError

    version_str = os_release['VERSION_ID']
    version = version_str.split('.')
    if os_release['ID'] == 'rhel':
        # RedHat specific logic to distinguish between UBI and UBI-minimal
        try:
            docker_socket.containers.run(image_name, entrypoint='ls /usr/bin/microdnf', remove=True)
        except docker.errors.ContainerError:
            distro = f'redhat/ubi{version[0]}:{version_str}'
        else:
            distro = f'redhat/ubi{version[0]}-minimal:{version_str}'
    else:
        # Some OS distros (e.g. Alpine) have very precise versions (e.g. 3.17.3), and to support these
        # OS distros, we need to truncate at the 2nd dot.
        distro = os_release['ID'] + ':' + '.'.join(version[:2])
```
___
*[`gsc.py` line 269 at r10](https://reviewable.io/reviews/gramineproject/gsc/207#-O2CBTU1EiLSba9VbAII:-O2CBTU1EiLSba9VbAIJ:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/b08676cbfae74bd393c16e7e1f0e50b5df404e92/gsc.py#L269)):*
> ```Python
> 
>     # RedHat specific logic to distinguish between UBI and UBI-minimal
>     if (os_release['ID'] == 'rhel'):
> ```





_Suggestion:_
```Python
    if os_release['ID'] == 'rhel':
```
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-DqX1wwG6nS3f_eh:-O2LaWvE1M6tK9pdULRu:b-m03hp7) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

This parsing has been done according to what was suggested by @dimakuv 
Link to the discussion here - [templates/redhat/ubi/Dockerfile.build.template line 13 at r3 (reviewable.io)](https://reviewable.io/reviews/gramineproject/gsc/207#-O1G5JJcAZ7k9pVb3eK-:-O1G5JJd5peGbcsoLp87:b5fw7ix)

Please link the discussion that you are referring to.
</blockquote></details>

https://reviewable.io/reviews/gramineproject/gsc/207#-O21tXbL0TQQJ8fIYQol


<!-- Sent from Reviewable.io -->

2024-07-22 07:18 UTC, adarshan-intel commented
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O22-DqX1wwG6nS3f_eh:-O2OIHn0CNU85nEw144C:bed0d4) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/templates/redhat/ubi/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/gramineproject/gsc/207#-O21tXbL0TQQJ8fIYQol
</blockquote></details>

Done.
Implemented the regex_match function to validate regular expressions across various templates.


<!-- Sent from Reviewable.io -->

2024-07-22 07:18 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 18 of 23 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`gsc.py` line 268 at r8](https://reviewable.io/reviews/gramineproject/gsc/207#-O21wBAG5sMvZSFlE4al:-O2Np-5DAk1B4yLXIq8Y:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/747a51a71f2955dba74177d8c34b481c9f70c20e/gsc.py#L268)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Something like that:
</blockquote></details>

Done.
___
*[`gsc.py` line 269 at r10](https://reviewable.io/reviews/gramineproject/gsc/207#-O2CBTU1EiLSba9VbAII:-O2NiJao5THXeMrWnera:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b08676cbfae74bd393c16e7e1f0e50b5df404e92/gsc.py#L269)):*
> ```Python
> 
>     # RedHat specific logic to distinguish between UBI and UBI-minimal
>     if (os_release['ID'] == 'rhel'):
> ```

Done.


<!-- Sent from Reviewable.io -->

2024-07-22 14:05 UTC, mkow requested changes
@adarshan-intel: FYI: You don't have to ping me each time you reply in the review, I get a notification when you reply.

> Reviewed 2 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207#-:-O2P6evR7wRqlxtBwGoi:bm5uzql)* status: 20 of 23 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`gsc.py` line 277 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2PkiaYC5vf3vvruhiE:-O2PkiaYC5vf3vvruhiF:b-n66qs2) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/gsc.py#L277)):*
> ```Python
>             distro = f'redhat/ubi{version[0]}-minimal:{version_str}'
>     else:
>         # Some OS distros (e.g. Alpine) have very precise versions (e.g. 3.17.3), and to support these
> ```

Please rewrap
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 6 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Ph73k3eF3GpH1dXf7:-O2Ph73k3eF3GpH1dXf8:bbl4tzj) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L6)):*
> ```
> 
> {% if Distro | regex_match('^redhat/ubi(\d+)(-minimal)?:(\d+).(\d+)$') %}
>     {% set ver = Distro.split(':')[0].split('ubi')[1] %}
> ```

Could you use the result of regex parsing, instead of parsing the string again, but differently?
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Pk8l14E6kYW7m5QKS:-O2Pk8l14E6kYW7m5QKT:bocyvtx) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L8)):*
> ```
>     {% set ver = Distro.split(':')[0].split('ubi')[1] %}
> {% else %}
>     RUN echo "ERROR: Unsupported Red Hat distribution - {{ Distro }}." && exit 1;
> ```

I'd prefer to fail during templating. You can achieve that e.g. by adding a custom filter `assert_not_none(error_msg)` and pass the regex matching result through it.


<!-- Sent from Reviewable.io -->

2024-07-23 04:30 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 18 of 23 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`gsc.py` line 277 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2PkiaYC5vf3vvruhiE:-O2Scucn7OBk_9IBCLgu:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/gsc.py#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please rewrap
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 6 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Ph73k3eF3GpH1dXf7:-O2Sp4GO-kq6S4TCrNWS:b-ej6q4o) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you use the result of regex parsing, instead of parsing the string again, but differently?
</blockquote></details>

Created a single function `get_ubi_version` that checks if distro is valid or not. If valid then get the version from string.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Pk8l14E6kYW7m5QKS:-O2Sg-6I7ycYc7ICnCAi:bi3tmsf) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer to fail during templating. You can achieve that e.g. by adding a custom filter `assert_not_none(error_msg)` and pass the regex matching result through it.
</blockquote></details>

Done.
Created custom `assert_not_none(error_msg)` that shows templating error when wrong distro given. 
I am unable to test this because whenever I give the wrong distro name in config.yaml, fetch\_and\_validate\_distro\_support function makes sure it throws error.


<!-- Sent from Reviewable.io -->

2024-07-23 14:24 UTC, mkow requested changes
> Reviewed 1 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 19 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`gsc.py` line 277 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2PkiaYC5vf3vvruhiE:-O2UrkyhAiouYT3haY3_:bfhqml6) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/gsc.py#L277)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 6 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Ph73k3eF3GpH1dXf7:-O2UtTTSABQeQqTTd3Dm:b5t2mao) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Created a single function `get_ubi_version` that checks if distro is valid or not. If valid then get the version from string.
</blockquote></details>

But now you still call it twice...
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Pk8l14E6kYW7m5QKS:-O2UtWxmD6Gbgd-UHhlI:b-8hxhfx) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L8)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Created custom `assert_not_none(error_msg)` that shows templating error when wrong distro given. 
I am unable to test this because whenever I give the wrong distro name in config.yaml, fetch\_and\_validate\_distro\_support function makes sure it throws error.
</blockquote></details>

That's not what I meant, "assert" as in "checking a condition" - see how `assert` works in Python or C/C++. It should be something like `{% set ver = get_ubi_version(Distro) | assert_not_none('error message'} %}` or `{% set ver = (Distro | regex_match('^redhat/ubi(\d+)(-minimal)?:(\d+).(\d+)$') | assert_not_none('error message').group(1) %}`.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r13](https://reviewable.io/reviews/gramineproject/gsc/207#-O2UyTrG7_ZRrP6NXx4S:-O2UyTrG7_ZRrP6NXx4T:b7he58q) ([raw file](https://github.com/gramineproject/gsc/blob/4436d72b09d306ec86eb75dce71f86ee7ab23393/templates/redhat/ubi/Dockerfile.build.template#L8)):*
> ```
>     {% set ver = get_ubi_version(Distro) %}
> {% else %}
>     {{ assert_not_none('ERROR: Unsupported Red Hat distribution - {{ Distro }}.') }}
> ```

Does this work? (nested templating) Have you tested this?



_Code quote:_
```
{{ Distro }}
```


<!-- Sent from Reviewable.io -->

2024-07-24 05:01 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 18 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`gsc.py` line 277 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2PkiaYC5vf3vvruhiE:-O2XrfHJAHdr6zJui0SJ:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/gsc.py#L277)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 6 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Ph73k3eF3GpH1dXf7:-O2Xz7aH0OxFPu07TCks:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you still call it twice...
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Pk8l14E6kYW7m5QKS:-O2XysVFEJONanFfhSLR:bjw6bo8) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

That's not what I meant, "assert" as in "checking a condition" - see how `assert` works in Python or C/C++. It should be something like `{% set ver = get_ubi_version(Distro) | assert_not_none('error message'} %}` or `{% set ver = (Distro | regex_match('^redhat/ubi(\d+)(-minimal)?:(\d+).(\d+)$') | assert_not_none('error message').group(1) %}`.
</blockquote></details>

Yes now have implemented in a single line like this
```
{% set ver = get_ubi_version(Distro) | assert_not_none('ERROR: Unsupported Red Hat distribution - {{ Distro }}.') %}
```
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r13](https://reviewable.io/reviews/gramineproject/gsc/207#-O2UyTrG7_ZRrP6NXx4S:-O2Xymgt2xm7ME5pvll_:b33dljj) ([raw file](https://github.com/gramineproject/gsc/blob/4436d72b09d306ec86eb75dce71f86ee7ab23393/templates/redhat/ubi/Dockerfile.build.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Does this work? (nested templating) Have you tested this?
</blockquote></details>

Done 
Removed this


<!-- Sent from Reviewable.io -->

2024-07-24 12:34 UTC, mkow requested changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 256 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZXRsPDisyEtgqjW1a:-O2ZXRsPDisyEtgqjW1b:b-6abii8) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/gsc.py#L256)):*
> ```Python
> def assert_not_none(value, error_message):
>     if value is None:
>         raise jinja2.TemplateAssertionError(error_message, lineno=0, name='assert_not_none')
> ```

This way you don't need to pass a fake line number.



_Suggestion:_
```Python
jinja2.TemplateError(error_message)
```
___
*[`gsc.py` line 260 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZWukK2SF61JH4aFMB:-O2ZWukK2SF61JH4aFMC:br1sr4l) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/gsc.py#L260)):*
> ```Python
> 
> def get_ubi_version(distro):
>     match = re.match(r'^redhat/ubi(\d+)(-minimal)?:(\d+).(\d+)$', distro)
> ```

`match` is a keyword in Python



_Suggestion:_
```Python
match_
```
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r11](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Pk8l14E6kYW7m5QKS:-O2ZiIQvAFDUIadH0AFU:b-1mm46y) ([raw file](https://github.com/gramineproject/gsc/blob/3965d17785887fbf1af6ff0137b2844790e419df/templates/redhat/ubi/Dockerfile.build.template#L8)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Yes now have implemented in a single line like this
```
{% set ver = get_ubi_version(Distro) | assert_not_none('ERROR: Unsupported Red Hat distribution - {{ Distro }}.') %}
```
</blockquote></details>

FYI: No need to paste the code here, I see the diff :P
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZiQ7QAvDY_6NrzpkI:-O2ZiQ7QAvDY_6NrzpkJ:b-2yfgtp) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi/Dockerfile.build.template#L5)):*
> ```
> {% block install %}
> 
> {% set ver = get_ubi_version(Distro) | assert_not_none('ERROR: Unsupported Red Hat distribution - ' + Distro) %}
> ```

Please wrap.
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZiaGE8-CU6e2Ucprf:-O2ZiaGE8-CU6e2Ucprg:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi/Dockerfile.compile.template#L5)):*
> ```
> {% block install %}
> 
> {% set ver = get_ubi_version(Distro) | assert_not_none('ERROR: Unsupported Red Hat distribution - ' + Distro) %}
> ```

ditto
___
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Zie4b9tuDY9hvA2ul:-O2Zie4b9tuDY9hvA2um:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi-minimal/Dockerfile.build.template#L5)):*
> ```
> {% block install %}
> 
> {% set ver = get_ubi_version(Distro) | assert_not_none('ERROR: Unsupported Red Hat distribution - ' + Distro) %}
> ```

ditto
___
*[`templates/redhat/ubi-minimal/Dockerfile.compile.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Zig5t9dnK9ENhenSE:-O2Zig5t9dnK9ENhenSF:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi-minimal/Dockerfile.compile.template#L5)):*
> ```
> {% block install %}
> 
> {% set ver = get_ubi_version(Distro) | assert_not_none('ERROR: Unsupported Red Hat distribution - ' + Distro) %}
> ```

ditto


<!-- Sent from Reviewable.io -->

2024-07-25 05:47 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 18 of 23 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`gsc.py` line 256 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZXRsPDisyEtgqjW1a:-O2cLcue5SVZWk39KgrP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/gsc.py#L256)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This way you don't need to pass a fake line number.
</blockquote></details>

Done.
___
*[`gsc.py` line 260 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZWukK2SF61JH4aFMB:-O2cLiOZ8ha_VLAXaBCO:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/gsc.py#L260)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`match` is a keyword in Python
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.build.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZiQ7QAvDY_6NrzpkI:-O2cMxqz1fFF_a2QBHk2:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please wrap.
</blockquote></details>

Done.
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2ZiaGE8-CU6e2Ucprf:-O2cMy8U3yxx0Di7HZ53:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi/Dockerfile.compile.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`templates/redhat/ubi-minimal/Dockerfile.build.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Zie4b9tuDY9hvA2ul:-O2cMyoR0lMJYv8u7a4K:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi-minimal/Dockerfile.build.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`templates/redhat/ubi-minimal/Dockerfile.compile.template` line 5 at r14](https://reviewable.io/reviews/gramineproject/gsc/207#-O2Zig5t9dnK9ENhenSE:-O2cMz4C95gPt60FqQy2:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d920537a809850e9da9f48ed4b030ed14c82733b/templates/redhat/ubi-minimal/Dockerfile.compile.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-25 12:30 UTC, mkow requested changes
> Reviewed 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r15](https://reviewable.io/reviews/gramineproject/gsc/207#-O2drA-y7AzEewdB5RYd:-O2drA-y7AzEewdB5RYe:b-tzv2t1) ([raw file](https://github.com/gramineproject/gsc/blob/cf7139107e724f6f36b0123669f255a71b1461ef/templates/redhat/ubi/Dockerfile.build.template#L8)):*
> ```
>     'ERROR: Unsupported Red Hat distribution - ' +
>     Distro,
> ) %}
> ```

ditto in the other places



_Suggestion:_
```
{% set ver = get_ubi_version(Distro) | assert_not_none(
    'ERROR: Unsupported Red Hat distribution - ' + Distro)
%}
```


<!-- Sent from Reviewable.io -->

2024-07-25 13:13 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: 19 of 23 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`templates/redhat/ubi/Dockerfile.build.template` line 8 at r15](https://reviewable.io/reviews/gramineproject/gsc/207#-O2drA-y7AzEewdB5RYd:-O2e0PMe4xF25LYNgG-7:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/cf7139107e724f6f36b0123669f255a71b1461ef/templates/redhat/ubi/Dockerfile.build.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto in the other places
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-25 16:53 UTC, mkow approved these changes
> Reviewed 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-26 10:08 UTC, dimakuv approved these changes
> Reviewed 1 of 5 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-29 08:31 UTC, kailun-qin approved these changes
> Reviewed 1 of 13 files at r1, 14 of 22 files at r2, 1 of 6 files at r4, 1 of 2 files at r6, 1 of 1 files at r7, 1 of 5 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-07-29 09:23 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/207)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-29 10:41 UTC, merged