Add support for SLES 15.4 and openSUSE Leap 15.6
gramineproject/gsc pull request #211
Opened 2024-08-12 06:14 UTC by adarshan-intel

## Description of the changes 
Add support for SLES 15.4 and openSUSE Leap 15.6

## How to test this PR? 
To test this PR, set follow similar procedure as followed with Ubuntu and do gsc build and signing commands.

2024-08-13 04:22 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 5 of 9 files reviewed, 11 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Pm-x25LJyGXhFlWp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you decipher "SLES" in the commit message body?
</blockquote></details>

Added **SUSE Linux Enterprise Server** (SLES) in Description of the PR changes
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PqyYDBu_6vM8w6D7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is there any need to specify such specific version numbers? Why not just `v15`?
</blockquote></details>

That would also work, I thought to be more specific, doing v15 pulls from the latest tag
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44QFNW8N8BHqtgYoxY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you explain the difference between the two OS distros inside the commit message body?
</blockquote></details>

Updated PR description
___
*[`config.yaml.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PxnsBx2zITbSP3kC:-O48uFrG4xWYqVas_T90:b8aweme) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/config.yaml.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why such specific version numbers)
</blockquote></details>

The user needs to specify which version they want for sle, it can be 15.4, 15.6 etc. If we don't give then pulls from latest, image name would be registry.suse.com/suse/sle15:latest which would make difficult to extract version numbers, for further processing. Also earlier all the distros have a specific version number so thinking to go by this approach
___
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O44gmuTDZW-Jz0tNObc:bk17ms7) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this needed? I would imagine that the for loop below won't be executed, and you effectively has the same `''` returned by the end of this function.
</blockquote></details>

The same thing you mentioned. The "for" loop was not executing, so I added this line.
___
*[`gsc.py` line 305 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Qqpn8b8MJg3Kjpr0:-O44h39K5VEstpa6jEEE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L305)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add an empty line before this `return distro`?
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 320 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Qw1Y6qHjLHStnZvP:-O44h8vv4K_k-nURR2fW:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/Documentation/index.rst#L320)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Forgot to put a comma after `minimal`
</blockquote></details>

Done.
___
*[`Documentation/index.rst` line 321 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R0hd4VkvwqHqRRob:-O44h9AZBZbZG9KLZpuY:byqu0tf) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/Documentation/index.rst#L321)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (why such specific versions)
</blockquote></details>

Made generic v15.
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O44hWuh4EFOt_3xRHNg:b-n1jxh6) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

SUSE uses Musl instead of Glibc? This must be explained in the commit message body at least.
</blockquote></details>

Done.
Updated PR description
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44RpVM3f-cTKGMHguE:-O48y4sS4xrfqZa7OlFe:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks ugly... Can we propagate `template_path` from `gsc.py` and use that in such places, instead of `Distro`?
</blockquote></details>

Done.
___
*[`templates/suse/Dockerfile.build.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44SPzs6awPDrbbLrik:-O44iJcz0FspdOZaJJFT:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/suse/Dockerfile.build.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't see any uninstall commands here (which makes this comment incorrect). Why didn't you add them?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-13 06:50 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Pm-x25LJyGXhFlWp):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Added **SUSE Linux Enterprise Server** (SLES) in Description of the PR changes
</blockquote></details>

Ok, we will also fix the commit message during final rebase.
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PqyYDBu_6vM8w6D7):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

That would also work, I thought to be more specific, doing v15 pulls from the latest tag
</blockquote></details>

Ok, we will also fix the commit message during final rebase.
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44QFNW8N8BHqtgYoxY):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Updated PR description
</blockquote></details>

Ok, we will also fix the commit message during final rebase.
___
*[`config.yaml.template` line 14 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PxnsBx2zITbSP3kC:-O49TZSm3DRqMQkSvJtJ:bjanrgg) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/config.yaml.template#L14)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

The user needs to specify which version they want for sle, it can be 15.4, 15.6 etc. If we don't give then pulls from latest, image name would be registry.suse.com/suse/sle15:latest which would make difficult to extract version numbers, for further processing. Also earlier all the distros have a specific version number so thinking to go by this approach
</blockquote></details>

Yeah, that's true, other OS distros also have specific versions (like UBI). Ok, let's stick to these specific version numbers.
___
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O49TigtEIsoC61MzTCt:b-u5xbfq) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

The same thing you mentioned. The "for" loop was not executing, so I added this line.
</blockquote></details>

Sorry, I didn't understand your reply. If the for loop was *not* executing, then the effect is the same -- with these two new lines or without them. And if the effect is the same, then why add the two lines? I would revert this change, it's redundant.
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O49U60i87d6pHblKg_-:bwdg3sx) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Updated PR description
</blockquote></details>

Ok, we will also fix the commit message during final rebase.
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44RpVM3f-cTKGMHguE:-O49UBqiD57VeQfKdJ71:b-bjkbw) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you also do this, since we're here:
```diff
-       {% if Distro.startswith('ubuntu') %}-Ddcap=enabled{% endif %} \
+       {% if template_path(Distro) == 'ubuntu' %}-Ddcap=enabled{% endif %} \
```
___
*[`templates/suse/Dockerfile.build.template` line 22 at r2](https://reviewable.io/reviews/gramineproject/gsc/211#-O49UHiF1m3CR2juD95G:-O49UHiF1m3CR2juD95H:b-cev66x) ([raw file](https://github.com/gramineproject/gsc/blob/8736243fe0fc233a0aa22dc12565acb7e191542e/templates/suse/Dockerfile.build.template#L22)):*
> ```
>                                         'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>                                         voluptuous \
>     && zypper clean -a;
> ```

I don't think you need the `;` at the end?
___
*[`templates/suse/Dockerfile.compile.template` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/211#-O49UKr12D2VgudqWLWZ:-O49UKr12D2VgudqWLW_:bm9koe7) ([raw file](https://github.com/gramineproject/gsc/blob/8736243fe0fc233a0aa22dc12565acb7e191542e/templates/suse/Dockerfile.compile.template#L9)):*
> ```
>         autoconf \
>         bison \
>         cmake \ 
> ```

Please remove the space at the end of the line


<!-- Sent from Reviewable.io -->

2024-08-13 08:15 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 6 of 9 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Pm-x25LJyGXhFlWp):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, we will also fix the commit message during final rebase.
</blockquote></details>

Sure
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PqyYDBu_6vM8w6D7):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, we will also fix the commit message during final rebase.
</blockquote></details>

Sure
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44QFNW8N8BHqtgYoxY):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, we will also fix the commit message during final rebase.
</blockquote></details>

Sure
___
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O49lc5i1vTyboBGhUDU:bwmqo64) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I didn't understand your reply. If the for loop was *not* executing, then the effect is the same -- with these two new lines or without them. And if the effect is the same, then why add the two lines? I would revert this change, it's redundant.
</blockquote></details>

I want to clarify my previous message. If we omit the above 2 lines, the build will fail with the error "# [TypeError: 'NoneType' object is not iterable](https://stackoverflow.com/questions/3887381/typeerror-nonetype-object-is-not-iterable)". It is crucial to address the scenario in which the env_list is empty, which is why we need to include the above lines.
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O49n4lDEHwRhRvLLa1t:bb74ce2) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, we will also fix the commit message during final rebase.
</blockquote></details>

Sure
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44RpVM3f-cTKGMHguE:-O49mcWE0WMeczAjLuL-:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you also do this, since we're here:
```diff
-       {% if Distro.startswith('ubuntu') %}-Ddcap=enabled{% endif %} \
+       {% if template_path(Distro) == 'ubuntu' %}-Ddcap=enabled{% endif %} \
```
</blockquote></details>

Done.
___
*[`templates/suse/Dockerfile.build.template` line 22 at r2](https://reviewable.io/reviews/gramineproject/gsc/211#-O49UHiF1m3CR2juD95G:-O49mkuA42zOEAnFfw6G:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/8736243fe0fc233a0aa22dc12565acb7e191542e/templates/suse/Dockerfile.build.template#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't think you need the `;` at the end?
</blockquote></details>

Done.
___
*[`templates/suse/Dockerfile.compile.template` line 9 at r2](https://reviewable.io/reviews/gramineproject/gsc/211#-O49UKr12D2VgudqWLWZ:-O49mum511mSKmTOr3IP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/8736243fe0fc233a0aa22dc12565acb7e191542e/templates/suse/Dockerfile.compile.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove the space at the end of the line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-13 08:27 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-13 14:09 UTC, kailun-qin submitted a review, later dismissed
> Reviewed 4 of 9 files at r1, 2 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O4AyQI12JznmwOyUv17:b8x36mi) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I want to clarify my previous message. If we omit the above 2 lines, the build will fail with the error "# [TypeError: 'NoneType' object is not iterable](https://stackoverflow.com/questions/3887381/typeerror-nonetype-object-is-not-iterable)". It is crucial to address the scenario in which the env_list is empty, which is why we need to include the above lines.
</blockquote></details>

hmm... I'd sugget below but I'm not blocking:
```
    env_list = config.get('Env')
    if not env_list:
        return ''

    base_image_environment = ''
    ...
```


<!-- Sent from Reviewable.io -->

2024-08-14 03:17 UTC, adarshan-intel commented
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O4DsrrF6GkTIlMzo-Rx:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, kailun-qin (Kailun Qin) wrote…</i></summary><blockquote>

hmm... I'd sugget below but I'm not blocking:
```
    env_list = config.get('Env')
    if not env_list:
        return ''

    base_image_environment = ''
    ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-14 06:33 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O4E_IkBA3C2f0kfI0mF:b-dm13fk) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I prefer @kailun-qin's way. @adarshan-intel Please fix exactly how Kailun wrote the snippet (`base_image_environment = ''` *after* the if check).


<!-- Sent from Reviewable.io -->

2024-08-14 06:58 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 121 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Q-Bq9hk5QH05Xsnz:-O4EfZKl7nA8B08pNdZP:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/gsc.py#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I prefer @kailun-qin's way. @adarshan-intel Please fix exactly how Kailun wrote the snippet (`base_image_environment = ''` *after* the if check).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-14 07:39 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`gsc.py` line 121 at r5](https://reviewable.io/reviews/gramineproject/gsc/211#-O4EopRL2TCGlxa6mbpj:-O4EopRL2TCGlxa6mbpk:b4nh5oo) ([raw file](https://github.com/gramineproject/gsc/blob/4ff96165efa1a45cdb7322fda0af03f076aa87bf/gsc.py#L121)):*
> ```Python
>     if env_list is None:
>         return ''
>     
> ```

Please remove whitespace here


<!-- Sent from Reviewable.io -->

2024-08-14 08:10 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 8 of 9 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`gsc.py` line 121 at r5](https://reviewable.io/reviews/gramineproject/gsc/211#-O4EopRL2TCGlxa6mbpj:-O4Ew7_P5jqKQlGAnSf3:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/4ff96165efa1a45cdb7322fda0af03f076aa87bf/gsc.py#L121)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove whitespace here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-14 10:01 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-08-21 09:57 UTC, adarshan-intel reviewed
@mkow Can you reivew this PR?        

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211#-:-O4oMTyWEa4XSObZ_ULT:b-mvnxnr)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2024-08-21 15:39 UTC, woju requested changes
> Reviewed 5 of 9 files at r1, 1 of 5 files at r2, 3 of 3 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PqyYDBu_6vM8w6D7):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Please no, SUSE minor versions change yearly and there can be quite a difference between versions of software available in repos, so those should be `openSUSE Leap 15.6` and `SLE 15 SP4`.

https://en.wikipedia.org/wiki/SUSE_Linux_Enterprise#Version_history
https://en.wikipedia.org/wiki/OpenSUSE#Version_history
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O4pP28z6f8_Xdd74sVT:bd4lz6u) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
I think this is wrong:

```
% docker run -it --rm opensuse/leap:15.6
Unable to find image 'opensuse/leap:15.6' locally
15.6: Pulling from opensuse/leap
5eb27e12feda: Pull complete 
Digest: sha256:b92aba5f8413624d1a4b671dff4858e454fcbe5e38dff1880cc48241750c2e8e
Status: Downloaded newer image for opensuse/leap:15.6
f42e35442333:/ # /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.38 (git 36f2487f13).
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Configured for x86_64-suse-linux.
Compiled by GNU CC version 13.2.1 20240206 [revision 67ac78caf31f7cb3202177e6428a46d829b70f23].
libc ABIs: UNIQUE IFUNC ABSOLUTE
Minimum supported kernel: 3.2.0
For bug reporting instructions, please see:
<http://bugs.opensuse.org>.
```

Why do you need musl instead of glibc?

In PR desc. you wrote:
> To run gramine on SLES (SUSE Linux Enterprise Server) or openSUSE Leap, we need to compile gramine with musl instead of glibc.

Why is this so? What happens if you try glibc?
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O4pTfyH0--pz8_eYqyi:bfkivja) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
> ```
>     && /usr/bin/python3 -B -m pip install click jinja2 protobuf pyelftools \
>                                         'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>                                         voluptuous \
> ```

AFAICS Leap has `python3-click`, `python3-Jinja2`, `python3-pyelftools`, `python3-tomli` and `python3-voluptuous` — why aren't those used? (IIUC `tomli-w` is missing, there's only `python311-tomli-w`; for `python3-protobuf` see next comment)
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pWo7x5OETc2BTefDS:-O4pWo7x5OETc2BTefDT:b-2pcva) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
> ```
>     && /usr/bin/python3 -B -m pip install click jinja2 protobuf pyelftools \
>                                         'tomli>=1.1.0' 'tomli-w>=0.4.0' \
>                                         voluptuous \
> ```

Why are you installing protobuf twice: `zypper install python3-protobuf && pip install protobuf`?
___
*[`templates/suse/Dockerfile.compile.template` line 32 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXA6ZD0VbZ7BkP610:-O4pXA6ZD0VbZ7BkP611:b-sbwm9w) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.compile.template#L32)):*
> ```
>         wget \
>         which \
>     && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'
> ```

for tomli and tomli-w see other comment, but now I'd like to ask why not `zypper install meson`?
___
*[`templates/suse/Dockerfile.sign.template` line 15 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXhxgC55bTj6Xj1-V:-O4pXhxgC55bTj6Xj1-W:b-b8q46v) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.sign.template#L15)):*
> ```
> {% endblock %}
> 
> {% block path %}export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib64 -type d -path '*/site-packages')" &&{% endblock %}
> ```

Is PYTHONPATH previously set? if not, it will result in PYTHONPATH=":$(find...)", so with empty first part. To avoid this, you can do this:

```sh
PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$(find ...)"
```

`${:+}` substitution expands only if the variable is set (but possibly null): https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02


<!-- Sent from Reviewable.io -->

2024-08-22 05:54 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 7 of 9 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PqyYDBu_6vM8w6D7):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Please no, SUSE minor versions change yearly and there can be quite a difference between versions of software available in repos, so those should be `openSUSE Leap 15.6` and `SLE 15 SP4`.

https://en.wikipedia.org/wiki/SUSE_Linux_Enterprise#Version_history
https://en.wikipedia.org/wiki/OpenSUSE#Version_history
</blockquote></details>

Updated PR title and description to use `openSUSE Leap 15.6` and `SLE 15 SP4`.
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O4sbweh4yg1nMmZhB-T:bjxf6j1) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I think this is wrong:

```
% docker run -it --rm opensuse/leap:15.6
Unable to find image 'opensuse/leap:15.6' locally
15.6: Pulling from opensuse/leap
5eb27e12feda: Pull complete 
Digest: sha256:b92aba5f8413624d1a4b671dff4858e454fcbe5e38dff1880cc48241750c2e8e
Status: Downloaded newer image for opensuse/leap:15.6
f42e35442333:/ # /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.38 (git 36f2487f13).
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Configured for x86_64-suse-linux.
Compiled by GNU CC version 13.2.1 20240206 [revision 67ac78caf31f7cb3202177e6428a46d829b70f23].
libc ABIs: UNIQUE IFUNC ABSOLUTE
Minimum supported kernel: 3.2.0
For bug reporting instructions, please see:
<http://bugs.opensuse.org>.
```

Why do you need musl instead of glibc?

In PR desc. you wrote:
> To run gramine on SLES (SUSE Linux Enterprise Server) or openSUSE Leap, we need to compile gramine with musl instead of glibc.

Why is this so? What happens if you try glibc?
</blockquote></details>

I've encountered an issue with building the Docker image using glibc. It is showing an error 
`"ninja: build stopped: subcommand failed."`

`"Failed to build unsigned graminized Docker image 'gsc-registry.suse.com/suse/sle15:15.4-unsigned'".`

 As a solution, I have added a line to ensure that musl is always used for building SUSE packages, which works just fine.
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O4sZ_5y-8t-dCfwQHoS:b-1ccjng) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

AFAICS Leap has `python3-click`, `python3-Jinja2`, `python3-pyelftools`, `python3-tomli` and `python3-voluptuous` — why aren't those used? (IIUC `tomli-w` is missing, there's only `python311-tomli-w`; for `python3-protobuf` see next comment)
</blockquote></details>

The two lines are installing similar packages but using different methods:
Eg.
1. `zypper install python3-click`
2. `pip install click`

Both install the same packages since 
`/usr/bin/python3 -B -m pip install click jinja2 protobuf pyelftools \ ................` text is used in multiple templates, so decided to maintain consistency across all the templates.
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pWo7x5OETc2BTefDS:-O4sUmjG-1vHW2aMhFjT:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why are you installing protobuf twice: `zypper install python3-protobuf && pip install protobuf`?
</blockquote></details>

Done.
___
*[`templates/suse/Dockerfile.compile.template` line 32 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXA6ZD0VbZ7BkP610:-O4sVTKv5DwC5l48WmYZ:bhm38i5) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.compile.template#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

for tomli and tomli-w see other comment, but now I'd like to ask why not `zypper install meson`?
</blockquote></details>

Both offer the same utility as other templates, such as centos/Dockerfile.compile.template, we utilized the same syntax, hence the decision to maintain consistency across all the templates.
___
*[`templates/suse/Dockerfile.sign.template` line 15 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXhxgC55bTj6Xj1-V:-O4sWNJI-4F2-5wprvu8:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.sign.template#L15)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Is PYTHONPATH previously set? if not, it will result in PYTHONPATH=":$(find...)", so with empty first part. To avoid this, you can do this:

```sh
PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$(find ...)"
```

`${:+}` substitution expands only if the variable is set (but possibly null): https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-22 11:40 UTC, woju requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O4t7sVH2FZEGsH-lYyG:b-te9wqu) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
> I've encountered an issue with building the Docker image using glibc. It is showing an error  
> `"ninja: build stopped: subcommand failed."`

Somewhere above this line there's `FAILED:` line, please see what exactly happened happened. If it's a problem with compiling glibc, then there's an error in the logfile. Please paste the real error.
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O4t8HRuCknwQ43yTwLj:bojj55p) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

The two lines are installing similar packages but using different methods:
Eg.
1. `zypper install python3-click`
2. `pip install click`

Both install the same packages since 
`/usr/bin/python3 -B -m pip install click jinja2 protobuf pyelftools \ ................` text is used in multiple templates, so decided to maintain consistency across all the templates.
</blockquote></details>

The difference between those "different methods" is that RPM packages are signed by distro (which is aready in TCB), but `pip install` relies on HTTPS for integrity protection, therefore pulling whole WebPKI into TCB, which we should avoid if possible. So you should prefer distro install method over pip. Please fix.

If you want to "maintain consistency", then you can go through all other files, gather understanding what versions from what repos will be installed, if they satisfy our requirements, and then possibly fix them to `apt-get`, `dnf` or whatever else. That would be a big ask, so I'm not insisting that you fix that everywhere right now, but here, please do what you can.
___
*[`templates/suse/Dockerfile.compile.template` line 32 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXA6ZD0VbZ7BkP610:-O4tsi4MCdd5q1WLSPVl:b4q7ept) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.compile.template#L32)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Both offer the same utility as other templates, such as centos/Dockerfile.compile.template, we utilized the same syntax, hence the decision to maintain consistency across all the templates.
</blockquote></details>

So same as in other subthread, please install tomli and meson from zypper.


<!-- Sent from Reviewable.io -->

2024-08-23 06:17 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 8 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O4xoysf84oksj9kFhwd:ba4yptj) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> I've encountered an issue with building the Docker image using glibc. It is showing an error  
> `"ninja: build stopped: subcommand failed."`

Somewhere above this line there's `FAILED:` line, please see what exactly happened happened. If it's a problem with compiling glibc, then there's an error in the logfile. Please paste the real error.
</blockquote></details>

This is the error message 

```
[397/404] Linking target tools/sgx/ra-tls/gramine-ratls
FAILED: subprojects/glibc-2.40-1/crt1.o subprojects/glibc-2.40-1/crti.o subprojects/glibc-2.40-1/crtn.o subprojects/glibc-2.40-1/libdl.so subprojects/glibc-2.40-1/libdl.so.2 subprojects/glibc-2.40-1/libc.so subprojects/glibc-2.40-1/libc.so.6 subprojects/glibc-2.40-1/libutil.so subprojects/glibc-2.40-1/libutil.so.1 subprojects/glibc-2.40-1/libm.so subprojects/glibc-2.40-1/libm.so.6 subprojects/glibc-2.40-1/libnsl.so subprojects/glibc-2.40-1/libnsl.so.1 
subprojects/glibc-2.40-1/libpthread.so subprojects/glibc-2.40-1/libpthread.so.0 subprojects/glibc-2.40-1/libthread_db.so subprojects/glibc-2.40-1/libthread_db.so.1 subprojects/glibc-2.40-1/libnss_compat.so subprojects/glibc-2.40-1/libnss_compat.so.2 subprojects/glibc-2.40-1/libnss_db.so subprojects/glibc-2.40-1/libnss_db.so.2 subprojects/glibc-2.40-1/libnss_files.so subprojects/glibc-2.40-1/libnss_files.so.2 subprojects/glibc-2.40-1/libanl.so subprojects/glibc-2.40-1/libanl.so.1 subprojects/glibc-2.40-1/libnss_dns.so
 subprojects/glibc-2.40-1/libnss_dns.so.2 subprojects/glibc-2.40-1/libresolv.so subprojects/glibc-2.40-1/libresolv.so.2 subprojects/glibc-2.40-1/librt.so subprojects/glibc-2.40-1/librt.so.1 subprojects/glibc-2.40-1/ld-linux-x86-64.so.2 subprojects/glibc-2.40-1/ld.so subprojects/glibc-2.40-1/libmvec.so subprojects/glibc-2.40-1/libmvec.so.1
/bin/sh /gramine/subprojects/glibc-2.40-1/compile.sh x86_64 ../subprojects/glibc-2.40-1 ../subprojects/glibc-2.40-1/glibc-2.40 /gramine/build/subprojects/glibc-2.40-1 
subprojects/glibc-2.40-1/crt1.o.p /gramine/meson_build_output lib64 '' csu/crt1.o csu/crti.o csu/crtn.o dlfcn/libdl.so dlfcn/libdl.so.2 libc.so libc.so.6 login/libutil.so login/libutil.so.1 math/libm.so math/libm.so.6 nis/libnsl.so nis/libnsl.so.1 nptl/libpthread.so nptl/libpthread.so.0 nptl_db/libthread_db.so nptl_db/libthread_db.so.1 nss/libnss_compat.so nss/libnss_compat.so.2 nss/libnss_db.so nss/libnss_db.so.2 nss/libnss_files.so nss/libnss_files.so.2 
resolv/libanl.so resolv/libanl.so.1 resolv/libnss_dns.so resolv/libnss_dns.so.2 resolv/libresolv.so resolv/libresolv.so.2 rt/librt.so rt/librt.so.1 elf/ld-linux-x86-64.so.2 elf/ld.so mathvec/libmvec.so mathvec/libmvec.so.1
[399/404] Generating subprojects/mbedtls-3.6.0/mbedtls_curl with a custom command
+ CURRENT_SOURCE_DIR=../subprojects/mbedtls-3.6.0
+ VENDOR_SOURCE_DIR=../subprojects/mbedtls-3.6.0/mbedtls-3.6.0
+ CURRENT_BUILD_DIR=/gramine/build/subprojects/mbedtls-3.6.0
+ PRIVATE_DIR=subprojects/mbedtls-3.6.0/libmbedcrypto.a.p
+ SUBPROJ_ROOT=/gramine/build/subprojects
+ shift 5


```


It worked with musl, so was thinking it to keep it that way
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O4xnpkMD3l4cuuizidp:b-h8pzon) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

The difference between those "different methods" is that RPM packages are signed by distro (which is aready in TCB), but `pip install` relies on HTTPS for integrity protection, therefore pulling whole WebPKI into TCB, which we should avoid if possible. So you should prefer distro install method over pip. Please fix.

If you want to "maintain consistency", then you can go through all other files, gather understanding what versions from what repos will be installed, if they satisfy our requirements, and then possibly fix them to `apt-get`, `dnf` or whatever else. That would be a big ask, so I'm not insisting that you fix that everywhere right now, but here, please do what you can.
</blockquote></details>

 Packages like - python3-click, python3-Jinja2 are included in Basesystem Module 15 SP4 x86\_64 Package.

 So installing these using zypper commands in dockerfile templates.

 Rest of the packages are included in different modules and to install them, we need to add the respective module to the image, which requires a subscription. So, keeping them with pip install.

 For python3-pyelftools ->  SUSE Package Hub 15 SP4

 For python3-tomli -> SUSE Package Hub 15 SP4

 For python3-tomli-w ->   Python 3 Module 15 SP4

 For python3-voluptuous -> SUSE Package Hub 15 SP4

 Please recommend if there is any other way to install these packages.
___
*[`templates/suse/Dockerfile.compile.template` line 32 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXA6ZD0VbZ7BkP610:-O4xoNcK8A5XySNuB_Li:bvukhro) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.compile.template#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

So same as in other subthread, please install tomli and meson from zypper.
</blockquote></details>

Likewise, for the package meson, this is the following module needed to be installed
 
For meson -> Development Tools Module 15 SP4

We need to add the module, which again requires a subscription. 

Please recommend if there is any other way to install these packages.


<!-- Sent from Reviewable.io -->

2024-08-23 14:31 UTC, woju requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O4yBSdT5yddArPylCbO:b-j66e65) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

This is the error message 

```
[397/404] Linking target tools/sgx/ra-tls/gramine-ratls
FAILED: subprojects/glibc-2.40-1/crt1.o subprojects/glibc-2.40-1/crti.o subprojects/glibc-2.40-1/crtn.o subprojects/glibc-2.40-1/libdl.so subprojects/glibc-2.40-1/libdl.so.2 subprojects/glibc-2.40-1/libc.so subprojects/glibc-2.40-1/libc.so.6 subprojects/glibc-2.40-1/libutil.so subprojects/glibc-2.40-1/libutil.so.1 subprojects/glibc-2.40-1/libm.so subprojects/glibc-2.40-1/libm.so.6 subprojects/glibc-2.40-1/libnsl.so subprojects/glibc-2.40-1/libnsl.so.1 
subprojects/glibc-2.40-1/libpthread.so subprojects/glibc-2.40-1/libpthread.so.0 subprojects/glibc-2.40-1/libthread_db.so subprojects/glibc-2.40-1/libthread_db.so.1 subprojects/glibc-2.40-1/libnss_compat.so subprojects/glibc-2.40-1/libnss_compat.so.2 subprojects/glibc-2.40-1/libnss_db.so subprojects/glibc-2.40-1/libnss_db.so.2 subprojects/glibc-2.40-1/libnss_files.so subprojects/glibc-2.40-1/libnss_files.so.2 subprojects/glibc-2.40-1/libanl.so subprojects/glibc-2.40-1/libanl.so.1 subprojects/glibc-2.40-1/libnss_dns.so
 subprojects/glibc-2.40-1/libnss_dns.so.2 subprojects/glibc-2.40-1/libresolv.so subprojects/glibc-2.40-1/libresolv.so.2 subprojects/glibc-2.40-1/librt.so subprojects/glibc-2.40-1/librt.so.1 subprojects/glibc-2.40-1/ld-linux-x86-64.so.2 subprojects/glibc-2.40-1/ld.so subprojects/glibc-2.40-1/libmvec.so subprojects/glibc-2.40-1/libmvec.so.1
/bin/sh /gramine/subprojects/glibc-2.40-1/compile.sh x86_64 ../subprojects/glibc-2.40-1 ../subprojects/glibc-2.40-1/glibc-2.40 /gramine/build/subprojects/glibc-2.40-1 
subprojects/glibc-2.40-1/crt1.o.p /gramine/meson_build_output lib64 '' csu/crt1.o csu/crti.o csu/crtn.o dlfcn/libdl.so dlfcn/libdl.so.2 libc.so libc.so.6 login/libutil.so login/libutil.so.1 math/libm.so math/libm.so.6 nis/libnsl.so nis/libnsl.so.1 nptl/libpthread.so nptl/libpthread.so.0 nptl_db/libthread_db.so nptl_db/libthread_db.so.1 nss/libnss_compat.so nss/libnss_compat.so.2 nss/libnss_db.so nss/libnss_db.so.2 nss/libnss_files.so nss/libnss_files.so.2 
resolv/libanl.so resolv/libanl.so.1 resolv/libnss_dns.so resolv/libnss_dns.so.2 resolv/libresolv.so resolv/libresolv.so.2 rt/librt.so rt/librt.so.1 elf/ld-linux-x86-64.so.2 elf/ld.so mathvec/libmvec.so mathvec/libmvec.so.1
[399/404] Generating subprojects/mbedtls-3.6.0/mbedtls_curl with a custom command
+ CURRENT_SOURCE_DIR=../subprojects/mbedtls-3.6.0
+ VENDOR_SOURCE_DIR=../subprojects/mbedtls-3.6.0/mbedtls-3.6.0
+ CURRENT_BUILD_DIR=/gramine/build/subprojects/mbedtls-3.6.0
+ PRIVATE_DIR=subprojects/mbedtls-3.6.0/libmbedcrypto.a.p
+ SUBPROJ_ROOT=/gramine/build/subprojects
+ shift 5


```


It worked with musl, so was thinking it to keep it that way
</blockquote></details>

Yeah, so glibc failed to build. `[397/]` and `[399/]` lines are not related, just interleaved because the builds happen in parallel. Somewhere yet earlier you have a path to glibc build log, and it probably contains the actual problem. I suspect it's a missing header or library that it's not included in `zypper install`, but it should have been.
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O4ypxgB0uFlpmWDvnMW:b-6rz4td) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Packages like - python3-click, python3-Jinja2 are included in Basesystem Module 15 SP4 x86\_64 Package.

 So installing these using zypper commands in dockerfile templates.

 Rest of the packages are included in different modules and to install them, we need to add the respective module to the image, which requires a subscription. So, keeping them with pip install.

 For python3-pyelftools ->  SUSE Package Hub 15 SP4

 For python3-tomli -> SUSE Package Hub 15 SP4

 For python3-tomli-w ->   Python 3 Module 15 SP4

 For python3-voluptuous -> SUSE Package Hub 15 SP4

 Please recommend if there is any other way to install these packages.
</blockquote></details>

What about leap? If you can install them in leap without subscription (possibly from secondary/non-default repos, but still provided by distro), then I'd say you should make the subscription work in SLES, like it was done in RHEL.
___
*[`templates/suse/Dockerfile.compile.template` line 32 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXA6ZD0VbZ7BkP610:-O4zc6XT0UKRyJTuuXBd:b-2gbpsa) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.compile.template#L32)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Likewise, for the package meson, this is the following module needed to be installed
 
For meson -> Development Tools Module 15 SP4

We need to add the module, which again requires a subscription. 

Please recommend if there is any other way to install these packages.
</blockquote></details>

Right, it's the same problem. I continued in the other thread. I'll keep this one blocked until we come up with a solution.


<!-- Sent from Reviewable.io -->

2024-08-26 04:43 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 6 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5BzEjk9pyDsNJD8u8L:b-xac9) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yeah, so glibc failed to build. `[397/]` and `[399/]` lines are not related, just interleaved because the builds happen in parallel. Somewhere yet earlier you have a path to glibc build log, and it probably contains the actual problem. I suspect it's a missing header or library that it's not included in `zypper install`, but it should have been.
</blockquote></details>

Where can I find the build logs? 
It's not present in the gsc build folder for the distro.
It compiles with musl properly, should I keep it that way in common compile template for SLES ? 
___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O5BwdUA6-CRdWd5GiXp:b-ujc4zt) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

What about leap? If you can install them in leap without subscription (possibly from secondary/non-default repos, but still provided by distro), then I'd say you should make the subscription work in SLES, like it was done in RHEL.
</blockquote></details>

I am considering removing the addition of OpenSUSE Leap and retaining only SLES in this PR. Will work on OpenSUSE Leap in different PR. For SLES to work as per your requirement, the user's image (pulled from registry.suse.com/suse/sle15:15.4) must already be subscribed. Only then is it possible to add modules and install packages from them. I believe my solution above for pulling in images from python would be generic and should work. 

Do you suggest any other approach?
___
*[`templates/suse/Dockerfile.compile.template` line 32 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pXA6ZD0VbZ7BkP610:-O5Bxxc8A4B63tyUGH44:b-fihtsw) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.compile.template#L32)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Right, it's the same problem. I continued in the other thread. I'll keep this one blocked until we come up with a solution.
</blockquote></details>

Likewise


<!-- Sent from Reviewable.io -->

2024-08-27 08:00 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5Hp_om-bfQALkyDyLl:b-tx8a6a) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
> Where can I find the build logs?

I think the easiest for you would be to first manually jump into a SLES distro Docker container, and try to install Gramine from within (manually). There the `ninja -C build` command should fail in the same way as you observe in GSC. And you'll be able to locate the Glibc build logs. It should be something like `<gramine-dir>/build/subprojects/glibc-2.40-1/glibc-build.log`.

After you'll figure out what goes wrong with Glibc on SLES manually, you'll be able to fix it in GSC.


<!-- Sent from Reviewable.io -->

2024-08-27 21:49 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O5Kft3fA4hNzmNyA7e6:bdq1x9r) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I am considering removing the addition of OpenSUSE Leap and retaining only SLES in this PR. Will work on OpenSUSE Leap in different PR. For SLES to work as per your requirement, the user's image (pulled from registry.suse.com/suse/sle15:15.4) must already be subscribed. Only then is it possible to add modules and install packages from them. I believe my solution above for pulling in images from python would be generic and should work. 

Do you suggest any other approach?
</blockquote></details>

RHEL we patch by just copying the keys from the host into the container: https://github.com/gramineproject/gsc/blob/fcf96546f4a23a4e6bcc6a14d80cf1521c018fc9/templates/redhat/ubi/Dockerfile.build.template#L9-L11
I don't know anything about SUSE subscriptions to say if it would work for this.

Another option about which I don't know enough would be SUSE's BCI. They say the subscriptions are automatically forwarded from host: https://documentation.suse.com/container/all/html/Container-guide/index.html#sec-bci-highlights but that would mean you're not doing SLES proper either, just those base images which is yet another distro flavour, so I'm not sure if that would be fulfilling your primary requirements. But if those BCIs are OK with you, I'd suggest this one.


<!-- Sent from Reviewable.io -->

2024-08-28 06:21 UTC, adarshan-intel commented
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5MEtkXB1izC2KJH_MK:bjwvmif) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> Where can I find the build logs?

I think the easiest for you would be to first manually jump into a SLES distro Docker container, and try to install Gramine from within (manually). There the `ninja -C build` command should fail in the same way as you observe in GSC. And you'll be able to locate the Glibc build logs. It should be something like `<gramine-dir>/build/subprojects/glibc-2.40-1/glibc-build.log`.

After you'll figure out what goes wrong with Glibc on SLES manually, you'll be able to fix it in GSC.
</blockquote></details>

After manual installation of gramine followed above steps and found the glibc build logs. Attaching logs here - [glibc-build.log](https://gist.github.com/adarshan-intel/1e891757a12d2d72d5ddaea7a583f99a)

This was the error with compiling with glibc, but running with musl command below compiles just fine
` meson setup build/ \--buildtype=release -Ddirect=enabled -Dsgx=enabled -Dlibc=musl
`


<!-- Sent from Reviewable.io -->

2024-08-28 09:48 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 6 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @kailun-qin, and @woju)

___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O5NCJWjCv8COsa4F7aD:b-4u31mg) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

RHEL we patch by just copying the keys from the host into the container: https://github.com/gramineproject/gsc/blob/fcf96546f4a23a4e6bcc6a14d80cf1521c018fc9/templates/redhat/ubi/Dockerfile.build.template#L9-L11
I don't know anything about SUSE subscriptions to say if it would work for this.

Another option about which I don't know enough would be SUSE's BCI. They say the subscriptions are automatically forwarded from host: https://documentation.suse.com/container/all/html/Container-guide/index.html#sec-bci-highlights but that would mean you're not doing SLES proper either, just those base images which is yet another distro flavour, so I'm not sure if that would be fulfilling your primary requirements. But if those BCIs are OK with you, I'd suggest this one.
</blockquote></details>

I was reading online and found a way to implement the first method. We need to copy the credentials file `/etc/zypp/credentials.d/SCCcredentials` from the host to the docker image and then remove it during cleanup (similar to what we did for RHEL). I have implemented it by taking reference from RHEL PR, so please take a look. Thank you for your assistance.

Keeping `python311-tomli-w` with zypper install results in `ModuleNotFoundError: No module named tomli_w`, so keeping it with pip install. For the rest of them installed using zypper. 


<!-- Sent from Reviewable.io -->

2024-08-28 15:09 UTC, woju requested changes
> Reviewed 2 of 3 files at r9, 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)

___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O5OVEI18epebgRXQGN9:ba0156b) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I was reading online and found a way to implement the first method. We need to copy the credentials file `/etc/zypp/credentials.d/SCCcredentials` from the host to the docker image and then remove it during cleanup (similar to what we did for RHEL). I have implemented it by taking reference from RHEL PR, so please take a look. Thank you for your assistance.

Keeping `python311-tomli-w` with zypper install results in `ModuleNotFoundError: No module named tomli_w`, so keeping it with pip install. For the rest of them installed using zypper.
</blockquote></details>

`python311-` packages are not for `python3` interpreter (which is Python 3.6 on 15.6), but for `python311`, so yeah, those won't work, unless you install all `python311-*` packages and instead of running `./gsc` you'll execute it as `python3.11 gsc` *everywhere* on OpenSUSE. That would be a big ask. So yeah for now you can pip install it.
___
*[`templates/suse/Dockerfile.compile.template` line 44 at r10](https://reviewable.io/reviews/gramineproject/gsc/211#-O5OVlV5AIhrNieTaeQi:-O5OVlV73aTV85PM00ab:b-76410m) ([raw file](https://github.com/gramineproject/gsc/blob/d0264e875a5055fd5af7baede6428b9e1e0a6f75/templates/suse/Dockerfile.compile.template#L44)):*
> ```
>         python3-protobuf \
>         python3-tomli \
>         python311-tomli-w \
> ```

You said it was meant to be installed from pip, is this a leftover?


<!-- Sent from Reviewable.io -->

2024-08-29 04:21 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: 7 of 9 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`templates/suse/Dockerfile.build.template` line 21 at r6](https://reviewable.io/reviews/gramineproject/gsc/211#-O4pTfyH0--pz8_eYqyh:-O5RMKfG1srYxVT86B6s:b-mk6sd3) ([raw file](https://github.com/gramineproject/gsc/blob/80309de3167ccf582785d1e8994fb8aa8e245df0/templates/suse/Dockerfile.build.template#L21)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`python311-` packages are not for `python3` interpreter (which is Python 3.6 on 15.6), but for `python311`, so yeah, those won't work, unless you install all `python311-*` packages and instead of running `./gsc` you'll execute it as `python3.11 gsc` *everywhere* on OpenSUSE. That would be a big ask. So yeah for now you can pip install it.
</blockquote></details>

Done.
Keeping it pip install only
___
*[`templates/suse/Dockerfile.compile.template` line 44 at r10](https://reviewable.io/reviews/gramineproject/gsc/211#-O5OVlV5AIhrNieTaeQi:-O5RLp0-ArMcOnTpD2O0:b-gr48i0) ([raw file](https://github.com/gramineproject/gsc/blob/d0264e875a5055fd5af7baede6428b9e1e0a6f75/templates/suse/Dockerfile.compile.template#L44)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

You said it was meant to be installed from pip, is this a leftover?
</blockquote></details>

Yeah updated it


<!-- Sent from Reviewable.io -->

2024-08-29 07:46 UTC, dimakuv requested changes
> Reviewed 1 of 2 files at r7, 1 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @woju)

___
*[`gsc.py` line 269 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S2pva0-dCy7Do59SN:-O5S2pva0-dCy7Do59SO:bgxfafr) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/gsc.py#L269)):*
> ```Python
>             print('Cannot find username or password in /etc/zypp/credentials.d/SCCcredentials. '
>                     'Please register and subscribe your SUSE system to the SUSE Customer Center.')
>             sys.exit(1)
> ```

Is this "check for username and password" snippet really needed? Did you take this snippet from some official web site? Sounds weird to me to open a sensitive file just to error out if login/pass not found there.
___
*[`gsc.py` line 273 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S31qs4aMaJhJ6Re8U:-O5S31qs4aMaJhJ6Re8V:btylzwu) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/gsc.py#L273)):*
> ```Python
>         # This file contains the credentials for the SUSE Customer Center (SCC) account for the
>         # system to authenticate and receive software updates and support from SUSE. Copy it to
>         # the temporary build directory to include it in the graminized Docker image
> ```

Please add a dot at the end of the sentence.
___
*[`gsc.py` line 274 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S2geA87WPJainwFwS:-O5S2geA87WPJainwFwT:b19yocn) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/gsc.py#L274)):*
> ```Python
>         # system to authenticate and receive software updates and support from SUSE. Copy it to
>         # the temporary build directory to include it in the graminized Docker image
>         shutil.copyfile('/etc/zypp/credentials.d/SCCcredentials', tmp_build_path / 'SCCcredentials')
> ```

Why is this under `with open() ...` ? Shouldn't it be in a normal context of this function? (I.e., I think you must de-indent by 4 spaces.)
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5S3LV30ieOp5V5FA0t:b-rskn3) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

After manual installation of gramine followed above steps and found the glibc build logs. Attaching logs here - [glibc-build.log](https://gist.github.com/adarshan-intel/1e891757a12d2d72d5ddaea7a583f99a)

This was the error with compiling with glibc, but running with musl command below compiles just fine
` meson setup build/ \--buildtype=release -Ddirect=enabled -Dsgx=enabled -Dlibc=musl
`
</blockquote></details>

Thanks for the log.

The problem is hinted at here:
```
n file included from ../sysdeps/unix/sysv/linux/x86_64/sysdep.h:29:0,
                 from ../sysdeps/x86_64/nptl/tls.h:28,
                 from ../include/link.h:51,
                 from <stdin>:1:
/home/intel/adarsh_opensuse/gramine/subprojects/glibc-2.40-1/../../libos/include/arch/x86_64/gramine_entry_api.h:52:48: error: ‘naked’ attribute directive ignored [-Werror=attributes]
                                                unsigned long arg2 __attribute__((unused))) {
                                                ^~~~~~~~
/home/intel/adarsh_opensuse/gramine/subprojects/glibc-2.40-1/../../libos/include/arch/x86_64/gramine_entry_api.h: In function ‘gramine_call’:
/home/intel/adarsh_opensuse/gramine/subprojects/glibc-2.40-1/../../libos/include/arch/x86_64/gramine_entry_api.h:58:1: error: no return statement in function returning non-void [-Werror=return-type]
 }
 ^
```

The root cause is that OpenSUSE 15.x uses **super-old GCC 7** as the default GCC. See e.g. [this discussion](https://documentation.suse.com/sbp/server-linux/html/SBP-GCC-11/index.html).

Now GCC 7 is so old that it doesn't support the `naked` attribute. Its support was added only in GCC 8, [see here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25967#c18).

So I think we must force OpenSUSE to switch to GCC 11, which is also found in OpenSUSE 15.x. According to this [official tutorial](https://documentation.suse.com/sbp/server-linux/html/SBP-GCC-11/index.html#sec-gcc11-overview), it should be enough to `zypper install gcc11 gcc11-c++` (after you added the subscription, which you did).

Now how to force OpenSUSE to switch to GCC 11 after it is installed? I think it should be enough to add:
```
export AS=/usr/bin/gcc-11
export CC=/usr/bin/gcc-11
export CXX=/usr/bin/g++-11
```
in the Dockerfile.compile of OpenSUSE, see my other note.
___
*[`templates/suse/Dockerfile.compile.template` line 48 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S58S80oyzN9J5It9v:-O5S58S80oyzN9J5It9w:b-fyot2s) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/templates/suse/Dockerfile.compile.template#L48)):*
> ```
>         which \
>     && /usr/bin/python3 -B -m pip install 'tomli-w>=0.4.0'
> ```

I think you should also add GCC-11 installation here, and the `export AS= export CC= export CXX=` lines here. See my other note on Glibc build.


<!-- Sent from Reviewable.io -->

2024-08-29 21:08 UTC, woju reviewed
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @dimakuv)



<!-- Sent from Reviewable.io -->

2024-08-30 03:48 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`gsc.py` line 269 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S2pva0-dCy7Do59SN:-O5SC67u3UusO0xM-CEL:b-ndf9uw) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/gsc.py#L269)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this "check for username and password" snippet really needed? Did you take this snippet from some official web site? Sounds weird to me to open a sensitive file just to error out if login/pass not found there.
</blockquote></details>

Removed this, now just checking for existence of `/etc/zypp/credentials.d/SCCcredentials` file, if yes then copy it to docker image else not
___
*[`gsc.py` line 273 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S31qs4aMaJhJ6Re8U:-O5SBvBZAmqy4G34katO:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/gsc.py#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a dot at the end of the sentence.
</blockquote></details>

Done.
___
*[`gsc.py` line 274 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S2geA87WPJainwFwS:-O5SCGuq6kRNUDCdcyV7:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/gsc.py#L274)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this under `with open() ...` ? Shouldn't it be in a normal context of this function? (I.e., I think you must de-indent by 4 spaces.)
</blockquote></details>

Done.
___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5SGC0E97o_dhMH7azb:b-5ce7e4) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Thanks for the log.

The problem is hinted at here:
```
n file included from ../sysdeps/unix/sysv/linux/x86_64/sysdep.h:29:0,
                 from ../sysdeps/x86_64/nptl/tls.h:28,
                 from ../include/link.h:51,
                 from <stdin>:1:
/home/intel/adarsh_opensuse/gramine/subprojects/glibc-2.40-1/../../libos/include/arch/x86_64/gramine_entry_api.h:52:48: error: ‘naked’ attribute directive ignored [-Werror=attributes]
                                                unsigned long arg2 __attribute__((unused))) {
                                                ^~~~~~~~
/home/intel/adarsh_opensuse/gramine/subprojects/glibc-2.40-1/../../libos/include/arch/x86_64/gramine_entry_api.h: In function ‘gramine_call’:
/home/intel/adarsh_opensuse/gramine/subprojects/glibc-2.40-1/../../libos/include/arch/x86_64/gramine_entry_api.h:58:1: error: no return statement in function returning non-void [-Werror=return-type]
 }
 ^
```

The root cause is that OpenSUSE 15.x uses **super-old GCC 7** as the default GCC. See e.g. [this discussion](https://documentation.suse.com/sbp/server-linux/html/SBP-GCC-11/index.html).

Now GCC 7 is so old that it doesn't support the `naked` attribute. Its support was added only in GCC 8, [see here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25967#c18).

So I think we must force OpenSUSE to switch to GCC 11, which is also found in OpenSUSE 15.x. According to this [official tutorial](https://documentation.suse.com/sbp/server-linux/html/SBP-GCC-11/index.html#sec-gcc11-overview), it should be enough to `zypper install gcc11 gcc11-c++` (after you added the subscription, which you did).

Now how to force OpenSUSE to switch to GCC 11 after it is installed? I think it should be enough to add:
```
export AS=/usr/bin/gcc-11
export CC=/usr/bin/gcc-11
export CXX=/usr/bin/g++-11
```
in the Dockerfile.compile of OpenSUSE, see my other note.
</blockquote></details>

I followed your instructions above but am still facing the same issue. Probably, the env variables are set back to their original values during gramine installation as in the file `gramine/subprojects/packagefiles/glibc-2.40/compile.sh.`
has following lines
CC\=gcc

CXX\=g++

AS\=gcc
Sending the updated codes
___
*[`templates/suse/Dockerfile.compile.template` line 48 at r11](https://reviewable.io/reviews/gramineproject/gsc/211#-O5S58S80oyzN9J5It9v:-O5WMSVmCIT9k8FHGo03:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/74bab51c96225bf7884ea03a941c1f87b3b732aa/templates/suse/Dockerfile.compile.template#L48)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think you should also add GCC-11 installation here, and the `export AS= export CC= export CXX=` lines here. See my other note on Glibc build.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-30 07:52 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @woju)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5XGDEU86A5W5WMxdXo:b-a678l4) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I followed your instructions above but am still facing the same issue. Probably, the env variables are set back to their original values during gramine installation as in the file `gramine/subprojects/packagefiles/glibc-2.40/compile.sh.`
has following lines
CC\=gcc

CXX\=g++

AS\=gcc
Sending the updated codes
</blockquote></details>

Yes, I agree, the problem seems to be in these hard-coded lines of Glibc script: https://github.com/gramineproject/gramine/blob/ca534cea27bff7a13e2127c8db0b77e676f6b7de/subprojects/packagefiles/glibc-2.40/compile.sh#L19-L21

I propose another approach then, with `sudo update-alternatives`, see my other comment.
___
*[`templates/suse/Dockerfile.compile.template` line 11 at r12](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XFqZd75Fo2HVr2kR0:-O5XFqZe9SsZWNf5eCHH:b-3h4o0r) ([raw file](https://github.com/gramineproject/gsc/blob/60fbe4710517482507b26faa19880abb40373ff2/templates/suse/Dockerfile.compile.template#L11)):*
> ```
> ENV AS=/usr/bin/gcc-11
> ENV CC=/usr/bin/gcc-11
> ENV CXX=/usr/bin/g++-11
> ```

Ok, this apparently doesn't work so you can remove this.
___
*[`templates/suse/Dockerfile.compile.template` line 53 at r12](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XG-JG9ML7278MoSqC:-O5XG-JG9ML7278MoSqD:boxw7ei) ([raw file](https://github.com/gramineproject/gsc/blob/60fbe4710517482507b26faa19880abb40373ff2/templates/suse/Dockerfile.compile.template#L53)):*
> ```
>         which \
>     && /usr/bin/python3 -B -m pip install 'tomli-w>=0.4.0'
> ```

Please try adding these lines here:
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 10
```

This should update `gcc` and `g++` binaries to version 11 (that you just installed above).


<!-- Sent from Reviewable.io -->

2024-08-30 08:54 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @woju)

___
*[`templates/Dockerfile.common.compile.template` line 34 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44R54q6SU71ySqTsjv:-O5XRAxv5LrimJ8Kejzy:bmfxpif) ([raw file](https://github.com/gramineproject/gsc/blob/7702bf7407c4cb5c96f8dfa32919ab79cde1e943/templates/Dockerfile.common.compile.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, I agree, the problem seems to be in these hard-coded lines of Glibc script: https://github.com/gramineproject/gramine/blob/ca534cea27bff7a13e2127c8db0b77e676f6b7de/subprojects/packagefiles/glibc-2.40/compile.sh#L19-L21

I propose another approach then, with `sudo update-alternatives`, see my other comment.
</blockquote></details>

Done.
___
*[`templates/suse/Dockerfile.compile.template` line 11 at r12](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XFqZd75Fo2HVr2kR0:-O5XOW2SBeedtBwo5MD2:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/60fbe4710517482507b26faa19880abb40373ff2/templates/suse/Dockerfile.compile.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, this apparently doesn't work so you can remove this.
</blockquote></details>

Done.
___
*[`templates/suse/Dockerfile.compile.template` line 53 at r12](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XG-JG9ML7278MoSqC:-O5XS0-F0Kbi6aaQ3ndY:b-fuc52n) ([raw file](https://github.com/gramineproject/gsc/blob/60fbe4710517482507b26faa19880abb40373ff2/templates/suse/Dockerfile.compile.template#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please try adding these lines here:
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 10
```

This should update `gcc` and `g++` binaries to version 11 (that you just installed above).
</blockquote></details>

Done.
Great solution. The build is now successful!
I can now remove the musl flag for building SUSE Images.


<!-- Sent from Reviewable.io -->

2024-08-30 09:07 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XXFxi5oSw22b8O_-Q:-O5XXFxi5oSw22b8O_-R:b-ni907k) (no related file):*
Ok, I'm approving this PR (the changes to the commit message we can do for the final merge).

IIUC, @woju is also approving (or at least not having objections to the PR). @mkow should also check I guess.

@anjalirai-intel Is this something that is/will be added to the CI?

___
___
*[`templates/suse/Dockerfile.compile.template` line 53 at r12](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XG-JG9ML7278MoSqC:-O5XXC-3CtZYpO5sBKiO:b903kkx) ([raw file](https://github.com/gramineproject/gsc/blob/60fbe4710517482507b26faa19880abb40373ff2/templates/suse/Dockerfile.compile.template#L53)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Great solution. The build is now successful!
I can now remove the musl flag for building SUSE Images.
</blockquote></details>

Awesome :)


<!-- Sent from Reviewable.io -->

2024-08-30 12:04 UTC, woju submitted a review, later dismissed
> Reviewed 1 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XXFxi5oSw22b8O_-Q:-O5Y9xP065dvag7y5kRZ:bj4rlhq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ok, I'm approving this PR (the changes to the commit message we can do for the final merge).

IIUC, @woju is also approving (or at least not having objections to the PR). @mkow should also check I guess.

@anjalirai-intel Is this something that is/will be added to the CI?
</blockquote></details>

Yes, I approve.

___


<!-- Sent from Reviewable.io -->

2024-08-30 13:22 UTC, mkow requested changes
> Reviewed 2 of 9 files at r1, 1 of 2 files at r7, 2 of 3 files at r9, 1 of 2 files at r11, 1 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel, @anjalirai-intel, and @dimakuv)

___
*[`gsc.py` line 120 at r13](https://reviewable.io/reviews/gramineproject/gsc/211#-O5YNwk0EqD8a9aQq5RV:-O5YNwk0EqD8a9aQq5RW:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/44836fd7c8e23864087302c8ec472b0f9cc22d01/gsc.py#L120)):*
> ```Python
>     env_list = config['Env']
>     if env_list is None:
>         return ''
> ```





_Suggestion:_
```Python
    env_list = config['Env'] or []
```
___
*[`gsc.py` line 288 at r13](https://reviewable.io/reviews/gramineproject/gsc/211#-O5YP8F9B0tTVMkxZoKf:-O5YP8F9B0tTVMkxZoKg:b-umfv3z) ([raw file](https://github.com/gramineproject/gsc/blob/44836fd7c8e23864087302c8ec472b0f9cc22d01/gsc.py#L288)):*
> ```Python
> 
> def get_sles_version(distro):
>     match_ = re.match(r'^registry.suse.com/suse/sle(\d+):(\d+).(\d+)$', distro)
> ```

No need to concatenate the dot manually then (in the code below).



_Suggestion:_
```Python
(\d+.\d+)
```


<!-- Sent from Reviewable.io -->

2024-09-02 04:21 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XXFxi5oSw22b8O_-Q:-O5ktinE1zaihdEeKD5k:b-896fix) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Yes, I approve.
</blockquote></details>

Done.

___
___
*[`gsc.py` line 120 at r13](https://reviewable.io/reviews/gramineproject/gsc/211#-O5YNwk0EqD8a9aQq5RV:-O5ktssO3DdidP_S3aU6:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/44836fd7c8e23864087302c8ec472b0f9cc22d01/gsc.py#L120)):*
> ```Python
>     env_list = config['Env']
>     if env_list is None:
>         return ''
> ```

Done.
___
*[`gsc.py` line 288 at r13](https://reviewable.io/reviews/gramineproject/gsc/211#-O5YP8F9B0tTVMkxZoKf:-O5kxBvh45OGWuNqOH6A:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/44836fd7c8e23864087302c8ec472b0f9cc22d01/gsc.py#L288)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No need to concatenate the dot manually then (in the code below).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-02 07:39 UTC, dimakuv reviewed
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @mkow)



<!-- Sent from Reviewable.io -->

2024-09-02 14:14 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @dimakuv)



<!-- Sent from Reviewable.io -->

2024-09-02 18:00 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/211#-O5XXFxi5oSw22b8O_-Q:-O5ntFhH9BofgmthyF-f:b-2d9jgi) (no related file):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

FYI: Currently waiting on @anjalirai-intel  to report the results of CI.

___


<!-- Sent from Reviewable.io -->

2024-09-03 06:23 UTC, anjalirai-intel commented
@dimakuv The workload runs were successful on OpenSUSE, with no issues to report.

2024-09-03 06:33 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 3 unresolved discussions, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-09-03 06:39 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)

___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44Pm-x25LJyGXhFlWp):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Done
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44PqyYDBu_6vM8w6D7):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Updated PR title and description to use `openSUSE Leap 15.6` and `SLE 15 SP4`.
</blockquote></details>

Done
___
*[`-- commits` line 3 at r1](https://reviewable.io/reviews/gramineproject/gsc/211#-O44QFNW8N8BHqtgYoxY):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-09-03 14:42 UTC, woju submitted a review, later dismissed
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: all files reviewed, 3 unresolved discussions (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-09-03 15:08 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 4 at r15](https://reviewable.io/reviews/gramineproject/gsc/211#-O5sOVjf3oALDDCFYT2j):*
typo, but it's just the commit message body so I won't block



_Suggestion:_
```
This commit adds support
```


<!-- Sent from Reviewable.io -->

2024-09-03 18:01 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`-- commits` line 4 at r15](https://reviewable.io/reviews/gramineproject/gsc/211#-O5sOVjf3oALDDCFYT2j):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

typo, but it's just the commit message body so I won't block
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-04 01:42 UTC, mkow submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 01:48 UTC, mkow approved these changes
Ok, one more formatting fix, I noticed that when merging.
@dimakuv: Please re-check.

> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211#-:-O5uhwRI2vuJenTfbv9r:bvx78ia)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2024-09-04 06:16 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/211)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-09-04 06:19 UTC, merged

2024-09-09 09:12 UTC, adarshanand67 commented
Customers must ensure that the read permission is given to the credentials file `/etc/zypp/credentials.d/SCCcredentials` so that the gsc codebase can read and copy the credentials from the host to the docker image by running :- 

`chmod 666 /etc/zypp/credentials.d/SCCcredentials`

2024-09-09 11:51 UTC, mkow commented
That's a terrible advice, that command makes the credentials readable by anyone on the system.