Fix installation of Gramine DCAP support on Ubuntu
gramineproject/gsc pull request #216
Opened 2024-09-27 09:48 UTC by dimakuv

## Description of the changes 

Commit 7620ef04 "Add support for SLES 15 SP4" introduced a bug in `Dockerfile.common.compile.template`. Instead of enabling Gramine DCAP support when the distro name starts with "ubuntu", the commit changed it to exactly equal to "ubuntu". This resulted in Gramine DCAP support always being disabled because `template_path(Distro)` returned strings like "ubuntu:22.04".

## How to test this PR? 

Try any Ubuntu distro.

2024-09-27 10:33 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/216)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[`templates/Dockerfile.common.compile.template` line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/216#-O7n1Y-XDT19hRP7eb_7:-O7n1Y-XDT19hRP7eb_8:b-p8tw82) ([raw file](https://github.com/gramineproject/gsc/blob/46170dc4e84ff9d41f36896b9f0ac82eeedd3f61/templates/Dockerfile.common.compile.template#L33)):*
> ```
>        --buildtype={{buildtype}} \
>        -Ddirect=enabled -Dsgx=enabled \
>        {% if template_path(Distro).startswith('ubuntu') %}-Ddcap=enabled{% endif %} \
> ```

If it's `ubuntu:VER` then it should be `.startswith('ubuntu:')` to match exactly what we want.


<!-- Sent from Reviewable.io -->

2024-09-27 10:46 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/216)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[`templates/Dockerfile.common.compile.template` line 33 at r1](https://reviewable.io/reviews/gramineproject/gsc/216#-O7n1Y-XDT19hRP7eb_7:-O7n4_Uf30e-mOUUUN2q:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/46170dc4e84ff9d41f36896b9f0ac82eeedd3f61/templates/Dockerfile.common.compile.template#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If it's `ubuntu:VER` then it should be `.startswith('ubuntu:')` to match exactly what we want.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-27 11:46 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/216)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2024-10-07 10:18 UTC, woju approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/216)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-07 10:18 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/216)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-10-07 11:01 UTC, merged