Remove support for older distros
gramineproject/gsc pull request #226
Opened 2024-11-15 05:08 UTC by adarshan-intel

## Description of the changes 

Removed support for older distros like ubuntu:21.04, ubuntu:23.04, debian:10, centos:8, debian:11, ubuntu:20.04 from the GSC config.yaml.template as part of local CI clean-up.

## How to test this PR? 

Ensure that the GSC build and deployment processes work correctly with the updated list of supported distros.

2024-11-19 05:47 UTC, adarshan-intel commented
@mkow @woju Can you review?

2024-11-28 08:01 UTC, adarshan-intel commented
@woju @mkow Please review

2024-12-04 10:15 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`config.yaml.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/226#-ODG96UKD_VoAufjKDsa:-ODG96UKD_VoAufjKDsb:b-dcmub) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/config.yaml.template#L8)):*
> ```
> # Currently supported distros are:
> # - ubuntu:20.04, ubuntu:21.04, ubuntu:22.04, ubuntu:23.04
> # - debian:10, debian:11, debian:12
> ```

Why `debian:11` is being dropped? It's still supported by Gramine project.

Why `ubuntu:24.04` is not supported?


<!-- Sent from Reviewable.io -->

2024-12-05 13:07 UTC, woju reviewed
@adarshan-intel The review already started, I've asked you a question in the review. Please engage with the question instead of pinging me.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226#-:-ODLvNLGDamrUBZAlO0o:bd3hcwg)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)



<!-- Sent from Reviewable.io -->

2024-12-06 04:19 UTC, adarshan-intel reviewed
@woju Alright I did not make myself clear. Have added a note here.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226#-:-ODPBQz25IZZqqB684j2:bxa2iac)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`config.yaml.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/226#-ODG96UKD_VoAufjKDsa:-ODPBAkEAkTDmx5cRzwR:b-qqxqdn) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/config.yaml.template#L8)):*

> Why `ubuntu:24.04` is not supported?

Have added `ubuntu:24.04` in config.yaml.templates, 

> Why `debian:11` is being dropped? It's still supported by Gramine project.

Debian 11 is being removed as discussed in PDT Meeting, it doesn't come under the list of supported distros.


<!-- Sent from Reviewable.io -->

2024-12-06 04:59 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: 0 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`config.yaml.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/226#-ODG96UKD_VoAufjKDsa:-ODPKPtZ7MHijHXvXPp2:b-3pyb2h) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/config.yaml.template#L8)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

> Why `ubuntu:24.04` is not supported?

Have added `ubuntu:24.04` in config.yaml.templates, 

> Why `debian:11` is being dropped? It's still supported by Gramine project.

Debian 11 is being removed as discussed in PDT Meeting, it doesn't come under the list of supported distros.
</blockquote></details>

@woju  - This is based on @mkow  suggestion to deprecate distros aggressively to minimize maintenance burden. @mkow  - What say keep deb 11?
All clients I track are on Deb 12 already.


<!-- Sent from Reviewable.io -->

2024-12-06 11:38 UTC, woju requested changes
Sure, thanks!

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226#-:-ODQktNx0BFJX9yH0Lju:bkf6n0q)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`config.yaml.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/226#-ODG96UKD_VoAufjKDsa:-ODQjv2J2FlwhhApOKMY:bry436v) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/config.yaml.template#L8)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

@woju  - This is based on @mkow  suggestion to deprecate distros aggressively to minimize maintenance burden. @mkow  - What say keep deb 11?
All clients I track are on Deb 12 already.
</blockquote></details>

IIUC @mkow was talking about distros not supported by Gramine itself. Gramine supports Debian 12 and 11 (for about half a year, until release of `trixie`, which will happen around July 2025 I think).

So `debian:10` rightfully goes away, but not `debian:11`.


<!-- Sent from Reviewable.io -->

2024-12-09 07:10 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: 3 of 5 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @woju)

___
*[`config.yaml.template` line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/226#-ODG96UKD_VoAufjKDsa:-ODeFGG5-V7fftpJz7ed:b9sz6mb) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/config.yaml.template#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

IIUC @mkow was talking about distros not supported by Gramine itself. Gramine supports Debian 12 and 11 (for about half a year, until release of `trixie`, which will happen around July 2025 I think).

So `debian:10` rightfully goes away, but not `debian:11`.
</blockquote></details>

Keeping `debian:11` in the latest fixup commit


<!-- Sent from Reviewable.io -->

2024-12-09 17:55 UTC, woju submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-10 01:20 UTC, kailun-qin approved these changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-16 05:42 UTC, adarshan-intel commented
Can we merge this?

2024-12-22 17:23 UTC, mkow requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`test/README.rst` line 33 at r3](https://reviewable.io/reviews/gramineproject/gsc/226#-OEjNiJI7hCbNSdFZKBe:-OEjNiJI7hCbNSdFZKBf:b-k80gu9) ([raw file](https://github.com/gramineproject/gsc/blob/c46c1f52a1a66b98794deea0a01ffcb98a68c39f/test/README.rst#L33)):*
> ```reStructuredText
>    cd ..
> 
>    docker build --tag ubuntu22.04-bash --file test/ubuntu22.04-bash.dockerfile .
> ```

Could we advertise 24.04 instead? It's newer, we shouldn't suggest people to start with an older distro because it will be deprecated sooner.


<!-- Sent from Reviewable.io -->

2025-01-06 05:10 UTC, adarshan-intel commented
*[`test/README.rst` line 33 at r3](https://reviewable.io/reviews/gramineproject/gsc/226#-OEjNiJI7hCbNSdFZKBe:-OFu-URS08RupmFzhc_X:b7zxzqm) ([raw file](https://github.com/gramineproject/gsc/blob/c46c1f52a1a66b98794deea0a01ffcb98a68c39f/test/README.rst#L33)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could we advertise 24.04 instead? It's newer, we shouldn't suggest people to start with an older distro because it will be deprecated sooner.
</blockquote></details>

Done
Have updated docker files and manifest to the latest 24.04 


<!-- Sent from Reviewable.io -->

2025-01-06 15:37 UTC, mkow approved these changes
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/226#-OFwFSv-21xHFzvyObUz:-OFwFSv-21xHFzvyObV-:b-qmnmhi) (no related file):*
FYI: There are still some examples left on 20.04, we should also update them to 24.04, but in separate PRs.


<!-- Sent from Reviewable.io -->

2025-01-06 15:40 UTC, kailun-qin approved these changes
> Reviewed 4 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2025-01-06 16:42 UTC, kailun-qin approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-06 17:43 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/226)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2025-01-07 02:05 UTC, merged