Update GSC with Gramine's new SGX Driver Requirements
gramineproject/gsc pull request #228
Opened 2024-11-27 06:33 UTC by adarshan-intel

## Description of the changes 
This PR updates GSC for new SGX driver requirements, modifying Dockerfile and entry point templates for CentOS and Debian.
Removes -Dsgx_driver, -Dsgx_driver_include_path options while building gramine
For more info read https://github.com/gramineproject/gramine/pull/2061

Fixes #227 

## How to test this PR? 
CI

2024-11-28 08:02 UTC, adarshan-intel commented
@woju @mkow Please review

2024-12-02 00:58 UTC, anirbanbasu commented
These changes now result in `meson.build:108:7: ERROR: C header 'asm/sgx.h' not found` -- I am not sure what am I missing.

2024-12-02 04:13 UTC, adarshan-intel reviewed
Can you go through this PR - [Remove support for OOT (out-of-tree) SGX driver by woju · Pull Request #2061 · gramineproject/gramine](https://github.com/gramineproject/gramine/pull/2061)
It has explanation of why this could be failing, probably older kernel?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228#-:-OD4XKoL9znlu9NYaNOI:bm49eqv)* status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-02 04:54 UTC, anirbanbasu commented
> Can you go through this PR - [Remove support for OOT (out-of-tree) SGX driver by woju · Pull Request #2061 · gramineproject/gramine](https://github.com/gramineproject/gramine/pull/2061) It has explanation of why this could be failing, probably older kernel?
> 
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228#-:-OD4XKoL9znlu9NYaNOI:bm49eqv)_ status: 0 of 4 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners

Thanks @adarshan-intel, I am using the 6.8.0-40-generic kernel -- thus, `asm/sgx.h` should be available to meson on line 108 of the meson build (https://github.com/gramineproject/gramine/blob/5789620a6d04208e5803321953e09eca2c24dd7b/meson.build#L108), isn't it?

2024-12-02 08:04 UTC, adarshan-intel commented
@woju Do you have an idea how to proceed with this?

2024-12-02 10:03 UTC, woju commented
> @woju Do you have an idea how to proceed with this?

The correct solution is to install `linux-libc-dev` package that needs to match kernel >= 5.11, provided that distro ships recent enough version (all distros supported by Gramine do). On which distros this error happens?

(Downloading the header from the Internet and copying it into `/usr/include` is not a correct solution).

2024-12-02 10:13 UTC, anirbanbasu commented
@adarshan-intel, downloading to `/usr/include` does not throw the `asm/sgx.h` not found error. It builds but the built container does not execute -- it may be some other application-level error, which I need to investigate. I see that you have changed some other files but I have not tried those changes yet.

@woju, this is happening on Ubuntu and Debian. Should I install `linux-libc-dev` on my application container?

2024-12-02 10:19 UTC, anirbanbasu commented
While the build process succeeds, I get a separate error when starting the built container as `[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)` but I am inclined to believe that this is some misconfiguration at my application level.

2024-12-02 13:46 UTC, anirbanbasu commented
> While the build process succeeds, I get a separate error when starting the built container as `[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)` but I am inclined to believe that this is some misconfiguration at my application level.

Just to make sure that this comment of mine does not confuse anyone, this turned out to be a misconfiguration in my application, which has now been dealt with.

2024-12-02 14:30 UTC, woju commented
> @woju, should this (https://github.com/gramineproject/gsc/blob/master/templates/Dockerfile.common.compile.template) not be the one to install `linux-libc-dev`?

It should be installed in templates that derive from this one, because package installation is different in different distributions (i.e. in this `apt-get install`: https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/debian/Dockerfile.compile.template#L7 and other distros have comparable commands that also need to be adjusted).

2024-12-02 16:06 UTC, adarshan-intel commented
The latest commit does what @woju said, to remove instllation of sgx.h from internet and use pacakges, I have tested on ubuntu, debian, centos and centos stream 9. Redhat and SLES validation are pending.

2024-12-03 01:53 UTC, anirbanbasu commented
> The latest commit [`e57fc97` (#228)](https://github.com/gramineproject/gsc/pull/228/commits/e57fc97323da1c1e3a0abec7796b1d30c822e045) does what @woju said, to remove instllation of sgx.h from internet and install from linux-libc-dev package that provides sgx.h,
> 
> I have tested basic runs on Ubuntu, Debian, CentOS, CentOS Stream 9, Red Hat, and SLES. Everything is running fine.

@adarshan-intel @woju in my case, this brought back the `ERROR: C header 'asm/sgx.h' not found` again, which can be fixed (again) by downloading `sgx.h` into `/usr/include`!

2024-12-03 04:41 UTC, adarshan-intel commented
@anirbanbasu The solution I mentioned seems like a bit of a hack and might not be the best approach. According to @woju I've added the necessary package to the `templates/debian/Dockerfile.compile.template` Docker file, which includes the `sgx.h` header. Since you're using Ubuntu or debian, `linux-libc-dev` should already be installed in the latest commit when you run `gsc build` which contains `sgx.h` package

@woju Is there something I am missing here?

2024-12-03 04:43 UTC, adarshan-intel commented
@anirbanbasu By the way, which Ubuntu version are you using? Is it 20.04, 22.04, or 24.04?

2024-12-03 05:00 UTC, anirbanbasu commented
> @anirbanbasu By the way, which Ubuntu version are you using? Is it 20.04, 22.04, 23.10 or 24.04? If you are using `Ubuntu 20.04` then this distro is not supported in further release cycle.

@adarshan-intel I am using Ubuntu 22.04.5 LTS.

2024-12-03 05:39 UTC, adarshan-intel commented
@anirbanbasu The changes I made should be working on Ubuntu 22.04.5. Everything looks good from my end, but let's wait for @woju's opinion to confirm.

2024-12-03 06:08 UTC, adarshan-intel commented
@anirbanbasu Could you share the logs with me? Also, template files to troubleshoot the issue?

2024-12-03 11:05 UTC, anirbanbasu commented
> @anirbanbasu Could you share the logs with me? Also, template files to troubleshoot the issue?

@adarshan-intel unfortunately, due to confidentiality reasons, I cannot.

The template file `templates/Dockerfile.common.compile.template` looks exactly like the one you have on this pull request except for internal proxy configuration that should be enabled within my network to have git pull from the Gramine repository. I also modified each and every other file the way you have in your pull request.

Regarding the logs, if I remove the manual download of `sgx.h` into `/usr/include/asm` then I get the same error as the original one I reported, i.e., `meson.build:108:7: ERROR: C header 'asm/sgx.h' not found`.

2024-12-03 11:14 UTC, anirbanbasu commented on templates/Dockerfile.common.compile.template
> -        https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/arch/x86/include/uapi/asm/sgx.h?h=v5.11 \
@adarshan-intel  Previously, this was downloading `sgx.h` from `uapi/asm/sgx.h` for `x86`. The `linux-libc-dev` package seems to have a number of these `sgx.h` (https://packages.debian.org/sid/all/linux-libc-dev/filelist). Could there be a conflict of includes? I am not too familiar with the internals of what's going on here, so I may be poking around in the dark.

2024-12-03 16:48 UTC, woju requested changes
Sorry to be blunt, but without seeing both logs and your actual changes (rather than relying on your descriptions of changes, because you might have made a typo), it's hard to tell anything about the reasons of the error you see. I've tested this PR's `./gsc build-gramine` with `debian:12`, works fine with regard to `<asm/sgx.h>`, so unless proven otherwise, I'm going to assume the problem is on your side.

```
woju@[...] ~/src/gsc [git||remotes/origin/pull/228/head] [17:36 4295]% ./gsc build-gramine asdf
/usr/local/lib/python3.8/dist-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Building base-Gramine Docker image `asdf`...
Step 1/8 : FROM debian:12 AS gramine
[...]
Step 8/8 : RUN cd /gramine     && meson setup build/ --prefix="/gramine/meson_build_output"        --buildtype=release        -Ddirect=enabled -Dsgx=enabled             && ninja -C build     && ninja -C build install

 ---> Running in 46f06c28de1e
The Meson build system
[...]
Has header "asm/sgx.h" : YES
[...]
 ---> 4c336f858e3c
Successfully built 4c336f858e3c
Successfully tagged asdf:latest
Successfully built a base-Gramine Docker image `asdf`.
```

Or am I missing something?

> Reviewed 2 of 3 files at r2, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228#-:-ODCNnzkArbEPROZIkT2:b-ug2l6p)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @anirbanbasu)

___
*[`templates/centos/Dockerfile.compile.template` line 22 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCIJVDAPEIifwstrBe:-ODCIJVDAPEIifwstrBf:b-kugtj) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/centos/Dockerfile.compile.template#L22)):*
> ```
>         git \
>         httpd \
>         kernel-devel \
> ```

This package needs to be `kernel-headers`. If you write `kernel-devel`, it will also install `kernel-headers` because of dependencies, (`kernel-devel` → `gcc` → `glibc-devel` → `kernel-headers`), but this is not what you want to write here.



_Suggestion:_
```
kernel-headers
```
___
*[`templates/centos/Dockerfile.compile.template` line 40 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCLbczD0rbT2gIWjmq:-ODCLbczD0rbT2gIWjmr:b-1q272z) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/centos/Dockerfile.compile.template#L40)):*
> ```
>         python3-protobuf \
>         rpm-build \
>         wget \
> ```

I think `wget` is not used anywhere else, apart from the section that downloaded `sgx.h`, which you just removed, so you can also remove `wget` installation (here and everywhere else).
___
*[`templates/suse/Dockerfile.compile.template` line 29 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJDHY0AhqmX5Ob9jB:-ODCJDHY0AhqmX5Ob9jC:b80h2hp) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/suse/Dockerfile.compile.template#L29)):*
> ```
>         gcc11-c++ \
>         git \
>         kernel-devel \
> ```

On SUSE it's called `linux-glibc-devel` (https://software.opensuse.org/package/linux-glibc-devel)



_Suggestion:_
```
linux-glibc-devel
```
___
*[`templates/debian/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJ3cWAM_kR2b62VX4:-ODCJ3cWAM_kR2b62VX5:b-piyqu0) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/debian/entrypoint.manifest.template#L4)):*
> ```
> 
> {% block loader %}
> loader.entrypoint = "file:/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/libsysdb.so"
> ```

ditto (put it in that second commit, together with the other entrypoint line)
___
*[`templates/redhat/ubi-minimal/Dockerfile.compile.template` line 28 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJA0q9NZa8-ENKH0w:-ODCJA0rD_NkckCCJtCZ:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/redhat/ubi-minimal/Dockerfile.compile.template#L28)):*
> ```
>         git \
>         httpd \
>         kernel-devel \
> ```





_Suggestion:_
```
kernel-headers
```
___
*[`templates/centos/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCItDo1D_rZ0EamLh0:-ODCItDo1D_rZ0EamLh1:b-ryilea) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/centos/entrypoint.manifest.template#L4)):*
> ```
> 
> {% block loader %}
> loader.entrypoint = "file:/gramine/meson_build_output/lib64/gramine/libsysdb.so"
> ```

This is unrelated change, needs to be in a separate commit.
___
*[`templates/centos/stream/Dockerfile.compile.template` line 21 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJ-iU-N2bTm5d8GVI:-ODCJ-iU-N2bTm5d8GVJ:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/centos/stream/Dockerfile.compile.template#L21)):*
> ```
>         git \
>         httpd \
>         kernel-devel \
> ```





_Suggestion:_
```
kernel-headers
```
___
*[`templates/redhat/ubi/Dockerfile.compile.template` line 28 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJ7YOEF_3liJIDeMX:-ODCJ7YOEF_3liJIDeMY:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/redhat/ubi/Dockerfile.compile.template#L28)):*
> ```
>         git \
>         httpd \
>         kernel-devel \
> ```





_Suggestion:_
```
kernel-headers
```


<!-- Sent from Reviewable.io -->

2024-12-03 16:48 UTC, woju commented on templates/Dockerfile.common.compile.template
> -        https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/plain/arch/x86/include/uapi/asm/sgx.h?h=v5.11 \
No, it's OK. Note they're in a directories named after compiler triplets (those things like `x86_64-linux-gnu`), so only one will be used at a time. It's fine.

Please use reviewable for discussions about PRs.
<!-- Reviewable comment -ODCGvnx4HWjOYUBrSM_:b-3yxdax -->
<!-- Sent from Reviewable.io -->

2024-12-04 00:35 UTC, anirbanbasu commented
> Sorry to be blunt, but without seeing both logs and your actual changes (rather than relying on your descriptions of changes, because you might have made a typo), it's hard to tell anything about the reasons of the error you see.

@woju, yes, understandable. I will check things at my end.

> Please use reviewable for discussions about PRs.

Okay!

2024-12-05 06:09 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 4 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anirbanbasu and @woju)

___
*[`templates/centos/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCItDo1D_rZ0EamLh0:-ODKQxhc0H8BpXhwbMwA:bky71e3) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/centos/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is unrelated change, needs to be in a separate commit.
</blockquote></details>

Done.
Removing this as of now 
___
*[`templates/debian/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJ3cWAM_kR2b62VX4:-ODKR-9n2a2qMBceim53:bky71e3) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/debian/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (put it in that second commit, together with the other entrypoint line)
</blockquote></details>

Done.
Removing this as of now 


<!-- Sent from Reviewable.io -->

2024-12-05 07:02 UTC, anirbanbasu reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 4 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @woju)

___
*[`templates/Dockerfile.common.compile.template` line 28 at r5](https://reviewable.io/reviews/gramineproject/gsc/228#-ODKa5WY4Ws7lvasSTaO:-ODKa5WY4Ws7lvasSTaP:b-9t05v4) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/Dockerfile.common.compile.template#L28)):*
> ```
>     && sha256sum sgx.h | grep -q a34a997ade42b61376b1c5d3d50f839fd28f2253fa047cb9c0e68a1b00477956
> {% endif %}
> ```

I did a clean check out of this PR and I am met with the same error as before. See the meson build excerpt below.

```
 ---> Running in 92a25c93b6ec
The Meson build system
Version: 1.6.0
Source dir: /gramine
Build dir: /gramine/build
Build type: native build
Project name: gramine
Project version: 1.8post~UNRELEASED
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
C++ linker for the host machine: c++ ld.bfd 2.35.2
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -std=c23: NO
Compiler for C supports arguments -std=c2x: YES
meson.build:28: WARNING: Consider using the built-in option for language standard version instead of using "-std=c2x".
Program check-no-reloc.sh found: YES (/gramine/scripts/check-no-reloc.sh)
Program gen-pal-map.py found: YES (/gramine/scripts/gen-pal-map.py)
Program get-python-platlib.py found: YES (/gramine/scripts/get-python-platlib.py)
Program meson-clang-format.sh found: YES (/gramine/scripts/meson-clang-format.sh)
Program meson-render-script.py found: YES (/gramine/scripts/meson-render-script.py)
Fetching value of define "__GLIBC__" : 2
Program objcopy found: YES (/usr/bin/objcopy)
Program python3 found: YES (/usr/bin/python3)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in meson 2.0.
         See also: https://github.com/mesonbuild/meson/issues/9300
Program nasm found: YES (/usr/bin/nasm)
Compiler for C supports arguments -Wtrampolines: YES
Compiler for C supports arguments -Wnull-dereference: YES
meson.build:85: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:85: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".

meson.build:108:7: ERROR: C header 'asm/sgx.h' not found

```


<!-- Sent from Reviewable.io -->

2024-12-05 08:51 UTC, anjalirai-intel commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)_ status: 4 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @woju)
> 
> _[`templates/Dockerfile.common.compile.template` line 28 at r5](https://reviewable.io/reviews/gramineproject/gsc/228#-ODKa5WY4Ws7lvasSTaO:-ODKa5WY4Ws7lvasSTaP:b-9t05v4) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/Dockerfile.common.compile.template#L28)):_
> 
> > ```
> >     && sha256sum sgx.h | grep -q a34a997ade42b61376b1c5d3d50f839fd28f2253fa047cb9c0e68a1b00477956
> > {% endif %}
> > ```
> 
> I did a clean check out of this PR and I am met with the same error as before. See the meson build excerpt below.
> 
> ```
>  ---> Running in 92a25c93b6ec
> The Meson build system
> Version: 1.6.0
> Source dir: /gramine
> Build dir: /gramine/build
> Build type: native build
> Project name: gramine
> Project version: 1.8post~UNRELEASED
> C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
> C linker for the host machine: cc ld.bfd 2.35.2
> C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
> C++ linker for the host machine: c++ ld.bfd 2.35.2
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Compiler for C supports arguments -std=c23: NO
> Compiler for C supports arguments -std=c2x: YES
> meson.build:28: WARNING: Consider using the built-in option for language standard version instead of using "-std=c2x".
> Program check-no-reloc.sh found: YES (/gramine/scripts/check-no-reloc.sh)
> Program gen-pal-map.py found: YES (/gramine/scripts/gen-pal-map.py)
> Program get-python-platlib.py found: YES (/gramine/scripts/get-python-platlib.py)
> Program meson-clang-format.sh found: YES (/gramine/scripts/meson-clang-format.sh)
> Program meson-render-script.py found: YES (/gramine/scripts/meson-render-script.py)
> Fetching value of define "__GLIBC__" : 2
> Program objcopy found: YES (/usr/bin/objcopy)
> Program python3 found: YES (/usr/bin/python3)
> WARNING: You should add the boolean check kwarg to the run_command call.
>          It currently defaults to false,
>          but it will default to true in meson 2.0.
>          See also: https://github.com/mesonbuild/meson/issues/9300
> Program nasm found: YES (/usr/bin/nasm)
> Compiler for C supports arguments -Wtrampolines: YES
> Compiler for C supports arguments -Wnull-dereference: YES
> meson.build:85: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
> meson.build:85: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
> 
> meson.build:108:7: ERROR: C header 'asm/sgx.h' not found
> ```

@anirbanbasu Can you also share logs where apt packages are getting installed

2024-12-05 09:38 UTC, anirbanbasu commented
> > > _[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)_ status: 4 of 11 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @woju)
> > 
> > 
> > _[`templates/Dockerfile.common.compile.template` line 28 at r5](https://reviewable.io/reviews/gramineproject/gsc/228#-ODKa5WY4Ws7lvasSTaO:-ODKa5WY4Ws7lvasSTaP:b-9t05v4) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/Dockerfile.common.compile.template#L28)):_
> > > ```
> > >     && sha256sum sgx.h | grep -q a34a997ade42b61376b1c5d3d50f839fd28f2253fa047cb9c0e68a1b00477956
> > > {% endif %}
> > > ```
> > 
> > 
> > I did a clean check out of this PR and I am met with the same error as before. See the meson build excerpt below.
> > ```
> >  ---> Running in 92a25c93b6ec
> > The Meson build system
> > Version: 1.6.0
> > Source dir: /gramine
> > Build dir: /gramine/build
> > Build type: native build
> > Project name: gramine
> > Project version: 1.8post~UNRELEASED
> > C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
> > C linker for the host machine: cc ld.bfd 2.35.2
> > C++ compiler for the host machine: c++ (gcc 10.2.1 "c++ (Debian 10.2.1-6) 10.2.1 20210110")
> > C++ linker for the host machine: c++ ld.bfd 2.35.2
> > Host machine cpu family: x86_64
> > Host machine cpu: x86_64
> > Compiler for C supports arguments -std=c23: NO
> > Compiler for C supports arguments -std=c2x: YES
> > meson.build:28: WARNING: Consider using the built-in option for language standard version instead of using "-std=c2x".
> > Program check-no-reloc.sh found: YES (/gramine/scripts/check-no-reloc.sh)
> > Program gen-pal-map.py found: YES (/gramine/scripts/gen-pal-map.py)
> > Program get-python-platlib.py found: YES (/gramine/scripts/get-python-platlib.py)
> > Program meson-clang-format.sh found: YES (/gramine/scripts/meson-clang-format.sh)
> > Program meson-render-script.py found: YES (/gramine/scripts/meson-render-script.py)
> > Fetching value of define "__GLIBC__" : 2
> > Program objcopy found: YES (/usr/bin/objcopy)
> > Program python3 found: YES (/usr/bin/python3)
> > WARNING: You should add the boolean check kwarg to the run_command call.
> >          It currently defaults to false,
> >          but it will default to true in meson 2.0.
> >          See also: https://github.com/mesonbuild/meson/issues/9300
> > Program nasm found: YES (/usr/bin/nasm)
> > Compiler for C supports arguments -Wtrampolines: YES
> > Compiler for C supports arguments -Wnull-dereference: YES
> > meson.build:85: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
> > meson.build:85: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
> > 
> > meson.build:108:7: ERROR: C header 'asm/sgx.h' not found
> > ```
> 
> @anirbanbasu Can you also share logs where apt packages are getting installed

@anjalirai-intel please see the excerpts below. The step or steps hidden due to confidentiality reasons are for configuring access to a proxy server so that `apt-get` and `git` can work behind the proxy.

```
Building unsigned graminized Docker image `[name-retracted-for-confidentiality]-unsigned` from original application image `[name-retracted-for-confidentiality]`...
Warning: Duplicate key `sgx.debug`. Overriding value from `debian/entrypoint.manifest.template` by the one in `[path-retracted-for-confidentiality].manifest`.
Warning: Duplicate key `loader.env.PATH`. Concatenating values from `<merged [path-retracted-for-confidentiality].manifest and debian/entrypoint.manifest.template>` and `<[name-retracted-for-confidentiality] image env>`.

Step 1/34 : FROM debian:11 AS gramine

 ---> 91a3af22c9b3
Step 2/34 : [step-retracted-for-confidentiality]

 ---> Using cache
 ---> 0b9aa5b4d593
Step 3/34 : RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y         autoconf         bison         build-essential         cmake         coreutils         curl         gawk         git         libprotobuf-c-dev         linux-libc-dev         linux-headers-generic         nasm         ninja-build         pkg-config         protobuf-c-compiler         protobuf-compiler         python3         python3-cryptography         python3-protobuf         wget            python3-pip            && /usr/bin/python3 -B -m pip install 'tomli>=1.1.0' 'tomli-w>=0.4.0' 'meson>=0.56,!=1.2.*'

 ---> Using cache
 ---> c09484fc96d2
Step 4/34 : COPY intel-sgx-deb.key /

 ---> Using cache
 ---> bb42690b5d69
Step 5/34 : RUN echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic main'     > /etc/apt/sources.list.d/intel-sgx.list     && apt-key add /intel-sgx-deb.key

 ---> Using cache
 ---> 11fd2f1f4919
Step 6/34 : RUN env DEBIAN_FRONTEND=noninteractive apt-get update     && env DEBIAN_FRONTEND=noninteractive apt-get install -y libsgx-dcap-quote-verify-dev

 ---> Using cache
 ---> 2a269044c833
Step 7-10/34 : [steps-retracted-for-confidentiality]

Step 11/34 : RUN git clone https://github.com/gramineproject/gramine.git /gramine

 ---> Using cache
 ---> 008cb588f8a8
Step 12/34 : RUN cd /gramine     && git fetch origin master     && git checkout master

 ---> Using cache
 ---> 5007eda930e9
Step 13/34 : RUN cd /gramine     && meson setup build/ --prefix="/gramine/meson_build_output"        --buildtype=release        -Ddirect=enabled -Dsgx=enabled             && ninja -C build     && ninja -C build install

```

2024-12-05 09:58 UTC, anjalirai-intel commented
@anirbanbasu In your logs, it is mentioned that you are using debian:11 `Step 1/34 : FROM debian:11 AS gramine` but you mentioned earlier that you are using ubuntu 22.04

Issue is reproducible on debian:11 workload image and also debian:11 distro will not be supported from gramine master.

sgx.h is not available as part of linux-libc-dev for debian 11 whereas it is present as part of debian 12

you can refer attached images
![debian11-linux-libc-dev](https://github.com/user-attachments/assets/dc60c4d4-c26f-4a1d-8d7b-c7412fd92c6a)
![debian12-linux-libc-dev](https://github.com/user-attachments/assets/977638b9-a692-4655-b92b-46b89f55c7af)

2024-12-05 10:43 UTC, anirbanbasu commented
> @anirbanbasu In your logs, it is mentioned that you are using debian:11 `Step 1/34 : FROM debian:11 AS gramine` but you mentioned earlier that you are using ubuntu 22.04
> 
> Issue is reproducible on debian:11 workload image and also debian:11 distro will not be supported from gramine master.
> 
> sgx.h is not available as part of linux-libc-dev for debian 11 whereas it is present as part of debian 12
> 
> you can refer attached images ![debian11-linux-libc-dev](https://private-user-images.githubusercontent.com/65150333/392759418-dc60c4d4-c26f-4a1d-8d7b-c7412fd92c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTQ3OTcsIm5iZiI6MTczMzM5NDQ5NywicGF0aCI6Ii82NTE1MDMzMy8zOTI3NTk0MTgtZGM2MGM0ZDQtYzI2Zi00YTFkLThkN2ItYzc0MTJmZDkyYzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEwMjgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNDZiYzhkNDg4OTU3YTE3ODljYjNhMDYwZmRkZDA1NjcyZmIwZDQ5NDgwODZjNDVkMTc1YWEwODNkYzcxN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VDObPkkPJBmBfv8b_2OWq6_JPzw-y1ByVGxlhr1AS1k) ![debian12-linux-libc-dev](https://private-user-images.githubusercontent.com/65150333/392759438-977638b9-a692-4655-b92b-46b89f55c7af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzOTQ3OTcsIm5iZiI6MTczMzM5NDQ5NywicGF0aCI6Ii82NTE1MDMzMy8zOTI3NTk0MzgtOTc3NjM4YjktYTY5Mi00NjU1LWI5MmItNDZiODlmNTVjN2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA1VDEwMjgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MzliYTYwNzkxNTkyMGE5MjYyMTQ5NDQ4Mjc1MTA0OWRjMWZkOTFjMTc4OGZhMGE2MGI5OWFlMTdlZGJkOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S2otLpl6sy5yVxNMN2tEJoCFHfN-Qi_3liV4t_snYQI)

@anjalirai-intel thanks, well spotted. My oversight there! Apologies.

However, where is this debian 11 being picked up from? Isn't it supposed to be the same base image that my non-Graminized image built from? In my case, that is `python:3.12.5-bookworm`, which is Debian 12?

2024-12-05 12:28 UTC, anirbanbasu commented
> However, where is this debian 11 being picked up from? Isn't it supposed to be the same base image that my non-Graminized image built from? In my case, that is python:3.12.5-bookworm, which is Debian 12?

Okay, it was specified in the default `config.yaml`. I have now specified Debian 12 in my app-specific `config.yaml`. There is no further error with `asm/sgx.h`. Apologies for the oversight. Thanks a lot for helping me with this, @adarshan-intel, @woju and @anjalirai-intel.

(I do have other errors now but I will check if they are at all related to this PR.)

2024-12-05 12:59 UTC, woju requested changes
> Reviewed 2 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 6 of 11 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel and @anjalirai-intel)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/228#-ODLtEhQ9jP01LU1obid:-ODLtEhR6gVSKO3MbBqz:bjaesrw) (no related file):*
@anirbanbasu @anjalirai-intel: Debian 11 has linux-libc-dev 6.1, but in `bullseye-backports` repository: https://packages.debian.org/bullseye-backports/linux-libc-dev

So either gsc needs to support `Distro: debian:bullseye-backports` (that would involve doing away with `distro[1] | int` in some way), or needs to detect version equal to `11` and add backports repo manually, like in this Dockerfile: https://github.com/debuerreotype/docker-debian-artifacts/blob/f5527c9b022448b28981cf274721d9749d8fc5c4/bullseye/backports/Dockerfile

Blocking on this.
___
*[`templates/centos/Dockerfile.compile.template` line 40 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCLbczD0rbT2gIWjmq:-ODLsU4fCf30UeqMPf1h:b7959fl) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/centos/Dockerfile.compile.template#L40)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, you didn't remove elsewhere.
___
*[`templates/centos/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCItDo1D_rZ0EamLh0:-ODLtnOGDehCfVG-7ewz:bvxsrga) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/centos/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Removing this as of now
</blockquote></details>

Not done, I don't see a separate commit in commit list that has different commit message that would propertly describe this change, there are only fixups.
___
*[`templates/debian/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJ3cWAM_kR2b62VX4:-ODLto28ClU4-TPBtE9N:b-1wjvw3) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/debian/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

Done.
Removing this as of now
</blockquote></details>

ditto (not done)


<!-- Sent from Reviewable.io -->

2024-12-06 02:42 UTC, anirbanbasu commented
@adarshan-intel @woju now I am facing this error, which is related to: https://github.com/gramineproject/gsc/pull/225

```
Traceback (most recent call last):
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 174, in <module>

    main() # pylint: disable=no-value-for-parameter
    ^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__

    return self.main(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main

    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke

    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke

    return __callback(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 26, in new_func

    return f(get_current_context(), *args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gramine/meson_build_output/bin/gramine-sgx-sign", line 130, in main

    manifest = Manifest.load(manifest_file)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gramine/meson_build_output/lib/python3.11/site-packages/graminelibos/manifest.py", line 388, in load

    return cls.loads(f.read())

           ^^^^^^^^^^^^^^^^^^^
  File "/gramine/meson_build_output/lib/python3.11/site-packages/graminelibos/manifest.py", line 384, in loads

    return cls(s)

           ^^^^^^
  File "/gramine/meson_build_output/lib/python3.11/site-packages/graminelibos/manifest.py", line 348, in __init__

    raise ManifestError('Unknown loader.entrypoint format (not a TOML table)')
graminelibos.manifest.ManifestError: Unknown loader.entrypoint format (not a TOML table)

```

2024-12-06 03:22 UTC, anirbanbasu commented
> I am facing this error, which is related to: https://github.com/gramineproject/gsc/pull/225

In addition, by updating the files as suggested in PR https://github.com/gramineproject/gsc/pull/225, my container compiles and runs fine.

2024-12-06 04:14 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 6 of 11 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`templates/centos/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCItDo1D_rZ0EamLh0:-ODP9ipB8R5sF-PBOeBA:b36dqko) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/centos/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not done, I don't see a separate commit in commit list that has different commit message that would propertly describe this change, there are only fixups.
</blockquote></details>

I want to clarify that PR #225 already implements this change, so I am not including it here. Once PR #225 is merged, this PR can proceed. Therefore, I am not adding any separate commit.
___
*[`templates/debian/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCJ3cWAM_kR2b62VX4:-ODPAIPAAyFzZ2KWYOyb:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/debian/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

ditto (not done)
</blockquote></details>

ditto


<!-- Sent from Reviewable.io -->

2024-12-06 04:55 UTC, adarshan-intel commented
*[`templates/centos/Dockerfile.compile.template` line 40 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCLbczD0rbT2gIWjmq:-ODPJXyM1ZNzPW-JiH2x:bw3qmfg) ([raw file](https://github.com/gramineproject/gsc/blob/e57fc97323da1c1e3a0abec7796b1d30c822e045/templates/centos/Dockerfile.compile.template#L40)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Not done, you didn't remove elsewhere.
</blockquote></details>

Done.
Remove wget from all templates


<!-- Sent from Reviewable.io -->

2024-12-06 04:56 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 5 of 13 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anirbanbasu, @anjalirai-intel, and @woju)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/228#-ODLtEhQ9jP01LU1obid:-ODPJpl30c5WukS4SKc4:b-v8wbfy) (no related file):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

@anirbanbasu @anjalirai-intel: Debian 11 has linux-libc-dev 6.1, but in `bullseye-backports` repository: https://packages.debian.org/bullseye-backports/linux-libc-dev

So either gsc needs to support `Distro: debian:bullseye-backports` (that would involve doing away with `distro[1] | int` in some way), or needs to detect version equal to `11` and add backports repo manually, like in this Dockerfile: https://github.com/debuerreotype/docker-debian-artifacts/blob/f5527c9b022448b28981cf274721d9749d8fc5c4/bullseye/backports/Dockerfile

Blocking on this.
</blockquote></details>

I will discuss this with Anees and get back to you.


<!-- Sent from Reviewable.io -->

2024-12-06 12:34 UTC, woju requested changes
> Reviewed 1 of 7 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel, @anirbanbasu, and @anjalirai-intel)

___
*[`templates/centos/entrypoint.manifest.template` line 4 at r4](https://reviewable.io/reviews/gramineproject/gsc/228#-ODCItDo1D_rZ0EamLh0:-ODQvqIt1DCymmFn6pKK:b4uuwan) ([raw file](https://github.com/gramineproject/gsc/blob/e57a501fe2e54692742876ac1cc3b81cfa24af86/templates/centos/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I want to clarify that PR #225 already implements this change, so I am not including it here. Once PR #225 is merged, this PR can proceed. Therefore, I am not adding any separate commit.
</blockquote></details>

OK, I understand. Yes, that makes sense, but in this case you should rebase the branch on top of that other branch (instead of adding another diff to a commit in this branch) and change the base of the PR in GitHub UI. Without doing that, it's not clear which branch should be merged on top of which one, and you run a risk that you'll have circular dependencies between several PRs. If you expliticly base the PRs on top of one another, then you won't make such a mistake, and we won't make a mistake when reviewing and merging.

Right now, if I'm counting correctly, we have 4 PRs against gsc repo with at least slightly overlapping scope (#223, #225, #226, #228) and it's not clear to me, in which order they should be merged, or if this matter at all. It's up to you to decide, I won't mind any particular order, as long as it won't break anything. If you're sure the order of those other PRs doesn't matter, you can leave them based on master, but at least this stuff needs to be adjusted.


<!-- Sent from Reviewable.io -->

2024-12-09 07:05 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 12 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @anjalirai-intel and @woju)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/228#-ODLtEhQ9jP01LU1obid:-ODeE2mn0k2jJWTMNxq2:bnhqicv) (no related file):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

I will discuss this with Anees and get back to you.
</blockquote></details>

In the latest commit 47dcb58c446b8eae34b6b97218be7254bedd9baa have done the 2nd method of adding backports repo manually by detecting the debian 11 version


<!-- Sent from Reviewable.io -->

2024-12-09 17:54 UTC, woju requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/228#-ODLtEhQ9jP01LU1obid:-ODgYIL_14E7jvVR7Lyd:b-ucfknh) (no related file):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

In the latest commit 47dcb58c446b8eae34b6b97218be7254bedd9baa have done the 2nd method of adding backports repo manually by detecting the debian 11 version
</blockquote></details>

Thanks!
___
*[`templates/debian/Dockerfile.compile.template` line 37 at r7](https://reviewable.io/reviews/gramineproject/gsc/228#-ODgEULsBWwPNtbyJrXW:-ODgEULtBkUwRTVoP0NC:bczija8) ([raw file](https://github.com/gramineproject/gsc/blob/47dcb58c446b8eae34b6b97218be7254bedd9baa/templates/debian/Dockerfile.compile.template#L37)):*
> ```
>         {%- endif %}
> 
> {%- if (distro[0] == "debian" and distro[1] | int == 11) %}
> ```

1. parens are unnecessary (I suppose you copy-pasted a bit too much from above). 
2. The repo should be added before `apt-get install` above I think (just below `{% set distro %}`). If you do that, then you can also install meson, tomli, and tomli-w from the backports repo.

(the logic itself is OK)



_Suggestion:_
```
distro[0] == "debian" and distro[1] | int == 11
```


<!-- Sent from Reviewable.io -->

2024-12-10 05:42 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 12 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`templates/debian/Dockerfile.compile.template` line 37 at r7](https://reviewable.io/reviews/gramineproject/gsc/228#-ODgEULsBWwPNtbyJrXW:-ODj1DjTBSchVFcsPePQ:b-y6s5me) ([raw file](https://github.com/gramineproject/gsc/blob/47dcb58c446b8eae34b6b97218be7254bedd9baa/templates/debian/Dockerfile.compile.template#L37)):*
> 1. parens are unnecessary (I suppose you copy-pasted a bit too much from above).

Removed brackets

> 2.  The repo should be added before `apt-get install` above I think (just below `{% set distro %}`). If you do that, then you can also install meson, tomli, and tomli-w from the backports repo.
Have moved  `{%- if (distro[0] == "debian" and distro[1] | int == 11) %}` logic just below `{% set distro %}`

Yes I moved the logic part below `{% set distro %}`, if distro is `debian:11` then pull the linux headers from the backports repos, for all other distros `debian:12` and ubuntu packages it pulls from normal repos.


<!-- Sent from Reviewable.io -->

2024-12-10 05:44 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: 12 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @woju)

___
*[`templates/debian/Dockerfile.compile.template` line 37 at r7](https://reviewable.io/reviews/gramineproject/gsc/228#-ODgEULsBWwPNtbyJrXW:-ODj4y_g1XsZcDHqE3zc:b-j28doy) ([raw file](https://github.com/gramineproject/gsc/blob/47dcb58c446b8eae34b6b97218be7254bedd9baa/templates/debian/Dockerfile.compile.template#L37)):*
<details><summary><i>Previously, adarshan-intel (Adarsh Anand) wrote…</i></summary><blockquote>

> 1. parens are unnecessary (I suppose you copy-pasted a bit too much from above).

Removed brackets

> 2.  The repo should be added before `apt-get install` above I think (just below `{% set distro %}`). If you do that, then you can also install meson, tomli, and tomli-w from the backports repo.
Have moved  `{%- if (distro[0] == "debian" and distro[1] | int == 11) %}` logic just below `{% set distro %}`

Yes I moved the logic part below `{% set distro %}`, if distro is `debian:11` then pull the linux headers from the backports repos, for all other distros `debian:12` and ubuntu packages it pulls from normal repos.
</blockquote></details>

Also updating `linux-headers-generic` to `linux-libc-dev` package for installing kernel headers as both packages cannot be used together due to mismatch


<!-- Sent from Reviewable.io -->

2024-12-11 13:05 UTC, woju approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-11 23:04 UTC, anirbanbasu reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-12 04:47 UTC, adarshan-intel commented
@woju @kailun-qin Can you review?

2024-12-12 14:34 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-12 16:58 UTC, kailun-qin approved these changes
> Reviewed 2 of 3 files at r2, 1 of 9 files at r4, 3 of 7 files at r5, 6 of 7 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2024-12-12 18:47 UTC, mkow approved these changes
> Reviewed 2 of 3 files at r2, 1 of 9 files at r4, 3 of 7 files at r5, 6 of 7 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @adarshan-intel)

___
*[`-- commits` line 3 at r8](https://reviewable.io/reviews/gramineproject/gsc/228#-ODw9fnlCfGnsquBGn6G:-ODw9fnlCfGnsquBGn6H:b-o9kr68):*
Please Don't Capitalize Every Word In A Sentence :)



_Suggestion:_
```
Update GSC with Gramine's new SGX driver requirements
```


<!-- Sent from Reviewable.io -->

2024-12-13 04:51 UTC, adarshan-intel reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[`-- commits` line 3 at r8](https://reviewable.io/reviews/gramineproject/gsc/228#-ODw9fnlCfGnsquBGn6G:-ODyKlp6Bqoj86i0MNUx:bq4d6ro):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please Don't Capitalize Every Word In A Sentence :)
</blockquote></details>

Done.
Have updated the commit message and rebased PR


<!-- Sent from Reviewable.io -->

2024-12-13 06:03 UTC, kailun-qin approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-12-16 05:40 UTC, adarshan-intel commented
Can we merge this?

2024-12-18 05:26 UTC, adarshan-intel commented
Any more pending action items on this PR ?
@woju @kailun-qin @mkow

2024-12-19 15:05 UTC, kailun-qin approved these changes
> Any more pending action items on this PR ?

No action item. Let's just wait a bit for mkow to unblock his last comment.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228#-:-OEUQmi-4g_MKbzn0xUj:b-hc3uaw)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2024-12-22 16:58 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/228)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-12-22 17:16 UTC, merged

2024-12-23 11:46 UTC, anirbanbasu commented
@adarshan-intel @woju after pulling the latest commit from the repository, now, I get the error at the `gsc-sign-image` stage:

```console
graminelibos.manifest.ManifestError: Unknown loader.entrypoint format (not a TOML table)
```

What did I do wrong? I haven't changed any of my configurations or code. Or, what am I missing that the updated GSC needs?