Use proper TOML parser instead of ad-hoc string-based parsing
gramineproject/gsc pull request #26
Opened 2021-10-22 20:18 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 
This PR fixes the toml duplicate entry error seen during gsc sign-image step.  Previously, our ad-hoc string-based TOML parser could not correctly handle cases like the following (the parser simply concatenated contents of two files which resulted in duplicate `sgx.trusted_files` TOML key, which is prohibited):

    # entrypoint.manifest.template contains the following snippet
    sgx.trusted_files = [
      "file:/trusted_argv",
    ]

    # application-specific manifest contains the following snippet
    sgx.trusted_files = [
      "file:app_specific_file",
    ]

This PR merges data from templates/entrypoint.manifest.template and application-specific manifest , and creates unique entries  ( by updating gsc.py).
Also, the auto-generated trusted files are correctly merged into sgx.trusted_files [] (by updating finalize_manifest.py).

**Note:** Old dictionary based format for trusted_files , allowed_files, and protected_files keys is still supported.
                 sgx.allowed_files.file1 = "file:files/plain.txt"    // still supported by gsc.

## How to test this PR? 
Gsc build and sign steps should work smoothly.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gsc/26)

2021-11-08 10:12 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: 3 of 4 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

___
*[gsc.py, line 218 at r4](https://reviewable.io/reviews/gramineproject/gsc/26#-Mn4nz_J0GYcKS-vKA1m:-Mnz0kuv18toZylNtDRj:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/1e16d1e822e53b1fa95233e1788db70d0766a61a/gsc.py#L218)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, this is hard to read. Can we switch to the way I suggested?
</blockquote></details>

done, thanks.
___
*[gsc.py, line 211 at r5](https://reviewable.io/reviews/gramineproject/gsc/26#-Mn54EavDXpOYQFGq3hK:-Mnz0sUw0FUpYs4ATiBB:b-qo8254) ([raw file](https://github.com/gramineproject/gsc/blob/8b84f240f5dde96c08c60e834bc91f8fadc6374b/gsc.py#L211)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you split this in two statements then?
```
        entrypoint_manifest_render = env.get_template('entrypoint.manifest.template').render()
        entrypoint_manifest_dict = toml.loads(entrypoint_manifest_render)
```
</blockquote></details>

done, thanks. Sorry I forgot to reply here, though pushed the  changes 11 days ago only.


<!-- Sent from Reviewable.io -->

2021-11-09 07:53 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo2fsqjE6ndz6QKt9uk:-Mo2fsqjE6ndz6QKt9ul:b-6uy31d) (no related file):*
We need one more reviewer for this from ITL: @mkow @boryspoplawski @pwmarcz @woju Could anyone review this?

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/26#-MmqoIl8By78_c404vpi):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Ok, understood thanks.
</blockquote></details>

Blocking this so I don't forget to fix the commit message during final rebase.
___
*[gsc.py, line 220 at r6](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo2fY1JDA6CiC__WoCs:-Mo2fY1K8-42mRGGLuBm:bj7b291) ([raw file](https://github.com/gramineproject/gsc/blob/c2c90997debe39ae9761b51266c332bc12ecf803/gsc.py#L220)):*
> ```Python
>                 if isinstance(user_manifest_dict['sgx']['trusted_files'], dict):
>                     as_dict = dict_to_list(user_manifest_dict['sgx']['trusted_files'])
>                     user_manifest_dict['sgx']['trusted_file'] = as_dict
> ```

Sorry, I suggested a bad name. Please rename `as_dict` to `as_list` everywhere -- we transform a TOML-dict to a TOML-list, so the name `as_list` is more meaningful.


<!-- Sent from Reviewable.io -->

2021-11-09 08:01 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: 3 of 4 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, and @veenasai2)

___
*[gsc.py, line 220 at r6](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo2fY1JDA6CiC__WoCs:-Mo2hUiXEWhQcsxZZXS8:beaonw6) ([raw file](https://github.com/gramineproject/gsc/blob/c2c90997debe39ae9761b51266c332bc12ecf803/gsc.py#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Sorry, I suggested a bad name. Please rename `as_dict` to `as_list` everywhere -- we transform a TOML-dict to a TOML-list, so the name `as_list` is more meaningful.
</blockquote></details>

done, thanks. 


<!-- Sent from Reviewable.io -->

2021-11-09 08:04 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo2iEZI1GLRBJlsZ6GR:-Mo2iEZI1GLRBJlsZ6GS:b778hoa) (no related file):*
I'm satisfied with this PR. Blocking only on the commit message, to not forget about it during the final rebase.

---


<!-- Sent from Reviewable.io -->

2021-11-10 11:06 UTC, aneessahib commented
@mkow could you review this one in priority.

2021-11-10 11:44 UTC, mkow requested changes
> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @pwmarcz, @veenasai2, and @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo2fsqjE6ndz6QKt9uk:-Mo8Y6Jk0cUJYJzECand:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We need one more reviewer for this from ITL: @mkow @boryspoplawski @pwmarcz @woju Could anyone review this?
</blockquote></details>

Done.

---
___
*[finalize_manifest.py, line 78 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8Yr9RCpIPCkoy7k6L:-Mo8Yr9S2dXV6vgql8jc:b-9vvzyz) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L78)):*
> ```Python
>                 continue
> 
>             escaped_filename = filename.translate(str.maketrans({'\\': r'\\', '"': r'\"'}))
> ```

Hmm, isn't TOML library doing the escaping for us now? If so, we'll escape everything twice. Could you try using a file with `"` in its name and check if it still works?
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-Mo8_-OG2IwSYbVCD_hl:b-dt2yo6) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
> ```Python
>             files.append(user_file)
>         else:
>             raise Exception(f'Unknown user file format: {user_file!r}')
> ```

How could this ever happen? What case is this handling? Why not just call `.values()` on the dict?


<!-- Sent from Reviewable.io -->

2021-11-10 14:45 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @pwmarcz, @veenasai2, and @woju)

___
*[finalize_manifest.py, line 8 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9GzylED7qf7c0yLhS:-Mo9GzylED7qf7c0yLhT:bcihykf) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L8)):*
> ```Python
> 
> import argparse
> import jinja2
> ```

`import jinja2` should be below `import sys` for PEP8: first import stdlib, then external, then internal packages.
___
*[finalize_manifest.py, line 13 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9H9Ps2bFdEga-cr4j:-Mo9H9Ps2bFdEga-cr4k:bdqq9pf) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L13)):*
> ```Python
> import subprocess
> import sys
> import toml    # pylint: disable=import-error
> ```

Why the disable?
___
*[finalize_manifest.py, line 35 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9HTm-CVNxXWtBXCs8:-Mo9HTm-CVNxXWtBXCs9:b-t2898f) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L35)):*
> ```Python
>     if 'protected_files' in manifest['sgx']:
>         for pf in manifest['sgx']['protected_files']:
>             files.append(pf)
> ```

Wouldn't it be shorter like this:

```python
files.extend(manifest['sgx'].get('trusted_files', ()))
files.extend(manifest['sgx'].get('allowed_files', ()))
files.extend(manifest['sgx'].get('protected_files', ()))
```


<!-- Sent from Reviewable.io -->

2021-11-11 10:01 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: 3 of 4 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, @mkow, @pwmarcz, @veenasai2, and @woju)

___
*[finalize_manifest.py, line 8 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9GzylED7qf7c0yLhS:-MoDK0xdEsWfBlm53noG:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L8)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`import jinja2` should be below `import sys` for PEP8: first import stdlib, then external, then internal packages.
</blockquote></details>

done, thanks.
___
*[finalize_manifest.py, line 13 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9H9Ps2bFdEga-cr4j:-MoCq2gM8EcUyUK5T_Xc:b-rcmuyk) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why the disable?
</blockquote></details>

I never faced this error. But this is how "import toml" was done in gsc.py, so I followed the same. Not very sure , how this flag is getting checked in python to prevent any import error. Thanks. 
___
*[finalize_manifest.py, line 35 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9HTm-CVNxXWtBXCs8:-MoDJgQz3ZDtpI25VEIj:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L35)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Wouldn't it be shorter like this:

```python
files.extend(manifest['sgx'].get('trusted_files', ()))
files.extend(manifest['sgx'].get('allowed_files', ()))
files.extend(manifest['sgx'].get('protected_files', ()))
```
</blockquote></details>

done, thanks.
___
*[finalize_manifest.py, line 78 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8Yr9RCpIPCkoy7k6L:-MoDIJrT0YFiKKVOXo0t:b66jh35) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L78)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Hmm, isn't TOML library doing the escaping for us now? If so, we'll escape everything twice. Could you try using a file with `"` in its name and check if it still works?
</blockquote></details>

yes, you are right. 

I renamed a file README to READM\"E

Case 1: Keeping escaped_filename line

Escaping done by escaped_filename : "file:READM\\"E"
Escaping done by toml library : "file:READM\\\"E"

Error:     raise ManifestError(f'Cannot resolve {path}')
graminelibos.manifest.ManifestError: Cannot resolve /ra-tls-secret-prov/files/READM\"E


Case 2: Removed escaped_filename line 

Escaping done by toml library : "file:READM\"E"

Error: no error. 

Thanks.
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoCsSw1DJN_jAJ48atE:bqqewxy) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

How could this ever happen? What case is this handling? Why not just call `.values()` on the dict?
</blockquote></details>

if sgx.allowed_files.file1 = 1           //when filename is non-string 

then 

    raise Exception(f'Unknown user file format: {user_file!r}')
Exception: Unknown user file format: 1
  
Thanks.


<!-- Sent from Reviewable.io -->

2021-11-12 00:10 UTC, mkow requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @pwmarcz, @veenasai2, and @woju)

___
*[-- commits, line 35 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoGSN6h5iLYWvC7-N05):*
> ```
> fixup! fixup! fixup! fixup! 
> ```

In the future, please point fixups at the target commit, not other fixups.
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoGSqoGELhLMIuPLHDg:bmqeix3) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

if sgx.allowed_files.file1 = 1           //when filename is non-string 

then 

    raise Exception(f'Unknown user file format: {user_file!r}')
Exception: Unknown user file format: 1
  
Thanks.
</blockquote></details>

But we don't do such checks for the new syntax? Why do it here then?


<!-- Sent from Reviewable.io -->

2021-11-12 06:18 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @mkow, @pwmarcz, @veenasai2, and @woju)

___
*[-- commits, line 35 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoGSN6h5iLYWvC7-N05):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> fixup! fixup! fixup! fixup! 
> ```

In the future, please point fixups at the target commit, not other fixups.
</blockquote></details>

sure, thanks.
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoHljBP1my-_vWZMi0D:b-802xk1) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But we don't do such checks for the new syntax? Why do it here then?
</blockquote></details>

Actually, I found this check at couple of places in gramine source code

https://github.com/gramineproject/gramine/blob/master/python/graminelibos/manifest.py#L53

https://github.com/gramineproject/gramine/blob/master/python/graminelibos/manifest.py#L119

https://github.com/gramineproject/gramine/blob/master/python/graminelibos/manifest.py#L127


Also, rather than throwing error at later step, we can warn the user at gsc build step only, if the filename is not a proper string. Please let me know, if I should remove this exception. Thanks. 


<!-- Sent from Reviewable.io -->

2021-11-12 08:11 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @mkow, @veenasai2, and @woju)

___
*[finalize_manifest.py, line 35 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9HTm-CVNxXWtBXCs8:-MoIADuHEe6en63DOBZM:b-fe5e7g) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L35)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

done, thanks.
</blockquote></details>

Nice, one-liner kung fu!
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoIAoGw4I8WJiimGIir:b2xc1mk) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Actually, I found this check at couple of places in gramine source code

https://github.com/gramineproject/gramine/blob/master/python/graminelibos/manifest.py#L53

https://github.com/gramineproject/gramine/blob/master/python/graminelibos/manifest.py#L119

https://github.com/gramineproject/gramine/blob/master/python/graminelibos/manifest.py#L127


Also, rather than throwing error at later step, we can warn the user at gsc build step only, if the filename is not a proper string. Please let me know, if I should remove this exception. Thanks. 
</blockquote></details>

I agree with @veenasai2, we have such checks in other places and it definitely doesn't hurt to inform the user if she wrote a weird manifest file (I mean the "extra" app-specific manifest file that is an additional input to GSC).


<!-- Sent from Reviewable.io -->

2021-11-12 12:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @veenasai2, and @woju)

___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoJ4LhI0i8PbBEZHQcA:b-rareqq) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I agree with @veenasai2, we have such checks in other places and it definitely doesn't hurt to inform the user if she wrote a weird manifest file (I mean the "extra" app-specific manifest file that is an additional input to GSC).
</blockquote></details>

But my point is that we don't have it here in the analogous place for the new syntax. I just don't like this inconsistency.
And the links you posted are from a different script.


<!-- Sent from Reviewable.io -->

2021-11-12 12:26 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @mkow, @veenasai2, and @woju)

___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoJ5UsrDGE3O1r1mGJ0:b924r3v) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But my point is that we don't have it here in the analogous place for the new syntax. I just don't like this inconsistency.
And the links you posted are from a different script.
</blockquote></details>

Hm, I see your point now. Well, ok, let's just simplify everything and go with Michal's approach.

@veenasai2 Basically, we can remove `dict_to_list()` function and simply write:
```
    user_manifest_dict['sgx']['trusted_files'] = user_manifest_dict['sgx']['trusted_files'].values()
```

See my other comments below.
___
*[gsc.py, line 220 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ5jzm48HnLftn-vRD:-MoJ5jzm48HnLftn-vRE:b-m21q3l) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L220)):*
> ```Python
>                 if isinstance(user_manifest_dict['sgx']['trusted_files'], dict):
>                     as_list = dict_to_list(user_manifest_dict['sgx']['trusted_files'])
>                     user_manifest_dict['sgx']['trusted_file'] = as_list
> ```

Oops. Just noticed the typo: `trusted_file` -> `trusted_files`
___
*[gsc.py, line 220 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ66Y738KbsIEdMqUF:-MoJ66Y738KbsIEdMqUG:b-huijsn) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L220)):*
> ```Python
>                 if isinstance(user_manifest_dict['sgx']['trusted_files'], dict):
>                     as_list = dict_to_list(user_manifest_dict['sgx']['trusted_files'])
>                     user_manifest_dict['sgx']['trusted_file'] = as_list
> ```

As mentioned in the other comment, let's just simplify:
```
    user_manifest_dict['sgx']['trusted_files'] = user_manifest_dict['sgx']['trusted_files'].values()
```
___
*[gsc.py, line 224 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ6AON2UB6nOtgOD0x:-MoJ6AON2UB6nOtgOD0y:by698kp) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L224)):*
> ```Python
>                 if isinstance(user_manifest_dict['sgx']['allowed_files'], dict):
>                     as_list = dict_to_list(user_manifest_dict['sgx']['allowed_files'])
>                     user_manifest_dict['sgx']['allowed_files'] = as_list
> ```

As mentioned in the other comment, let's just simplify:
```
    user_manifest_dict['sgx']['allowed_files'] = user_manifest_dict['sgx']['allowed_files'].values()
```
___
*[gsc.py, line 228 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ6F2_0bJKMl7LFuoW:-MoJ6F2_0bJKMl7LFuoX:b453wo9) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L228)):*
> ```Python
>                 if isinstance(user_manifest_dict['sgx']['protected_files'], dict):
>                     as_list = dict_to_list(user_manifest_dict['sgx']['protected_files'])
>                     user_manifest_dict['sgx']['protected_files'] = as_list
> ```

As mentioned in the other comment, let's just simplify:
```
    user_manifest_dict['sgx']['protected_files'] = user_manifest_dict['sgx']['protected_files'].values()
```


<!-- Sent from Reviewable.io -->

2021-11-12 21:17 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @dimakuv, @mkow, and @veenasai2)

___
*[finalize_manifest.py, line 13 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9H9Ps2bFdEga-cr4j:-MoKxUKa2O4LINnhY22x:b7eosdy) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L13)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

I never faced this error. But this is how "import toml" was done in gsc.py, so I followed the same. Not very sure , how this flag is getting checked in python to prevent any import error. Thanks. 
</blockquote></details>

This flag is not for python, but for pylint. In runtime, this is just a comment.
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoKyx0D3ORm10YDLwBW:b-7tsusm) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Hm, I see your point now. Well, ok, let's just simplify everything and go with Michal's approach.

@veenasai2 Basically, we can remove `dict_to_list()` function and simply write:
```
    user_manifest_dict['sgx']['trusted_files'] = user_manifest_dict['sgx']['trusted_files'].values()
```

See my other comments below.
</blockquote></details>

<code>... = <strong>list</strong>(user_manifest_dict['sgx']['trusted_files'].values())</code> please. In Python 3, `D.values()` is a view into existing dict. The assignment itself is perfectly safe, but you don't want to have such objects in this structure (`isinstance()` in the function below is one of the reasons).
___
*[gsc.py, line 220 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ66Y738KbsIEdMqUF:-MoL-H9o8HrNgmjRMsty:b-z1bf3u) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned in the other comment, let's just simplify:
```
    user_manifest_dict['sgx']['trusted_files'] = user_manifest_dict['sgx']['trusted_files'].values()
```
</blockquote></details>

`list()`
___
*[gsc.py, line 224 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ6AON2UB6nOtgOD0x:-MoL-Iu5B7AURDh5q8OZ:b-z1bf3u) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L224)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned in the other comment, let's just simplify:
```
    user_manifest_dict['sgx']['allowed_files'] = user_manifest_dict['sgx']['allowed_files'].values()
```
</blockquote></details>

`list()`
___
*[gsc.py, line 228 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ6F2_0bJKMl7LFuoW:-MoL-L5V-iVGLzENTvV0:b-z1bf3u) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L228)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

As mentioned in the other comment, let's just simplify:
```
    user_manifest_dict['sgx']['protected_files'] = user_manifest_dict['sgx']['protected_files'].values()
```
</blockquote></details>

`list()`


<!-- Sent from Reviewable.io -->

2021-11-15 06:53 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: 3 of 4 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, @mkow, @veenasai2, and @woju)

___
*[finalize_manifest.py, line 13 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo9H9Ps2bFdEga-cr4j:-MoX9Wi-2xCDiBGkxgf9:b-wpb374) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/finalize_manifest.py#L13)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This flag is not for python, but for pylint. In runtime, this is just a comment.
</blockquote></details>

ok, thanks.
___
*[gsc.py, line 136 at r7](https://reviewable.io/reviews/gramineproject/gsc/26#-Mo8_-OG2IwSYbVCD_hk:-MoXGji_78INlT4jCYbm:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/873f2107756ae09bef713fdb382fca3c455a2817/gsc.py#L136)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

<code>... = <strong>list</strong>(user_manifest_dict['sgx']['trusted_files'].values())</code> please. In Python 3, `D.values()` is a view into existing dict. The assignment itself is perfectly safe, but you don't want to have such objects in this structure (`isinstance()` in the function below is one of the reasons).
</blockquote></details>

done, thanks.
___
*[gsc.py, line 220 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ66Y738KbsIEdMqUF:-MoXG-8p163vnqB_AxFE:beaonw6) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L220)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`list()`
</blockquote></details>

done, thanks. 
___
*[gsc.py, line 220 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ5jzm48HnLftn-vRD:-MoXGGqi-yxct39Yn-zu:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L220)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Oops. Just noticed the typo: `trusted_file` -> `trusted_files`
</blockquote></details>

done, thanks
___
*[gsc.py, line 224 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ6AON2UB6nOtgOD0x:-MoXFyr27_3ka-9SYvSE:b-lhs69o) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L224)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`list()`
</blockquote></details>

done, thanks
___
*[gsc.py, line 228 at r8](https://reviewable.io/reviews/gramineproject/gsc/26#-MoJ6F2_0bJKMl7LFuoW:-MoXFvDzDbE6N3GcS97k:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/4e7197884088e78702ea4342460eaccd6b062968/gsc.py#L228)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`list()`
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-11-15 09:27 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @mkow, @veenasai2, and @woju)



<!-- Sent from Reviewable.io -->

2021-11-15 11:39 UTC, aneessahib approved these changes

2021-11-15 12:09 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib, @veenasai2, and @woju)

___
*[-- commits, line 40 at r9](https://reviewable.io/reviews/gramineproject/gsc/26#-MoYUj_w-vzgHVUJkOGN):*
Please use fixup commits ;)


<!-- Sent from Reviewable.io -->

2021-11-15 13:42 UTC, woju approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib and @veenasai2)



<!-- Sent from Reviewable.io -->

2021-11-15 13:49 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 2 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib and @veenasai2)

___
*[-- commits, line 40 at r9](https://reviewable.io/reviews/gramineproject/gsc/26#-MoYUj_w-vzgHVUJkOGN):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use fixup commits ;)
</blockquote></details>

sure. From next PR onwards, I will use fixup commits. Thanks.


<!-- Sent from Reviewable.io -->

2021-11-15 15:01 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 3 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @aneessahib, @mkow, and @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/26#-MoZ62pm5WkhkGM1lsOV:-MoZ62pm5WkhkGM1lsOW:b44s2wc) (no related file):*
Please don't try to rebase or merge it, anyone. I'm rebasing and fixing the issues...

@veenasai2  Have you checked that your changes work? I couldn't graminize an example Python image (https://gramine.readthedocs.io/projects/gsc/en/latest/#example) because of the bug in how GSC handles envvars from the base Docker image... I'm fixing it right now.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/26#-MmqoIl8By78_c404vpi):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Blocking this so I don't forget to fix the commit message during final rebase.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-11-15 17:45 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/26#-MoZ62pm5WkhkGM1lsOV:-MoZff1oCg5WtDclkHfd:bvdff20) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please don't try to rebase or merge it, anyone. I'm rebasing and fixing the issues...

@veenasai2  Have you checked that your changes work? I couldn't graminize an example Python image (https://gramine.readthedocs.io/projects/gsc/en/latest/#example) because of the bug in how GSC handles envvars from the base Docker image... I'm fixing it right now.
</blockquote></details>

Done. This PR is ready for final review and (if reviewers are fine) merging.

I manually tested it with 3 workloads: Python example and two tests we have in GSC.

---
___
*[gsc.py, line 196 at r10](https://reviewable.io/reviews/gramineproject/gsc/26#-MoZfuRaDkaEV36OLu1u:-MoZfuRaDkaEV36OLu1v:buvoev8) ([raw file](https://github.com/gramineproject/gsc/blob/9fb6b65480387742a90b13b835d37ceacd197dee/gsc.py#L196)):*
> ```Python
> 
>     base_image_environment = extract_environment_from_image_config(original_image.attrs['Config'])
>     base_image_dict = toml.loads(base_image_environment)
> ```

FYI: There was a bug that `base_image_environment` was simply appended to the manifest file as-is (in text form). This led to a mix of auto-generated TOML formatting and appended "simply-strings" TOML formatting. This broke the default Python's TOML parser.

I fixed this bug by simply transforming the strings into `base_image_dict` and merging it with the other two dicts.
___
*[test/generic.manifest, line 5 at r10](https://reviewable.io/reviews/gramineproject/gsc/26#-MoZgIrOCK-92DhAVmKi:-MoZgIrOCK-92DhAVmKj:bb03iwx) ([raw file](https://github.com/gramineproject/gsc/blob/9fb6b65480387742a90b13b835d37ceacd197dee/test/generic.manifest#L5)):*
> ```
> 
> sgx.trusted_files = [
>   "file:/entrypoint.manifest",  # unused entry, only to test merging of manifests
> ```

FYI: Unfortunately, the default Python's TOML parser is too stupid to be able to combine `{ uri: ..., sha256: ...}` entries with just-string entries. So there was another bug that Python's TOML complained about this.

I fixed it (worked around it) by simply removing the `sha256` formatting and keeping a simple string. This is unfortunate, but that's how current TOML parser works in Python. I had an issue about it somewhere (I already encountered this before) but can't find...


<!-- Sent from Reviewable.io -->

2021-11-15 20:36 UTC, mkow approved these changes
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 1 unresolved discussion (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2021-11-15 21:42 UTC, dimakuv approved these changes
> Dismissed @aneessahib from a discussion.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2021-11-15 21:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/26)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[finalize_manifest.py, line 24 at r1](https://reviewable.io/reviews/gramineproject/gsc/26#-MmddrU6P0GPEbr3owD4-r1-24:-Mo_YUnS42LbTscWRuW2:b-85i63v) ([raw file](https://github.com/gramineproject/gsc/blob/4a20c7c28a4e62d27744ce8302932aeb7178de06/finalize_manifest.py#L24)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

Yes, you are right. Updated the code to support old format too. Thanks.
</blockquote></details>

LGTM.


<!-- Sent from Reviewable.io -->

2021-11-15 21:44 UTC, merged