Display error message when Manifest file path is incorrect
gramineproject/gsc pull request #33
Opened 2021-11-24 11:01 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 

Currently GSC does not throw any error when user_manifest file is not present at the path specified by the user, instead gsc build proceeds silently with empty user_manifest file and default manifest options. This problem is severe as the user will not know if he provided a wrong user_manifest path and the configs that are specified in the user_manifest file (such as enclave_size) will not take effect. This may lead to unexpected results while running the gsc image (such as insufficient enclave memory, if the image requires large enclave_size)

## How to test this PR? 
1. Provide a wrong manifest path (means manifest file is not present at the specified path): an exception will be thrown.
2. Provide correct manifest path: gsc build will proceed.

2021-11-24 12:05 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/33#-MpGpNFz8WAUqTcktjqQ:-MpGpNFz8WAUqTcktjqR:bhtcup5) (no related file):*
Other than commit message typo, the PR looks good to me.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpGorEYDHbzhAMmoOKB):*
`Manifest` -> `manifest`

We'll fix it during final rebase.


<!-- Sent from Reviewable.io -->

2021-11-25 05:03 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/33#-MpGpNFz8WAUqTcktjqQ:-MpKTMCu-ijBXC2xezmE:b-54avio) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Other than commit message typo, the PR looks good to me.
</blockquote></details>

Ok, thanks.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpGorEYDHbzhAMmoOKB):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Manifest` -> `manifest`

We'll fix it during final rebase.
</blockquote></details>

ok, thanks.


<!-- Sent from Reviewable.io -->

2021-11-25 14:37 UTC, mkow requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @veenasai2)

___
*[gsc.py, line 200 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpMWt36Ac9677WjcVPm:-MpMWt36Ac9677WjcVPn:b1j75wq) ([raw file](https://github.com/gramineproject/gsc/blob/f499addfe9d2ff0650ceb41c95034bf842be0700/gsc.py#L200)):*
> ```
> Exception
> ```

This should probably be `FileNotFoundError` instead


<!-- Sent from Reviewable.io -->

2021-11-26 05:51 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[gsc.py, line 200 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpMWt36Ac9677WjcVPm:-MpPn1c5DXvey9QbgRAP:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/f499addfe9d2ff0650ceb41c95034bf842be0700/gsc.py#L200)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Exception
> ```

This should probably be `FileNotFoundError` instead
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-11-26 07:44 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @veenasai2)

___
*[gsc.py, line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/33#-MpQBcMR4V64bo_OMF5H:-MpQBcMR4V64bo_OMF5I:b5fheas) ([raw file](https://github.com/gramineproject/gsc/blob/6e6cc309a3ab058ebf707d8ff47f6386b830506f/gsc.py#L16)):*
You don't need to `import errno`. Please remove this line.

`FileNotFoundError` is a built-in in Python3. No need to import anything. I checked it:
```
$ python3
>>> raise FileNotFoundError("Oops")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: Oops
```

As you can see, raising `FileNotFoundError` doesn't require any imports at all.


<!-- Sent from Reviewable.io -->

2021-11-26 08:02 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: 0 of 1 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[gsc.py, line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/33#-MpQBcMR4V64bo_OMF5H:-MpQFV2e8ioPQbP7T86V:b-gbb36v) ([raw file](https://github.com/gramineproject/gsc/blob/6e6cc309a3ab058ebf707d8ff47f6386b830506f/gsc.py#L16)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You don't need to `import errno`. Please remove this line.

`FileNotFoundError` is a built-in in Python3. No need to import anything. I checked it:
```
$ python3
>>> raise FileNotFoundError("Oops")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: Oops
```

As you can see, raising `FileNotFoundError` doesn't require any imports at all.
</blockquote></details>

Yes, you are correct, we don't require it. I was checking the below syntax as well 
raise FileNotFoundError(
    errno.ENOENT, os.strerror(errno.ENOENT), filename)

that's why kept the import statement. But forgot to remove. Thanks.


<!-- Sent from Reviewable.io -->

2021-11-26 08:13 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-11-28 20:56 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @veenasai2)

___
*[gsc.py, line 16 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpcK2bQBPVrYr1yEdqQ:-MpcK2bR0WEs67kTqguI:b-6x2py9) ([raw file](https://github.com/gramineproject/gsc/blob/f499addfe9d2ff0650ceb41c95034bf842be0700/gsc.py#L16)):*
> ```Python
> import sys
> import tempfile
> ```

But now you removed the empty line, which was intentional (see r1 vs r3 diff and https://www.python.org/dev/peps/pep-0008/#imports).


<!-- Sent from Reviewable.io -->

2021-11-29 04:22 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: 0 of 1 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[gsc.py, line 16 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpcK2bQBPVrYr1yEdqQ:-MpdvP2_-vegzERxx0ee:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/f499addfe9d2ff0650ceb41c95034bf842be0700/gsc.py#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

But now you removed the empty line, which was intentional (see r1 vs r3 diff and https://www.python.org/dev/peps/pep-0008/#imports).
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-11-29 07:31 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)



<!-- Sent from Reviewable.io -->

2021-11-29 11:20 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2021-11-29 12:42 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/33#-MpGorEYDHbzhAMmoOKB):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

ok, thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 12:44 UTC, mkow requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @veenasai2)

___
*[-- commits, line 2 at r5](https://reviewable.io/reviews/gramineproject/gsc/33#-MpfiKYG1HFr-Ny2Pj2t):*
wanifest?


<!-- Sent from Reviewable.io -->

2021-11-29 12:47 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[-- commits, line 2 at r5](https://reviewable.io/reviews/gramineproject/gsc/33#-MpfiKYG1HFr-Ny2Pj2t):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

wanifest?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 12:48 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/33)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-29 12:49 UTC, merged