Fix LD_LIBRARY_PATH in Ubuntu 21.04 Docker images
gramineproject/gsc pull request #40
Opened 2021-12-23 09:14 UTC by veenasai2

Signed-off-by: Veena Saini <veena.saini@intel.com>

## Description of the changes 
This PR fixes “bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory” error, seen in Ubuntu 21.04 gsc-images.  ldconfig utility in Ubuntu 21.04 images produces output lines like “/usr/local/lib: (from /etc/ld.so.conf.d/libc.conf:2)”. Here, only the first part of this line (the actual path name) should be taken, so we put a filter as part of generate_library_paths() code in finalize_manifest.py.

**Before including the fix in finalize_manifest.py:**

**For Ubuntu-21.04** 
LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu/libfakeroot: (from /etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf:1)/usr/local/lib: (from /etc/ld.so.conf.d/libc.conf:2)/lib/x86_64-linux-gnu: (from /etc/ld.so.conf.d/x86_64-linux-gnu.conf:3)/lib: (from <builtin>:0)"

**For Ubuntu-18.04**
LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:"

**After including the fix in finalize_manifest.py:**

**For Ubuntu-21.04** 
LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/lib:"

**For Ubuntu-18.04** 
LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:"

The fix in finalize_manifest.py was only to remove the “(from …)” statements from ldconfig -v output.  With that fix, we continue to see the error “bash: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory”.

By comparing Ubuntu 21.04 and Ubuntu 18.04 LD_LIBRARY_PATH, we can see that , “/usr/lib/x86_64-linux-gnu” is not part of Ubuntu 21.04 LD_LIBRARY_PATH, so we updated loader.env.LD_LIBRARY_PATH in entrypoint.manifest.template  

## How to test this PR? 
gsc-bash images for Ubuntu 18.04 and Ubuntu 21.04 should work smoothly. Dockerfile and manifest file for bash image are present in gsc/test folder.

2021-12-23 14:38 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @veenasai2)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/40#-MrbhTUU4WHrc06yueEV:-MrbhTUV36-SexnMei5F:brbwfek) (no related file):*
> gsc-bash images for Ubuntu 18.04 and Ubuntu 21.04 should work smoothly. Dockerfile and manifest file for bash image are present in gsc/test folder.

What do you mean by this? I only see `ubuntu18.04-bash.dockerfile` and `ubuntu18.04-bash.manifest` under gsc/test directory. Did you add some new files locally (and forgot to git-add them to this PR)? Or do you mean that a person can use `ubuntu18.04-bash.dockerfile` as a basis and create a 21.04 Dockerfile?

---
___
*[templates/entrypoint.manifest.template, line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/40#-Mrbhz_TAPPaDbWVLklP:-Mrbhz_TAPPaDbWVLklQ:b-fibf0z) ([raw file](https://github.com/gramineproject/gsc/blob/48f9e04f5da2d2364c7a8a1b8e6160357ae58058/templates/entrypoint.manifest.template#L4)):*
> ```
> libos.entrypoint = "/{{binary}}"
> 
> loader.env.LD_LIBRARY_PATH = "/gramine/meson_build_output/lib/x86_64-linux-gnu/gramine/runtime/glibc:/usr/lib/x86_64-linux-gnu:{{"{{library_paths}}"}}"
> ```

Can you add a comment before this line, smth like this:
```
# ldconfig in Ubuntu 21.04 doesn't produce "/usr/lib/x86_64-linux-gnu" so add it explicitly
```


<!-- Sent from Reviewable.io -->

2021-12-23 15:33 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/40#-MrbhTUU4WHrc06yueEV:-MrbsN689ZrZ_D6UYBPf:b7e8vnq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

> gsc-bash images for Ubuntu 18.04 and Ubuntu 21.04 should work smoothly. Dockerfile and manifest file for bash image are present in gsc/test folder.

What do you mean by this? I only see `ubuntu18.04-bash.dockerfile` and `ubuntu18.04-bash.manifest` under gsc/test directory. Did you add some new files locally (and forgot to git-add them to this PR)? Or do you mean that a person can use `ubuntu18.04-bash.dockerfile` as a basis and create a 21.04 Dockerfile?
</blockquote></details>

   @dimakuv  Yes, A person can use ubuntu18.04-bash.dockerfile as a basis and create a 21.04 Dockerfile.  Thanks.

---
___
*[templates/entrypoint.manifest.template, line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/40#-Mrbhz_TAPPaDbWVLklP:-Mrbsydw5xYxQYGEaCfP:b77i4af) ([raw file](https://github.com/gramineproject/gsc/blob/48f9e04f5da2d2364c7a8a1b8e6160357ae58058/templates/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Can you add a comment before this line, smth like this:
```
# ldconfig in Ubuntu 21.04 doesn't produce "/usr/lib/x86_64-linux-gnu" so add it explicitly
```
</blockquote></details>

sure, thanks.


<!-- Sent from Reviewable.io -->

2021-12-27 06:01 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: 1 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[templates/entrypoint.manifest.template, line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/40#-Mrbhz_TAPPaDbWVLklP:-MruTcNpDV0XQmSUIANm:b-r18wie) ([raw file](https://github.com/gramineproject/gsc/blob/48f9e04f5da2d2364c7a8a1b8e6160357ae58058/templates/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

sure, thanks.
</blockquote></details>

done, thanks.


<!-- Sent from Reviewable.io -->

2021-12-27 07:30 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

___
*[templates/entrypoint.manifest.template, line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/40#-Mrbhz_TAPPaDbWVLklP:-Mruml4NChYOFsQwP_HI:b-16if6q) ([raw file](https://github.com/gramineproject/gsc/blob/48f9e04f5da2d2364c7a8a1b8e6160357ae58058/templates/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, veenasai2 wrote…</i></summary><blockquote>

done, thanks.
</blockquote></details>

Now that I think of it... I'm fine with this solution, but it is a temporary hack. I'm fine with this PR, but why doesn't Ubuntu 21.04 add this directory? Or, to put it differently, what is that `fakeroot/` directory that Ubuntu 21.04 started to use? There was some discussion on that, but I always forget the details.


<!-- Sent from Reviewable.io -->

2022-01-06 17:16 UTC, mkow approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/40#-MskNG_w9DF4HpoJCFq5:-MskNG_w9DF4HpoJCFq6:br9za82) (no related file):*
Please use proper Markdown for PR description, right now it's hard to see which parts are pasted logs/snippets and which are your comments about them.

---


<!-- Sent from Reviewable.io -->

2022-01-06 17:35 UTC, veenasai2 reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/40#-MskNG_w9DF4HpoJCFq5:-MskS9oIA_jnnUn21b7B:brek4u5) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use proper Markdown for PR description, right now it's hard to see which parts are pasted logs/snippets and which are your comments about them.
</blockquote></details>

@mkow sure, I will take care for future PRs. Thanks. 

---


<!-- Sent from Reviewable.io -->

2022-01-07 08:08 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-01-07 11:01 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/40)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-01-07 11:05 UTC, merged