Add CentOS support to GSC
gramineproject/gsc pull request #43
Opened 2022-01-10 10:32 UTC by aneessahib

Signed-off-by: aneessahib <anees.a.sahib@intel.com>

Adding CentOS support to GSC. 
To test - follow similar procedure as followed with Ubuntu (test/README).

2022-01-12 16:00 UTC, dimakuv requested changes
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

___
*[config.yaml.template, line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDpA8gD4m4DA-I31yO:-MtDpA8gD4m4DA-I31yP:b-jovhyh) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/config.yaml.template#L1)):*
> ```
> # Specify the OS distro. Currently tested distros are Ubuntu and CentOS.
> ```

Actually, can we enumerate the exact distros we tested? I think these are `ubuntu:18.04`, `ubuntu:20.04`, `ubuntu:21.04` and `centos:8`?
___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDpfDk1nno5rth6-DI:-MtDpfDk1nno5rth6-DJ:bzhkq7a) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
> ```Python
>     distro = env.globals["Distro"]
>     distro = distro.split(":")
>     env.loader =jinja2.FileSystemLoader(f'templates/{distro[0]}')
> ```

You seem to never use `distro[1]`. So I would replace with a more convinient:
```
    distro = distro.split(":")[0]
    env.loader =jinja2.FileSystemLoader(f'templates/{distro}')
```

And use `{distro}` everywhere below instead of `{distro[0]}`
___
*[gsc.py, line 271 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDq4Gv-oPGxCWpIU7g:-MtDq4Gv-oPGxCWpIU7h:b-y5ko8l) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L271)):*
> ```Python
>     env.globals.update(config)
>     env.globals.update(vars(args))
>     distro = env.globals["Distro"]
> ```

Please add an empty line before this line
___
*[gsc.py, line 273 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDq6hB14Fqqbboqrp2:-MtDq6hB14Fqqbboqrp3:bvk0zbb) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L273)):*
> ```Python
>     distro = env.globals["Distro"]
>     distro = distro.split(":")
>     env.loader = jinja2.FileSystemLoader(f'templates/{distro[0]}')
> ```

ditto (replace with `{distro}`)
___
*[gsc.py, line 315 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDqJe0966W0SJhvjra:-MtDqJe0966W0SJhvjrb:b-y5ko8l) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L315)):*
> ```Python
>     env = jinja2.Environment()
>     env.globals.update(yaml.safe_load(args.config_file))
>     distro = env.globals["Distro"]
> ```

Please add an empty line before this line
___
*[gsc.py, line 317 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDqKsM9EjIq1j_oOs4:-MtDqKsM9EjIq1j_oOs5:bvk0zbb) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L317)):*
> ```Python
>     distro = env.globals["Distro"]
>     distro = distro.split(":")
>     env.loader = jinja2.FileSystemLoader(f'templates/{distro[0]}')
> ```

ditto (replace with `{distro}`)
___
*[Documentation/index.rst, line 467 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDv49S00WmEYHwqunC:-MtDv49S00WmEYHwqunD:b-4fy8ed) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/Documentation/index.rst#L467)):*
> ```reStructuredText
> of known limitations and serves as a discussion board for workarounds.
> 
> Operating system dependency
> ```

I think it should be `Operating System` (both capitalized)
___
*[Documentation/index.rst, line 474 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDvRlp6CwV6C2qLD2n:-MtDvRlp6CwV6C2qLD2o:bgdtujs) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/Documentation/index.rst#L474)):*
> ```reStructuredText
> repositories. Docker images based on Ubuntu and CentOS are supported by GSC.
> GSC can simply be extended to support other distributions by
> providing a template for this distribution in :file:`templates/`.
> ```

`a template` -> `a set of templates` (because we have 5 files for each OS distro)
___
*[templates/centos/apploader.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtE-_WC9aNZ4gKNE-Wj:-MtE-_WC9aNZ4gKNE-Wk:b8s3mg1) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/apploader.template#L9)):*
> ```
> 
> # Include Meson build output packages dir in $PKG_CONFIG_PATH, contains mbedTLS and util libs
> export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(find /gramine/meson_build_output/lib64 -type d -path '*/pkgconfig')"
> ```

From what I understand, the only difference in this template (between Ubuntu vs CentOS) is the `lib64/` directory?

If this is the only diff, maybe we just replace `lib64` with a new variable `{{gramine_lib_path}}`? This `gramine_lib_path` will be assigned to `lib/x86_64_...` for Ubuntu and to `lib64` for CentOS in the GSC python scripts (based on the `config.yaml` option `Distro`).
___
*[templates/centos/Dockerfile.centos.build.template, line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtE009LCW5r8lhiMYH2:-MtE009LCW5r8lhiMYH3:bluaac2) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/Dockerfile.centos.build.template#L1)):*
> ```
> # Include previously-prepared Docker image with Gramine (if any) or compile Gramine from sources
> ```

There seems to be no sense in calling this file `Dockerfile.centos.build.template` -- it is under the `centos/` directory so the `.centos.` part can be removed. Same for all other Dockerfiles.
___
*[templates/centos/Dockerfile.centos.build.template, line 62 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDzebUDb7Aoz_223Ln:-MtDzebUDb7Aoz_223Lo:bd9g4c7) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/Dockerfile.centos.build.template#L62)):*
> ```
> # Define default command
> ENTRYPOINT ["/bin/bash", "/apploader.sh"]
> CMD [{% if insecure_args %} "{{'", "'.join(cmd)}}" {% endif %}]
> ```

I'm torn here. It looks like we have a lot of duplication in CentOS and Ubuntu Dockerfile templates.

What about we put all the generic code in `templates/Dockerfile.generic.build.template`, and in this file (and in `templates/centos/Dockerfile.centos.build.template`) we remove this generic code? And in our GSC python scripts, we concatenate the distro-specific template with the generic template?

I would definitely prefer such a solution.
___
*[templates/centos/Dockerfile.centos.compile.template, line 70 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtE-RrN-g32ucqT-_4t:-MtE-RrN-g32ucqT-_4u:bt0ijqk) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/Dockerfile.centos.compile.template#L70)):*
> ```
>        {% endif %} \
>     && ninja -C build \
>     && ninja -C build install
> ```

ditto (deduplicate)
___
*[templates/centos/Dockerfile.centos.sign.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDxxhJ0EVOremVo1jp:-MtDxxhJ0EVOremVo1jq:biobp0z) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/Dockerfile.centos.sign.template#L8)):*
> ```
> #ENV LC_ALL en_US.UTF-8
> #ENV LANG en_US.UTF-8
> #ENV LANGUAGE en_US.UTF-8
> ```

Debug leftover? Please remove the comment lines.
___
*[templates/centos/Dockerfile.centos.sign.template, line 22 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtE-WVY3J5QRFQEI1hZ:-MtE-WVY3J5QRFQEI1h_:bt0ijqk) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/Dockerfile.centos.sign.template#L22)):*
> ```
> 
> COPY  [...]

2022-01-13 20:08 UTC, woju reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @dimakuv)

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDpfDk1nno5rth6-DI:-MtK2LQiE7tigvcHaFhC:b-amy73e) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You seem to never use `distro[1]`. So I would replace with a more convinient:
```
    distro = distro.split(":")[0]
    env.loader =jinja2.FileSystemLoader(f'templates/{distro}')
```

And use `{distro}` everywhere below instead of `{distro[0]}`
</blockquote></details>

```python
distro, _ = distro.split(':')
```


<!-- Sent from Reviewable.io -->

2022-01-26 17:57 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: 0 of 22 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @woju)

___
*[config.yaml.template, line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDpA8gD4m4DA-I31yO:-MuMSGIT4jWLoHM_BsCy:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/config.yaml.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Actually, can we enumerate the exact distros we tested? I think these are `ubuntu:18.04`, `ubuntu:20.04`, `ubuntu:21.04` and `centos:8`?
</blockquote></details>

Done.
___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDpfDk1nno5rth6-DI:-MuMSHM_ArO40e-xx9yh:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

```python
distro, _ = distro.split(':')
```
</blockquote></details>

Done.
___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MuMSIpm6vMCTY5BEBrw:byosqwx) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`FileSystemLoader(f'templates/{distro[0]}')` is wrong. You should have done `env.get_template(f'{distro}/[...]')` instead (or `select_template` or whatever).

You need to have a single tree of templates to have a good deduplication of code between distros, which you could use.

common-template.dockerfile:

```jinja
FROM {% block from %}{% endblock %}

{% block install %}{% endblock %}

RUN ./common-command-1.sh

RUN ./common-command-2.sh

# ...
```

distro1.dockerfile:

```jinja
{% extends 'common-template.dockerfile' %}

{% block from %}distro1{% endblock %}

{% block install %}
RUN apt-get install -y ...
{% endblock %}
```

You can have as many blocks as needed (just named consistently), and you don't need to override all of them. If you don't, the value from the extended (parent) template remains as is, so for example if you, say, had a difference between debian and ubuntu in some block, but `apt-get install` was the same, you can have a middle-level template with only this block, or inherit one from another.
</blockquote></details>

done. Have created a parent common template that the child extends, while implementing the necessary distro specific block.  But passing  ``env.get_template(f'{distro}/[...]')`` would end up being a little tedious since there are about 5 templates that we load. Instead just pass the path to the file system loader, and then reference the templates by name in ``get_template``. Also, providing the path in the same format from an ``extends`` statement from a child template throws error (or may be there's another way to do it).
___
*[gsc.py, line 271 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDq4Gv-oPGxCWpIU7g:-MuMVz28-nxfw6mLia_T:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L271)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line before this line
</blockquote></details>

Done.
___
*[gsc.py, line 273 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDq6hB14Fqqbboqrp2:-MuMW0wO3Dao2TV2K-wT:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (replace with `{distro}`)
</blockquote></details>

Done.
___
*[gsc.py, line 315 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDqJe0966W0SJhvjra:-MuMW7aSCt26e602yp-D:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L315)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add an empty line before this line
</blockquote></details>

Done.
___
*[gsc.py, line 317 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDqKsM9EjIq1j_oOs4:-MuMW8hQ4Dhc9H347kax:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L317)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto (replace with `{distro}`)
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 467 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDv49S00WmEYHwqunC:-MuMWAZ_AHngQolA0ETR:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/Documentation/index.rst#L467)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think it should be `Operating System` (both capitalized)
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 474 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDvRlp6CwV6C2qLD2n:-MuMWEbA51tUTvCESy-i:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/Documentation/index.rst#L474)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`a template` -> `a set of templates` (because we have 5 files for each OS distro)
</blockquote></details>

Done.
___
*[templates/centos/apploader.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtE-_WC9aNZ4gKNE-Wj:-MuMWQ7Y-Hswz0xc9CSb:b3spk2y) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/apploader.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From what I understand, the only difference in this template (between Ubuntu vs CentOS) is the `lib64/` directory?

If this is the only diff, maybe we just replace `lib64` with a new variable `{{gramine_lib_path}}`? This `gramine_lib_path` will be assigned to `lib/x86_64_...` for Ubuntu and to `lib64` for CentOS in the GSC python scripts (based on the `config.yaml` option `Distro`).
</blockquote></details>

Have provided a child template where ``lib64`` is mentioned. All others are pulled from the parent common template. 
___
*[templates/centos/entrypoint.manifest.template, line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDw25v5-AbXrpqxZTq:-MuMWjYE2JivnUSx6hJs:b3dftrk) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/entrypoint.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Leftover from debugging? Please remove.
</blockquote></details>

yuk. Done.
___
*[templates/centos/entrypoint.manifest.template, line 5 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtDwDI512DFPx-xDjwp:-MuMWnH366yjLyZJwJwo:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/templates/centos/entrypoint.manifest.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

From what I understand, the only difference in this template (between Ubuntu vs CentOS) is the `lib64/` directory?

If this is the only diff, maybe we just replace `lib64` with a new variable `{{gramine_lib_path}}`? This `gramine_lib_path` will be assigned to `lib/x86_64_...` for Ubuntu and to `lib64` for CentOS in the GSC python scripts (based on the `config.yaml` option `Distro`).
</blockquote></details>

di [...]

2022-01-27 12:23 UTC, dimakuv requested changes
> Reviewed 10 of 22 files at r2, 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @woju)

___
*[config.yaml.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQEBoV-B80nBaKEz-Q:-MuQEBoV-B80nBaKEz-R:b-l95n51) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/config.yaml.template#L1)):*
> ```
> # Specify the OS distro. Currently tested distros are ``ubuntu:18.04``, ``ubuntu:20.04``, ``ubuntu:21.04`` and ``centos:8``.
> ```

This looks more than our 100 chars per line limit.

Please re-wrap to the 100 char limit
___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MuQUGeG9m2BshlkrVwV:bdi4kds) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

done. Have created a parent common template that the child extends, while implementing the necessary distro specific block.  But passing  ``env.get_template(f'{distro}/[...]')`` would end up being a little tedious since there are about 5 templates that we load. Instead just pass the path to the file system loader, and then reference the templates by name in ``get_template``. Also, providing the path in the same format from an ``extends`` statement from a child template throws error (or may be there's another way to do it).
</blockquote></details>

The new version looks quite awesome!
___
*[gsc.py, line 273 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQEq9uBFkqD6mgyOCl:-MuQEq9v9KxqHo3fwRMD:bjw9k5j) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/gsc.py#L273)):*
> ```Python
>     env.globals.update(vars(args))
>     distro = env.globals["Distro"]
>     
> ```

You have spaces here, please remove them.
___
*[Documentation/index.rst, line 298 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQEx8c3p3wpZF5eqP4:-MuQEx8c3p3wpZF5eqP5:bebxhyz) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/Documentation/index.rst#L298)):*
> ```reStructuredText
> 
>    Defines Linux distribution to be used to build Gramine in. Currently tested
>    distros are Ubuntu 18.04, Ubuntu 20.04, Ubuntu 21.04 and CentOS 8. Default value is ``ubuntu:18.04``.
> ```

Our documentation (`.rst`) files must be wrapped to 80 chars per line limit. I think you exceed it here. Please re-wrap to 80-char limit.
___
*[templates/apploader.common.template, line 5 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQQ8AT-FyxmqbqPGoA:-MuQQ8AT-FyxmqbqPGoB:b-xkqus) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/apploader.common.template#L5)):*
> ```
> set -ex
> 
> {% block path %} {% endblock %}
> ```

Please add a comment before this line like this:
```
# Export distro-specific paths (typically `PYTHONPATH` and `PKG_CONFIG_PATH`)
```
___
*[templates/apploader.common.template, line 14 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQU74GAaM-dZdASs7X:-MuQU74GAaM-dZdASs7Y:boe83wy) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/apploader.common.template#L14)):*
> ```
> else
>     gramine-direct /entrypoint {{binary_arguments}} "${@}"
> fi
> ```

In all these files it looks like you don't have a final end-of-line character... Can you fix it?
___
*[templates/Dockerfile.common.sign.template, line 5 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQR7pm5ilA27pVsuZB:-MuQR7pm5ilA27pVsuZC:b-tzkhay) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.sign.template#L5)):*
> ```
> COPY gsc-signer-key.pem /gsc-signer-key.pem
> 
> {% block path %} {% endblock %} \
> ```

I dislike this pattern. You combine the `block` commands (that will be expanded) with the `&&` on the following line. This implies that you have `RUN ` inside the expanded block. Instead, I suggest to make it simpler and more readable:

- In this file:
```
# Export distro-specific paths (typically `PYTHONPATH`)
{% block path %} {% endblock %}

RUN gramine-sgx-sign \
         --key /gsc-signer-key.pem \
         --manifest /entrypoint.manifest \
         --output /entrypoint.manifest.sgx
```

- In `templates/ubuntu/Dockerfile.sign.template` (and in `centos` version):
```
ENV PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')"
```

This will look much cleaner, and also similar to how you do it in other files.
___
*[templates/centos/apploader.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTgRsD5xn0wH1Nl6q:-MuQTgRsD5xn0wH1Nl6r:b-3p9s96) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/apploader.template#L1)):*
> ```
> #!/usr/bin/env bash
> ```

I think this is not needed (it is already in `apploader.common.template`)
___
*[templates/centos/Dockerfile.build.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQShhX7LL4J3rE19nn:-MuQShhX7LL4J3rE19no:b-587hg8) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L4)):*
> ```
> 
> {% block install %}
> RUN sed 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo  | tee /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
> ```

Why so strange? You can use `-i` option to edit the file in place, like this:
```
RUN sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
```
___
*[templates/centos/Dockerfile.build.template, line 14 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQSw2V4JtDtfV3LOUP:-MuQSw2V4JtDtfV3LOUQ:b-6f3byc) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L14)):*
> ```
>         python3 \
>         python3-pip \
>         python3-protobuf \
> ```

Could you sort this list?
___
*[templates/centos/Dockerfile.compile.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQT1ZdDP4LKLN_lmDi:-MuQT1ZdDP4LKLN_lmDj:b-7ropln) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.compile.template#L4)):*
> ```
> 
> {% block install %}
> RUN sed 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo  | tee /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
> ```

ditto
___
*[templates/centos/Dockerfile.compile.template, line 35 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQT38q0vNqeVYq80YQ:-MuQT38q0vNqeVYq80YR:b-z61q29) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.compile.template#L35)):*
> ```
>         python3-pip \
>         python3-protobuf \
>         wget \
> ```

Please sort this list
___
*[templates/centos/Dockerfile.sign.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTF3r9VF39ogDl4GA:-MuQTF3r9VF39ogDl4GB:bkich8o) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.sign.template#L1)):*
> ```
> # Sign image in a separate stage to ensure that signing key is never part of the final image
> ```

Please move this comment to `Dockerfile.common.sign.template`.
___
*[templates/centos/Dockerfile.sign.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTJS39VoK [...]

2022-01-27 16:14 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @woju)

___
*[templates/centos/Dockerfile.sign.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTJS39VoKC7WIkgZJ:-MuRJ3TE-4Xj9uKb8vPA:bx1cw7d) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I suggest to do `ENV PYTHONPATH=...` here. See my other comment on this.
</blockquote></details>

The problem with this one is that `find` doesn't run with ENV keyword. Any ideas? 



_Code quote:_
```
RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib64 -type d -path '*/site-packages')"
```


<!-- Sent from Reviewable.io -->

2022-01-27 21:04 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @woju)

___
*[templates/Dockerfile.common.sign.template, line 5 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQR7pm5ilA27pVsuZB:-MuSLYqwCQh0NwP3WI8p:b5019bf) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.sign.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I dislike this pattern. You combine the `block` commands (that will be expanded) with the `&&` on the following line. This implies that you have `RUN ` inside the expanded block. Instead, I suggest to make it simpler and more readable:

- In this file:
```
# Export distro-specific paths (typically `PYTHONPATH`)
{% block path %} {% endblock %}

RUN gramine-sgx-sign \
         --key /gsc-signer-key.pem \
         --manifest /entrypoint.manifest \
         --output /entrypoint.manifest.sgx
```

- In `templates/ubuntu/Dockerfile.sign.template` (and in `centos` version):
```
ENV PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')"
```

This will look much cleaner, and also similar to how you do it in other files.
</blockquote></details>

UPDATE: This is not possible, see another comment thread. Basically, ENV cannot be used with commands, only with hard-coded strings. See https://github.com/moby/moby/issues/29110. I'm resolving.
___
*[templates/centos/Dockerfile.sign.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTJS39VoKC7WIkgZJ:-MuSLD4Y0gHvq10h6ltz:bb26hgt) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.sign.template#L4)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

The problem with this one is that `find` doesn't run with ENV keyword. Any ideas? 
</blockquote></details>

You are right, apparently this is an unsolved Docker problem from 2016: https://github.com/moby/moby/issues/29110. Also see the context here: https://stackoverflow.com/questions/34911622/dockerfile-set-env-to-result-of-command (read the upvoted comments as well!).

I didn't realize this. Well, instead of going with some hacks, I am fine with your approach. I'm onblocking my comments.


<!-- Sent from Reviewable.io -->

2022-01-28 05:03 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: 5 of 22 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib, @dimakuv, and @woju)

___
*[config.yaml.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQEBoV-B80nBaKEz-Q:-MuTzK2L3_oke_DSxSig:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/config.yaml.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This looks more than our 100 chars per line limit.

Please re-wrap to the 100 char limit
</blockquote></details>

Done.
___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MuTzM85Cb6EPuRT2Msb:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The new version looks quite awesome!
</blockquote></details>

Done.
___
*[gsc.py, line 273 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQEq9uBFkqD6mgyOCl:-MuTzMh01gxl8RzAmEgu:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/gsc.py#L273)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have spaces here, please remove them.
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 298 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQEx8c3p3wpZF5eqP4:-MuTzUrw2xd0rZ0sbfMG:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/Documentation/index.rst#L298)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Our documentation (`.rst`) files must be wrapped to 80 chars per line limit. I think you exceed it here. Please re-wrap to 80-char limit.
</blockquote></details>

Done.
___
*[templates/apploader.common.template, line 5 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQQ8AT-FyxmqbqPGoA:-MuTzYx21-Hn8vG3qFaR:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/apploader.common.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment before this line like this:
```
# Export distro-specific paths (typically `PYTHONPATH` and `PKG_CONFIG_PATH`)
```
</blockquote></details>

Done.
___
*[templates/apploader.common.template, line 14 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQU74GAaM-dZdASs7X:-MuTz_5yD6JfC2BxXi4h:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/apploader.common.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In all these files it looks like you don't have a final end-of-line character... Can you fix it?
</blockquote></details>

Done.
___
*[templates/centos/apploader.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTgRsD5xn0wH1Nl6q:-MuTzsjo8MNb_zgUOmJq:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/apploader.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this is not needed (it is already in `apploader.common.template`)
</blockquote></details>

Done.
___
*[templates/centos/Dockerfile.build.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQShhX7LL4J3rE19nn:-MuTzul6D7TlGyrhcmud:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why so strange? You can use `-i` option to edit the file in place, like this:
```
RUN sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
```
</blockquote></details>

Done.
___
*[templates/centos/Dockerfile.build.template, line 14 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQSw2V4JtDtfV3LOUP:-MuTzvra7rv7QFSAptJ7:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you sort this list?
</blockquote></details>

Done.
___
*[templates/centos/Dockerfile.compile.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQT1ZdDP4LKLN_lmDi:-MuTzx09BIrs8LqzxZB7:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.compile.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[templates/centos/Dockerfile.compile.template, line 35 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQT38q0vNqeVYq80YQ:-MuU-0WW4sF_jfGeLVr9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.compile.template#L35)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please sort this list
</blockquote></details>

Done.
___
*[templates/Dockerfile.common.build.template, line 11 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQQP5S2Rm030iW-ooi:-MuTzfxf02QRcUqn2IVp:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.build.template#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment before this line like this:
```
# Install distro-specific packages to run Gramine (e.g., python3, protobuf, toml, etc.)
```
</blockquote></details>

Done.
___
*[templates/Dockerfile.common.compile.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQQlcqDZhJAo4-Kj4o:-MuTzkYb9DEEiws91ilM:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.compile.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment before this line like this:
```
# Install distro-specific packages to build Gramine (e.g., python3, protobuf, toml, etc.)
```
</blockquote></details>

Done.
___
*[templates/entrypoint.common.manifest.template, line 3 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQSNHa4kjheHM4IgHd:-MuTzpnj7IWzZFKlch5m:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/entrypoint.common.manifest.template#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add a comment before this line like this:
```
# Add distro-specific `loader.entrypoint` and `loader.env.LD_LIBRARY_PATH`
```
</blockquote></details>

Done.
___
*[templates/ubuntu/apploader.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTZ9vETJYx28kNyMu:-MuU37O8CtQW1MXnLHZG:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/ubuntu/apploader.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I think this is not needed (it is already in `apploader.common.template`)
</blockquote></details>

Done. [...]

2022-01-28 05:37 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: 4 of 22 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @woju)

___
*[templates/centos/Dockerfile.sign.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTF3r9VF39ogDl4GA:-MuUB-8Y3iscts84d_iy:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.sign.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this comment to `Dockerfile.common.sign.template`.
</blockquote></details>

Done.
___
*[templates/ubuntu/Dockerfile.sign.template, line 1 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQU2cWB9lQ0Tg_cOW7:-MuUB0mAA-f1X62iScTj:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/ubuntu/Dockerfile.sign.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move this comment to `Dockerfile.common.sign.template`.
</blockquote></details>

Done.
___
*[templates/entrypoint.manifest.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQTulV81fnaBRP6Ez-:-MuUAisoDhXrW-RaHvJj:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/634ef1ad0a32795f4b61de66b13c1973a64af314/templates/entrypoint.manifest.template#L4)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please keep this comment in this file, the comment is important.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-28 08:54 UTC, dimakuv approved these changes
> Reviewed 13 of 17 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-01-28 09:07 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/43#-MuUw32U0Zl4ERauO6jT:-MuUw32U0Zl4ERauO6jU:bei3vgi) (no related file):*
I verified manually, this PR works for me.

---


<!-- Sent from Reviewable.io -->

2022-01-28 10:03 UTC, aneessahib commented
@woju - pls check if all looks good.

2022-01-30 13:57 UTC, mkow reviewed
> Reviewed 4 of 22 files at r2, 13 of 17 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib and @woju)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufB1A79HLvMmaNqF0h):*
Please drop "to GSC", we are already in GSC repository.
___
*[gsc.py, line 180 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufBJWm5BEP4v-XFrD1:-MufBJWm5BEP4v-XFrD2:b34qrxi) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/gsc.py#L180)):*
> ```Python
> 
>     distro, _ = distro.split(":")
>     env.loader =jinja2.FileSystemLoader([f'templates/{distro}', 'templates/'])
> ```

missing space after `=`
___
*[templates/apploader.common.template, line 8 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufCQRc69FVBaVWDbLo:-MufCQRd7-wATZZCD-Uy:bfbd2xl) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/templates/apploader.common.template#L8)):*
> ```
> Set default PAL to Linux-SGX
> ```

This was a bit confusing to me, because you're not setting anything (no config change, etc). Please reword to something like "Default to Linux-SGX if no PAL was specified".
___
*[templates/Dockerfile.common.compile.template, line 1 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufEIZ-DkqsP4KkR99Q:-MufEIZ-DkqsP4KkR99R:b-nkhv3u) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/templates/Dockerfile.common.compile.template#L1)):*
> ```
> # Currently tested base OS images are Ubuntu 18.04, Ubuntu 20.04, Ubuntu 21.04 and CentOS 8.
> ```

I think this comment is not relevant anymore, as this file is now mostly distro-agnostic.


<!-- Sent from Reviewable.io -->

2022-01-30 14:46 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib, @dimakuv, and @woju)

___
*[templates/Dockerfile.common.compile.template, line 1 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufEIZ-DkqsP4KkR99Q:-MufPcWr6jy5krlRgiTT:b-bfnzg5) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/templates/Dockerfile.common.compile.template#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think this comment is not relevant anymore, as this file is now mostly distro-agnostic.
</blockquote></details>

hmm yea makes sense to me, since there are other places where we call this out. @dimakuv - what do you think. 


<!-- Sent from Reviewable.io -->

2022-01-30 15:05 UTC, dimakuv approved these changes
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib, @mkow, and @woju)

___
*[templates/Dockerfile.common.compile.template, line 1 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufEIZ-DkqsP4KkR99Q:-MufW2o5-_RIUxjasFnT:bjlbcn0) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/templates/Dockerfile.common.compile.template#L1)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

hmm yea makes sense to me, since there are other places where we call this out. @dimakuv - what do you think. 
</blockquote></details>

Yes, sure, we can remove it now (we already have this list in other places).


<!-- Sent from Reviewable.io -->

2022-01-30 15:06 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufB1A79HLvMmaNqF0h):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please drop "to GSC", we are already in GSC repository.
</blockquote></details>

Done.
___
*[gsc.py, line 180 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufBJWm5BEP4v-XFrD1:-MufWOJb7aqi1Xqa3YY8:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/gsc.py#L180)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

missing space after `=`
</blockquote></details>

Done.
___
*[templates/apploader.common.template, line 8 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufCQRc69FVBaVWDbLo:-MufWPCz4R5pAy_GbtJN:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/templates/apploader.common.template#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> Set default PAL to Linux-SGX
> ```

This was a bit confusing to me, because you're not setting anything (no config change, etc). Please reword to something like "Default to Linux-SGX if no PAL was specified".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-30 15:10 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow and @woju)

___
*[templates/Dockerfile.common.compile.template, line 1 at r6](https://reviewable.io/reviews/gramineproject/gsc/43#-MufEIZ-DkqsP4KkR99Q:-MufXRV15kT_TTocBabe:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/92e641c55d9820a13fe04f497c392396811e6d5f/templates/Dockerfile.common.compile.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, sure, we can remove it now (we already have this list in other places).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-30 16:10 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-01-31 07:11 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/43#-MuiyBxR8z-Hy9WvkekX:-MuiyBxR8z-Hy9WvkekY:b-5iweot) (no related file):*
@woju Could you take another look at this PR? Me and Michal approved it already, and we want to merge this before the new release.

---


<!-- Sent from Reviewable.io -->

2022-02-01 14:24 UTC, woju requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 8 unresolved discussions (waiting on @aneessahib and @dimakuv)

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MukRfSi4mFpmaBmxl8_:b-5djxhk) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
No, this is wrong. Having nested template loaders is a big footgun. Consider `FileSystemLoader(['templates', 'templates/subdir'])`, then:

`templates/template.jinja`:
```jinja
a
```

`templates/subdir/template.jinja`:
```jinja
b
```

Now, without looking through jinja's doc, what this does?

`templates/subdir/template2.jinja`
```jinja
{% include 'template.jinja` %}
```

Multiple paths in to `FileSystemLoader` are meant for flask's blueprints, where you have additional `template/` directory in different python packages.

> But passing `env.get_template(f'{distro}/[...]')` would end up being a little tedious since there are about 5 templates that we load.

I think this is better than the surprise mentioned above. If you really want to move this to jinja, you can do calculations in the string that ends up being the name of the template inherited:

```jinja
{% extends '{}/template'.format(distro) %}
```
___
*[templates/apploader.common.template, line 6 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupHQ532iac2J-geoah:-MupHQ532iac2J-geoai:b23o9dp) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/apploader.common.template#L6)):*
> ```
> 
> # Export distro-specific paths (typically `PYTHONPATH` and `PKG_CONFIG_PATH`)
> {% block path %} {% endblock %}
> ```

Remove the space inside (for lack of surprises in `{{ super() }}`).
___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-MupRvnZ-7bZFTGov9Jb:b-igchly) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
> ```
>          --key /gsc-signer-key.pem \
>          --manifest /entrypoint.manifest \
>          --output /entrypoint.manifest.sgx
> ```

OK, this is bad. If, say, implementing another distro flavour, you forget to override this block, this will be a syntax error. Can't you do `PYTHONPATH` in `ENV` before `gramine-sgx-sign`?

```jinja
{% block env_paths %}{% endblock %}

RUN gramine-sgx-sign ...
```

```jinja
{% extends 'Dockerfile.common.sign.template' %}

{% block env_paths %}
ENV PYTHONPATH=...
ENV PKG_CONFIG_PATH=...
{% endblock %}
```

Optimally this should be removed altogether and gramine should be installed so it won't need path adjustments. Possibly even from packages.
___
*[templates/centos/Dockerfile.build.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQShhX7LL4J3rE19nn:-MupdG_LBDyX5vuF6Muw:b-jw0sdx) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L4)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Even better, you should use `--enablerepo=powertools` to `dnf`/`yum` and get rid of this sed. `powertools` repo on my almalinux test instance is in different file (`/etc/yum.repos.d/almalinux-powertools.repo`; I didn't check rocky linux) and while this doesn't matter here, because you explicitly inherit from a specific upstream image, we should keep things generic enough to make porting to different distros easier.
___
*[templates/centos/Dockerfile.build.template, line 6 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupdBJq0z7H_hRIcZQe:-MupdBJq0z7H_hRIcZQf:b-tpzgv4) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/centos/Dockerfile.build.template#L6)):*
> ```
> RUN sed -i 's/enabled=0/enabled=1/g' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
> 
> RUN yum update -y \
> ```

`dnf`?
___
*[templates/centos/Dockerfile.compile.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQT1ZdDP4LKLN_lmDi:-MupeTj1EC1LR7Mg6eLr:b-89a4l7) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.compile.template#L4)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ditto
___
*[templates/Dockerfile.common.compile.template, line 4 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupI9RYBCBYtT5MF2oX:-MupI9RYBCBYtT5MF2oY:b-7jbqan) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.compile.template#L4)):*
> ```
> 
> # Install distro-specific packages to build Gramine (e.g., python3, protobuf, toml, etc.)
> {% block install %} {% endblock %}
> ```

space
___
*[templates/entrypoint.common.manifest.template, line 4 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupcCcS30GmfV9Hbt4Z:-MupcCcT7VqhWYPG77mN:b-7jbqan) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/entrypoint.common.manifest.template#L4)):*
> ```
> 
> # Add distro-specific `loader.entrypoint` and `loader.env.LD_LIBRARY_PATH`
> {% block loader %} {% endblock %}
> ```

space


<!-- Sent from Reviewable.io -->

2022-02-01 14:37 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 8 unresolved discussions (waiting on @aneessahib, @dimakuv, and @woju)

___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-MuphgeY9MwVgQwEKllg:b-czaatp) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

OK, this is bad. If, say, implementing another distro flavour, you forget to override this block, this will be a syntax error. Can't you do `PYTHONPATH` in `ENV` before `gramine-sgx-sign`?

```jinja
{% block env_paths %}{% endblock %}

RUN gramine-sgx-sign ...
```

```jinja
{% extends 'Dockerfile.common.sign.template' %}

{% block env_paths %}
ENV PYTHONPATH=...
ENV PKG_CONFIG_PATH=...
{% endblock %}
```

Optimally this should be removed altogether and gramine should be installed so it won't need path adjustments. Possibly even from packages.
</blockquote></details>

@woju This is impossible, we already had this discussion: https://github.com/gramineproject/gsc/pull/43#pullrequestreview-865427038

Basically, it is impossible to set an `ENV` to the result of a command in Dockerfile. https://github.com/moby/moby/issues/29110

Or maybe you had another idea and I misunderstood?


<!-- Sent from Reviewable.io -->

2022-02-01 16:19 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib and @dimakuv)

___
*[templates/Dockerfile.common.sign.template, line 15 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-Muq0fU231j3L-m6tVSP:-Muq0fU231j3L-m6tVSQ:b-6uv90s) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.sign.template#L15)):*
> ```
> 
> COPY --from=unsigned_image /*.sig /
> COPY --from=unsigned_image /*.sgx /
> ```

Missing newline at EOF.
___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-Muq068H8nciqehB2Q5v:b-o5r5nu) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju This is impossible, we already had this discussion: https://github.com/gramineproject/gsc/pull/43#pullrequestreview-865427038

Basically, it is impossible to set an `ENV` to the result of a command in Dockerfile. https://github.com/moby/moby/issues/29110

Or maybe you had another idea and I misunderstood?
</blockquote></details>

No, unfortunately I had the exact idea that was in the resolved discussion, which I missed, because it was resolved.

But still, NAK the idea of splitting command in half, with one being in the block. I see multiple solutions:

1) Get rid of meson, install gramine from package, no need to adjust paths at all (I would prefer this one if this wasn't too big a change).
2) Do the paths really change, or the `find` was just a shortcut taken, because whoever wrote this didn't want to paste the full path? Maybe `find` command is really unneeded, and we can use `{% block %}` with `ENV` inside after all.
3) Use macros instead of template inheritance:

`{distro}/macros`:
```jinja
{% set PYTHONPATH_find_start = '/a/b/c' %}
```

`Dockerfile.common.sign.template`:
```jinja
{% import '{}/macros'.format(distro) as distro_macros -%}

RUN export PYTHONPATH=$(find {{ distro_macros.PYTHONPATH_find_start }} ...) && gramine-sgx-sign
```

4) Use block in a way, so it doesn't hurt if something is missing:

```jinja
RUN {% block export_pythonpath %}{% endblock %} gramine-sgx-sign ...
```

```jinja
{% extends ... %}
{% block export_pythonpath -%}
export PYTHONPATH="$(find)" &&
{%- endblock %}
```

(in this case you must carefully think about whitespace and newlines in the block, but in original solution you need too).


<!-- Sent from Reviewable.io -->

2022-02-01 16:41 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib, @dimakuv, and @woju)

___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-Muq8foi0aqyywZzQfiq:b-th4lfk) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, unfortunately I had the exact idea that was in the resolved discussion, which I missed, because it was resolved.

But still, NAK the idea of splitting command in half, with one being in the block. I see multiple solutions:

1) Get rid of meson, install gramine from package, no need to adjust paths at all (I would prefer this one if this wasn't too big a change).
2) Do the paths really change, or the `find` was just a shortcut taken, because whoever wrote this didn't want to paste the full path? Maybe `find` command is really unneeded, and we can use `{% block %}` with `ENV` inside after all.
3) Use macros instead of template inheritance:

`{distro}/macros`:
```jinja
{% set PYTHONPATH_find_start = '/a/b/c' %}
```

`Dockerfile.common.sign.template`:
```jinja
{% import '{}/macros'.format(distro) as distro_macros -%}

RUN export PYTHONPATH=$(find {{ distro_macros.PYTHONPATH_find_start }} ...) && gramine-sgx-sign
```

4) Use block in a way, so it doesn't hurt if something is missing:

```jinja
RUN {% block export_pythonpath %}{% endblock %} gramine-sgx-sign ...
```

```jinja
{% extends ... %}
{% block export_pythonpath -%}
export PYTHONPATH="$(find)" &&
{%- endblock %}
```

(in this case you must carefully think about whitespace and newlines in the block, but in original solution you need too).
</blockquote></details>

I think option 2 doesn't work because `PYTHONPATH` contains the Python version (e.g. `python3.6`) which changes among Ubuntu versions.

I like option 4.


<!-- Sent from Reviewable.io -->

2022-02-01 17:08 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib and @woju)

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MuqApJf-_ZGRgHnnPVL:b473m5j) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, this is wrong. Having nested template loaders is a big footgun. Consider `FileSystemLoader(['templates', 'templates/subdir'])`, then:

`templates/template.jinja`:
```jinja
a
```

`templates/subdir/template.jinja`:
```jinja
b
```

Now, without looking through jinja's doc, what this does?

`templates/subdir/template2.jinja`
```jinja
{% include 'template.jinja` %}
```

Multiple paths in to `FileSystemLoader` are meant for flask's blueprints, where you have additional `template/` directory in different python packages.

> But passing `env.get_template(f'{distro}/[...]')` would end up being a little tedious since there are about 5 templates that we load.

I think this is better than the surprise mentioned above. If you really want to move this to jinja, you can do calculations in the string that ends up being the name of the template inherited:

```jinja
{% extends '{}/template'.format(distro) %}
```
</blockquote></details>

Let me explain why we add the `templates` directory as well to the filesystem loader - this is to include the common templates that are outside of the sub directories. So we do not have a scenario where templates with identical names are present across both these location (i.e `templates` and `templates\subdir`. Now another option would be to have a `common` subfolder as well that would host all the common templates - and we pass this common directory to the loader too - and this would remove the nested problem  you are talking about - in which case i'd have to rename the common templates differently as they would be in a common sub-folder. This would also add other complexities of string formations etc. Can we keep the existing simple solution given this explanation of why we are including `templates` and `templates\subdir` to the loader

I'll work on getting the other comments here incorporated.


<!-- Sent from Reviewable.io -->

2022-02-01 23:25 UTC, woju requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib and @dimakuv)

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MurV9wN-ax4c4yHzY-K:bka381k) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Let me explain why we add the `templates` directory as well to the filesystem loader - this is to include the common templates that are outside of the sub directories. So we do not have a scenario where templates with identical names are present across both these location (i.e `templates` and `templates\subdir`. Now another option would be to have a `common` subfolder as well that would host all the common templates - and we pass this common directory to the loader too - and this would remove the nested problem  you are talking about - in which case i'd have to rename the common templates differently as they would be in a common sub-folder. This would also add other complexities of string formations etc. Can we keep the existing simple solution given this explanation of why we are including `templates` and `templates\subdir` to the loader

I'll work on getting the other comments here incorporated.
</blockquote></details>

No, this is not "simple". I'm sure you know how this works, what to do and what to avoid, but you're setting up a nasty surprise for some poor developer, who comes after you and doesn't have time to read through all of this setup. IOW this violates [law of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) (see also: "Tao of Programming" 4.1). I'd expect better from a reviewer.

`common/` directory would be OK, provided you have only the `templates/` directory in `FileSystemLoader`. You'll still need to `get_template(f'{distro}/...')` and `{% extends 'common/...` %}.

Or, if you really, don't want to have `get_template(f'{}')`, you can skip template inheritance and switch to macros, have one macro library per distro and have distro-specific variables there. This would be actually the simplest solution in terms of number of files (N + M, where N is number of stages and M is number of distros), but may not be flexible enough if we need to considerably diverge somewhere in the dockerfiles.
___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-MurTmcE2xhNACrIUSsG:b-3ebm0r) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
> I think option 2 doesn't work because PYTHONPATH contains the Python version (e.g. python3.6) which changes among Ubuntu versions.

No, dist-packages should be in `python3`, not `python3.y`, exactly for this reason (so you can have a single `deb` package installable across different distros; and it works, we have a single repo for all debian-derived distros). Unless something is broken here, which I didn't check.


<!-- Sent from Reviewable.io -->

2022-02-02 08:13 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib and @woju)

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MutSe2Y-2WY6PqIoShe:beo15sy) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
@aneessahib I agree with Woju that his scenario of three templates (see his second comment) is realistic and problematic.

> `common/` directory would be OK, provided you have only the `templates/` directory in `FileSystemLoader`. You'll still need to `get_template(f'{distro}/...')` and `{% extends 'common/... %}`.

This suggestion from Woju makes sense. Is there any problem in implementing this? If I understand correctly, then the changes to your PR are pretty limited with this approach. In particular:

- In this file:
    - `env.loader = jinja2.FileSystemLoader([f'templates/{distro}', 'templates/'])` -> `env.loader = jinja2.FileSystemLoader(['templates/'])`
    -  `build_template = env.get_template('Dockerfile.build.template')` -> `build_template = env.get_template(f'{distro}/Dockerfile.build.template')`
    - (and all similar places)

- From what I understand, there will be *no* changes to the CentOS- and Ubuntu-specific template files (because they extend like this: `extends "Dockerfile.common.build.template"`, and this file is already located under the FileSystemLoader's base directory `templates`/).

This looks like a trivial change, what am I missing here?

Maybe I'm missing the need for the `common/` directory Woju mentions. @woju Why do we need a tree hierarchy like you suggest (parent `templates/` dir, then `templates/common/` for common to-be-extended templates, then `templates/centos/` and `templates/ubuntu/` for distro-specific templates)? Cannot we have common templates directly under `templates/` dir, as is done now in this PR?
___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-MutOHRz8WCcHKsf8IfL:b-rdl15p) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

> I think option 2 doesn't work because PYTHONPATH contains the Python version (e.g. python3.6) which changes among Ubuntu versions.

No, dist-packages should be in `python3`, not `python3.y`, exactly for this reason (so you can have a single `deb` package installable across different distros; and it works, we have a single repo for all debian-derived distros). Unless something is broken here, which I didn't check.
</blockquote></details>

@woju I don't understand your reply. In our documentation, you create the following table: https://gramine.readthedocs.io/en/latest/devel/building.html#additional-build-options. It lists the value for `$PYTHONPATH` as `<prefix>/lib/python<version>/site-packages` (note the `<version>`).

Also, when I look at my local installation of Gramine, I see this directory hierarchy:
```
~/gramineproject/gramine$ tree -d built-debug/
built-debug/
├── bin
└── lib
    ├── python3.6
    │   └── site-packages
    │       └── graminelibos
    ...
```

So clearly the version number is used. Maybe it's because of that Ubuntu quirk that Python libs are placed in some special dirs, and you were thinking of RHEL/CentOS?


<!-- Sent from Reviewable.io -->

2022-02-02 08:22 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib and @woju)

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-MutVbiv3pvOsGvXlX38:bl8ea1s) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@aneessahib I agree with Woju that his scenario of three templates (see his second comment) is realistic and problematic.

> `common/` directory would be OK, provided you have only the `templates/` directory in `FileSystemLoader`. You'll still need to `get_template(f'{distro}/...')` and `{% extends 'common/... %}`.

This suggestion from Woju makes sense. Is there any problem in implementing this? If I understand correctly, then the changes to your PR are pretty limited with this approach. In particular:

- In this file:
    - `env.loader = jinja2.FileSystemLoader([f'templates/{distro}', 'templates/'])` -> `env.loader = jinja2.FileSystemLoader(['templates/'])`
    -  `build_template = env.get_template('Dockerfile.build.template')` -> `build_template = env.get_template(f'{distro}/Dockerfile.build.template')`
    - (and all similar places)

- From what I understand, there will be *no* changes to the CentOS- and Ubuntu-specific template files (because they extend like this: `extends "Dockerfile.common.build.template"`, and this file is already located under the FileSystemLoader's base directory `templates`/).

This looks like a trivial change, what am I missing here?

Maybe I'm missing the need for the `common/` directory Woju mentions. @woju Why do we need a tree hierarchy like you suggest (parent `templates/` dir, then `templates/common/` for common to-be-extended templates, then `templates/centos/` and `templates/ubuntu/` for distro-specific templates)? Cannot we have common templates directly under `templates/` dir, as is done now in this PR?
</blockquote></details>

`common` directory was my suggestion, provided we pass that as well to the loader. I was just trying to understand how would a new developer looking at this would get confused as Woju mentioned since we name common templates, sub-directories etc explicitly. Im through with the changes. some tests are in progress. 


<!-- Sent from Reviewable.io -->

2022-02-02 12:29 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 9 unresolved discussions (waiting on @aneessahib and @woju)

___
*[templates/centos/Dockerfile.build.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQShhX7LL4J3rE19nn:-MuuMDBlDuLRJmx8isdr:b-bjims8) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L4)):*
> --enablerepo=powertools


I had tried this in the past as well- always fails with `Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist` when I tried installing the config-manager and the dnf plugin core to enable powertools. And this was indeed faced by many others working with centos VMs and containers. The only solution widely available online is what I have done here already, or another one is to update the mirror list .. again locally. 
`
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* &&\
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
`


<!-- Sent from Reviewable.io -->

2022-02-02 13:43 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: 12 of 22 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @woju)

___
*[templates/apploader.common.template, line 6 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupHQ532iac2J-geoah:-Muudv8U-WoNnj0vL10Y:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/apploader.common.template#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Remove the space inside (for lack of surprises in `{{ super() }}`).
</blockquote></details>

Done.
___
*[templates/Dockerfile.common.sign.template, line 15 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-Muq0fU231j3L-m6tVSP:-Muue-bX-TcYldJd4Crr:b1kheu) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.sign.template#L15)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Missing newline at EOF.
</blockquote></details>

It is added but doesn't show explicitly here I think. Same is the case for all other files. perhaps im missing something. When i had missing new lines earlier - it clearly called it out in red. pls reconfirm
___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-MuudzI627AGgQ2it-UA:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@woju I don't understand your reply. In our documentation, you create the following table: https://gramine.readthedocs.io/en/latest/devel/building.html#additional-build-options. It lists the value for `$PYTHONPATH` as `<prefix>/lib/python<version>/site-packages` (note the `<version>`).

Also, when I look at my local installation of Gramine, I see this directory hierarchy:
```
~/gramineproject/gramine$ tree -d built-debug/
built-debug/
├── bin
└── lib
    ├── python3.6
    │   └── site-packages
    │       └── graminelibos
    ...
```

So clearly the version number is used. Maybe it's because of that Ubuntu quirk that Python libs are placed in some special dirs, and you were thinking of RHEL/CentOS?
</blockquote></details>

Done.
___
*[templates/centos/Dockerfile.build.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQShhX7LL4J3rE19nn:-MuueIu_0uwmEP64OA8H:bz0tslx) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L4)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

> --enablerepo=powertools


I had tried this in the past as well- always fails with `Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist` when I tried installing the config-manager and the dnf plugin core to enable powertools. And this was indeed faced by many others working with centos VMs and containers. The only solution widely available online is what I have done here already, or another one is to update the mirror list .. again locally. 
`
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* &&\
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
`
</blockquote></details>

We did some more tests today. for this to consistently work everywhere, i had to add the mirror list as well in addition to enabling power tools ( as suggested by google).
___
*[templates/centos/Dockerfile.build.template, line 6 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupdBJq0z7H_hRIcZQe:-Muuef2w4N0ghA9cEAyS:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/centos/Dockerfile.build.template#L6)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

`dnf`?
</blockquote></details>

Done.
___
*[templates/centos/Dockerfile.compile.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQT1ZdDP4LKLN_lmDi:-Muuegyv4U-PrDWDna5G:bod8p2h) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.compile.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

same as the earlier response
___
*[templates/Dockerfile.common.compile.template, line 4 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupI9RYBCBYtT5MF2oX:-MuudxgpDuLjWfLotArX:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.compile.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.
___
*[templates/entrypoint.common.manifest.template, line 4 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupcCcS30GmfV9Hbt4Z:-MuueHqX1h8AI3erih8T:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/entrypoint.common.manifest.template#L4)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-02 19:10 UTC, dimakuv requested changes
> Reviewed 10 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, 15 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib and @woju)

___
*[gsc.py, line 177 at r10](https://reviewable.io/reviews/gramineproject/gsc/43#-MuvpMGw7c7sBECdvaIu:-MuvpMGw7c7sBECdvaIv:b-yd2f) ([raw file](https://github.com/gramineproject/gsc/blob/87a7728afeab7202849d39c4da33d2d8a444714e/gsc.py#L177)):*
> ```Python
>     os.makedirs(tmp_build_path, exist_ok=True)
> 
>     distro = env.globals["Distro"]
> ```

I just noticed that you use `"` (double quotes) instead of `'` (single quotes) everywhere in this PR. Can you replace them with single quotes, for uniformity with the rest of the code?
___
*[gsc.py, line 179 at r10](https://reviewable.io/reviews/gramineproject/gsc/43#-MuvpWGL4zbNU-tYiy4V:-MuvpWGL4zbNU-tYiy4W:b-s8x4u6) ([raw file](https://github.com/gramineproject/gsc/blob/87a7728afeab7202849d39c4da33d2d8a444714e/gsc.py#L179)):*
> ```Python
>     distro = env.globals["Distro"]
> 
>     distro, _ = distro.split(":")
> ```

ditto (double quotes -> single quotes)
___
*[gsc.py, line 273 at r10](https://reviewable.io/reviews/gramineproject/gsc/43#-MuvpZ-SBJ5OeWblKMPF:-MuvpZ-SBJ5OeWblKMPG:b-s8x4u6) ([raw file](https://github.com/gramineproject/gsc/blob/87a7728afeab7202849d39c4da33d2d8a444714e/gsc.py#L273)):*
> ```Python
>     env.globals.update(config)
>     env.globals.update(vars(args))
>     distro = env.globals["Distro"]
> ```

ditto (double quotes -> single quotes)
___
*[gsc.py, line 275 at r10](https://reviewable.io/reviews/gramineproject/gsc/43#-MuvpZfU0_-xljV1oPgR:-MuvpZfU0_-xljV1oPgS:b-s8x4u6) ([raw file](https://github.com/gramineproject/gsc/blob/87a7728afeab7202849d39c4da33d2d8a444714e/gsc.py#L275)):*
> ```Python
>     distro = env.globals["Distro"]
> 
>     distro, _ = distro.split(":")
> ```

ditto (double quotes -> single quotes)
___
*[gsc.py, line 318 at r10](https://reviewable.io/reviews/gramineproject/gsc/43#-Muvp_OL0h-TSpnf3AO7:-Muvp_OM0u0SAaWILC1H:b-s8x4u6) ([raw file](https://github.com/gramineproject/gsc/blob/87a7728afeab7202849d39c4da33d2d8a444714e/gsc.py#L318)):*
> ```Python
>     env = jinja2.Environment()
>     env.globals.update(yaml.safe_load(args.config_file))
>     distro = env.globals["Distro"]
> ```

ditto (double quotes -> single quotes)
___
*[gsc.py, line 320 at r10](https://reviewable.io/reviews/gramineproject/gsc/43#-Muvpa0i43x4a_GNRRxO:-Muvpa0i43x4a_GNRRxP:b-s8x4u6) ([raw file](https://github.com/gramineproject/gsc/blob/87a7728afeab7202849d39c4da33d2d8a444714e/gsc.py#L320)):*
> ```Python
>     distro = env.globals["Distro"]
> 
>     distro, _ = distro.split(":")
> ```

ditto (double quotes -> single quotes)


<!-- Sent from Reviewable.io -->

2022-02-03 04:14 UTC, aneessahib commented
@dimakuv - all done. took me a while to notice that you hadn't used reviewable for the latest set of comments.

2022-02-03 09:14 UTC, dimakuv approved these changes
Strange, I used Reviewable for my latest review. Maybe a glitch in Reviewable or GitHub.

Anyway, I approved. Thanks.

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43#-:-MuyqTbG7QpT6GtDoYT9:b-8maypg)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @woju)



<!-- Sent from Reviewable.io -->

2022-02-04 15:02 UTC, woju submitted a review, later dismissed
> Reviewed 2 of 22 files at r2, 7 of 17 files at r4, 1 of 4 files at r5, 9 of 10 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[gsc.py, line 179 at r1](https://reviewable.io/reviews/gramineproject/gsc/43#-MtK-gm--nTQWPYC_LZZ:-Mv4CjE808GtJ7PCzO5p:b9yn1sd) ([raw file](https://github.com/gramineproject/gsc/blob/f9b01f2bb9998ffa8b3b8358c5278ad43dd67760/gsc.py#L179)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

`common` directory was my suggestion, provided we pass that as well to the loader. I was just trying to understand how would a new developer looking at this would get confused as Woju mentioned since we name common templates, sub-directories etc explicitly. Im through with the changes. some tests are in progress. 
</blockquote></details>

How this is confusing: imagine new dev adds two files with the same basename and in two directories, one under another, then attempts to `{% import %}` or `{% extends %}` from one of them, but gets the other. Now s/he wonders why this happened and how to fix it.
___
*[templates/Dockerfile.common.sign.template, line 15 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-Muq0fU231j3L-m6tVSP:-Mv4E5Ey0Cs9YzxvkB05:b-99esuj) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/Dockerfile.common.sign.template#L15)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

It is added but doesn't show explicitly here I think. Same is the case for all other files. perhaps im missing something. When i had missing new lines earlier - it clearly called it out in red. pls reconfirm
</blockquote></details>

It's fixed now. Reviewable onle shows explicitly when there's no newline (red arrow and crossed circle).
___
*[templates/Dockerfile.common.sign.template, line 10 at r9](https://reviewable.io/reviews/gramineproject/gsc/43#-MupRvnZ-7bZFTGov9Ja:-Mv4DmPh6DuKF5CQ6g_8:b-wwrx7i) ([raw file](https://github.com/gramineproject/gsc/blob/a8315f131b3805f75714d7941f278fe2c6e00d64/templates/Dockerfile.common.sign.template#L10)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Weird. Well, if that's how it is, then I stand corrected.

The fix is OK.
___
*[templates/centos/Dockerfile.build.template, line 4 at r3](https://reviewable.io/reviews/gramineproject/gsc/43#-MuQShhX7LL4J3rE19nn:-Mv4ElB45S-09l5M8wJ1:b-ywm4nq) ([raw file](https://github.com/gramineproject/gsc/blob/b9241b54c055698e432df6ba6b545e944cab2399/templates/centos/Dockerfile.build.template#L4)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

We did some more tests today. for this to consistently work everywhere, i had to add the mirror list as well in addition to enabling power tools ( as suggested by google).
</blockquote></details>

"No URLs in mirrorlist" is because CentOS 8 is dead: https://bugs.centos.org/view.php?id=18394.

I'd suggest to switch to AlmaLinux or Rocky Linux, but this is out of scope of this PR. I'll resolve this for now, this will need fixing in the near future.


<!-- Sent from Reviewable.io -->

2022-02-05 10:18 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, all discussions resolved, "Merge branch '" found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-02-06 10:04 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-02-06 12:22 UTC, mkow approved these changes
> Reviewed 9 of 10 files at r10, 1 of 1 files at r11, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-02-07 07:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/43)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/43#-MvI7faY8MWa6ogQTZMx:-MvI7faY8MWa6ogQTZMy:b-tapclo) (no related file):*
FYI: I verified manually that the rebased and ready-for-merge version of this PR works correctly on my Ubuntu.

---


<!-- Sent from Reviewable.io -->

2022-02-07 07:43 UTC, merged