Added support for specifying an image registry (#51)
gramineproject/gsc pull request #52
Opened 2022-04-05 09:40 UTC by fsmunoz

## Description of the changes 

Added a `Registry` variable to the config template, and the jinja2 logic to the Dockerfile template to make use of it if present.
## How to test this PR? 

1. Existing builds should work as expected, i.e. no regression from the existing situation.
2. Using image names with registry paths in it should now work.

2022-04-05 11:37 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @fsmunoz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUAXyCYhR_Y7a9Nyi:-MztUAXyCYhR_Y7a9Nyj:bv2axa8) (no related file):*
Nice PR! Thanks, very reasonable feature.

I left my comments (please use the Reviewable plugin -- there is a big purple button in the PR description -- to check them). Also, if you need some guidance on how to correctly work on the PRs in Gramine/GSC, check this: https://gramine.readthedocs.io/en/latest/devel/onboarding.html

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUDlj8WQ8qHAyADoN:-MztUDlj8WQ8qHAyADoO:b-q7yihj) (no related file):*
Please modify the documentation page, adding the new `Registry` field: https://github.com/gramineproject/gsc/blob/master/Documentation/index.rst#configuration

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztURS4C1wNI6LXV8BR):*
We don't use past tense in commit messages. Please change to `Add support for specifying an image registry`.
___
*[config.yaml.template, line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUflWBzmKDHJe5_Xu:-MztUflWBzmKDHJe5_Xv:b-f4lo0p) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/config.yaml.template#L7)):*
> ```
> # If the image has a specific registry, define it here. Strictly
> # speaking this can contain both the registry and repository name:
> # it's everything that will be prepended tp the image name (as defined
> ```

Typo: `tp` -> `to`
___
*[config.yaml.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUhUt4AJUANrxInJi:-MztUhUt4AJUANrxInJj:b6eug7b) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/config.yaml.template#L8)):*
> ```
> # speaking this can contain both the registry and repository name:
> # it's everything that will be prepended tp the image name (as defined
> # in Distro).
> ```

Please re-wrap your 4-line comment to 100-char limit. We in Gramine/GSC use the 100-char limit instead of the more classic 72/80 char limit.
___
*[config.yaml.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUrvj3zR9As0J-kUX:-MztUrvj3zR9As0J-kUY:b-436g71) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/config.yaml.template#L9)):*
> ```
> # it's everything that will be prepended tp the image name (as defined
> # in Distro).
> # Registry: "registry.access.redhat.com/ubi8"
> ```

I don't like this logic of "uncomment to use". In other places on this config file, we use the logic "if empty then not used; fill the value to use".

So I suggest to always have the `Registry` field, just have it as empty by default. So I'd change to this:
```
# ... Empty by default; example value: "registry.access.redhat.com/ubi8".
Registry: ""
```
___
*[templates/Dockerfile.common.compile.template, line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztVMfbCWPRFnjDCqU8:-MztVMfbCWPRFnjDCqU9:b-k0n3iu) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/templates/Dockerfile.common.compile.template#L1)):*
> ```
> {% if Registry is defined %}
> ```

With my proposed approach of "empty value by default", this will be changed to the check of length:
```
{% if Registry|length %}
```


<!-- Sent from Reviewable.io -->

2022-04-05 13:33 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: 0 of 3 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUAXyCYhR_Y7a9Nyi:-MztnWdoD_7EAFO6l42U:b-kqktos) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Nice PR! Thanks, very reasonable feature.

I left my comments (please use the Reviewable plugin -- there is a big purple button in the PR description -- to check them). Also, if you need some guidance on how to correctly work on the PRs in Gramine/GSC, check this: https://gramine.readthedocs.io/en/latest/devel/onboarding.html
</blockquote></details>

Thank you, never used Reviewable before. I can't say I've read the entire recommended bibliography (yet), but I had read it, albeit perhaps not with the attention I should. 

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUDlj8WQ8qHAyADoN:-Mztt2Ce5OO7tIzNPsd9:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please modify the documentation page, adding the new `Registry` field: https://github.com/gramineproject/gsc/blob/master/Documentation/index.rst#configuration
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztURS4C1wNI6LXV8BR):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We don't use past tense in commit messages. Please change to `Add support for specifying an image registry`.
</blockquote></details>

Done.
___
*[config.yaml.template, line 8 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUhUt4AJUANrxInJi:-MztvEJJ2YGiCKTZcKjz:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/config.yaml.template#L8)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please re-wrap your 4-line comment to 100-char limit. We in Gramine/GSC use the 100-char limit instead of the more classic 72/80 char limit.
</blockquote></details>

Done.
___
*[config.yaml.template, line 9 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUrvj3zR9As0J-kUX:-MztvGjx2pN3T6g7ggvR:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/config.yaml.template#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like this logic of "uncomment to use". In other places on this config file, we use the logic "if empty then not used; fill the value to use".

So I suggest to always have the `Registry` field, just have it as empty by default. So I'd change to this:
```
# ... Empty by default; example value: "registry.access.redhat.com/ubi8".
Registry: ""
```
</blockquote></details>

Done.
___
*[templates/Dockerfile.common.compile.template, line 1 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztVMfbCWPRFnjDCqU8:-MztvJcB9pF0sHXAO_aa:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/d928bbbeadc8f128b0ddca0748d8c5a6abbb422a/templates/Dockerfile.common.compile.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

With my proposed approach of "empty value by default", this will be changed to the check of length:
```
{% if Registry|length %}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-05 15:08 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @fsmunoz)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUAXyCYhR_Y7a9Nyi:-MzuG-ywD6XZ4rqIRLK5:b-qv6h2g) (no related file):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

Thank you, never used Reviewable before. I can't say I've read the entire recommended bibliography (yet), but I had read it, albeit perhaps not with the attention I should. 
</blockquote></details>

No need to read the bibliography, I meant the "typical flows" part of that document :)

https://gramine.readthedocs.io/en/latest/devel/onboarding.html#typical-gramine-development-flows -- this one

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuG9jIDNvWCQmOv0iN:-MzuG9jIDNvWCQmOv0iO:b-o4chf6) (no related file):*
@fsmunoz What would be the simplest way to verify this PR? I mean, what would be the HelloWorld Docker image from some registry? I want to quickly test it myself.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/52#-MztURS4C1wNI6LXV8BR):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I'll merge the two commit messages when I'll do the final preparation of this PR.


<!-- Sent from Reviewable.io -->

2022-04-05 16:20 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MztUAXyCYhR_Y7a9Nyi:-MzuWJJU1uM5JcSoKmwR:b-igcy3e) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

No need to read the bibliography, I meant the "typical flows" part of that document :)

https://gramine.readthedocs.io/en/latest/devel/onboarding.html#typical-gramine-development-flows -- this one
</blockquote></details>

Yeah, got you, I was joking about the comprehensiveness of the recommended reading :)

---


<!-- Sent from Reviewable.io -->

2022-04-05 16:23 UTC, mkow requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @fsmunoz)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuWMh6-3h7U2yRqb41):*
Please try to shorten the one-liner, it's _way_ to long. See e.g. https://commit.style/ (we don't have any hard limit for this, just make it reasonably short).
___
*[Documentation/index.rst, line 304 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuX3fm2ONdgJLHpm2y:-MzuX3fm2ONdgJLHpm2z:b-f5zg6i) ([raw file](https://github.com/gramineproject/gsc/blob/31a0ee3d6810b510b88f94c8fce4a12262c9d90a/Documentation/index.rst#L304)):*
> where the Linux distribution image is.

This reads weird to me, I'd rather say "is located".


<!-- Sent from Reviewable.io -->

2022-04-05 22:38 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv and @mkow)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuWMh6-3h7U2yRqb41):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please try to shorten the one-liner, it's _way_ to long. See e.g. https://commit.style/ (we don't have any hard limit for this, just make it reasonably short).
</blockquote></details>

Done.
___
*[Documentation/index.rst, line 304 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuX3fm2ONdgJLHpm2y:-MzvsAmd4euLkrMscXC9:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/31a0ee3d6810b510b88f94c8fce4a12262c9d90a/Documentation/index.rst#L304)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> where the Linux distribution image is.

This reads weird to me, I'd rather say "is located".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-05 22:58 UTC, mkow requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), period found at the end of a one-liner (waiting on @dimakuv and @fsmunoz)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuWMh6-3h7U2yRqb41):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please read https://commit.style/ again ;)
___
*[-- commits, line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/52#-MzvvmUMAVpu_zfflzmS):*
This split doesn't make sense, now your PR consists of: (simplifying)
- A commit which introduces a feature plus its documentation
- A commit which fixes documentation added in the commit above

This isn't something which we want to merge to `master`, because the development history of this specific change is not relevant for anyone reading the commit log on `master`. If you wanted us to squash this commit later, then please use `--fixup` with git (see https://gramine.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle).


<!-- Sent from Reviewable.io -->

2022-04-05 23:34 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: 2 of 3 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuWMh6-3h7U2yRqb41):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please read https://commit.style/ again ;)
</blockquote></details>

I did, I initially assumed that a single <50 message was the part you were focusing on. I'm assuming by your answer that that wasn't it, so I've added a small text as well.
___
*[-- commits, line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/52#-MzvvmUMAVpu_zfflzmS):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This split doesn't make sense, now your PR consists of: (simplifying)
- A commit which introduces a feature plus its documentation
- A commit which fixes documentation added in the commit above

This isn't something which we want to merge to `master`, because the development history of this specific change is not relevant for anyone reading the commit log on `master`. If you wanted us to squash this commit later, then please use `--fixup` with git (see https://gramine.readthedocs.io/en/latest/devel/contributing.html#pr-life-cycle).
</blockquote></details>

I've cleaned up history to have the initial code and another one focusing on the changes as discussed here. If needed I can include it all in the first.


<!-- Sent from Reviewable.io -->

2022-04-06 07:38 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @fsmunoz and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuG9jIDNvWCQmOv0iN:-MzxncBb3k9JXqqdoKVl:b-poxs1h) (no related file):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

Good question; my end goal with this is to add UBI 8 support (https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image) since it's used as a base image in quite a few offerings, but t have that  as a separate PR. The following should however work for the standard tests (like `python`) that use Ubuntu 20.04: it specifies the version of it I've found in the AWS public registry.
```
Distro: "ubuntu:20.04"

# If the image has a specific registry, defined it here. Strictly                                                                                                                       
# speaking this can contain both the registry and repository name:                                                                                                                      
# it's everything that will be prepended tp the image name (as defined                                                                                                                  
# in Distro).                                                                                                                                                                           
Registry: "public.ecr.aws/lts"
```

</blockquote></details>

Thanks. I manually verified using the proposed AWS registry, and your PR works nicely.

---
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/52#-MzxniTpErdHQJyMhM6G:-MzxniTqBrQogkdmzETa:bbg8zzs) (no related file):*
@aneessahib Does this PR look good to you?

---
___
*[-- commits, line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/52#-MzvvmUMAVpu_zfflzmS):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

I've cleaned up history to have the initial code and another one focusing on the changes as discussed here. If needed I can include it all in the first.
</blockquote></details>

Yes, it all should be included in the first commit. By included we mean -- you can still split this PR into two commits, but the second commit should contain the magic `fixup!` word, which tells Git to consider the two commits as one logical entity (and during the final git-rebase before merging your PR into our master branch, Git will automatically merge these two commits into one commit).

In general, we're using this flow in Gramine/GSC development: https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash

You can look at a couple open PRs in our core Gramine repo to see the actual examples of how other Gramine developers do it: https://github.com/gramineproject/gramine/pulls

But in general, you don't need to bother with it. The final rebase & merge is done by us anyway (Gramine maintainers), so we can do these small changes to your commits during that step. So just don't bother to fix it in this PR, but if you plan to submit more PRs to our Gramine/GSC repos, please take into account our git-fixup flow.


<!-- Sent from Reviewable.io -->

2022-04-06 08:14 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @fsmunoz and @mkow)

___
*[-- commits, line 12 at r3](https://reviewable.io/reviews/gramineproject/gsc/52#-MzvvmUMAVpu_zfflzmS):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yes, it all should be included in the first commit. By included we mean -- you can still split this PR into two commits, but the second commit should contain the magic `fixup!` word, which tells Git to consider the two commits as one logical entity (and during the final git-rebase before merging your PR into our master branch, Git will automatically merge these two commits into one commit).

In general, we're using this flow in Gramine/GSC development: https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash

You can look at a couple open PRs in our core Gramine repo to see the actual examples of how other Gramine developers do it: https://github.com/gramineproject/gramine/pulls

But in general, you don't need to bother with it. The final rebase & merge is done by us anyway (Gramine maintainers), so we can do these small changes to your commits during that step. So just don't bother to fix it in this PR, but if you plan to submit more PRs to our Gramine/GSC repos, please take into account our git-fixup flow.
</blockquote></details>

Thank you. I will leave it as is then, and will apply it in my next PR.


<!-- Sent from Reviewable.io -->

2022-04-06 08:28 UTC, aneessahib commented
looks fine to me.

2022-04-06 11:33 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @fsmunoz)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuWMh6-3h7U2yRqb41):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

I did, I initially assumed that a single <50 message was the part you were focusing on. I'm assuming by your answer that that wasn't it, so I've added a small text as well.
</blockquote></details>

It was actually about punctuation - what you did after reading my link was that you added periods at the end of all one-liners, which https://commit.style/ explicitly recommends against ;) (and before you didn't have them, so I guess you misread this point of the guide?)
___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/gramineproject/gsc/52#-Mzyd8oz51gjG2qDKQcH):*
Should be "Add", not "Added" (but we can fix this ourselves when rebasing).


<!-- Sent from Reviewable.io -->

2022-04-06 12:20 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @fsmunoz)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/gramineproject/gsc/52#-MzuWMh6-3h7U2yRqb41):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It was actually about punctuation - what you did after reading my link was that you added periods at the end of all one-liners, which https://commit.style/ explicitly recommends against ;) (and before you didn't have them, so I guess you misread this point of the guide?)
</blockquote></details>

Understood, I didn't even noticed that at the time.


<!-- Sent from Reviewable.io -->

2022-04-06 12:21 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @fsmunoz and @mkow)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/gramineproject/gsc/52#-Mzyd8oz51gjG2qDKQcH):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be "Add", not "Added" (but we can fix this ourselves when rebasing).
</blockquote></details>

Ugh, I could've swear I had fixed that when rebasing. 


<!-- Sent from Reviewable.io -->

2022-04-06 21:19 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @fsmunoz)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/gramineproject/gsc/52#-Mzyd8oz51gjG2qDKQcH):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

Ugh, I could've swear I had fixed that when rebasing. 
</blockquote></details>

No worries :) Please just be more careful next time ;)


<!-- Sent from Reviewable.io -->

2022-04-07 09:09 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @mkow)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/gramineproject/gsc/52#-Mzyd8oz51gjG2qDKQcH):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

No worries :) Please just be more careful next time ;)
</blockquote></details>

Will do.


<!-- Sent from Reviewable.io -->

2022-04-07 15:30 UTC, fsmunoz reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/gramineproject/gsc/52#-Mzyd8oz51gjG2qDKQcH):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

This was bothering me so I ended up correcting both things: I squashed the commits and amended the message. Hope it's OK now.


<!-- Sent from Reviewable.io -->

2022-04-08 00:04 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)

___
*[-- commits, line 3 at r4](https://reviewable.io/reviews/gramineproject/gsc/52#-Mzyd8oz51gjG2qDKQcH):*
<details><summary><i>Previously, fsmunoz (Frederico Muñoz) wrote…</i></summary><blockquote>

This was bothering me so I ended up correcting both things: I squashed the commits and amended the message. Hope it's OK now.
</blockquote></details>

Looks good now, thanks!


<!-- Sent from Reviewable.io -->

2022-04-08 07:13 UTC, dimakuv submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-04-11 14:14 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/52)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-04-11 14:38 UTC, merged