Add gramine sources when built with debug flag
gramineproject/gsc pull request #57
Opened 2022-05-04 15:59 UTC by vijaydhanraj

## Description of the changes 
This PR adds Gramine sources into GSC when built with `-d` flag. This is useful when debugging with GDB.

## How to test this PR? 
Regular CI tests.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gramineproject/gsc/57)

2022-05-04 16:28 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/57#-N1Etc3L-ZMIdf7MNn7A:-N1Etc3M-1WMTAGsiMTV:b-1ga6dc) (no related file):*
Note to myself: check manually that this PR works as expected.

---


<!-- Sent from Reviewable.io -->

2022-05-05 06:45 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @vijaydhanraj)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/57#-N1Etc3L-ZMIdf7MNn7A:-N1Hx9Nx4P9GDYm8nA_-:b-rzml1l) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Note to myself: check manually that this PR works as expected.
</blockquote></details>

@vijaydhanraj I had to add `loader.pal_internal_mem_size = "128M"` to `test/generic.manifest` to test the default Python Docker image. I think in our private conversation, you also encountered this problem.

So I suggest to add this line to the very beginning of the `test/generic.manifest` file, with a comment. Something like this:
```
# some workloads like Python may generate huge manifest files
loader.pal_internal_mem_size = "128M"
```

Apart from this, the PR works perfectly.

---


<!-- Sent from Reviewable.io -->

2022-05-05 17:58 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: 2 of 3 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/57#-N1Etc3L-ZMIdf7MNn7A:-N1KMA1eEpg5PuXTg0Gm:b4jrdia) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@vijaydhanraj I had to add `loader.pal_internal_mem_size = "128M"` to `test/generic.manifest` to test the default Python Docker image. I think in our private conversation, you also encountered this problem.

So I suggest to add this line to the very beginning of the `test/generic.manifest` file, with a comment. Something like this:
```
# some workloads like Python may generate huge manifest files
loader.pal_internal_mem_size = "128M"
```

Apart from this, the PR works perfectly.
</blockquote></details>

Thanks @dimakuv for checking.

Yes, I did observe the same issue but thought it was my setting issue. I didn't realize `debug` option adds tons of other files in the manifest. I have added this option `loader.pal_internal_mem_size = "128M"` and the comment as well.

---


<!-- Sent from Reviewable.io -->

2022-05-05 18:02 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-05-06 09:52 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @vijaydhanraj)

___
*[`templates/entrypoint.common.manifest.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/57#-N1Nm78hA1u1O-I5tt1p:-N1Nm78i1XAFxR_UUCvj:b-ichdlv) ([raw file](https://github.com/gramineproject/gsc/blob/9408b937bcf4cceb1d63a272ea626f81aae4507a/templates/entrypoint.common.manifest.template#L16)):*
> ```
> 
> sgx.nonpie_binary = true
> sgx.debug = {% if debug %} true {% else %} false {% endif %}
> ```

This isn't mentioned in the commit message and seems like an important and breaking change. Please split it into a separate commit.


<!-- Sent from Reviewable.io -->

2022-05-06 10:50 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`templates/entrypoint.common.manifest.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/57#-N1Nm78hA1u1O-I5tt1p:-N1NzFdk8kv8fvThOW72:b-ejompu) ([raw file](https://github.com/gramineproject/gsc/blob/9408b937bcf4cceb1d63a272ea626f81aae4507a/templates/entrypoint.common.manifest.template#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This isn't mentioned in the commit message and seems like an important and breaking change. Please split it into a separate commit.
</blockquote></details>

Yes, I think a separate commit for this change makes sense. Something like `Enabled DEBUG attribute in enclaves when built with debug flag`


<!-- Sent from Reviewable.io -->

2022-05-06 20:38 UTC, vijaydhanraj reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow)

___
*[`templates/entrypoint.common.manifest.template` line 16 at r2](https://reviewable.io/reviews/gramineproject/gsc/57#-N1Nm78hA1u1O-I5tt1p:-N1Q4x083-g2tl4_RsXS:b-1eh3wi) ([raw file](https://github.com/gramineproject/gsc/blob/9408b937bcf4cceb1d63a272ea626f81aae4507a/templates/entrypoint.common.manifest.template#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

*Enable
</blockquote></details>

Sure, done.


<!-- Sent from Reviewable.io -->

2022-05-08 14:13 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL)



<!-- Sent from Reviewable.io -->

2022-05-09 06:13 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-05-09 13:48 UTC, dimakuv approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-05-09 13:59 UTC, mkow approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-05-09 16:08 UTC, merged