Remove `libcurl-dev` dependency
gramineproject/gsc pull request #81
Opened 2022-07-20 14:11 UTC by kailun-qin

This dependency is not required for `tools/sgx` in Gramine after the core Gramine's commit "[tools/sgx,curl,Docs] Link all dependencies of tools/sgx statically".

2023-02-21 09:37 UTC, kailun-qin commented
https://github.com/gramineproject/gramine/pull/773 was already merged; a new Gramine release v1.4 was also released. Should we move this PR forward?

2023-02-21 10:48 UTC, dimakuv approved these changes
Well, we're still waiting to merge https://github.com/gramineproject/gsc/pull/132 (I would feel more secure if you first tag GSC with `v1.4`, and only then apply this PR on the `master` branch).

But yes, this PR will be next in line for merge right after that one.

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81#-:-NOn_Tu5EiII692HhIGx:b-t21lne)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/81#-N7QxD7P9xqVXeRBnKKf:-NOn_f7m0QUwztps7u3d:bb6un1j) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The PR itself is good.

Blocking this until we do the following two things:
1. Merge gramineproject/gramine#773 into master
2. Produce a new Gramine release (v1.3 if the PR 773 is merged before v1.3's deadline; if not then v1.4)

This is because GSC is supposed to work correctly with the *last stable Gramine release*. We should not break this backwards-compatibility.
</blockquote></details>

Done

___


<!-- Sent from Reviewable.io -->

2023-02-21 14:04 UTC, dimakuv submitted a review, later dismissed
@kailun-qin Now we merged #132. Can you rebase your PR on top of the latest master?

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81#-:-NOoHSUD6HoaNy4bT5h5:bkdvtvb)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-02-21 15:15 UTC, kailun-qin reviewed
Rebased, thanks!

> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81#-:-NOoXjnfBDVi5DPfGUOC:b-c47yrb)* status: 0 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)



<!-- Sent from Reviewable.io -->

2023-02-22 10:06 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @kailun-qin)

___
*[`templates/ubuntu/Dockerfile.build.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/81#-NOs_BwpE6KwCrTJrzTj:-NOs_BwpE6KwCrTJrzTk:b-q9wcx6) ([raw file](https://github.com/gramineproject/gsc/blob/e7073b7d4444c6943afcc08cdf60da0dd39f747c/templates/ubuntu/Dockerfile.build.template#L7)):*
> ```
>     && env DEBIAN_FRONTEND=noninteractive apt-get install -y \
>         binutils \
>         libcurl4-openssl-dev \
> ```

Why did you revert the removal of `libcurl4-openssl-dev`?

Aren't you supposed to do this removal in `debian/` templates now?


<!-- Sent from Reviewable.io -->

2023-02-22 12:44 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-11 07:52 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2023-07-11 10:42 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/81)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-07-11 10:56 UTC, merged