Add option to use signing key protected by a pass phrase
gramineproject/gsc pull request #88
Opened 2022-09-18 09:30 UTC by aneessahib

This PR add some basic security to the gsc sign stage by providing users the option to use a signing key protected by a pass phrase.

To test
`./gsc sign-image <base-image> <key> -p <passphrase>`

2022-09-20 08:31 UTC, dimakuv requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @aneessahib)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP-kYJ0M7Viurg95X0:-NCP-kYK42ewUdYzjKqD:bfa6jzt) (no related file):*
Please update this part of documentation as well: https://gramine.readthedocs.io/projects/gsc/en/latest/#gsc-sign-image-signs-a-graminized-image

I mean, you should add `--passphrase`.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP0UuFA2_K_1zI9tub:-NCP0UuFA2_K_1zI9tuc:b-95ar4h) (no related file):*
Could you show some examples, how to reproduce (test) this PR?

___
___
*[`gsc.py` line 344 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP09lS2-nxPK9nLPsb:-NCP09lS2-nxPK9nLPsc:b-b48vsl) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/gsc.py#L344)):*
> ```Python
>         dockerfile.write(sign_template.render(image=unsigned_image_name))
> 
>     # copy user-provided signing key to our tmp build dir (to copy it later inside Docker image)
> ```

Please update this comment:
`...signing key and signing Bash script ... (to copy them later...)`
___
*[`sign.sh` line 13 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCOynxo2a3iP1-3HJN4:-NCOynxo2a3iP1-3HJN5:b-y3p7o3) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L13)):*
> ```Shell
>             exit 0
>       }
>       send "[lindex $argv 3]\r"
> ```

So waht happens in these three cases:
1. User didn't specify `passphrase` but the key requires a passphrase? `./gsc sign-image` command will simply fail? What will be the error message? Or will it stop and wait for user's input?
2. User did specify a `passphrase` but the key does *not* require a passphrase? Will everything just work, or this `expect` trick will complain or even fail?
3. The old case: what happens if the user doesn't specify `passphrase` and the key does *not* require a passphrase? Does everything just work as it worked before?
___
*[`sign.sh` line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP--TPDZBDRJAkanai:-NCP--TPDZBDRJAkanaj:b-djfam9) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L15)):*
> ```Shell
>       send "[lindex $argv 3]\r"
>       set times [ expr $times + 1];
>       exp_continue
> ```

Why do you even need this loop? Can't you just do it once? Or is it considered a good practice to have such a loop? (If yes, then please give us some links on this `expect` flow.)
___
*[`templates/Dockerfile.common.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP-Ebb7B36nU7hrtck:-NCP-Ebb7B36nU7hrtcl:b-2ekbwz) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/templates/Dockerfile.common.sign.template#L6)):*
> ```
> COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem
> COPY sign.sh /gramine/app_files/sign.sh
> RUN chmod +x /gramine/app_files/sign.sh
> ```

Could you have these three new lines as a separate code block, to make it visually more clear? Like this:
```
# Sign image in a separate stage to ensure that signing key is never part of the final image
FROM {{image}} as unsigned_image
COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem

ARG passphrase
COPY sign.sh /gramine/app_files/sign.sh
RUN chmod +x /gramine/app_files/sign.sh

RUN ...
```


<!-- Sent from Reviewable.io -->

2022-09-20 11:49 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP-kYJ0M7Viurg95X0:-NCPYxog68dTxq9Xq40v:b-xtd155) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please update this part of documentation as well: https://gramine.readthedocs.io/projects/gsc/en/latest/#gsc-sign-image-signs-a-graminized-image

I mean, you should add `--passphrase`.
</blockquote></details>

added `-p` to keep it consistent with `-c`

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP0UuFA2_K_1zI9tub:-NCPZB-R44VCiMVOpAoG:bp340mu) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you show some examples, how to reproduce (test) this PR?
</blockquote></details>

Generate a key encrypted with a password, for eg
`openssl genrsa -3 -aes128 -passout pass:test@123 -out enclave-key.pem 3072`

Provide the password during the gsc sign step as shown below 
`./gsc sign-image <base-image> enclave-key.pem -p test@123`

I have just added these to the PR description as well

___
___
*[`gsc.py` line 344 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP09lS2-nxPK9nLPsb:-NCPbEwcBH2rlgfYVECH:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/gsc.py#L344)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please update this comment:
`...signing key and signing Bash script ... (to copy them later...)`
</blockquote></details>

Done.
___
*[`sign.sh` line 13 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCOynxo2a3iP1-3HJN4:-NCPbHeX9GLS2WRZqxw-:b-ys8sdg) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L13)):*
>1 . User didn't specify passphrase but the key requires a passphrase? ./gsc sign-image command will simply fail? What will be the error message? Or will it stop and wait for user's input?
User didn't specify passphrase but the key requires a passphrase? ./gsc sign-image command will simply fail? What will be the error message? Or will it stop and wait for user's input?

Will be treated as no password provided, `OpenSSL` immediately errors out terminating `gsc sign`.  Error messages have differed time to time - we have no control since this is all OpenSSL, for eg below are two such messages

`
unable to load key file
140504697643456:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:564:
140504697643456:error:0906A065:PEM routines:PEM_do_header:bad decrypt:../crypto/pem/pem_lib.c:461:
`
`
unable to load key file
140504697643456:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:564:
140504697643456:error:0906A065:PEM routines:PEM_do_header:bad decrypt:../crypto/pem/pem_lib.c:461:
`

>2. User did specify a passphrase but the key does not require a passphrase? Will everything just work, or this expect trick will complain or even fail?

In this case expect loop does not execute since the condition wont be met. And the sign operation in `spawn` completes successfully.

>3. The old case: what happens if the user doesn't specify passphrase and the key does not require a passphrase? Does everything just work as it worked before?

Yes everything works just like before. The password ARG stays initialized at `''`.  Expect loop does not execute, and spawn completes successfully.
___
*[`sign.sh` line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP--TPDZBDRJAkanai:-NCPiAUu7_870J8mBwO5:bdc960f) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L15)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do you even need this loop? Can't you just do it once? Or is it considered a good practice to have such a loop? (If yes, then please give us some links on this `expect` flow.)
</blockquote></details>

Passphrase prompt appears twice. This is because of the two operations we do in the `gramine-sgx-sign` tool (once for obtaining the modulus of the key and the other for signing). And this is why I'm exiting the `expect` loop after 2 iterations.
___
*[`templates/Dockerfile.common.sign.template` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP-Ebb7B36nU7hrtck:-NCPisdIClvhJiFq9dkV:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/templates/Dockerfile.common.sign.template#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you have these three new lines as a separate code block, to make it visually more clear? Like this:
```
# Sign image in a separate stage to ensure that signing key is never part of the final image
FROM {{image}} as unsigned_image
COPY gsc-signer-key.pem /gramine/app_files/gsc-signer-key.pem

ARG passphrase
COPY sign.sh /gramine/app_files/sign.sh
RUN chmod +x /gramine/app_files/sign.sh

RUN ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-20 11:53 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`sign.sh` line 13 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCOynxo2a3iP1-3HJN4:-NCPjUs_CSGHZmBrcnQd:b8yrx6i) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L13)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

>1 . User didn't specify passphrase but the key requires a passphrase? ./gsc sign-image command will simply fail? What will be the error message? Or will it stop and wait for user's input?
User didn't specify passphrase but the key requires a passphrase? ./gsc sign-image command will simply fail? What will be the error message? Or will it stop and wait for user's input?

Will be treated as no password provided, `OpenSSL` immediately errors out terminating `gsc sign`.  Error messages have differed time to time - we have no control since this is all OpenSSL, for eg below are two such messages

`
unable to load key file
140504697643456:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:564:
140504697643456:error:0906A065:PEM routines:PEM_do_header:bad decrypt:../crypto/pem/pem_lib.c:461:
`
`
unable to load key file
140504697643456:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:564:
140504697643456:error:0906A065:PEM routines:PEM_do_header:bad decrypt:../crypto/pem/pem_lib.c:461:
`

>2. User did specify a passphrase but the key does not require a passphrase? Will everything just work, or this expect trick will complain or even fail?

In this case expect loop does not execute since the condition wont be met. And the sign operation in `spawn` completes successfully.

>3. The old case: what happens if the user doesn't specify passphrase and the key does not require a passphrase? Does everything just work as it worked before?

Yes everything works just like before. The password ARG stays initialized at `''`.  Expect loop does not execute, and spawn completes successfully.


</blockquote></details>

OpenSSL error when no password is given
`
Enter pass phrase for /gramine/app_files/gsc-signer-key.pem:

140060795971392:error:2807106B:UI routines:UI_process:processing error:crypto/ui/ui_lib.c:545:while reading strings
`


<!-- Sent from Reviewable.io -->

2022-09-20 12:07 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`sign.sh` line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP--TPDZBDRJAkanai:-NCPmBNj8KF3ALJw-mzC:b-6sgibm) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L15)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Passphrase prompt appears twice. This is because of the two operations we do in the `gramine-sgx-sign` tool (once for obtaining the modulus of the key and the other for signing). And this is why I'm exiting the `expect` loop after 2 iterations.
</blockquote></details>

Forgot to mention one more thing - OpenSSL never quits asking till it get the correct passphrase (for keys that need one ofcourse), so thats another reason why I kept a `while` loop plus exit after 2 iterations.


<!-- Sent from Reviewable.io -->

2022-09-20 12:35 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv)

___
*[`sign.sh` line 13 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCOynxo2a3iP1-3HJN4:-NCPqtus0AP5e3WG6x4v:bsetnlh) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L13)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

OpenSSL error when no password is given
`
Enter pass phrase for /gramine/app_files/gsc-signer-key.pem:

140060795971392:error:2807106B:UI routines:UI_process:processing error:crypto/ui/ui_lib.c:545:while reading strings
`
</blockquote></details>

Summarizing correctly once to clearly differentiate between no passphrase and incorrect passphrase, for a key that needs a passphrase. 

- when no passphrase is given, OpenSSL throws the below error, and asks the user again.
`Enter pass phrase for /gramine/app_files/gsc-signer-key.pem:
139876781142464:error:28078065:UI routines:UI_set_result_ex:result too small:../crypto/ui/ui_lib.c:903:You must type in 4 to 1023 characters`

The `expect` while loop I have here will help exit after 2 unsuccessful attempts. But a user will be able to see the OpenSSL error


- when wrong passphrase is given, OpenSSL errors and exits 
`Enter pass phrase for /gramine/app_files/gsc-signer-key.pem:
unable to load key file
140604401168832:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:564:
140604401168832:error:0906A065:PEM routines:PEM_do_header:bad decrypt:../crypto/pem/pem_lib.c:461:`

In both the above cases, user must gets clues that the error has something to do with the passphrase


<!-- Sent from Reviewable.io -->

2022-09-21 11:03 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP0UuFA2_K_1zI9tub:-NCUhasCBlU8O7alH8Qt:b-sqslqx) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Generate a key encrypted with a password, for eg
`openssl genrsa -3 -aes128 -passout pass:test@123 -out enclave-key.pem 3072`

Provide the password during the gsc sign step as shown below 
`./gsc sign-image <base-image> enclave-key.pem -p test@123`

I have just added these to the PR description as well

</blockquote></details>

I tried these exact commands (on the classic Python docker image), but it doesn' work for me:
```
 ---> 0ebc8707faa9
Step 6/9 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && /gramine/app_files/sign.sh       /gramine/app_files/gsc-signer-key.pem       /gramine/app_files/entrypoint.manifest       /gramine/app_files/entrypoint.manifest.sgx       $passphrase

 ---> Running in bfcf3d556ed0
spawn gramine-sgx-sign --key /gramine/app_files/gsc-signer-key.pem --manifest /gramine/app_files/entrypoint.manifest --output /gramine/app_files/entrypoint.manifest.sgx
Removing intermediate container bfcf3d556ed0
 ---> 7e005cbed47d
Step 7/9 : FROM gsc-python-unsigned

 ---> c489515e428f
Step 8/9 : COPY --from=unsigned_image /gramine/app_files/*.sig /gramine/app_files/

Failed to build a signed graminized Docker image `gsc-python`.
```

What am I doing wrong?

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCUdjUY7rtXTjQDtBct:-NCUdjUZ9ciFCZhAqzQd:bkx36fp) (no related file):*
Testing **enclave signing key with passphrase**.

If I don't pass the `-p <passphrase>` to GSC, the result is very unintuitive:
```
$ ./gsc sign-image python enclave-key.pem                                        
Signing graminized Docker image `unsigned_image_name` -> `gsc-python`...
Step 1/9 : FROM gsc-python-unsigned as unsigned_image

...
Step 6/9 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && /gramine/app_files/sign.sh       /gramine/app_files/gsc-signer-key.pem       /gramine/app_files/entrypoint.manifest       /gramine/app_files/entrypoint.manifest.sgx       $passphrase

 ---> Running in d04fcbceae16
spawn gramine-sgx-sign --key /gramine/app_files/gsc-signer-key.pem --manifest /gramine/app_files/entrypoint.manifest --output /gramine/app_files/entrypoint.manifest.sgx
Removing intermediate container d04fcbceae16
 ---> bd324d6af90f
Step 7/9 : FROM gsc-python-unsigned

 ---> c489515e428f
Step 8/9 : COPY --from=unsigned_image /gramine/app_files/*.sig /gramine/app_files/

Failed to build a signed graminized Docker image `gsc-python`.
```

___
___
*[`sign.sh` line 15 at r1](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP--TPDZBDRJAkanai:-NCUTetA2SevqOakEPl2:b-wsvasg) ([raw file](https://github.com/gramineproject/gsc/blob/0749cdf953d48f6fa1cc155f09c7671a7f7ea267/sign.sh#L15)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Forgot to mention one more thing - OpenSSL never quits asking till it get the correct passphrase (for keys that need one ofcourse), so thats another reason why I kept a `while` loop plus exit after 2 iterations.
</blockquote></details>

Thanks for the explanation!
___
*[`Documentation/index.rst` line 158 at r2](https://reviewable.io/reviews/gramineproject/gsc/88#-NCUUKP3BtQFQkKjJXZC:-NCUUKP3BtQFQkKjJXZD:btfc250) ([raw file](https://github.com/gramineproject/gsc/blob/f06a2ab8df5c801af88d2cf0b8d97720b3ec2d8e/Documentation/index.rst#L158)):*
> ```reStructuredText
> 
>    Provide passphrase for the enclave signing key (if applicable)
> ```

Could you move this right-after `option:: -c`? It is more readable to have all such options before the `IMAGE-NAME` and `KEY-FILE` options.


<!-- Sent from Reviewable.io -->

2022-09-21 13:12 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @dimakuv)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP0UuFA2_K_1zI9tub:-NCVA8OS73sRecYuXYmr:b-msmut7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I tried these exact commands (on the classic Python docker image), but it doesn' work for me:
```
 ---> 0ebc8707faa9
Step 6/9 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && /gramine/app_files/sign.sh       /gramine/app_files/gsc-signer-key.pem       /gramine/app_files/entrypoint.manifest       /gramine/app_files/entrypoint.manifest.sgx       $passphrase

 ---> Running in bfcf3d556ed0
spawn gramine-sgx-sign --key /gramine/app_files/gsc-signer-key.pem --manifest /gramine/app_files/entrypoint.manifest --output /gramine/app_files/entrypoint.manifest.sgx
Removing intermediate container bfcf3d556ed0
 ---> 7e005cbed47d
Step 7/9 : FROM gsc-python-unsigned

 ---> c489515e428f
Step 8/9 : COPY --from=unsigned_image /gramine/app_files/*.sig /gramine/app_files/

Failed to build a signed graminized Docker image `gsc-python`.
```

What am I doing wrong?
</blockquote></details>

The expect loop timed-out. Have disabled timeouts now. Pls check once.

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCUdjUY7rtXTjQDtBct:-NCVAJbC7a7bIUYytgFm:b-89a4l7) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Testing **enclave signing key with passphrase**.

If I don't pass the `-p <passphrase>` to GSC, the result is very unintuitive:
```
$ ./gsc sign-image python enclave-key.pem                                        
Signing graminized Docker image `unsigned_image_name` -> `gsc-python`...
Step 1/9 : FROM gsc-python-unsigned as unsigned_image

...
Step 6/9 : RUN export PYTHONPATH="${PYTHONPATH}:$(find /gramine/meson_build_output/lib -type d -path '*/site-packages')" && /gramine/app_files/sign.sh       /gramine/app_files/gsc-signer-key.pem       /gramine/app_files/entrypoint.manifest       /gramine/app_files/entrypoint.manifest.sgx       $passphrase

 ---> Running in d04fcbceae16
spawn gramine-sgx-sign --key /gramine/app_files/gsc-signer-key.pem --manifest /gramine/app_files/entrypoint.manifest --output /gramine/app_files/entrypoint.manifest.sgx
Removing intermediate container d04fcbceae16
 ---> bd324d6af90f
Step 7/9 : FROM gsc-python-unsigned

 ---> c489515e428f
Step 8/9 : COPY --from=unsigned_image /gramine/app_files/*.sig /gramine/app_files/

Failed to build a signed graminized Docker image `gsc-python`.
```
</blockquote></details>

Ditto

___


<!-- Sent from Reviewable.io -->

2022-09-22 09:19 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCP0UuFA2_K_1zI9tub:-NCZTVKH5-P52eZgDwb3:banawpr) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

The expect loop timed-out. Have disabled timeouts now. Pls check once.
</blockquote></details>

I verified the new version, it works fine now!

___
*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCUdjUY7rtXTjQDtBct:-NCZTZMGAoAntxzyngP4:bbxey7n) (no related file):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

LGTM.

I tested the following scenarios:
1. enclave signing key with passphrase, and
    i. `gsc sign-image` with no passphrase provided -- fails with meaningful message
    ii. `gsc sign-image` with wrong passphrase provided -- fails with meaningful message
    iii. `gsc sign-image` with correct passphrase provided -- works
2. enclave signing key without passphrase, and
    i. `gsc sign-image` with no passphrase provided -- works
    ii. `gsc sign-image` with some (any) passphrase provided -- **passphrase ignored**, works

It makes sense to me. We could argue about the highlighted case 2.ii, but I think it's a reasonable action to just ignore the unused command-line argument (`-p <any-passphrase>`) when it is not required by the encryption key.

___


<!-- Sent from Reviewable.io -->

2022-09-23 13:52 UTC, mkow requested changes
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`gsc.py` line 355 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCe_alQ8LkYk4ZSO7ee:-NCe_alR2va0j3meS9ET:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/gsc.py#L355)):*
> ```Python
>         # builds, to not leave the signing key lingering in any Docker containers
>         build_docker_image(docker_socket.api, tmp_build_path, signed_image_name, 'Dockerfile.sign',
>                            forcerm=True, buildargs={"passphrase":args.passphrase})
> ```





_Suggestion:_
```Python
{"passphrase": args.passphrase}
```
___
*[`sign.sh` line 5 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaDeoALq0ZVklaXhU:-NCeaDeoALq0ZVklaXhV:b-mcb1hx) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L5)):*
> ```Shell
>             --key [lindex $argv 0] \
>             --manifest [lindex $argv 1] \
>             --output [lindex $argv 2]
> ```

this indentation is weird
___
*[`sign.sh` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaQMeCwhu3VYNhtEw:-NCeaQMeCwhu3VYNhtEx:undefined) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L10)):*
> ```Shell
> set times 0
> set maxtimes 1
> expect "Enter pass phrase for [lindex $argv 0]" {
> ```





_Suggestion:_
```Shell
passphrase
```
___
*[`sign.sh` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaSay2mj_2K4XdGyI:-NCeaSay2mj_2K4XdGyJ:b-7ilvfu) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L10)):*
> ```Shell
> set times 0
> set maxtimes 1
> expect "Enter pass phrase for [lindex $argv 0]" {
> ```

typo?



_Code quote:_
```Shell
lindex
```
___
*[`sign.sh` line 11 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaMQj3Dm4XmnTqpiw:-NCeaMQj3Dm4XmnTqpix:b6po9uo) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L11)):*
> ```Shell
> set maxtimes 1
> expect "Enter pass phrase for [lindex $argv 0]" {
>       if { $times > $maxtimes } {
> ```

ditto (weird indentation)
___
*[`templates/Dockerfile.common.sign.template` line 5 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCebQZ96m9T0U6wGF7T:-NCebQZ96m9T0U6wGF7U:b2fb8hi) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/templates/Dockerfile.common.sign.template#L5)):*
What about https://docs.docker.com/engine/reference/builder/#arg ?

>    Warning:
>
>    It is not recommended to use build-time variables for passing secrets like github keys, user credentials etc. Build-time variable values are visible to any user of the image with the docker history command.
>
>    Refer to the “build images with BuildKit” section to learn about secure ways to use secrets when building images.


<!-- Sent from Reviewable.io -->

2022-09-23 14:47 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 3 of 6 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[`gsc.py` line 355 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCe_alQ8LkYk4ZSO7ee:-NCene2wDPPUzuE9QzNv:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/gsc.py#L355)):*
> ```Python
>         # builds, to not leave the signing key lingering in any Docker containers
>         build_docker_image(docker_socket.api, tmp_build_path, signed_image_name, 'Dockerfile.sign',
>                            forcerm=True, buildargs={"passphrase":args.passphrase})
> ```

Done.
___
*[`sign.sh` line 5 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaDeoALq0ZVklaXhU:-NCenfe1DARC_hBEF1RG:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this indentation is weird
</blockquote></details>

Done.
___
*[`sign.sh` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaSay2mj_2K4XdGyI:-NCel9MYCc2crdNIqgul:b-72ods1) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

typo?
</blockquote></details>

Nope  https://wiki.tcl-lang.org/page/lindex
___
*[`sign.sh` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaQMeCwhu3VYNhtEw:-NCenhr-0jPfg5h30RUA:b2gr893) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L10)):*
> ```Shell
> set times 0
> set maxtimes 1
> expect "Enter pass phrase for [lindex $argv 0]" {
> ```

No can do - this is how OpenSSL prints it, so we `expect` the same.
___
*[`sign.sh` line 11 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaMQj3Dm4XmnTqpiw:-NCeo0vt9iH7dJ0neJ5r:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (weird indentation)
</blockquote></details>

Done.
___
*[`templates/Dockerfile.common.sign.template` line 5 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCebQZ96m9T0U6wGF7T:-NCeo2EW22M1ROcsC6IA:b-sym7p1) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/templates/Dockerfile.common.sign.template#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about https://docs.docker.com/engine/reference/builder/#arg ?

>    Warning:
>
>    It is not recommended to use build-time variables for passing secrets like github keys, user credentials etc. Build-time variable values are visible to any user of the image with the docker history command.
>
>    Refer to the “build images with BuildKit” section to learn about secure ways to use secrets when building images.
</blockquote></details>

Correct. This applies to enclave signing key as well. This image is discarded soon as we are done with it using the `FROM` keyword. Look few lines below.


<!-- Sent from Reviewable.io -->

2022-09-24 13:33 UTC, mkow requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib)

___
*[`sign.sh` line 10 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaQMeCwhu3VYNhtEw:-NCgZcc11rL-LDNb9C7m:bcn3o5u) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L10)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

No can do - this is how OpenSSL prints it, so we `expect` the same.
</blockquote></details>

Ah, right.
___
*[`sign.sh` line 11 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaMQj3Dm4XmnTqpiw:-NCgZvrC9chA9FbYGUJc:bnow8uy) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L11)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about `if`? Literally, every block of code in this PR was indented with a different number of spaces...
___
*[`templates/Dockerfile.common.sign.template` line 5 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCebQZ96m9T0U6wGF7T:-NCjgQ9IEo7BnzGgMwa8:b7sot80) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/templates/Dockerfile.common.sign.template#L5)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Correct. This applies to enclave signing key as well. This image is discarded soon as we are done with it using the `FROM` keyword. Look few lines below.
</blockquote></details>

Hmm, seems to indeed work due to this trick (although this is different than the case with .pem file, it didn't have to work the same way).


<!-- Sent from Reviewable.io -->

2022-09-24 14:43 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: 5 of 6 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[`sign.sh` line 11 at r4](https://reviewable.io/reviews/gramineproject/gsc/88#-NCeaMQj3Dm4XmnTqpiw:-NCjwyKE823Wo87mxN_-:b746t6z) ([raw file](https://github.com/gramineproject/gsc/blob/5ff793a0cc12dafc7d263d49112051f3ccb79ae5/sign.sh#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What about `if`? Literally, every block of code in this PR was indented with a different number of spaces...
</blockquote></details>

Done. Fixed the expect loop too


<!-- Sent from Reviewable.io -->

2022-09-24 23:32 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-26 07:41 UTC, dimakuv approved these changes
> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2022-09-26 10:06 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCtFlMxCxwE6HwUeHfN:-NCtFlMxCxwE6HwUeHfO:b-u9l4md) (no related file):*
FYI: I'm rebasing and testing this PR. Will be finished in several minutes. Please don't touch it anyone.

___


<!-- Sent from Reviewable.io -->

2022-09-26 10:17 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/88#-NCtFlMxCxwE6HwUeHfN:-NCtI5zG8FCfx4E4xxmm:bhbx8aq) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: I'm rebasing and testing this PR. Will be finished in several minutes. Please don't touch it anyone.
</blockquote></details>

Done. Rebased and performed quick tests.

___


<!-- Sent from Reviewable.io -->

2022-09-26 10:23 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/88)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-26 11:06 UTC, merged