Fix GSC gramine base build issue
gramineproject/gsc pull request #92
Opened 2022-09-27 06:54 UTC by manju956

- Copying intel-sgx-deb.key to docker build path was missing in "gsc_build_gramine". Added the key copy to the function.

Signed-off-by: manju956 <manjunath.a.c@intel.com>

2022-09-27 07:11 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/92)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @manju956)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/92#-NCxlrBR3bVYDpVoXGjk:-NCxlrBSBjTFbL1ouZy6:b-mr1nrd) (no related file):*
Thanks @manju956! We haven't used this command (`gsc build-gramine`) in a while, so it got broken. We didn't even test it :(

May I ask how you found this bug? Were you just playing with different GSC commands/options? Or was there a particular use case/scenario that you wanted to enabled?

I'm asking because I'm not sure we should keep this command (`gsc build-gramine`) at all. You're the first person in maybe a year who tried this command :) I am actually thinking of removing it completely.

___


<!-- Sent from Reviewable.io -->

2022-09-27 10:53 UTC, manju956 commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/92)_ status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @manju956)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/gsc/92#-NCxlrBR3bVYDpVoXGjk:-NCxlrBSBjTFbL1ouZy6:b-mr1nrd) (no related file):_ Thanks @manju956! We haven't used this command (`gsc build-gramine`) in a while, so it got broken. We didn't even test it :(
> 
> May I ask how you found this bug? Were you just playing with different GSC commands/options? Or was there a particular use case/scenario that you wanted to enabled?
> 
> I'm asking because I'm not sure we should keep this command (`gsc build-gramine`) at all. You're the first person in maybe a year who tried this command :) I am actually thinking of removing it completely.

@dimakuv We use the command (`gsc build-gramine`) quite extensively in our project to to avoid building gramine code every time. We build the base image and use it to graminize the application image(e.g Openvino based image inferencing).

2022-09-28 07:50 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/92)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @manju956)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/92#-NCxlrBR3bVYDpVoXGjk:-ND23YqxEu_y2Vilf-39:byf1jtk) (no related file):*
<details><summary><i>Previously, manju956 (Manjunath A C) wrote…</i></summary><blockquote>

@dimakuv We use the command (`gsc build-gramine`) in our project to avoid building gramine code every time as optimization measure. We build the base image and use it to graminize the application image(e.g Openvino based image inferencing).
Please share if there are better ways to optimize gramine build time.

</blockquote></details>

Thanks for the explanation. Good to know that someone uses `gsc build-gramine` command :)

I tested the command myself and found some some discrepancies from `gsc build` command. So I created my own PR that incorporates your change as well. Thanks for raising this issue, but I'll close this PR in favor of my PR.

@manju956 Can I add you as a co-author and your `Signed-off-by: manju956 manjunath.a.c@intel.com` line in my PR?

___


<!-- Sent from Reviewable.io -->

2022-09-28 07:53 UTC, manju956 commented
> > _[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/92)_ status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @manju956)
> 
> _[a discussion](https://reviewable.io/reviews/gramineproject/gsc/92#-NCxlrBR3bVYDpVoXGjk:-ND23YqxEu_y2Vilf-39:byf1jtk) (no related file):_
> 
> Previously, manju956 (Manjunath A C) wrote…
> Thanks for the explanation. Good to know that someone uses `gsc build-gramine` command :)
> 
> I tested the command myself and found some some discrepancies from `gsc build` command. So I created my own PR that incorporates your change as well. Thanks for raising this issue, but I'll close this PR in favor of my PR.
> 
> @manju956 Can I add you as a co-author and your `Signed-off-by: manju956 manjunath.a.c@intel.com` line in my PR?

Sure @dimakuv :)

2022-09-28 08:26 UTC, dimakuv commented
Superseded by https://github.com/gramineproject/gsc/pull/96

2022-09-28 08:26 UTC, closed without merging