Update documentation to v1.3
gramineproject/gsc pull request #95
Opened 2022-09-27 16:58 UTC by dimakuv

## Description of the changes 

This also removes a note about unimplemented "scripts as entrypoints" (previously, Gramine only supported binaries as entrypoints). This feature is implemented in Gramine v1.3.

## How to test this PR? 

N/A.

2022-09-27 17:03 UTC, aneessahib reviewed
LGTM

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95#-:-NCztkVpDJJClUxI8Pbv:bb6ywmx)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2022-09-27 17:37 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-09-27 19:38 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-09-28 14:26 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: all files reviewed, 3 unresolved discussions

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/95#-ND3UKdZ4d34pT_O8PSz):*
It will be `v1.3.1` (after we release it, in 1-2 days)
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/95#-ND3ULANBQM9zaR46dBO):*
It will be `v1.3.1` (after we release it, in 1-2 days)
___
*[`Documentation/index.rst` line 319 at r1](https://reviewable.io/reviews/gramineproject/gsc/95#-ND3UM8u0rL6b1C3ysq-:-ND3UM8u0rL6b1C3ysq0:b-ja4oi9) ([raw file](https://github.com/gramineproject/gsc/blob/e2e5e38ac00857efa69b95486243154a47c0d2e0/Documentation/index.rst#L319)):*
> ```reStructuredText
> .. describe:: Gramine.Branch
> 
>    Use this release/branch of the repository. Default value: ``v1.3``.
> ```

It will be `v1.3.1` (after we release it, in 1-2 days)


<!-- Sent from Reviewable.io -->

2022-09-30 11:19 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: 0 of 1 files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib, @boryspoplawski, and @mkow)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/95#-ND3UKdZ4d34pT_O8PSz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It will be `v1.3.1` (after we release it, in 1-2 days)
</blockquote></details>

Done
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/gramineproject/gsc/95#-ND3ULANBQM9zaR46dBO):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It will be `v1.3.1` (after we release it, in 1-2 days)
</blockquote></details>

Done
___
*[`Documentation/index.rst` line 319 at r1](https://reviewable.io/reviews/gramineproject/gsc/95#-ND3UM8u0rL6b1C3ysq-:-NDD6Z2F0xj6Tnj3ATOL:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/e2e5e38ac00857efa69b95486243154a47c0d2e0/Documentation/index.rst#L319)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It will be `v1.3.1` (after we release it, in 1-2 days)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-30 11:32 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: 0 of 1 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/95#-NDD9rQ13hyOvFZ0-12e:-NDD9rQ13hyOvFZ0-12f:b-nbqpuc) (no related file):*
See https://reviewable.io/reviews/gramineproject/gsc/94#-NDD9Y8VC54MkvW98poo.

___


<!-- Sent from Reviewable.io -->

2022-09-30 11:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: 0 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib, @boryspoplawski, and @mkow)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/95#-NDD9rQ13hyOvFZ0-12e:-NDDByb52ERVRAsuHhvF:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

See https://reviewable.io/reviews/gramineproject/gsc/94#-NDD9Y8VC54MkvW98poo.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-09-30 12:16 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-09-30 12:24 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/95)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-04 06:54 UTC, merged