Copy Intel key into Docker image during `gsc build-gramine`
gramineproject/gsc pull request #96
Opened 2022-09-28 08:26 UTC by dimakuv

## Description of the changes 

Copy Intel repo signing key into the resulting base-Gramine Docker image (as part of the `gsc build-gramine` command). This step was missing and resulted in failure of `gsc build-gramine`. Additionally, this commit improves the code quality of the `build-gramine` logic.

Kudos to Manjunath A C (@manju956) who reported this problem and fixed it in https://github.com/gramineproject/gsc/pull/92. My PR supersedes his PR, as I found some additional things to fix/improve during my testing.

## How to test this PR? 

- Create `config-prebuilt-image.yaml` that will contain these lines instead of `Gramine.Repository` + `Gramine.Branch`:
```
 Gramine:
    Image: "base-gramine-image"
```

- Now let's test:
```
# download the official Python image for testing
docker pull python

# this first command is just for testing of `-f` flag (creates the Dockerfile only)
./gsc build-gramine -c config.yaml -f base-gramine-image

# now the real Docker images' creation
./gsc build-gramine --rm -c config.yaml base-gramine-image
./gsc build --rm -c config-prebuilt-image.yaml --insecure-args python test/generic.manifest
./gsc sign-image python enclave-key.pem
docker run --device=/dev/sgx_enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-python -c 'print("HelloWorld!")'
```

2022-09-28 11:19 UTC, woju submitted a review, later dismissed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)

___
*[`gsc.py` line 180 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND2CHgwA6ltIjQA_Qbw:-ND2o2wP7b58ZTJZAOb1:bhyb0f0) ([raw file](https://github.com/gramineproject/gsc/blob/c516b3cf41183e0e7fb3580cfe8ef84a9d3958b8/gsc.py#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

FYI: This is purely for convenience of users when they incorrectly specify the base-Gramine image in the config file. It was missing previously, but I hit this problem (misspelled the image name), and Docker just failed with no meaningful message. So introduced this check.
</blockquote></details>

This is worthy mentioning in a comment or at least in the commit message.


<!-- Sent from Reviewable.io -->

2022-09-28 12:12 UTC, boryspoplawski requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @dimakuv)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND2ya6L7ZdWly5K5krz):*
NP: What's with this `-`? Not sure what's the meaning of it.



_Code quote:_
```
base-Gramine
```
___
*[`gsc.py` line 311 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND3-Qwp7SQOkdQCAgNF:-ND3-Qwp7SQOkdQCAgNG:bqg50w2) ([raw file](https://github.com/gramineproject/gsc/blob/c516b3cf41183e0e7fb3580cfe8ef84a9d3958b8/gsc.py#L311)):*
> ```Python
>         print(f'Successfully created Dockerfile.compile for base-Gramine Docker image '
>               f'`{gramine_image_name}` under `{tmp_build_path}`.')
>         sys.exit(0)
> ```

Why this `exit(0)`? What was wrong with `return`?


<!-- Sent from Reviewable.io -->

2022-09-28 13:27 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required) (waiting on @boryspoplawski and @woju)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND2ya6L7ZdWly5K5krz):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

NP: What's with this `-`? Not sure what's the meaning of it.
</blockquote></details>

Yeah, it was like this in GSC for a long time already (grep through `gsc.py`). Do you want me to replace it everywhere? If yes, then with what?
___
*[`gsc.py` line 180 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND2CHgwA6ltIjQA_Qbw:-ND3GhUbCDRxmMWkIcrZ:b94b9pj) ([raw file](https://github.com/gramineproject/gsc/blob/c516b3cf41183e0e7fb3580cfe8ef84a9d3958b8/gsc.py#L180)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This is worthy mentioning in a comment or at least in the commit message.
</blockquote></details>

I'll add to the commit message then.
___
*[`gsc.py` line 311 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND3-Qwp7SQOkdQCAgNF:-ND3GRGW-ahUZuBSR9sL:boqacs7) ([raw file](https://github.com/gramineproject/gsc/blob/c516b3cf41183e0e7fb3580cfe8ef84a9d3958b8/gsc.py#L311)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why this `exit(0)`? What was wrong with `return`?
</blockquote></details>

We use `sys.exit(0)` everywhere else in this file (for these big "command X" functions). So wanted to be uniform. Do you want me to change to `return [0|1]` everywhere in this file?


<!-- Sent from Reviewable.io -->

2022-09-28 13:40 UTC, boryspoplawski approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND2ya6L7ZdWly5K5krz):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Yeah, it was like this in GSC for a long time already (grep through `gsc.py`). Do you want me to replace it everywhere? If yes, then with what?
</blockquote></details>

Not in this PR. Generally I guess just remove `-`? Not sure, I would need to read gsc.py to check the contexts it's used in.
___
*[`gsc.py` line 311 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND3-Qwp7SQOkdQCAgNF:-ND3Jk_j5hFGvior4bF4:b-j69t5m) ([raw file](https://github.com/gramineproject/gsc/blob/c516b3cf41183e0e7fb3580cfe8ef84a9d3958b8/gsc.py#L311)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

We use `sys.exit(0)` everywhere else in this file (for these big "command X" functions). So wanted to be uniform. Do you want me to change to `return [0|1]` everywhere in this file?
</blockquote></details>

Whatever, not important 


<!-- Sent from Reviewable.io -->

2022-09-28 13:48 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

___
*[`gsc.py` line 180 at r1](https://reviewable.io/reviews/gramineproject/gsc/96#-ND2CHgwA6ltIjQA_Qbw:-ND3LhCdCWTA-wRn3OEL:bb6un1j) ([raw file](https://github.com/gramineproject/gsc/blob/c516b3cf41183e0e7fb3580cfe8ef84a9d3958b8/gsc.py#L180)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'll add to the commit message then.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-09-28 14:09 UTC, boryspoplawski approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-09-29 01:14 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-04 13:25 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-04 14:15 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/96)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-10-04 14:20 UTC, merged