Change ownership of signing script to the default user of the image
gramineproject/gsc pull request #98
Opened 2022-10-03 13:38 UTC by aneessahib

Signed-off-by: aneessahib <anees.a.sahib@intel.com>
This PR changes ownership of `sign.sh` to local user before adding execution privilege. Currently signing works only when the default user of the image is root. This should have been factored while developing commit `08add16203c26382b7b57a5503b2a3e2df638f94`

Sankar @svenkata9  ran into this issue while attempting at graminizing `memcached` docker images

2022-10-04 07:43 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDWwEC8BVxJvjPNTfIH):*
I would modify `signing script` -> `sign.sh` (just for brevity and more precision)

I can do it during final rebase.


<!-- Sent from Reviewable.io -->

2022-10-04 13:32 UTC, boryspoplawski requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDYBPOy2PxA_XZWMq5o:br6ncba) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
> ```
> ARG passphrase
> COPY --chown={{app_user}} sign.sh /gramine/app_files/sign.sh
> RUN chmod +x /gramine/app_files/sign.sh
> ```

Why not `chmod a+x` instead of changing user? Leaving this script as root owned doesn't sound like a bad idea.


<!-- Sent from Reviewable.io -->

2022-10-04 14:19 UTC, mkow reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @aneessahib and @boryspoplawski)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDYMPJr8q7za5xNp8Lr:b32v57) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
<details><summary><i>Previously, boryspoplawski (Borys Popławski) wrote…</i></summary><blockquote>

Why not `chmod a+x` instead of changing user? Leaving this script as root owned doesn't sound like a bad idea.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-10-06 08:18 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, @dimakuv, and @mkow)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDgN-Io5d5kDDdxvYWE:b-896fix) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-06 12:41 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDhJ5De-gkgmXt1meLJ:b-hao5ip) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@aneessahib Could you explain the reasoning in the new version of this PR? You changed `copyfile()` -> `copy()`. What does it change? Why does it work?


<!-- Sent from Reviewable.io -->

2022-10-07 04:03 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDkaNb381nHHAAWlzlF:b-6dhh8a) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

@aneessahib Could you explain the reasoning in the new version of this PR? You changed `copyfile()` -> `copy()`. What does it change? Why does it work?
</blockquote></details>

Sure - my bad, I should have given some explanation.
`sign.sh` already has `a+x` rights, but when gsc copies them (using `copyfile()`) to the build location, the file attributes and permissions are not omitted. Instead, `copy()` does a full copy of the file, and this eliminates the need to do a `chmod` from within the sign template. All users can now run `sign.sh`


<!-- Sent from Reviewable.io -->

2022-10-07 04:04 UTC, aneessahib reviewed
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @aneessahib, @boryspoplawski, and @dimakuv)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDkbHp6EycwwpXmrSlm:b-sp05vn) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
> not 

correction - are omitted


<!-- Sent from Reviewable.io -->

2022-10-07 06:43 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)

___
*[`templates/Dockerfile.common.sign.template` line 7 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDYBPOxEo_Q-yiRYebX:-NDlAo7w87mdeFgdh2bS:btbr9np) ([raw file](https://github.com/gramineproject/gsc/blob/43c45e82a6fc5240d9a4817f4460855cb1244691/templates/Dockerfile.common.sign.template#L7)):*
<details><summary><i>Previously, aneessahib (Anees Sahib) wrote…</i></summary><blockquote>

> not 

correction - are omitted
</blockquote></details>

Thanks for the explanation! Makes sense now.


<!-- Sent from Reviewable.io -->

2022-10-07 10:45 UTC, mkow approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners (waiting on @aneessahib and @boryspoplawski)



<!-- Sent from Reviewable.io -->

2022-10-07 10:59 UTC, boryspoplawski approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @aneessahib)



<!-- Sent from Reviewable.io -->

2022-10-07 11:21 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @boryspoplawski)

*[a discussion](https://reviewable.io/reviews/gramineproject/gsc/98#-NDm9LQKAc6t9S-DRMkr:-NDm9LQL8sm6N_Q0PSTw:b-czgunt) (no related file):*
I did a quick local test. Seems to work.

___
___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/gramineproject/gsc/98#-NDWwEC8BVxJvjPNTfIH):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I would modify `signing script` -> `sign.sh` (just for brevity and more precision)

I can do it during final rebase.
</blockquote></details>

Done. Completely changed the commit message.


<!-- Sent from Reviewable.io -->

2022-10-07 11:29 UTC, boryspoplawski approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gramineproject/gsc/98)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2022-10-07 13:33 UTC, merged